/**
 * العربية: what the platform itself says to the owner outside the
 * console (src/owner/say.ts), keyed by its English. The terms are the
 * console's (console/src/locales/ar.ts), so a button on the phone reads
 * as the same button in the app.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'حادث: {title}',
  'Done: {goal}': 'تم: {goal}',
  'Stopped before finishing: {goal}': 'توقفت قبل الإنجاز: {goal}',
  'Not done: {goal}': 'لم يُنجز: {goal}',
  'Why: {reason}': 'السبب: {reason}',
  'a task': 'مهمة',
  'Approval needed: {title}': 'بانتظار الموافقة: {title}',
  '{summary} — if denied: {consequence}': '{summary} — عند الرفض: {consequence}',
  '{role} asks:': '{role} يسأل:',
  'If denied:': 'عند الرفض:',
  'Expires:': 'تنتهي الصلاحية:',
  'This one is decided in the app.': 'يُبتّ في هذا العنصر داخل التطبيق.',
  'Open in PALUGADA': 'فتح في PALUGADA',
  'Approve': 'موافقة',
  'Deny': 'رفض',
  'Ask': 'سؤال',
  'Approved. Nothing left to press here.': 'تمت الموافقة. لم يبق شيء للضغط عليه هنا.',
  'Denied. Nothing left to press here.': 'تم الرفض. لم يبق شيء للضغط عليه هنا.',
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    'انتهت المهلة دون رد. والصمت رفض، لذا لم يُنفَّذ شيء.',
  'This bot only answers to its owner.': 'هذا البوت لا يستجيب إلا لمالكه.',
  'That one has to be approved in the app.': 'هذا العنصر تجب الموافقة عليه داخل التطبيق.',
  'That could not be recorded.': 'تعذّر تسجيل ذلك.',
  'That item no longer exists.': 'هذا العنصر لم يعد موجودًا.',
  'What do you want to ask about "{title}"? Reply to this message.':
    'ما سؤالك عن «{title}»؟ يكفي الرد على هذه الرسالة.',
  'Your question': 'سؤالك',
  'Type your question as a reply.': 'يُكتب السؤال ردًا على هذه الرسالة.',
  'Asked. The answer will be on the item in the app.': 'أُرسل السؤال. سيظهر الجواب على العنصر داخل التطبيق.',
  'Answer': 'الرد',
  'Answer in words': 'الرد بالكلمات',
  'That choice is not on this question.': 'هذا الخيار ليس ضمن هذا السؤال.',
  'Chosen: {choice}.': 'الاختيار: {choice}.',
  'Stop the task': 'إيقاف المهمة',
  'Your answer to "{question}"? Reply to this message.': 'ما ردّك على «{question}»؟ يكفي الرد على هذه الرسالة.',
  'Your answer': 'ردّك',
  'Type your answer as a reply.': 'تُكتب الإجابة ردًا على هذه الرسالة.',
  'Answered. The task carries on with it.': 'تم الرد. تواصل المهمة عملها به.',
  'That is too long for one question; keep it under {max} characters.':
    'هذا أطول من أن يكون سؤالًا واحدًا؛ الحد الأقصى للأحرف: {max}.',
  '[a key, not kept]': '[مفتاح، لم يُحفظ]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    'يبدو هذا مفتاحًا، لذا لم أحفظه ولم أرسله إلى أي مكان. المفاتيح تُكتب في الحقل المختوم على البطاقة، أو في صفحتها ضمن «هذه المنصة»: يكفي إخباري بالغرض منه، وسأضع البطاقة أمامك.',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'لم يُضبط أي نموذج بعد، لذا لا أستطيع التفكير. يمكن اختيار نموذج من «هذه المنصة»، «النموذج»؛ وبعدها أستطيع المساعدة في كل شيء آخر.',
  'The model did not answer: {reason}': 'لم يُجب النموذج: {reason}',
  'Here is what I propose.': 'إليك ما أقترحه.',
  'I have nothing to add.': 'ليس لديّ ما أضيفه.',
  '{name}, CEO of {company}': '{name}، الرئيس التنفيذي لشركة {company}',
  'That could not be answered: {reason}': 'تعذّرت الإجابة: {reason}',
  'I read text and voice notes.': 'أقرأ النصوص والرسائل الصوتية.',
  'Now talking to {name}.': 'المحادثة الآن مع {name}.',
  'Choose whom to talk to.': 'يُرجى اختيار المحاور.',
  'Choose whom to talk to': 'اختيار المحاور',
  'Talk to PALUGADA about the whole deployment': 'التحدث إلى PALUGADA عن المنصة كلها',
  'Who you are talking to, and how': 'محاورك، وطريقة التحدث',
  'Stopped.': 'تم الإيقاف.',
  'Write here to talk to {name}.': 'للتحدث إلى {name}، يكفي الكتابة هنا.',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    'محاورك الآن {name}. يمكنك الكتابة، أو إرسال رسالة صوتية. الأمر /ceo يختار المحاور؛ والأمر /palugada للتحدث إلى PALUGADA عن المنصة كلها.',
  'You said: "{words}"': 'قلت: «{words}»',
  'in the app': 'داخل التطبيق',
  'Apply: {summary}': 'تطبيق: {summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    'لا شيء يسمع الكلام بعد: يمكن اختيار مزوّد داخل التطبيق، من «هذه المنصة»، «الأدوات»، «الاستماع».',
  'That recording is too long; keep a voice note under {max} MB.':
    'هذا التسجيل طويل جدًا؛ يجب أن تكون الرسالة الصوتية أقل من {max} MB.',
  'I could not make out any words in that.': 'لم أتمكن من تمييز أي كلمات فيه.',
  'Done: {summary}': 'تم: {summary}',
  'That one is applied in the app.': 'هذه البطاقة تُطبَّق داخل التطبيق.',
  'That card no longer exists.': 'هذه البطاقة لم تعد موجودة.',
  'That card was already applied.': 'طُبّقت هذه البطاقة بالفعل.',
  'That card was dismissed.': 'تم تجاهل هذه البطاقة.',
  'That card failed when it was applied.': 'فشلت هذه البطاقة عند تطبيقها.',
  'That could not be done: {reason}': 'تعذّر تنفيذ ذلك: {reason}',
  'Choose': 'اختيار',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    'ما سؤالك عن «{title}»؟ يكفي الرد على هذه الرسالة بسؤالك.',
  'Your answer to "{question}"? Reply to this message with your answer.':
    'ما ردّك على «{question}»؟ يكفي الرد على هذه الرسالة بإجابتك.',
  'I read text messages here.': 'هنا أقرأ الرسائل النصية.',
  'Apply one of these here:': 'يمكن تطبيق إحدى هذه هنا:',
  'Apply {number}': 'تطبيق {number}',
  'Signed in to {provider} for the {alias} key': 'تم تسجيل الدخول إلى {provider} للمفتاح {alias}',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'يمكنك العودة إلى PALUGADA: القسم يحمل هذا المفتاح الآن، ويُجدَّد قبل انتهاء صلاحيته. ويمكن إغلاق علامة التبويب هذه.',
  'Signed in to {name}': 'تم تسجيل الدخول إلى {name}',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'يمكنك العودة إلى PALUGADA لاختيار الأدوات التي يحق للأدوار استخدامها. ويمكن إغلاق علامة التبويب هذه.',
  'Not signed in': 'لم يتم تسجيل الدخول',
  'Recorded: approved.': 'سُجّل: موافقة.',
  'Recorded: denied.': 'سُجّل: رفض.',
  'Recorded: asked.': 'سُجّل: سؤال.',
  'Asked. Nothing left to press here.': 'أُرسل السؤال. لم يبق شيء للضغط عليه هنا.',
  'Withdrawn: the task it was asking about has finished.': 'سُحب: انتهت المهمة التي كان يسأل عنها.',
  'Withdrawn: the task it was asking about has failed.': 'سُحب: فشلت المهمة التي كان يسأل عنها.',
  'Withdrawn: the task it was asking about was stopped.': 'سُحب: أُوقفت المهمة التي كان يسأل عنها.',
  'Withdrawn: the task it was asking about was cancelled.': 'سُحب: أُلغيت المهمة التي كان يسأل عنها.',
  'Decided. Nothing left to press here.': 'حُسم. لم يبق شيء للضغط عليه هنا.',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': 'سُحب: غيّر الوكيل ما يقترحه وأعاد السؤال عن المقترح الجديد.',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': 'سُحب: لم تعد الشركة في المرحلة التي كان هذا المقترح سينقلها منها.',
  'Withdrawn: it was already decided in the app.': 'سُحب: حُسم بالفعل داخل التطبيق.',
  'Withdrawn. Nothing left to press here.': 'سُحب. لم يبق شيء للضغط عليه هنا.',
  'company': 'الشركة',
  'Work stopped: the {account} account is out of tokens': 'توقف العمل: نفدت رموز الحساب {account}',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': 'توقف «{work}» لأن الحساب {account} استهلك {spent} من أصل {max} رمزًا. ارفع سقفه من صفحة «المال»، ثم افتح المهمة واضغط «متابعة»: ستكمل من حيث توقفت.',
  'Withdrawn: you continued the task it was about.': 'سُحب: لقد تابعتَ المهمة التي يخصها.',
  'Broke its contract': 'أخلّ بعقده',
  'Refused by a policy': 'رفضته سياسة',
  'Out of budget': 'نفدت الميزانية',
  'Handed on too many times': 'سُلّمت مرات كثيرة جدًا',
  'Missed its deadline': 'فاته موعده النهائي',
  'Its result did not check out': 'لم تصمد نتيجته أمام التحقق',
  'A capability it needs is down': 'إحدى القدرات التي يحتاجها متوقفة',
  'No runtime could take it': 'لم تستطع أي بيئة تشغيل تولّيها',
  'Went in a circle': 'دار في حلقة مفرغة',
  'Split into too many sub-tasks': 'قُسّمت إلى مهام فرعية كثيرة جدًا',
  'Wrote more than its role allows one run': 'كتب أكثر مما يسمح به دوره في تشغيل واحد',
  'Your approval was not given in time': 'لم تصل موافقتك في الوقت المحدد',
  'Stopped by you': 'أُوقف بطلبك',
  'Cancelled by you': 'أُلغيت بطلبك',
  'The company is frozen': 'الشركة مجمّدة',
  'Its record did not match on replay': 'لم يتطابق سجله عند إعادة التنفيذ',
  'It kept stopping the worker running it': 'تسببت مرارًا في توقف العامل الذي يشغّلها',
  'Not done': 'لم يُنجز',
  'Task failed': 'فشلت مهمة',
  'Digest for {day}': 'ملخص يوم {day}',
  'Spent: {amount}': 'المُنفَق: {amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': 'العمل — تم: {done}، فشل: {failed}، متوقف: {stopped}',
  'Inbox: {open} waiting (incidents: {incidents})': 'صندوق الوارد: {open} قيد الانتظار (الحوادث: {incidents})',
  'Stopped ({count}): {reason}': 'متوقف ({count}): {reason}',
  'Start an ad campaign': 'بدء حملة إعلانية',
  'Block time on the calendar': 'حجز وقت في التقويم',
  'Read the calendar': 'قراءة التقويم',
  'Run code': 'تشغيل شيفرة برمجية',
  'Add a note to a customer': 'إضافة ملاحظة إلى سجل عميل',
  'Read customer records': 'قراءة سجلات العملاء',
  'Release to the live site': 'النشر على الموقع العام',
  'Release to the test site': 'النشر على موقع الاختبار',
  'Change a domain\'s nameservers': 'تغيير خوادم الأسماء لنطاق',
  'Read a domain\'s records': 'قراءة سجلات نطاق',
  'Change a domain\'s record': 'تغيير سجل نطاق',
  'Write a document': 'كتابة مستند',
  'Sign a document': 'توقيع مستند',
  'Buy a domain': 'شراء نطاق',
  'Transfer a domain': 'نقل نطاق',
  'Draft an email': 'إعداد مسودة بريد إلكتروني',
  'Send an email': 'إرسال بريد إلكتروني',
  'List files': 'عرض قائمة الملفات',
  'Read a file': 'قراءة ملف',
  'Describe a picture': 'وصف صورة',
  'Transfer money': 'تحويل أموال',
  'Propose a goal change': 'اقتراح تغيير هدف',
  'Make a picture': 'إنشاء صورة',
  'Issue an invoice': 'إصدار فاتورة',
  'Pay an invoice': 'دفع فاتورة',
  'Read the books': 'قراءة الدفاتر المحاسبية',
  'Read the mailbox': 'قراءة صندوق البريد',
  'Search what the company knows': 'البحث فيما تعرفه الشركة',
  'Record a measure': 'تسجيل قيمة مقياس',
  'Read product numbers': 'قراءة أرقام المنتج',
  'Ask you a question': 'طرح سؤال عليك',
  'Write down a plan': 'تدوين خطة',
  'Delete a record': 'حذف سجل',
  'Propose a code change': 'اقتراح تغيير في الشيفرة',
  'Read the code': 'قراءة الشيفرة',
  'Destroy a server': 'تدمير خادم',
  'Read a skill': 'قراءة مهارة',
  'Publish a post': 'نشر تدوينة',
  'Read text aloud': 'قراءة نص بصوت مسموع',
  'Turn speech into text': 'تحويل الكلام إلى نص',
  'Propose a new stage': 'اقتراح مرحلة جديدة',
  'Wait for work handed on': 'انتظار عمل مُسلَّم إلى الغير',
  'Hand work to another role': 'تسليم عمل إلى دور آخر',
  'File a ticket': 'فتح تذكرة',
  'List tickets': 'عرض قائمة التذاكر',
  'Check a service is up': 'التحقق من استجابة خدمة',
  'Read a web page': 'قراءة صفحة ويب',
  'Open a web page': 'فتح صفحة ويب',
  'Search the web': 'البحث في الويب',
  'no stage': 'حالة بلا مرحلة',
  'Explore': 'الاستكشاف',
  'Validate': 'التحقق',
  'Build': 'البناء',
  'Launch': 'الإطلاق',
  'Grow': 'النمو',
  'Wind down': 'التصفية',
  'Monthly budget reached; the company is paused': 'بُلغت الميزانية الشهرية؛ الشركة متوقفة مؤقتًا',
  '{spent} of {limit} spent since {since}. No new task will start and no external action will run until you raise the ceiling or allow spending past it for a while, under Money.': 'أُنفق {spent} من {limit} منذ {since}. لن تبدأ أي مهمة جديدة ولن يُنفَّذ أي إجراء خارجي إلى أن يُرفع السقف أو يُسمح مؤقتًا بالإنفاق فوقه، من صفحة «المال».',
  'Monthly budget is 80% spent': 'أُنفق 80% من الميزانية الشهرية',
  '{spent} of {limit} spent since {since}. At 100% the company pauses.': 'أُنفق {spent} من {limit} منذ {since}. عند 100% تتوقف الشركة مؤقتًا.',
  'Role {role} is paused for spending too fast': 'أُوقف الدور {role} مؤقتًا لأنه ينفق بسرعة كبيرة',
  '{role} spent {spent} in the last hour, {multiple} times its usual {usual} an hour. It is paused before the monthly ceiling is reached, so there is money left to work with once you have found out why. Resume it when you have.': 'أنفق {role} مبلغ {spent} في الساعة الأخيرة، أي {multiple} ضعف إنفاقه المعتاد البالغ {usual} في الساعة. أُوقف مؤقتًا قبل بلوغ السقف الشهري، كي يبقى مال للعمل به بعد معرفة السبب. ويمكن استئنافه بعد ذلك.',
  'Daily model spend over threshold': 'الإنفاق اليومي على النماذج تجاوز العتبة',
  'Model spend today is {spent}, over the {limit} ceiling.': 'بلغ الإنفاق على النماذج اليوم {spent}، متجاوزًا السقف البالغ {limit}.',
  'Task failure rate over threshold': 'معدل فشل المهام تجاوز العتبة',
  '{failed} of {finished} tasks failed or stopped today ({rate}%), over the {limit}% threshold.': 'المهام التي فشلت أو توقفت اليوم: {failed} من أصل {finished} ({rate}%)، متجاوزةً العتبة البالغة {limit}%.',
  'Unusual number of policy refusals': 'عدد غير معتاد من مرات الرفض بسبب السياسات',
  'Actions refused by a policy today: {count}, over the threshold of {limit}. Either an agent is probing its limits or a policy is miscalibrated.': 'الإجراءات التي رفضتها سياسةٌ اليوم: {count}، متجاوزةً العتبة البالغة {limit}. فإما أن وكيلًا يختبر حدوده، وإما أن سياسةً معايَرة على نحو خاطئ.',
  'External writes failed verification': 'فشلت عمليات كتابة خارجية في القراءة للتحقق',
  'Writes outside that reported success but read back differently: {count}. Something is changing them other than as asked.': 'عمليات الكتابة الخارجية التي أفادت بالنجاح لكن القراءة للتحقق أظهرت غير ذلك: {count}. ثمة ما يغيّرها على غير ما طُلب.',
  'A capability stopped being usable': 'قدرة لم تعد صالحة للاستخدام',
  'Tasks that could not start today because a capability their role needs failed its check: {count}. A credential has probably expired or a quota is used up.': 'المهام التي تعذّر بدؤها اليوم لأن قدرةً يحتاجها دورها فشلت في فحصها: {count}. على الأرجح انتهت صلاحية بيانات اعتماد أو نفدت حصة.',
  'A worker stopped reporting mid-run': 'توقف عاملٌ عن الإبلاغ في منتصف التشغيل',
  'Runs that stopped reporting and were taken back today: {count}. The work was picked up again; the tokens they had already spent were not recovered.': 'عمليات التشغيل التي توقفت عن الإبلاغ وسُحبت من عمّالها اليوم: {count}. استُؤنف العمل؛ أما التوكنات التي كانت قد أُنفقت فلم تُسترد.',
  '{role} was refused {denials} times today, at the limit of {limit}. No task will run as this role until you lift the freeze. The usual causes are a missing capability grant, a policy the role\'s charter does not account for, or work the role was never equipped to do.': 'عدد مرات رفض {role} اليوم: {denials}، وهو الحد البالغ {limit}. لن تُشغَّل أي مهمة بهذا الدور إلى أن يُلغى تجميده. والأسباب المعتادة: نقص إذن لقدرة ما، أو سياسة لا يراعيها ميثاق الدور، أو عمل لم يُجهَّز الدور قط للقيام به.',
  'Role {role} is frozen after repeated denials': 'جُمّد الدور {role} بعد رفض متكرر',
  'What it was refused: {capabilities}': 'ما رُفض له: {capabilities}',
  'It is waiting for an approval, and none is open, so nothing you can answer will move it.': 'إنها تنتظر موافقة، ولا توجد موافقة مفتوحة، لذا لن يحرّكها أي رد منك.',
  'It is waiting for a review, and none is pending, so no reviewer and no decision of yours will move it.': 'إنها تنتظر مراجعة، ولا توجد مراجعة معلّقة، لذا لن يحرّكها أي مراجِع ولا أي قرار منك.',
  'It is parked until a window reopens, and the window never does.': 'إنها مُعلّقة إلى أن تُفتح نافذة زمنية من جديد، وتلك النافذة لا تُفتح أبدًا.',
  'A task is waiting on nothing': 'مهمة تنتظر شيئًا لن يأتي',
  '"{task}" has been waiting since {since}. {why} Approve to run it again from where it stopped, or deny to cancel it.': '«{task}» تنتظر منذ {since}. {why} «موافقة» تُعيد تشغيلها من حيث توقفت، و«رفض» يُلغيها.',
  'A task keeps stopping the worker running it': 'مهمة تتسبب مرارًا في توقف العامل الذي يشغّلها',
  '"{task}" lost its worker {lost} times: each time the worker running it stopped answering before the work finished. What it had done is kept. It is halted so it cannot take another worker down; run it again once the cause is found, or cancel it.': 'عدد مرات فقدان «{task}» لعاملها: {lost}؛ ففي كل مرة توقف العامل الذي يشغّلها عن الرد قبل انتهاء العمل. وما أنجزته محفوظ. أُوقفت كي لا تُسقط عاملًا آخر؛ ويمكن إعادة تشغيلها بعد معرفة السبب، أو إلغاؤها.',
  '{services} stayed unreachable, and the work that needs it stopped': 'تعذّر الوصول إلى {services}، فتوقف العمل الذي يعتمد على ذلك',
  'The task waited about {minutes} minutes, looking again each time, and has stopped. Once the service answers, run it again.': 'انتظرت المهمة نحو {minutes} من الدقائق، تعاود المحاولة في كل مرة، ثم توقفت. ويمكن إعادة تشغيلها حين تستجيب الخدمة.',
  'It was tried {tries} times over about {minutes} minutes.': 'عدد المحاولات: {tries}، خلال نحو {minutes} من الدقائق.',
  'This role can take actions that cannot be undone, so the run was not silently moved to a different model.': 'يستطيع هذا الدور اتخاذ إجراءات لا رجعة فيها، لذا لم يُنقل التشغيل بصمت إلى نموذج آخر.',
  'No fallback model is left for this role.': 'لم يتبقَّ نموذج بديل لهذا الدور.',
  'Model {model} failed and the run was not moved': 'فشل النموذج {model} ولم يُنقل التشغيل',
  'External write failed verification': 'فشلت عملية كتابة خارجية في القراءة للتحقق',
  'The task wrote to an outside service and read it back, and what it read did not match. Look at the place it wrote to before you run it again: the write may have happened.': 'كتبت المهمة إلى خدمة خارجية ثم قرأت ما كتبته للتحقق، فلم يتطابق ما قرأته. يُرجى فحص المكان الذي كتبت إليه قبل إعادة تشغيلها: فقد تكون الكتابة قد تمّت.',
  'Review deadlocked after {rounds} revisions: {capability}': 'تعثّرت المراجعة بعد {rounds} من جولات التعديل: {capability}',
  'The role and its reviewer did not agree on {capability}.': 'لم يتفق الدور ومراجِعه على {capability}.',
  'The reviewer\'s last note: {note}': 'آخر ملاحظة من المراجِع: {note}',
  'The reviewer left no note.': 'لم يترك المراجِع أي ملاحظة.',
  'What it was judged against: {criteria}': 'المعايير التي قُيِّم على أساسها: {criteria}',
  'Review produced no usable verdict: {capability}': 'لم تُسفر المراجعة عن حكم قابل للاستخدام: {capability}',
  'The reviewing task ended without a decision that could be read. The proposed action is still blocked and needs your judgement.': 'انتهت مهمة المراجعة دون قرار يمكن قراءته. ولا يزال الإجراء المقترح محظورًا ويحتاج إلى حكمك.',
  'another stage': 'مرحلة أخرى',
  'Either answer only closes this: the company stays in the {stage} stage.': 'أيّ الردّين يُغلق هذا فحسب: تبقى الشركة في مرحلة {stage}.',
  'Either answer only closes this: the company stays without a stage.': 'أيّ الردّين يُغلق هذا فحسب: تبقى الشركة بلا مرحلة.',
  'To move it anyway, set the stage on the Overview.': 'ولنقلها رغم ذلك، يمكن تحديد المرحلة من «نظرة عامة».',
  '{reviewer} stopped a proposal to move the company from {from} to {to}': 'أوقف {reviewer} اقتراحًا بنقل الشركة من {from} إلى {to}',
  '{reviewer} reviewed it before you and stopped it:': 'راجعه {reviewer} قبلك وأوقفه:',
  'No reason was given.': 'لم يُذكر أي سبب.',
  'What was proposed:': 'ما اقتُرح:',
  'The company stays in the {stage} stage.': 'تبقى الشركة في مرحلة {stage}.',
  'The company stays without a stage.': 'تبقى الشركة بلا مرحلة.',
  'Move the company from {from} to {to}?': 'نقل الشركة من {from} إلى {to}؟',
  'Reviewed by {reviewer} before you:': 'راجعه {reviewer} قبلك:',
  'The schedule "{schedule}" keeps producing the same result': 'الجدول الزمني «{schedule}» يُنتج النتيجة نفسها مرارًا',
  'Its last {runs} runs all ended with the same output. That is sometimes exactly right -- a report with nothing new to say -- and often a schedule that stopped doing anything useful while still being paid for. Deny to turn it off; approve to keep it running and not be asked about this result again.': 'عمليات التشغيل الأخيرة، وعددها {runs}، انتهت كلها بالمُخرَج نفسه. وهذا أحيانًا هو الصواب تمامًا — تقرير ليس فيه جديد — وكثيرًا ما يكون جدولًا زمنيًا كفّ عن فعل أي شيء مفيد بينما لا يزال يُدفع ثمنه. «رفض» يوقفه؛ و«موافقة» تُبقيه يعمل دون السؤال عن هذه النتيجة مرة أخرى.',
  'Capability {capability} failed preflight': 'فشلت القدرة {capability} في الفحص المسبق',
  'Work that needs it is stopped rather than started: fix the cause, then run that work again. The usual causes are an expired or wrongly scoped credential, a quota used up, or an address that is wrong.': 'العمل الذي يحتاجها يُوقف بدلًا من أن يبدأ: يُرجى إصلاح السبب، ثم إعادة تشغيل ذلك العمل. والأسباب المعتادة: بيانات اعتماد منتهية الصلاحية أو بنطاق صلاحيات خاطئ، أو حصة نفدت، أو عنوان خاطئ.',
  'Batch guard stopped {capability}': 'أوقف فحصُ حجم الدفعة {capability}',
  'It did not match the plan its run recorded. Nothing was sent, and no service was called.': 'لم يطابق الخطة التي سجّلها تشغيله. لم يُرسَل شيء، ولم تُستدعَ أي خدمة.',
  '{role} was asked first and has had {minutes} minutes.': 'أُحيل هذا إلى {role} أولًا، وقد مضى على ذلك {minutes} من الدقائق.',
  '{role} is not a role in this company, so this came to you at once.': '{role} ليس دورًا في هذه الشركة، لذا وصل هذا إليك مباشرة.',
  '{role} could not be given this: the company has no active goal or project to hang it from.': 'تعذّر إسناد هذا إلى {role}: ليس لدى الشركة هدف نشط أو مشروع نشط يُلحق به.',
  '{role} could not be given this ({record}), so this came to you at once.': 'تعذّر إسناد هذا إلى {role} ({record})، لذا وصل إليك مباشرة.',
  '{role} stopped without an account of what it did ({why}).': 'توقف {role} دون بيان ما فعله ({why}).',
  '{role} finished without an account of what it did.': 'أنهى {role} العمل دون بيان ما فعله.',
  '{role} failed without an account of what it did.': 'فشل {role} دون بيان ما فعله.',
  '{role} was stopped without an account of what it did.': 'أُوقف {role} دون بيان ما فعله.',
  'Proposed change to the {kind} "{goal}"': 'تعديل مقترح على {kind} «{goal}»',
  'Currently: {statement}': 'حاليًا: {statement}',
  'Currently: {statement} ({status})': 'حاليًا: {statement} ({status})',
  'Proposed: {statement}': 'المقترح: {statement}',
  'Proposed status: {status}': 'الحالة المقترحة: {status}',
  'Reason given: {reason}': 'السبب المذكور: {reason}',
  'Approving it changes the goal; until then the work carries on under the goal as it is.': 'الموافقة تغيّر الهدف؛ وحتى ذلك الحين يستمر العمل في إطار الهدف كما هو.',
  'The goal stays as it is.': 'يبقى الهدف كما هو.',
  'mission': 'الرسالة',
  'objective': 'الهدف',
  'key result': 'النتيجة الرئيسية',
  'Active': 'نشط',
  'Met': 'متحقق',
  'Abandoned': 'متروك',
  'This work asked for it at tier {tier}, and policy {policies} requires your approval.': 'طلبه هذا العمل في المستوى {tier}، والسياسة {policies} تشترط موافقتك.',
  'This work asked for it at tier {tier}, and the task began with content from outside the company.': 'طلبه هذا العمل في المستوى {tier}، وقد بدأت المهمة بمحتوى من خارج الشركة.',
  'This work asked for it at tier {tier}, and the work read content from outside the company before asking.': 'طلبه هذا العمل في المستوى {tier}، وكان قد قرأ محتوى من خارج الشركة قبل أن يطلبه.',
  'This work asked for it at tier {tier}, after the work read content from outside the company, and the guardian asked you first: {reason}': 'طلبه هذا العمل في المستوى {tier}، بعد أن قرأ محتوى من خارج الشركة، فعرضه الحارس عليك أولًا: {reason}',
  'it doubted this call before, and you allowed it once': 'سبق أن ارتاب في هذا الاستدعاء، وسمحت به مرة واحدة',
  'This work asked for it at tier {tier}, which cannot be reversed.': 'طلبه هذا العمل في المستوى {tier}، وهو مستوى لا رجعة فيه.',
  'You approved this once already, and the worker carrying it out stopped before it could say whether it happened: it may already have happened. Check before approving it again.': 'سبق أن وافقت على هذا مرة، وتوقف العامل الذي كان ينفّذه قبل أن يُبلغ هل تمّ أم لا: فربما تمّ بالفعل. يُرجى التحقق قبل الموافقة عليه مجددًا.',
  'What this is for — {goals}': 'الغاية من هذا — {goals}',
  'The task halts and no external change is made.': 'تتوقف المهمة ولا يُجرى أي تغيير خارجي.',
  'Scored against {total} references: {passed} passed, {failed} failed.': 'قُيِّم مقابل {total} من المراجع: نجح {passed}، وفشل {failed}.',
  'This role has fewer than {minimum} accepted references, so the change is unscored. That is not the same as passing.': 'لدى هذا الدور أقل من {minimum} من المراجع المقبولة، لذا لم يُقيَّم التغيير. وهذا لا يعني النجاح.',
  'The role keeps working exactly as it does now.': 'يستمر الدور في العمل تمامًا كما يعمل الآن.',
  '{role} asks: {question}': 'يسأل {role}: {question}',
  'The run did not say more than the question.': 'لم يقل التشغيل أكثر من السؤال.',
  'The task is stopped, and nothing it was going to do happens.': 'تتوقف المهمة، ولا يحدث شيء مما كانت ستفعله.',
  'You proposed it.': 'أنت من اقترحها.',
  'It came with a bundle.': 'جاءت ضمن حزمة.',
  'An agent proposed it.': 'اقترحها وكيل.',
  'It was learned from the company\'s work.': 'استُقيت من عمل الشركة.',
  'Skill "{skill}", version {version}': 'المهارة «{skill}»، الإصدار {version}',
  'The reviewer approved it: {note}': 'وافق عليها المراجِع: {note}',
  'The reviewer approved it.': 'وافق عليها المراجِع.',
  'Nothing changes; the current version of the skill stays in force.': 'لن يتغير شيء؛ يبقى الإصدار الحالي من المهارة ساريًا.',
  'Skills the bundle "{bundle}" brings: {count}': 'المهارات التي تجلبها الحزمة «{bundle}»: {count}',
  'The reviewer read them all and approved these:': 'قرأها المراجِع كلها ووافق على هذه:',
  'It turned these down, and they stay off:': 'رفض المراجِع هذه، وستبقى متوقفة:',
  'Approve to switch them all on, or deny to turn them all down. To decide one at a time, open the Skills page.': '«موافقة» تُفعّلها كلها، و«رفض» يرفضها كلها. ولتقرّر في كل واحدة على حدة، افتح صفحة «المهارات».',
  'Nothing changes; none of these skills is switched on.': 'لن يتغير شيء؛ لن تُفعَّل أي من هذه المهارات.',
  'I am {ceo}, and I run {company} for you. Three things before we start: what does {company} sell, and to whom? How much may it spend in a month? And what should its first piece of work be -- or shall I suggest one?': 'أنا {ceo}، وأدير شركة {company} نيابةً عنك. قبل أن نبدأ، ثلاثة أمور: ماذا تبيع {company}، ولمن؟ وكم يمكنها أن تنفق في الشهر؟ وما أول عمل ينبغي أن تقوم به — أم أقترح عملًا؟',
  'Read a customer conversation': 'قراءة محادثة مع عميل',
  'Reply to a customer': 'الرد على عميل',
  'Read a page in the browser': 'قراءة صفحة في المتصفح',
  'Fill in a page in the browser': 'تعبئة صفحة في المتصفح',
  'Ask you to take over the browser': 'يطلب منك تولي المتصفح',
};
