/**
 * العربية: what the platform itself says to the owner outside the
 * console (src/owner/say.ts), keyed by its English. The terms are the
 * console's (console/src/locales/ar.ts), so a button on the phone reads
 * as the same button in the app.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'حادث: {title}',
  'Done: {goal}': 'تم: {goal}',
  'Stopped before finishing: {goal}': 'توقفت قبل الإنجاز: {goal}',
  'Not done: {goal}': 'لم يُنجز: {goal}',
  'Why: {reason}': 'السبب: {reason}',
  'a task': 'مهمة',
  'Approval needed: {title}': 'بانتظار الموافقة: {title}',
  '{summary} — if denied: {consequence}': '{summary} — عند الرفض: {consequence}',
  '{role} asks:': '{role} يسأل:',
  'If denied:': 'عند الرفض:',
  'Expires:': 'تنتهي الصلاحية:',
  'This one is decided in the app.': 'يُبتّ في هذا العنصر داخل التطبيق.',
  'Open in PALUGADA': 'فتح في PALUGADA',
  'Approve': 'موافقة',
  'Deny': 'رفض',
  'Ask': 'سؤال',
  'Approved. Nothing left to press here.': 'تمت الموافقة. لم يبق شيء للضغط عليه هنا.',
  'Denied. Nothing left to press here.': 'تم الرفض. لم يبق شيء للضغط عليه هنا.',
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    'انتهت المهلة دون رد. والصمت رفض، لذا لم يُنفَّذ شيء.',
  'This bot only answers to its owner.': 'هذا البوت لا يستجيب إلا لمالكه.',
  'That one has to be approved in the app.': 'هذا العنصر تجب الموافقة عليه داخل التطبيق.',
  'That could not be recorded.': 'تعذّر تسجيل ذلك.',
  'That item no longer exists.': 'هذا العنصر لم يعد موجودًا.',
  'What do you want to ask about "{title}"? Reply to this message.':
    'ما سؤالك عن «{title}»؟ يكفي الرد على هذه الرسالة.',
  'Your question': 'سؤالك',
  'Type your question as a reply.': 'يُكتب السؤال ردًا على هذه الرسالة.',
  'Asked. The answer will be on the item in the app.': 'أُرسل السؤال. سيظهر الجواب على العنصر داخل التطبيق.',
  'Answer': 'الرد',
  'Answer in words': 'الرد بالكلمات',
  'That choice is not on this question.': 'هذا الخيار ليس ضمن هذا السؤال.',
  'Chosen: {choice}.': 'الاختيار: {choice}.',
  'Stop the task': 'إيقاف المهمة',
  'Your answer to "{question}"? Reply to this message.': 'ما ردّك على «{question}»؟ يكفي الرد على هذه الرسالة.',
  'Your answer': 'ردّك',
  'Type your answer as a reply.': 'تُكتب الإجابة ردًا على هذه الرسالة.',
  'Answered. The task carries on with it.': 'تم الرد. تواصل المهمة عملها به.',
  'That is too long for one question; keep it under {max} characters.':
    'هذا أطول من أن يكون سؤالًا واحدًا؛ الحد الأقصى للأحرف: {max}.',
  '[a key, not kept]': '[مفتاح، لم يُحفظ]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    'يبدو هذا مفتاحًا، لذا لم أحفظه ولم أرسله إلى أي مكان. المفاتيح تُكتب في الحقل المختوم على البطاقة، أو في صفحتها ضمن «هذه المنصة»: يكفي إخباري بالغرض منه، وسأضع البطاقة أمامك.',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'لم يُضبط أي نموذج بعد، لذا لا أستطيع التفكير. يمكن اختيار نموذج من «هذه المنصة»، «النموذج»؛ وبعدها أستطيع المساعدة في كل شيء آخر.',
  'The model did not answer: {reason}': 'لم يُجب النموذج: {reason}',
  'Here is what I propose.': 'إليك ما أقترحه.',
  'I have nothing to add.': 'ليس لديّ ما أضيفه.',
  '{name}, CEO of {company}': '{name}، الرئيس التنفيذي لشركة {company}',
  'That could not be answered: {reason}': 'تعذّرت الإجابة: {reason}',
  'I read text and voice notes.': 'أقرأ النصوص والرسائل الصوتية.',
  'Now talking to {name}.': 'المحادثة الآن مع {name}.',
  'Choose whom to talk to.': 'يُرجى اختيار المحاور.',
  'Choose whom to talk to': 'اختيار المحاور',
  'Talk to PALUGADA about the whole deployment': 'التحدث إلى PALUGADA عن المنصة كلها',
  'Who you are talking to, and how': 'محاورك، وطريقة التحدث',
  'Stopped.': 'تم الإيقاف.',
  'Write here to talk to {name}.': 'للتحدث إلى {name}، يكفي الكتابة هنا.',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    'محاورك الآن {name}. يمكنك الكتابة، أو إرسال رسالة صوتية. الأمر /ceo يختار المحاور؛ والأمر /palugada للتحدث إلى PALUGADA عن المنصة كلها.',
  'You said: "{words}"': 'قلت: «{words}»',
  'in the app': 'داخل التطبيق',
  'Apply: {summary}': 'تطبيق: {summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    'لا شيء يسمع الكلام بعد: يمكن اختيار مزوّد داخل التطبيق، من «هذه المنصة»، «الأدوات»، «الاستماع».',
  'That recording is too long; keep a voice note under {max} MB.':
    'هذا التسجيل طويل جدًا؛ يجب أن تكون الرسالة الصوتية أقل من {max} MB.',
  'I could not make out any words in that.': 'لم أتمكن من تمييز أي كلمات فيه.',
  'Done: {summary}': 'تم: {summary}',
  'That one is applied in the app.': 'هذه البطاقة تُطبَّق داخل التطبيق.',
  'That card no longer exists.': 'هذه البطاقة لم تعد موجودة.',
  'That card was already applied.': 'طُبّقت هذه البطاقة بالفعل.',
  'That card was dismissed.': 'تم تجاهل هذه البطاقة.',
  'That card failed when it was applied.': 'فشلت هذه البطاقة عند تطبيقها.',
  'That could not be done: {reason}': 'تعذّر تنفيذ ذلك: {reason}',
  'Choose': 'اختيار',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    'ما سؤالك عن «{title}»؟ يكفي الرد على هذه الرسالة بسؤالك.',
  'Your answer to "{question}"? Reply to this message with your answer.':
    'ما ردّك على «{question}»؟ يكفي الرد على هذه الرسالة بإجابتك.',
  'I read text messages here.': 'هنا أقرأ الرسائل النصية.',
  'Apply one of these here:': 'يمكن تطبيق إحدى هذه هنا:',
  'Apply {number}': 'تطبيق {number}',
  'Signed in to {provider} for the {alias} key': 'تم تسجيل الدخول إلى {provider} للمفتاح {alias}',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'يمكنك العودة إلى PALUGADA: القسم يحمل هذا المفتاح الآن، ويُجدَّد قبل انتهاء صلاحيته. ويمكن إغلاق علامة التبويب هذه.',
  'Signed in to {name}': 'تم تسجيل الدخول إلى {name}',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'يمكنك العودة إلى PALUGADA لاختيار الأدوات التي يحق للأدوار استخدامها. ويمكن إغلاق علامة التبويب هذه.',
  'Not signed in': 'لم يتم تسجيل الدخول',
  'Recorded: approved.': 'سُجّل: موافقة.',
  'Recorded: denied.': 'سُجّل: رفض.',
  'Recorded: asked.': 'سُجّل: سؤال.',
  'Asked. Nothing left to press here.': 'أُرسل السؤال. لم يبق شيء للضغط عليه هنا.',
  'Withdrawn: the task it was asking about has finished.': 'سُحب: انتهت المهمة التي كان يسأل عنها.',
  'Withdrawn: the task it was asking about has failed.': 'سُحب: فشلت المهمة التي كان يسأل عنها.',
  'Withdrawn: the task it was asking about was stopped.': 'سُحب: أُوقفت المهمة التي كان يسأل عنها.',
  'Withdrawn: the task it was asking about was cancelled.': 'سُحب: أُلغيت المهمة التي كان يسأل عنها.',
  'Decided. Nothing left to press here.': 'حُسم. لم يبق شيء للضغط عليه هنا.',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': 'سُحب: غيّر الوكيل ما يقترحه وأعاد السؤال عن المقترح الجديد.',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': 'سُحب: لم تعد الشركة في المرحلة التي كان هذا المقترح سينقلها منها.',
  'Withdrawn: it was already decided in the app.': 'سُحب: حُسم بالفعل داخل التطبيق.',
  'Withdrawn. Nothing left to press here.': 'سُحب. لم يبق شيء للضغط عليه هنا.',
  'company': 'الشركة',
  'Work stopped: the {account} account is out of tokens': 'توقف العمل: نفدت رموز الحساب {account}',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': 'توقف «{work}» لأن الحساب {account} استهلك {spent} من أصل {max} رمزًا. ارفع سقفه من صفحة «المال»، ثم افتح المهمة واضغط «متابعة»: ستكمل من حيث توقفت.',
  'Withdrawn: you continued the task it was about.': 'سُحب: لقد تابعتَ المهمة التي يخصها.',
  'Broke its contract': 'أخلّ بعقده',
  'Refused by a policy': 'رفضته سياسة',
  'Out of budget': 'نفدت الميزانية',
  'Handed on too many times': 'سُلّمت مرات كثيرة جدًا',
  'Missed its deadline': 'فاته موعده النهائي',
  'Its result did not check out': 'لم تصمد نتيجته أمام التحقق',
  'A capability it needs is down': 'إحدى القدرات التي يحتاجها متوقفة',
  'No runtime could take it': 'لم تستطع أي بيئة تشغيل تولّيها',
  'Went in a circle': 'دار في حلقة مفرغة',
  'Split into too many sub-tasks': 'قُسّمت إلى مهام فرعية كثيرة جدًا',
  'Wrote more than its role allows one run': 'كتب أكثر مما يسمح به دوره في تشغيل واحد',
  'Your approval was not given in time': 'لم تصل موافقتك في الوقت المحدد',
  'Stopped by you': 'أُوقف بطلبك',
  'Cancelled by you': 'أُلغيت بطلبك',
  'The company is frozen': 'الشركة مجمّدة',
  'Its record did not match on replay': 'لم يتطابق سجله عند إعادة التنفيذ',
  'It kept stopping the worker running it': 'تسببت مرارًا في توقف العامل الذي يشغّلها',
  'Not done': 'لم يُنجز',
  'Task failed': 'فشلت مهمة',
  'Digest for {day}': 'ملخص يوم {day}',
  'Spent: {amount}': 'المُنفَق: {amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': 'العمل — تم: {done}، فشل: {failed}، متوقف: {stopped}',
  'Inbox: {open} waiting (incidents: {incidents})': 'صندوق الوارد: {open} قيد الانتظار (الحوادث: {incidents})',
  'Stopped ({count}): {reason}': 'متوقف ({count}): {reason}',
  'Start an ad campaign': 'بدء حملة إعلانية',
  'Block time on the calendar': 'حجز وقت في التقويم',
  'Read the calendar': 'قراءة التقويم',
  'Run code': 'تشغيل شيفرة برمجية',
  'Add a note to a customer': 'إضافة ملاحظة إلى سجل عميل',
  'Read customer records': 'قراءة سجلات العملاء',
  'Release to the live site': 'النشر على الموقع العام',
  'Release to the test site': 'النشر على موقع الاختبار',
  'Change a domain\'s nameservers': 'تغيير خوادم الأسماء لنطاق',
  'Read a domain\'s records': 'قراءة سجلات نطاق',
  'Change a domain\'s record': 'تغيير سجل نطاق',
  'Write a document': 'كتابة مستند',
  'Sign a document': 'توقيع مستند',
  'Buy a domain': 'شراء نطاق',
  'Transfer a domain': 'نقل نطاق',
  'Draft an email': 'إعداد مسودة بريد إلكتروني',
  'Send an email': 'إرسال بريد إلكتروني',
  'List files': 'عرض قائمة الملفات',
  'Transfer money': 'تحويل أموال',
  'Propose a goal change': 'اقتراح تغيير هدف',
  'Make a picture': 'إنشاء صورة',
  'Issue an invoice': 'إصدار فاتورة',
  'Pay an invoice': 'دفع فاتورة',
  'Read the books': 'قراءة الدفاتر المحاسبية',
  'Read the mailbox': 'قراءة صندوق البريد',
  'Search what the company knows': 'البحث فيما تعرفه الشركة',
  'Record a measure': 'تسجيل قيمة مقياس',
  'Read product numbers': 'قراءة أرقام المنتج',
  'Ask you a question': 'طرح سؤال عليك',
  'Write down a plan': 'تدوين خطة',
  'Delete a record': 'حذف سجل',
  'Propose a code change': 'اقتراح تغيير في الشيفرة',
  'Read the code': 'قراءة الشيفرة',
  'Destroy a server': 'تدمير خادم',
  'Read a skill': 'قراءة مهارة',
  'Publish a post': 'نشر تدوينة',
  'Read text aloud': 'قراءة نص بصوت مسموع',
  'Turn speech into text': 'تحويل الكلام إلى نص',
  'Propose a new stage': 'اقتراح مرحلة جديدة',
  'Wait for work handed on': 'انتظار عمل مُسلَّم إلى الغير',
  'Hand work to another role': 'تسليم عمل إلى دور آخر',
  'File a ticket': 'فتح تذكرة',
  'List tickets': 'عرض قائمة التذاكر',
  'Check a service is up': 'التحقق من استجابة خدمة',
  'Read a web page': 'قراءة صفحة ويب',
  'Open a web page': 'فتح صفحة ويب',
  'Search the web': 'البحث في الويب',
};
