/**
 * Deutsch: what the platform itself says to the owner outside the console
 * (src/owner/say.ts), keyed by its English.
 *
 * The words are the console's (console/src/locales/de.ts): the owner is
 * "Sie"; Genehmigen, Ablehnen and Nachfragen on the buttons; "Diese Instanz,
 * Werkzeuge, Spracherkennung" for the screens it points at. WhatsApp cuts a
 * reply button's title at 20 characters and a list row's at 24, so those
 * stay short.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'Vorfall: {title}',
  'Done: {goal}': 'Erledigt: {goal}',
  'Stopped before finishing: {goal}': 'Vor dem Abschluss gestoppt: {goal}',
  'Not done: {goal}': 'Nicht erledigt: {goal}',
  'Why: {reason}': 'Grund: {reason}',
  'a task': 'eine Aufgabe',
  'Approval needed: {title}': 'Freigabe nötig: {title}',
  '{summary} — if denied: {consequence}': '{summary} – bei Ablehnung: {consequence}',
  '{role} asks:': '{role} fragt:',
  'If denied:': 'Bei Ablehnung:',
  'Expires:': 'Läuft ab:',
  'This one is decided in the app.': 'Darüber wird in der App entschieden.',
  'Open in PALUGADA': 'In PALUGADA öffnen',
  'Approve': 'Genehmigen',
  'Deny': 'Ablehnen',
  'Ask': 'Nachfragen',
  'Approved. Nothing left to press here.': 'Genehmigt. Hier gibt es nichts mehr zu tippen.',
  'Denied. Nothing left to press here.': 'Abgelehnt. Hier gibt es nichts mehr zu tippen.',
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    'Unbeantwortet abgelaufen. Schweigen gilt als Ablehnung, also wurde nichts getan.',
  'This bot only answers to its owner.': 'Dieser Bot antwortet nur seinem Inhaber.',
  'That one has to be approved in the app.': 'Das muss in der App genehmigt werden.',
  'That could not be recorded.': 'Das konnte nicht erfasst werden.',
  'That item no longer exists.': 'Diesen Eintrag gibt es nicht mehr.',
  'What do you want to ask about "{title}"? Reply to this message.':
    'Was möchten Sie zu „{title}“ fragen? Antworten Sie auf diese Nachricht.',
  'Your question': 'Ihre Frage',
  'Type your question as a reply.': 'Senden Sie Ihre Frage, indem Sie auf diese Nachricht antworten.',
  'Asked. The answer will be on the item in the app.': 'Gefragt. Die Antwort erscheint beim Eintrag in der App.',
  'Answer': 'Antworten',
  'Answer in words': 'Mit Worten antworten',
  'That choice is not on this question.': 'Diese Auswahl gehört nicht zu dieser Frage.',
  'Chosen: {choice}.': 'Gewählt: {choice}.',
  'Stop the task': 'Aufgabe stoppen',
  'Your answer to "{question}"? Reply to this message.': 'Ihre Antwort auf „{question}“? Antworten Sie auf diese Nachricht.',
  'Your answer': 'Ihre Antwort',
  'Type your answer as a reply.': 'Senden Sie Ihre Antwort, indem Sie auf diese Nachricht antworten.',
  'Answered. The task carries on with it.': 'Beantwortet. Die Aufgabe arbeitet damit weiter.',
  'That is too long for one question; keep it under {max} characters.':
    'Das ist zu lang für eine Frage; bleiben Sie unter {max} Zeichen.',
  '[a key, not kept]': '[ein Schlüssel, nicht gespeichert]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    'Das sieht wie ein Schlüssel aus, deshalb habe ich ihn weder gespeichert noch irgendwohin gesendet. Schlüssel gehören in das versiegelte Feld auf einer Karte oder auf ihre Seite unter „Diese Instanz“: Sagen Sie mir, wofür er ist, und ich lege Ihnen die Karte vor.',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'Es ist noch kein Modell eingerichtet, daher kann ich nicht denken. Wählen Sie eines unter „Diese Instanz, Modell“; dann kann ich bei allem anderen helfen.',
  'The model did not answer: {reason}': 'Das Modell hat nicht geantwortet: {reason}',
  'Here is what I propose.': 'Das schlage ich vor.',
  'I have nothing to add.': 'Ich habe nichts hinzuzufügen.',
  '{name}, CEO of {company}': '{name}, CEO von {company}',
  'That could not be answered: {reason}': 'Darauf konnte nicht geantwortet werden: {reason}',
  'I read text and voice notes.': 'Ich lese Texte und Sprachnachrichten.',
  'Now talking to {name}.': 'Sie sprechen jetzt mit {name}.',
  'Choose whom to talk to.': 'Wählen Sie, mit wem Sie sprechen.',
  'Choose whom to talk to': 'Gesprächspartner wählen',
  'Talk to PALUGADA about the whole deployment': 'Mit PALUGADA über die ganze Instanz sprechen',
  'Who you are talking to, and how': 'Mit wem Sie sprechen, und wie',
  'Stopped.': 'Gestoppt.',
  'Write here to talk to {name}.': 'Schreiben Sie hier, um mit {name} zu sprechen.',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    'Sie sprechen mit {name}. Schreiben Sie oder senden Sie eine Sprachnachricht. Mit /ceo wählen Sie, mit wem Sie sprechen; mit /palugada sprechen Sie mit PALUGADA über die ganze Instanz.',
  'You said: "{words}"': 'Sie haben gesagt: „{words}“',
  'in the app': 'in der App',
  'Apply: {summary}': 'Anwenden: {summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    'Noch hört nichts Sprache: Wählen Sie in der App einen Anbieter unter „Diese Instanz, Werkzeuge, Spracherkennung“.',
  'That recording is too long; keep a voice note under {max} MB.': 'Diese Aufnahme ist zu lang; halten Sie Sprachnachrichten unter {max} MB.',
  'I could not make out any words in that.': 'Darin konnte ich keine Wörter verstehen.',
  'Done: {summary}': 'Erledigt: {summary}',
  'That one is applied in the app.': 'Diese Karte wird in der App angewendet.',
  'That card no longer exists.': 'Diese Karte gibt es nicht mehr.',
  'That card was already applied.': 'Diese Karte wurde bereits angewendet.',
  'That card was dismissed.': 'Diese Karte wurde verworfen.',
  'That card failed when it was applied.': 'Diese Karte ist beim Anwenden fehlgeschlagen.',
  'That could not be done: {reason}': 'Das ließ sich nicht erledigen: {reason}',
  'Choose': 'Auswählen',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    'Was möchten Sie zu „{title}“ fragen? Antworten Sie auf diese Nachricht mit Ihrer Frage.',
  'Your answer to "{question}"? Reply to this message with your answer.':
    'Ihre Antwort auf „{question}“? Antworten Sie auf diese Nachricht mit Ihrer Antwort.',
  'I read text messages here.': 'Hier lese ich Textnachrichten.',
  'Apply one of these here:': 'Wenden Sie hier eine davon an:',
  'Apply {number}': '{number} anwenden',
  'Signed in to {provider} for the {alias} key': 'Bei {provider} für den Schlüssel {alias} angemeldet',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'Kehren Sie zu PALUGADA zurück: Die Abteilung hält diesen Schlüssel jetzt, und er wird vor Ablauf erneuert. Sie können diesen Tab schließen.',
  'Signed in to {name}': 'Bei {name} angemeldet',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'Kehren Sie zu PALUGADA zurück, um zu wählen, welche seiner Werkzeuge Rollen nutzen dürfen. Sie können diesen Tab schließen.',
  'Not signed in': 'Nicht angemeldet',
  'Recorded: approved.': 'Erfasst: genehmigt.',
  'Recorded: denied.': 'Erfasst: abgelehnt.',
  'Recorded: asked.': 'Erfasst: nachgefragt.',
  'Asked. Nothing left to press here.': 'Nachgefragt. Hier gibt es nichts mehr zu tippen.',
  'Withdrawn: the task it was asking about has finished.': 'Zurückgezogen: Die betreffende Aufgabe ist abgeschlossen.',
  'Withdrawn: the task it was asking about has failed.': 'Zurückgezogen: Die betreffende Aufgabe ist fehlgeschlagen.',
  'Withdrawn: the task it was asking about was stopped.': 'Zurückgezogen: Die betreffende Aufgabe wurde angehalten.',
  'Withdrawn: the task it was asking about was cancelled.': 'Zurückgezogen: Die betreffende Aufgabe wurde abgebrochen.',
  'Decided. Nothing left to press here.': 'Entschieden. Hier gibt es nichts mehr zu tippen.',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': 'Zurückgezogen: Der Agent schlägt jetzt etwas anderes vor und hat dafür erneut gefragt.',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': 'Zurückgezogen: Das Unternehmen ist nicht mehr in der Phase, aus der dieser Vorschlag es herausführen würde.',
  'Withdrawn: it was already decided in the app.': 'Zurückgezogen: Darüber wurde bereits in der App entschieden.',
  'Withdrawn. Nothing left to press here.': 'Zurückgezogen. Hier gibt es nichts mehr zu tippen.',
  'company': 'Unternehmen',
  'Work stopped: the {account} account is out of tokens': 'Arbeit gestoppt: Das Konto {account} hat keine Tokens mehr',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': '„{work}“ wurde gestoppt, weil das Konto {account} {spent} seiner {max} Tokens verbraucht hat. Erhöhen Sie unter Finanzen seine Obergrenze, öffnen Sie dann die Aufgabe und tippen Sie auf Fortsetzen: Sie macht dort weiter, wo sie aufgehört hat.',
  'Withdrawn: you continued the task it was about.': 'Zurückgezogen: Sie haben die betreffende Aufgabe fortgesetzt.',
  'Broke its contract': 'Vertrag gebrochen',
  'Refused by a policy': 'Von einer Richtlinie abgelehnt',
  'Out of budget': 'Budget erschöpft',
  'Handed on too many times': 'Zu oft weitergereicht',
  'Missed its deadline': 'Frist verpasst',
  'Its result did not check out': 'Ihr Ergebnis hat die Prüfung nicht bestanden',
  'A capability it needs is down': 'Eine benötigte Fähigkeit ist ausgefallen',
  'No runtime could take it': 'Keine Laufzeitumgebung konnte sie übernehmen',
  'Went in a circle': 'Im Kreis gelaufen',
  'Split into too many sub-tasks': 'In zu viele Teilaufgaben aufgeteilt',
  'Wrote more than its role allows one run': 'Mehr geschrieben, als ihre Rolle einem Lauf erlaubt',
  'Your approval was not given in time': 'Ihre Freigabe kam nicht rechtzeitig',
  'Stopped by you': 'Von Ihnen gestoppt',
  'Cancelled by you': 'Von Ihnen abgebrochen',
  'The company is frozen': 'Das Unternehmen ist eingefroren',
  'Its record did not match on replay': 'Ihr Protokoll stimmte bei der Wiederholung nicht überein',
  'It kept stopping the worker running it': 'Sie hat ihren Worker immer wieder zum Absturz gebracht',
  'Not done': 'Nicht erledigt',
  'Task failed': 'Aufgabe fehlgeschlagen',
  'Digest for {day}': 'Zusammenfassung für {day}',
  'Spent: {amount}': 'Ausgegeben: {amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': 'Arbeit: {done} erledigt, {failed} fehlgeschlagen, {stopped} gestoppt',
  'Inbox: {open} waiting (incidents: {incidents})': 'Posteingang: {open} offen (Vorfälle: {incidents})',
  'Stopped ({count}): {reason}': 'Gestoppt ({count}): {reason}',
  'Start an ad campaign': 'Werbekampagne starten',
  'Block time on the calendar': 'Zeit im Kalender blocken',
  'Read the calendar': 'Kalender lesen',
  'Run code': 'Code ausführen',
  'Add a note to a customer': 'Notiz zu einem Kunden hinzufügen',
  'Read customer records': 'Kundendaten lesen',
  'Release to the live site': 'Auf der Live-Website veröffentlichen',
  'Release to the test site': 'Auf der Test-Website veröffentlichen',
  'Change a domain\'s nameservers': 'Nameserver einer Domain ändern',
  'Read a domain\'s records': 'Einträge einer Domain lesen',
  'Change a domain\'s record': 'Eintrag einer Domain ändern',
  'Write a document': 'Dokument schreiben',
  'Sign a document': 'Dokument unterzeichnen',
  'Buy a domain': 'Domain kaufen',
  'Transfer a domain': 'Domain übertragen',
  'Draft an email': 'E-Mail entwerfen',
  'Send an email': 'E-Mail senden',
  'List files': 'Dateien auflisten',
  'Read a file': 'Eine Datei lesen',
  'Describe a picture': 'Ein Bild beschreiben',
  'Calculate in Python': 'Mit Python berechnen',
  'Transfer money': 'Geld überweisen',
  'Propose a goal change': 'Zieländerung vorschlagen',
  'Make a picture': 'Bild erzeugen',
  'Issue an invoice': 'Rechnung stellen',
  'Pay an invoice': 'Rechnung bezahlen',
  'Read the books': 'Buchhaltung einsehen',
  'Read the mailbox': 'Postfach lesen',
  'Search what the company knows': 'Wissen des Unternehmens durchsuchen',
  'Record a measure': 'Kennzahl erfassen',
  'Read product numbers': 'Produktzahlen lesen',
  'Ask you a question': 'Ihnen eine Frage stellen',
  'Write down a plan': 'Plan festhalten',
  'Delete a record': 'Datensatz löschen',
  'Propose a code change': 'Code-Änderung vorschlagen',
  'Read the code': 'Code lesen',
  'Destroy a server': 'Server endgültig löschen',
  'Read a skill': 'Skill lesen',
  'Publish a post': 'Beitrag veröffentlichen',
  'Read text aloud': 'Text vorlesen',
  'Turn speech into text': 'Sprache in Text umwandeln',
  'Propose a new stage': 'Neue Phase vorschlagen',
  'Wait for work handed on': 'Auf weitergegebene Arbeit warten',
  'Hand work to another role': 'Arbeit an eine andere Rolle weitergeben',
  'File a ticket': 'Vorgang anlegen',
  'List tickets': 'Vorgänge auflisten',
  'Check a service is up': 'Prüfen, ob ein Dienst läuft',
  'Read a web page': 'Webseite lesen',
  'Open a web page': 'Webseite öffnen',
  'Search the web': 'Im Web suchen',
  'no stage': 'keine Phase',
  'Explore': 'Erkunden',
  'Validate': 'Validieren',
  'Build': 'Aufbauen',
  'Launch': 'Markteinführung',
  'Grow': 'Wachsen',
  'Wind down': 'Abwickeln',
  'Monthly budget reached; the company is paused': 'Monatsbudget erreicht; das Unternehmen ist pausiert',
  '{spent} of {limit} spent since {since}. No new task will start and no external action will run until you raise the ceiling or allow spending past it for a while, under Money.': 'Seit dem {since} wurden {spent} von {limit} ausgegeben. Es startet keine neue Aufgabe und keine externe Aktion wird ausgeführt, bis Sie unter Finanzen die Obergrenze erhöhen oder Ausgaben darüber hinaus befristet erlauben.',
  'Monthly budget is 80% spent': 'Monatsbudget zu 80 % ausgegeben',
  '{spent} of {limit} spent since {since}. At 100% the company pauses.': 'Seit dem {since} wurden {spent} von {limit} ausgegeben. Bei 100 % wird das Unternehmen pausiert.',
  'Role {role} is paused for spending too fast': 'Rolle {role} wegen zu schneller Ausgaben pausiert',
  '{role} spent {spent} in the last hour, {multiple} times its usual {usual} an hour. It is paused before the monthly ceiling is reached, so there is money left to work with once you have found out why. Resume it when you have.': '{role} hat in der letzten Stunde {spent} ausgegeben, das {multiple}-Fache der üblichen {usual} pro Stunde. Die Rolle wird pausiert, bevor die monatliche Obergrenze erreicht ist, damit noch Geld zum Arbeiten bleibt, sobald Sie den Grund gefunden haben. Setzen Sie die Rolle dann fort.',
  'Daily model spend over threshold': 'Tägliche Modellausgaben über der Schwelle',
  'Model spend today is {spent}, over the {limit} ceiling.': 'Die Modellausgaben liegen heute bei {spent} und damit über der Obergrenze von {limit}.',
  'Task failure rate over threshold': 'Fehlerquote der Aufgaben über der Schwelle',
  '{failed} of {finished} tasks failed or stopped today ({rate}%), over the {limit}% threshold.': '{failed} von {finished} Aufgaben sind heute fehlgeschlagen oder wurden gestoppt ({rate} %), über der Schwelle von {limit} %.',
  'Unusual number of policy refusals': 'Ungewöhnlich viele Ablehnungen durch Richtlinien',
  'Actions refused by a policy today: {count}, over the threshold of {limit}. Either an agent is probing its limits or a policy is miscalibrated.': 'Heute von einer Richtlinie abgelehnte Aktionen: {count}, über der Schwelle von {limit}. Entweder testet ein Agent seine Grenzen aus, oder eine Richtlinie ist falsch eingestellt.',
  'External writes failed verification': 'Externe Schreibvorgänge haben die Prüfung nicht bestanden',
  'Writes outside that reported success but read back differently: {count}. Something is changing them other than as asked.': 'Schreibvorgänge nach außen, die als erfolgreich gemeldet wurden, beim Zurücklesen aber anders aussahen: {count}. Etwas verändert sie anders als verlangt.',
  'A capability stopped being usable': 'Eine Fähigkeit ist nicht mehr nutzbar',
  'Tasks that could not start today because a capability their role needs failed its check: {count}. A credential has probably expired or a quota is used up.': 'Aufgaben, die heute nicht starten konnten, weil eine Fähigkeit, die ihre Rolle braucht, ihre Prüfung nicht bestanden hat: {count}. Wahrscheinlich sind Zugangsdaten abgelaufen oder ein Kontingent ist aufgebraucht.',
  'A worker stopped reporting mid-run': 'Ein Worker hat sich mitten im Lauf nicht mehr gemeldet',
  'Runs that stopped reporting and were taken back today: {count}. The work was picked up again; the tokens they had already spent were not recovered.': 'Läufe, die sich heute nicht mehr gemeldet haben und zurückgeholt wurden: {count}. Die Arbeit wurde wieder aufgenommen; die Tokens, die sie bereits verbraucht hatten, sind verloren.',
  '{role} was refused {denials} times today, at the limit of {limit}. No task will run as this role until you lift the freeze. The usual causes are a missing capability grant, a policy the role\'s charter does not account for, or work the role was never equipped to do.': '{role} wurde heute {denials}-mal abgelehnt und hat damit die Grenze von {limit} erreicht. Keine Aufgabe läuft mehr als diese Rolle, bis Sie das Einfrieren aufheben. Die üblichen Ursachen sind eine fehlende Berechtigung für eine Fähigkeit, eine Richtlinie, die die Charta der Rolle nicht berücksichtigt, oder Arbeit, für die die Rolle nie ausgestattet war.',
  'Role {role} is frozen after repeated denials': 'Rolle {role} nach wiederholten Ablehnungen eingefroren',
  'What it was refused: {capabilities}': 'Abgelehnt wurde: {capabilities}',
  'It is waiting for an approval, and none is open, so nothing you can answer will move it.': 'Die Aufgabe wartet auf eine Freigabe, aber es ist keine offen, daher bringt sie keine Antwort von Ihnen weiter.',
  'It is waiting for a review, and none is pending, so no reviewer and no decision of yours will move it.': 'Die Aufgabe wartet auf eine Prüfung, aber es steht keine an, daher bringen sie weder ein Prüfer noch eine Entscheidung von Ihnen weiter.',
  'It is parked until a window reopens, and the window never does.': 'Die Aufgabe ist geparkt, bis sich ein Zeitfenster wieder öffnet, aber dieses Zeitfenster öffnet sich nie.',
  'A task is waiting on nothing': 'Eine Aufgabe wartet auf nichts',
  '"{task}" has been waiting since {since}. {why} Approve to run it again from where it stopped, or deny to cancel it.': 'Die Aufgabe „{task}“ wartet seit {since}. {why} Mit „Genehmigen“ wird sie ab der Stelle, an der sie stehen geblieben ist, erneut ausgeführt; mit „Ablehnen“ wird sie abgebrochen.',
  'A task keeps stopping the worker running it': 'Eine Aufgabe bringt ihren Worker immer wieder zum Absturz',
  '"{task}" lost its worker {lost} times: each time the worker running it stopped answering before the work finished. What it had done is kept. It is halted so it cannot take another worker down; run it again once the cause is found, or cancel it.': 'Die Aufgabe „{task}“ hat ihren Worker {lost}-mal verloren: Jedes Mal hat der ausführende Worker nicht mehr geantwortet, bevor die Arbeit fertig war. Was sie bereits erledigt hatte, bleibt erhalten. Sie ist angehalten, damit sie keinen weiteren Worker lahmlegt; führen Sie sie erneut aus, sobald die Ursache gefunden ist, oder brechen Sie sie ab.',
  '{services} stayed unreachable, and the work that needs it stopped': 'Nicht erreichbar: {services} – die Arbeit, die darauf angewiesen ist, wurde gestoppt',
  'The task waited about {minutes} minutes, looking again each time, and has stopped. Once the service answers, run it again.': 'Die Aufgabe hat etwa {minutes} Min. gewartet, immer wieder nachgesehen und ist jetzt gestoppt. Sobald der Dienst antwortet, führen Sie sie erneut aus.',
  'It was tried {tries} times over about {minutes} minutes.': 'Es wurde {tries}-mal in etwa {minutes} Min. versucht.',
  'This role can take actions that cannot be undone, so the run was not silently moved to a different model.': 'Diese Rolle kann unumkehrbare Aktionen ausführen, deshalb wurde der Lauf nicht stillschweigend auf ein anderes Modell verlegt.',
  'No fallback model is left for this role.': 'Für diese Rolle ist kein Ausweichmodell mehr übrig.',
  'Model {model} failed and the run was not moved': 'Modell {model} ist ausgefallen, und der Lauf wurde nicht verlegt',
  'External write failed verification': 'Externer Schreibvorgang hat die Prüfung nicht bestanden',
  'The task wrote to an outside service and read it back, and what it read did not match. Look at the place it wrote to before you run it again: the write may have happened.': 'Die Aufgabe hat in einen externen Dienst geschrieben und es zurückgelesen, und das Gelesene stimmte nicht überein. Sehen Sie dort nach, wohin sie geschrieben hat, bevor Sie sie noch einmal ausführen: Der Schreibvorgang ist vielleicht schon erfolgt.',
  'Review deadlocked after {rounds} revisions: {capability}': 'Prüfung nach {rounds} Überarbeitungen festgefahren: {capability}',
  'The role and its reviewer did not agree on {capability}.': 'Die Rolle und ihr Prüfer haben sich bei „{capability}“ nicht geeinigt.',
  'The reviewer\'s last note: {note}': 'Letzte Anmerkung des Prüfers: {note}',
  'The reviewer left no note.': 'Der Prüfer hat keine Anmerkung hinterlassen.',
  'What it was judged against: {criteria}': 'Woran es gemessen wurde: {criteria}',
  'Review produced no usable verdict: {capability}': 'Prüfung ohne verwertbares Urteil: {capability}',
  'The reviewing task ended without a decision that could be read. The proposed action is still blocked and needs your judgement.': 'Die prüfende Aufgabe endete ohne eine lesbare Entscheidung. Die vorgeschlagene Aktion bleibt blockiert und braucht Ihr Urteil.',
  'another stage': 'eine andere Phase',
  'Either answer only closes this: the company stays in the {stage} stage.': 'Beide Antworten schließen nur diesen Eintrag: Das Unternehmen bleibt in der Phase {stage}.',
  'Either answer only closes this: the company stays without a stage.': 'Beide Antworten schließen nur diesen Eintrag: Das Unternehmen bleibt ohne Phase.',
  'To move it anyway, set the stage on the Overview.': 'Um es trotzdem zu versetzen, legen Sie die Phase in der Übersicht fest.',
  '{reviewer} stopped a proposal to move the company from {from} to {to}': '{reviewer} hat den Vorschlag gestoppt, das Unternehmen von „{from}“ in „{to}“ zu versetzen',
  '{reviewer} reviewed it before you and stopped it:': '{reviewer} hat ihn vor Ihnen geprüft und gestoppt:',
  'No reason was given.': 'Es wurde kein Grund angegeben.',
  'What was proposed:': 'Vorgeschlagen wurde:',
  'The company stays in the {stage} stage.': 'Das Unternehmen bleibt in der Phase {stage}.',
  'The company stays without a stage.': 'Das Unternehmen bleibt ohne Phase.',
  'Move the company from {from} to {to}?': 'Unternehmen von „{from}“ in „{to}“ versetzen?',
  'Reviewed by {reviewer} before you:': 'Vor Ihnen geprüft von {reviewer}:',
  'The schedule "{schedule}" keeps producing the same result': 'Der Zeitplan „{schedule}“ liefert immer wieder dasselbe Ergebnis',
  'Its last {runs} runs all ended with the same output. That is sometimes exactly right -- a report with nothing new to say -- and often a schedule that stopped doing anything useful while still being paid for. Deny to turn it off; approve to keep it running and not be asked about this result again.': 'Seine letzten {runs} Läufe endeten alle mit derselben Ausgabe. Manchmal ist das genau richtig – ein Bericht, der nichts Neues zu sagen hat –, oft aber ist es ein Zeitplan, der nichts Nützliches mehr tut und trotzdem bezahlt wird. „Ablehnen“ schaltet ihn aus; „Genehmigen“ lässt ihn weiterlaufen, und Sie werden zu diesem Ergebnis nicht mehr gefragt.',
  'Capability {capability} failed preflight': 'Fähigkeit „{capability}“ hat die Vorabprüfung nicht bestanden',
  'Work that needs it is stopped rather than started: fix the cause, then run that work again. The usual causes are an expired or wrongly scoped credential, a quota used up, or an address that is wrong.': 'Arbeit, die sie braucht, wird gestoppt statt gestartet: Beheben Sie die Ursache und führen Sie diese Arbeit dann erneut aus. Die üblichen Ursachen sind abgelaufene oder mit falschem Umfang ausgestellte Zugangsdaten, ein aufgebrauchtes Kontingent oder eine falsche Adresse.',
  'Batch guard stopped {capability}': 'Stapelprüfung hat „{capability}“ gestoppt',
  'It did not match the plan its run recorded. Nothing was sent, and no service was called.': 'Der Aufruf passte nicht zu dem Plan, den sein Lauf erfasst hatte. Es wurde nichts gesendet und kein Dienst aufgerufen.',
  '{role} was asked first and has had {minutes} minutes.': '{role} wurde zuerst gefragt und hatte {minutes} Min. Zeit.',
  '{role} is not a role in this company, so this came to you at once.': '{role} ist keine Rolle in diesem Unternehmen, deshalb kam dies sofort zu Ihnen.',
  '{role} could not be given this: the company has no active goal or project to hang it from.': '{role} konnte dies nicht übertragen werden: Das Unternehmen hat kein aktives Ziel und kein Projekt, dem es zugeordnet werden könnte.',
  '{role} could not be given this ({record}), so this came to you at once.': '{role} konnte dies nicht übertragen werden ({record}), deshalb kam es sofort zu Ihnen.',
  '{role} stopped without an account of what it did ({why}).': '{role} hat angehalten, ohne zu berichten, was getan wurde ({why}).',
  '{role} finished without an account of what it did.': '{role} hat abgeschlossen, ohne zu berichten, was getan wurde.',
  '{role} failed without an account of what it did.': '{role} ist gescheitert, ohne zu berichten, was getan wurde.',
  '{role} was stopped without an account of what it did.': '{role} wurde gestoppt, ohne zu berichten, was getan wurde.',
  'Proposed change to the {kind} "{goal}"': 'Änderungsvorschlag für {kind} „{goal}“',
  'Currently: {statement}': 'Derzeit: {statement}',
  'Currently: {statement} ({status})': 'Derzeit: {statement} ({status})',
  'Proposed: {statement}': 'Vorgeschlagen: {statement}',
  'Proposed status: {status}': 'Vorgeschlagener Status: {status}',
  'Reason given: {reason}': 'Angegebener Grund: {reason}',
  'Record an entry in the books': 'Eine Buchung erfassen',
  'Record a customer or a deal': 'Einen Kunden oder ein Geschäft festhalten',
  'Not sent on its own: {reason}': 'Nicht selbst gesendet: {reason}',
  'it answers a conversation other than the one this work began with': 'sie antwortet in einer anderen Unterhaltung als der, mit der diese Arbeit begann',
  'it named no passage of a document for customers': 'sie nannte keinen Abschnitt eines Dokuments für Kunden',
  'it answers from a document not marked for customers': 'sie antwortet aus einem Dokument, das nicht für Kunden markiert ist',
  'it says a figure the documents and the customer did not: {detail}': 'sie nennt eine Zahl, die weder in den Dokumenten noch beim Kunden steht: {detail}',
  'it gives an address or link the documents and the customer did not: {detail}': 'sie nennt eine Adresse oder einen Link, die weder in den Dokumenten noch beim Kunden stehen: {detail}',
  'there have been six answers on its own in this conversation in the last hour': 'in dieser Unterhaltung gab es in der letzten Stunde schon sechs selbst gesendete Antworten',
  'the check found it is about a refund': 'die Prüfung fand, dass es um eine Erstattung geht',
  'the check found it offers a price or terms of its own': 'die Prüfung fand, dass sie einen eigenen Preis oder eigene Bedingungen anbietet',
  'the check found it answers a serious complaint': 'die Prüfung fand, dass sie auf eine ernste Beschwerde antwortet',
  'the check found it touches the law': 'die Prüfung fand, dass sie Rechtliches berührt',
  'the check found it gives or asks for personal data': 'die Prüfung fand, dass sie personenbezogene Daten gibt oder erfragt',
  'the check found it promises something the documents do not': 'die Prüfung fand, dass sie etwas verspricht, was die Dokumente nicht sagen',
  'the check could not judge it': 'die Prüfung konnte es nicht beurteilen',
  'the check found something in it the documents do not say': 'die Prüfung fand darin etwas, was die Dokumente nicht sagen',
  '{role} proposes the schedule {name}': '{role} schlägt den Zeitplan {name} vor',
  'Each run: {instruction}': 'Bei jedem Lauf: {instruction}',
  'Done by: {role}': 'Ausgeführt von: {role}',
  'When: {cron} ({timezone}); the next runs are {runs}': 'Wann: {cron} ({timezone}); die nächsten Läufe sind {runs}',
  'Approving it makes the schedule and starts it; it can be turned off or changed under Team, Schedules.': 'Die Genehmigung legt den Zeitplan an und startet ihn; er lässt sich unter Team, Zeitpläne abschalten oder ändern.',
  'No schedule is made.': 'Es wird kein Zeitplan angelegt.',
  'Propose a schedule': 'Einen Zeitplan vorschlagen',
  'Approving it changes the goal; until then the work carries on under the goal as it is.': 'Eine Genehmigung ändert das Ziel; bis dahin geht die Arbeit unter dem bisherigen Ziel weiter.',
  'The goal stays as it is.': 'Das Ziel bleibt, wie es ist.',
  'mission': 'Mission',
  'objective': 'Ziel',
  'key result': 'Schlüsselergebnis',
  'Active': 'Aktiv',
  'Met': 'Erreicht',
  'Abandoned': 'Aufgegeben',
  'This work asked for it at tier {tier}, and policy {policies} requires your approval.': 'Diese Arbeit hat dies auf Stufe {tier} angefordert, und die Richtlinie {policies} verlangt Ihre Freigabe.',
  'This work asked for it at tier {tier}, and the task began with content from outside the company.': 'Diese Arbeit hat dies auf Stufe {tier} angefordert, und die Aufgabe begann mit Inhalten von außerhalb des Unternehmens.',
  'This work asked for it at tier {tier}, and the work read content from outside the company before asking.': 'Diese Arbeit hat dies auf Stufe {tier} angefordert, und sie hat vorher Inhalte von außerhalb des Unternehmens gelesen.',
  'This work asked for it at tier {tier}, after the work read content from outside the company, and the guardian asked you first: {reason}': 'Diese Arbeit hat dies auf Stufe {tier} angefordert, nachdem sie Inhalte von außerhalb des Unternehmens gelesen hatte, und der Wächter fragt zuerst Sie: {reason}',
  'it doubted this call before, and you allowed it once': 'er hatte diesen Aufruf schon einmal angezweifelt, und Sie haben ihn einmal erlaubt',
  'This work asked for it at tier {tier}, which cannot be reversed.': 'Diese Arbeit hat dies auf Stufe {tier} angefordert, die sich nicht rückgängig machen lässt.',
  'You approved this once already, and the worker carrying it out stopped before it could say whether it happened: it may already have happened. Check before approving it again.': 'Sie haben dies bereits einmal genehmigt, und der ausführende Worker hat angehalten, bevor er melden konnte, ob es geschehen ist: Es ist vielleicht schon geschehen. Prüfen Sie das, bevor Sie es erneut genehmigen.',
  'What this is for — {goals}': 'Wozu es dient – {goals}',
  'The task halts and no external change is made.': 'Die Aufgabe hält an, und es wird keine externe Änderung vorgenommen.',
  'Scored against {total} references: {passed} passed, {failed} failed.': 'Bewertet anhand von {total} Referenzen: {passed} bestanden, {failed} nicht bestanden.',
  'This role has fewer than {minimum} accepted references, so the change is unscored. That is not the same as passing.': 'Diese Rolle hat weniger als {minimum} akzeptierte Referenzen, daher ist die Änderung unbewertet. Das ist nicht dasselbe wie bestanden.',
  'The role keeps working exactly as it does now.': 'Die Rolle arbeitet genau so weiter wie bisher.',
  '{role} asks: {question}': '{role} fragt: {question}',
  'The run did not say more than the question.': 'Der Lauf hat nicht mehr als die Frage gesagt.',
  'The task is stopped, and nothing it was going to do happens.': 'Die Aufgabe wird gestoppt, und nichts von dem, was sie vorhatte, geschieht.',
  'You proposed it.': 'Sie haben ihn vorgeschlagen.',
  'It came with a bundle.': 'Er stammt aus einem Paket.',
  'An agent proposed it.': 'Ein Agent hat ihn vorgeschlagen.',
  'It was learned from the company\'s work.': 'Er wurde aus der Arbeit des Unternehmens gelernt.',
  'Skill "{skill}", version {version}': 'Skill „{skill}“, Version {version}',
  'The reviewer approved it: {note}': 'Der Prüfer hat ihn genehmigt: {note}',
  'The reviewer approved it.': 'Der Prüfer hat ihn genehmigt.',
  'Nothing changes; the current version of the skill stays in force.': 'Es ändert sich nichts; die aktuelle Version des Skills bleibt in Kraft.',
  'Skills the bundle "{bundle}" brings: {count}': 'Skills, die das Paket „{bundle}“ mitbringt: {count}',
  'The reviewer read them all and approved these:': 'Der Prüfer hat alle gelesen und diese genehmigt:',
  'It turned these down, and they stay off:': 'Diese hat er abgelehnt, sie bleiben ausgeschaltet:',
  'Approve to switch them all on, or deny to turn them all down. To decide one at a time, open the Skills page.': 'Mit „Genehmigen“ werden alle eingeschaltet, mit „Ablehnen“ alle abgelehnt. Um einzeln zu entscheiden, öffnen Sie die Seite „Skills“.',
  'Nothing changes; none of these skills is switched on.': 'Es ändert sich nichts; keiner dieser Skills wird eingeschaltet.',
  'I am {ceo}, and I run {company} for you. Three things before we start: what does {company} sell, and to whom? How much may it spend in a month? And what should its first piece of work be -- or shall I suggest one?': 'Ich bin {ceo} und führe {company} für Sie. Drei Dinge, bevor wir anfangen: Was verkauft {company}, und an wen? Wie viel darf das Unternehmen im Monat ausgeben? Und was soll die erste Aufgabe sein – oder soll ich eine vorschlagen?',
  'Read a customer conversation': 'Ein Kundengespräch lesen',
  'Reply to a customer': 'Einem Kunden antworten',
  'Read a page in the browser': 'Seite im Browser lesen',
  'Fill in a page in the browser': 'Seite im Browser ausfüllen',
  'Ask you to take over the browser': 'Bittet Sie, den Browser zu übernehmen',
  '{host} refused the model key ({status}), so nothing that needs the model can run. Open Settings, This deployment, Model, paste a key that works, test it and save.':
    '{host} hat den Schlüssel des Modells abgelehnt ({status}), daher kann keine Arbeit laufen, die das Modell braucht. Öffnen Sie Einstellungen, Diese Instanz, Modell, fügen Sie einen funktionierenden Schlüssel ein, testen Sie ihn und speichern Sie.',
  '{host} refused the model key, and work is waiting': '{host} hat den Modellschlüssel abgelehnt, und die Arbeit wartet',
  'What is waiting for the model carries on by itself once a key that works is in use.':
    'Arbeit, die auf das Modell wartet, läuft von selbst weiter, sobald ein funktionierender Schlüssel verwendet wird.',
  'A task ended before it was done: {task}':
    'Eine Aufgabe endete, bevor sie fertig war: {task}',
  'It ended as: {reason}. No other card was raised for it, so it is here rather than silent.':
    'Sie endete so: {reason}. Für sie wurde keine andere Karte angelegt, deshalb steht sie hier und nicht stumm.',
  'Where its measures stand, as the platform reads them:':
    'Wo seine Kennzahlen stehen, so wie die Plattform sie liest:',
  '{name}: no value recorded yet, against a target of {target}.':
    '{name}: noch kein Wert erfasst, bei einem Ziel von {target}.',
  '{name}: {value} against a target of {target}, read back from its source.':
    '{name}: {value} bei einem Ziel von {target}, an der Quelle erneut gelesen.',
  '{name}: {value} against a target of {target}, reported and not checked.':
    '{name}: {value} bei einem Ziel von {target}, gemeldet und nicht geprüft.',
  'Look at it again later': 'Später erneut ansehen',
};
