/**
 * Español: what the platform itself says to the owner outside the console
 * (src/owner/say.ts), keyed by its English.
 *
 * The words are the console's (console/src/locales/es.ts): the owner is
 * «usted»; Aprobar, Rechazar and Preguntar on the buttons; «Esta instancia,
 * Herramientas, Escucha» for the screens it points at. WhatsApp cuts a reply
 * button's title at 20 characters and a list row's at 24, so those stay short.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'Incidente: {title}',
  'Done: {goal}': 'Terminada: {goal}',
  'Stopped before finishing: {goal}': 'Detenida antes de terminar: {goal}',
  'Not done: {goal}': 'No hecha: {goal}',
  'Why: {reason}': 'Motivo: {reason}',
  'a task': 'una tarea',
  'Approval needed: {title}': 'Se necesita su aprobación: {title}',
  '{summary} — if denied: {consequence}': '{summary} — si se rechaza: {consequence}',
  '{role} asks:': '{role} pregunta:',
  'If denied:': 'Si se rechaza:',
  'Expires:': 'Caduca:',
  'This one is decided in the app.': 'Esta decisión se toma en la app.',
  'Open in PALUGADA': 'Abrir en PALUGADA',
  'Approve': 'Aprobar',
  'Deny': 'Rechazar',
  'Ask': 'Preguntar',
  'Approved. Nothing left to press here.': 'Aprobado. Aquí ya no queda nada que pulsar.',
  'Denied. Nothing left to press here.': 'Rechazado. Aquí ya no queda nada que pulsar.',
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    'Caducó sin respuesta. El silencio equivale a un rechazo, así que no se hizo nada.',
  'This bot only answers to its owner.': 'Este bot solo responde a su propietario.',
  'That one has to be approved in the app.': 'Eso hay que aprobarlo en la app.',
  'That could not be recorded.': 'No se pudo registrar.',
  'That item no longer exists.': 'Ese elemento ya no existe.',
  'What do you want to ask about "{title}"? Reply to this message.':
    '¿Qué quiere preguntar sobre «{title}»? Responda a este mensaje.',
  'Your question': 'Su pregunta',
  'Type your question as a reply.': 'Escriba su pregunta respondiendo a este mensaje.',
  'Asked. The answer will be on the item in the app.': 'Pregunta enviada. La respuesta aparecerá en el elemento, en la app.',
  'Answer': 'Responder',
  'Answer in words': 'Responder por escrito',
  'That choice is not on this question.': 'Esa opción no forma parte de esta pregunta.',
  'Chosen: {choice}.': 'Elegido: {choice}.',
  'Stop the task': 'Detener la tarea',
  'Your answer to "{question}"? Reply to this message.': '¿Su respuesta a «{question}»? Responda a este mensaje.',
  'Your answer': 'Su respuesta',
  'Type your answer as a reply.': 'Escriba su respuesta respondiendo a este mensaje.',
  'Answered. The task carries on with it.': 'Respondido. La tarea continúa con su respuesta.',
  'That is too long for one question; keep it under {max} characters.':
    'Es demasiado largo para una pregunta; no pase de {max} caracteres.',
  '[a key, not kept]': '[una clave, no guardada]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    'Eso parece una clave, así que no la he guardado ni enviado a ningún sitio. Las claves van en el campo sellado de una tarjeta, o en su página dentro de Esta instancia: dígame para qué es y le presentaré la tarjeta.',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'Aún no hay ningún modelo configurado, así que no puedo pensar. Elija uno en Esta instancia, Modelo; después podré ayudarle con todo lo demás.',
  'The model did not answer: {reason}': 'El modelo no respondió: {reason}',
  'Here is what I propose.': 'Esto es lo que propongo.',
  'I have nothing to add.': 'No tengo nada que añadir.',
  '{name}, CEO of {company}': '{name}, CEO de {company}',
  'That could not be answered: {reason}': 'No se pudo responder: {reason}',
  'I read text and voice notes.': 'Leo texto y notas de voz.',
  'Now talking to {name}.': 'Ahora habla con {name}.',
  'Choose whom to talk to.': 'Elija con quién hablar.',
  'Choose whom to talk to': 'Elegir con quién hablar',
  'Talk to PALUGADA about the whole deployment': 'Hablar con PALUGADA sobre toda la instancia',
  'Who you are talking to, and how': 'Con quién habla y cómo',
  'Stopped.': 'Detenido.',
  'Write here to talk to {name}.': 'Escriba aquí para hablar con {name}.',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    'Está hablando con {name}. Escriba o envíe una nota de voz. /ceo elige con quién habla; /palugada habla con PALUGADA sobre toda la instancia.',
  'You said: "{words}"': 'Usted dijo: «{words}»',
  'in the app': 'en la app',
  'Apply: {summary}': 'Aplicar: {summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    'Todavía nada puede oír la voz: elija un proveedor en la app, en Esta instancia, Herramientas, Escucha.',
  'That recording is too long; keep a voice note under {max} MB.': 'Esa grabación es demasiado larga; una nota de voz debe ocupar menos de {max} MB.',
  'I could not make out any words in that.': 'No he podido distinguir ninguna palabra.',
  'Done: {summary}': 'Hecho: {summary}',
  'That one is applied in the app.': 'Esa se aplica en la app.',
  'That card no longer exists.': 'Esa tarjeta ya no existe.',
  'That card was already applied.': 'Esa tarjeta ya se aplicó.',
  'That card was dismissed.': 'Esa tarjeta se descartó.',
  'That card failed when it was applied.': 'Esa tarjeta falló al aplicarse.',
  'That could not be done: {reason}': 'No se pudo hacer: {reason}',
  'Choose': 'Elegir',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    '¿Qué quiere preguntar sobre «{title}»? Responda a este mensaje con su pregunta.',
  'Your answer to "{question}"? Reply to this message with your answer.':
    '¿Su respuesta a «{question}»? Responda a este mensaje con su respuesta.',
  'I read text messages here.': 'Aquí leo mensajes de texto.',
  'Apply one of these here:': 'Aplique aquí una de estas:',
  'Apply {number}': 'Aplicar {number}',
  'Signed in to {provider} for the {alias} key': 'Sesión iniciada en {provider} para la clave {alias}',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'Vuelva a PALUGADA: la división ya tiene esta clave, y se renueva antes de que caduque. Puede cerrar esta pestaña.',
  'Signed in to {name}': 'Sesión iniciada en {name}',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'Vuelva a PALUGADA para elegir cuáles de sus herramientas pueden usar los roles. Puede cerrar esta pestaña.',
  'Not signed in': 'Sin sesión iniciada',
  'Recorded: approved.': 'Registrado: aprobado.',
  'Recorded: denied.': 'Registrado: rechazado.',
  'Recorded: asked.': 'Registrado: pregunta enviada.',
  'Asked. Nothing left to press here.': 'Pregunta enviada. Aquí ya no queda nada que pulsar.',
  'Withdrawn: the task it was asking about has finished.': 'Retirado: la tarea sobre la que preguntaba ha terminado.',
  'Withdrawn: the task it was asking about has failed.': 'Retirado: la tarea sobre la que preguntaba ha fallado.',
  'Withdrawn: the task it was asking about was stopped.': 'Retirado: la tarea sobre la que preguntaba se detuvo.',
  'Withdrawn: the task it was asking about was cancelled.': 'Retirado: la tarea sobre la que preguntaba se canceló.',
  'Decided. Nothing left to press here.': 'Decidido. Aquí ya no queda nada que pulsar.',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': 'Retirado: el agente cambió lo que propone y le volvió a preguntar por la nueva propuesta.',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': 'Retirado: la empresa ya no está en la etapa de la que esta propuesta la sacaría.',
  'Withdrawn: it was already decided in the app.': 'Retirado: ya se decidió en la app.',
  'Withdrawn. Nothing left to press here.': 'Retirado. Aquí ya no queda nada que pulsar.',
  'company': 'empresa',
  'Work stopped: the {account} account is out of tokens': 'El trabajo se detuvo: la cuenta {account} se quedó sin tokens',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': '“{work}” se detuvo porque la cuenta {account} ha usado {spent} de sus {max} tokens. Sube su límite en Dinero, luego abre la tarea y pulsa Continuar: seguirá desde donde se detuvo.',
  'Withdrawn: you continued the task it was about.': 'Retirado: continuaste la tarea a la que se refería.',
  'Broke its contract': 'Incumplió su contrato',
  'Refused by a policy': 'Rechazado por una política',
  'Out of budget': 'Sin presupuesto',
  'Handed on too many times': 'Traspasada demasiadas veces',
  'Missed its deadline': 'No cumplió su plazo',
  'Its result did not check out': 'Su resultado no pasó la comprobación',
  'A capability it needs is down': 'Una capacidad que necesita no está disponible',
  'No runtime could take it': 'Ningún entorno de ejecución pudo encargarse de ella',
  'Went in a circle': 'Entró en un bucle',
  'Split into too many sub-tasks': 'Dividida en demasiadas subtareas',
  'Wrote more than its role allows one run': 'Escribió más de lo que su rol permite en una ejecución',
  'Your approval was not given in time': 'Su aprobación no llegó a tiempo',
  'Stopped by you': 'Detenida por usted',
  'Cancelled by you': 'Cancelada por usted',
  'The company is frozen': 'La empresa está congelada',
  'Its record did not match on replay': 'Su registro no coincidió al reproducirlo',
  'It kept stopping the worker running it': 'Hizo caer una y otra vez al ejecutor que la procesaba',
  'Not done': 'No hecha',
  'Task failed': 'Tarea fallida',
  'Digest for {day}': 'Resumen del {day}',
  'Spent: {amount}': 'Gastado: {amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': 'Trabajo — terminadas: {done}, fallidas: {failed}, detenidas: {stopped}',
  'Inbox: {open} waiting (incidents: {incidents})': 'Bandeja de entrada: {open} en espera (incidentes: {incidents})',
  'Stopped ({count}): {reason}': 'Detenidas ({count}): {reason}',
  'Start an ad campaign': 'Iniciar una campaña publicitaria',
  'Block time on the calendar': 'Reservar tiempo en el calendario',
  'Read the calendar': 'Leer el calendario',
  'Run code': 'Ejecutar código',
  'Add a note to a customer': 'Añadir una nota a un cliente',
  'Read customer records': 'Leer los registros de clientes',
  'Release to the live site': 'Publicar en el sitio público',
  'Release to the test site': 'Publicar en el sitio de pruebas',
  'Change a domain\'s nameservers': 'Cambiar los servidores de nombres de un dominio',
  'Read a domain\'s records': 'Leer los registros de un dominio',
  'Change a domain\'s record': 'Cambiar un registro de un dominio',
  'Write a document': 'Redactar un documento',
  'Sign a document': 'Firmar un documento',
  'Buy a domain': 'Comprar un dominio',
  'Transfer a domain': 'Transferir un dominio',
  'Draft an email': 'Crear un borrador de correo',
  'Send an email': 'Enviar un correo',
  'List files': 'Listar archivos',
  'Read a file': 'Leer un archivo',
  'Describe a picture': 'Describir una imagen',
  'Calculate in Python': 'Calcular con Python',
  'Transfer money': 'Transferir dinero',
  'Propose a goal change': 'Proponer un cambio de meta',
  'Make a picture': 'Crear una imagen',
  'Issue an invoice': 'Emitir una factura',
  'Pay an invoice': 'Pagar una factura',
  'Read the books': 'Consultar la contabilidad',
  'Read the mailbox': 'Leer el buzón de correo',
  'Search what the company knows': 'Buscar en lo que sabe la empresa',
  'Record a measure': 'Registrar una medición',
  'Read product numbers': 'Leer las cifras del producto',
  'Ask you a question': 'Hacerle una pregunta a usted',
  'Write down a plan': 'Anotar un plan',
  'Delete a record': 'Eliminar un registro',
  'Propose a code change': 'Proponer un cambio en el código',
  'Read the code': 'Leer el código',
  'Destroy a server': 'Destruir un servidor',
  'Read a skill': 'Leer una habilidad',
  'Publish a post': 'Publicar una entrada',
  'Read text aloud': 'Leer un texto en voz alta',
  'Turn speech into text': 'Convertir voz en texto',
  'Propose a new stage': 'Proponer una nueva etapa',
  'Wait for work handed on': 'Esperar un trabajo delegado',
  'Hand work to another role': 'Traspasar trabajo a otro rol',
  'File a ticket': 'Abrir una solicitud',
  'List tickets': 'Listar solicitudes',
  'Check a service is up': 'Comprobar si un servicio funciona',
  'Read a web page': 'Leer una página web',
  'Open a web page': 'Abrir una página web',
  'Search the web': 'Buscar en la web',
  'no stage': 'ninguna etapa',
  'Explore': 'Exploración',
  'Validate': 'Validación',
  'Build': 'Construcción',
  'Launch': 'Lanzamiento',
  'Grow': 'Crecimiento',
  'Wind down': 'Cierre',
  'Monthly budget reached; the company is paused': 'Presupuesto mensual alcanzado; la empresa está en pausa',
  '{spent} of {limit} spent since {since}. No new task will start and no external action will run until you raise the ceiling or allow spending past it for a while, under Money.': 'Se han gastado {spent} de {limit} desde el {since}. No se iniciará ninguna tarea nueva ni se ejecutará ninguna acción externa hasta que usted suba el tope o permita por un tiempo gastar por encima de él, en Dinero.',
  'Monthly budget is 80% spent': 'Se ha gastado el 80 % del presupuesto mensual',
  '{spent} of {limit} spent since {since}. At 100% the company pauses.': 'Se han gastado {spent} de {limit} desde el {since}. Al llegar al 100 %, la empresa se pone en pausa.',
  'Role {role} is paused for spending too fast': 'El rol {role} está en pausa por gastar demasiado rápido',
  '{role} spent {spent} in the last hour, {multiple} times its usual {usual} an hour. It is paused before the monthly ceiling is reached, so there is money left to work with once you have found out why. Resume it when you have.': '{role} gastó {spent} en la última hora, {multiple} veces su gasto habitual de {usual} por hora. Se ha puesto en pausa antes de alcanzar el tope mensual, para que quede dinero con el que trabajar cuando usted haya averiguado el motivo. Reanúdelo cuando lo sepa.',
  'Daily model spend over threshold': 'Gasto diario en modelos por encima del umbral',
  'Model spend today is {spent}, over the {limit} ceiling.': 'El gasto en modelos de hoy es de {spent}, por encima del tope de {limit}.',
  'Task failure rate over threshold': 'Tasa de fallos de tareas por encima del umbral',
  '{failed} of {finished} tasks failed or stopped today ({rate}%), over the {limit}% threshold.': 'Hoy fallaron o se detuvieron {failed} de {finished} tareas ({rate} %), por encima del umbral del {limit} %.',
  'Unusual number of policy refusals': 'Número inusual de rechazos por política',
  'Actions refused by a policy today: {count}, over the threshold of {limit}. Either an agent is probing its limits or a policy is miscalibrated.': 'Acciones rechazadas hoy por una política: {count}, por encima del umbral de {limit}. O bien un agente está tanteando sus límites, o bien una política está mal ajustada.',
  'External writes failed verification': 'Escrituras externas que no superaron la verificación',
  'Writes outside that reported success but read back differently: {count}. Something is changing them other than as asked.': 'Escrituras externas que informaron de éxito pero que, al volver a leerse, no coincidían: {count}. Algo las está cambiando de una forma distinta a la que se pidió.',
  'A capability stopped being usable': 'Una capacidad dejó de poder usarse',
  'Tasks that could not start today because a capability their role needs failed its check: {count}. A credential has probably expired or a quota is used up.': 'Tareas que hoy no pudieron iniciarse porque una capacidad que necesita su rol no superó su comprobación: {count}. Probablemente una credencial ha caducado o se ha agotado una cuota.',
  'A worker stopped reporting mid-run': 'Un ejecutor dejó de informar a mitad de una ejecución',
  'Runs that stopped reporting and were taken back today: {count}. The work was picked up again; the tokens they had already spent were not recovered.': 'Ejecuciones que dejaron de informar y se dieron por perdidas hoy: {count}. El trabajo se retomó; los tokens que ya habían gastado no se recuperaron.',
  '{role} was refused {denials} times today, at the limit of {limit}. No task will run as this role until you lift the freeze. The usual causes are a missing capability grant, a policy the role\'s charter does not account for, or work the role was never equipped to do.': '{role} recibió hoy {denials} rechazos y llegó al límite de {limit}. Ninguna tarea se ejecutará con este rol hasta que usted lo descongele. Las causas habituales son la falta de un permiso para una capacidad, una política que las directrices del rol no tienen en cuenta, o un trabajo para el que el rol nunca estuvo preparado.',
  'Role {role} is frozen after repeated denials': 'El rol {role} está congelado tras rechazos repetidos',
  'What it was refused: {capabilities}': 'Lo que se le rechazó: {capabilities}',
  'It is waiting for an approval, and none is open, so nothing you can answer will move it.': 'Está esperando una aprobación y no hay ninguna abierta, así que nada de lo que usted responda la hará avanzar.',
  'It is waiting for a review, and none is pending, so no reviewer and no decision of yours will move it.': 'Está esperando una revisión y no hay ninguna pendiente, así que ni un revisor ni una decisión suya la harán avanzar.',
  'It is parked until a window reopens, and the window never does.': 'Está en espera hasta que se reabra una franja, y esa franja nunca se reabre.',
  'A task is waiting on nothing': 'Una tarea está esperando algo que no existe',
  '"{task}" has been waiting since {since}. {why} Approve to run it again from where it stopped, or deny to cancel it.': '«{task}» está esperando desde el {since}. {why} Pulse Aprobar para volver a ejecutarla desde donde se detuvo, o Rechazar para cancelarla.',
  'A task keeps stopping the worker running it': 'Una tarea hace caer una y otra vez al ejecutor que la procesa',
  '"{task}" lost its worker {lost} times: each time the worker running it stopped answering before the work finished. What it had done is kept. It is halted so it cannot take another worker down; run it again once the cause is found, or cancel it.': '«{task}» perdió su ejecutor {lost} veces: cada vez, el ejecutor que la procesaba dejó de responder antes de que terminara el trabajo. Lo que ya había hecho se conserva. Está interrumpida para que no haga caer a otro ejecutor; vuelva a ejecutarla cuando se haya encontrado la causa, o cancélela.',
  '{services} stayed unreachable, and the work that needs it stopped': '{services} siguió sin responder, y el trabajo que lo necesita se detuvo',
  'The task waited about {minutes} minutes, looking again each time, and has stopped. Once the service answers, run it again.': 'La tarea esperó unos {minutes} minutos, volviendo a comprobarlo cada vez, y se ha detenido. Cuando el servicio responda, vuelva a ejecutarla.',
  'It was tried {tries} times over about {minutes} minutes.': 'Se intentó {tries} veces en unos {minutes} minutos.',
  'This role can take actions that cannot be undone, so the run was not silently moved to a different model.': 'Este rol puede realizar acciones que no se pueden deshacer, así que la ejecución no se pasó a otro modelo sin avisar.',
  'No fallback model is left for this role.': 'A este rol no le queda ningún modelo de respaldo.',
  'Model {model} failed and the run was not moved': 'El modelo {model} falló y la ejecución no se pasó a otro',
  'External write failed verification': 'Una escritura externa no superó la verificación',
  'The task wrote to an outside service and read it back, and what it read did not match. Look at the place it wrote to before you run it again: the write may have happened.': 'La tarea escribió en un servicio externo y lo volvió a leer, y lo que leyó no coincidía. Revise el lugar donde escribió antes de volver a ejecutarla: puede que la escritura se haya hecho.',
  'Review deadlocked after {rounds} revisions: {capability}': 'Revisión bloqueada tras {rounds} rondas de correcciones: {capability}',
  'The role and its reviewer did not agree on {capability}.': 'El rol y su revisor no se pusieron de acuerdo sobre {capability}.',
  'The reviewer\'s last note: {note}': 'Última nota del revisor: {note}',
  'The reviewer left no note.': 'El revisor no dejó ninguna nota.',
  'What it was judged against: {criteria}': 'Criterios con los que se evaluó: {criteria}',
  'Review produced no usable verdict: {capability}': 'La revisión no dio un veredicto utilizable: {capability}',
  'The reviewing task ended without a decision that could be read. The proposed action is still blocked and needs your judgement.': 'La tarea de revisión terminó sin una decisión que se pudiera leer. La acción propuesta sigue bloqueada y requiere su criterio.',
  'another stage': 'otra etapa',
  'Either answer only closes this: the company stays in the {stage} stage.': 'Cualquiera de las dos respuestas solo cierra esto: la empresa sigue en la etapa {stage}.',
  'Either answer only closes this: the company stays without a stage.': 'Cualquiera de las dos respuestas solo cierra esto: la empresa sigue sin etapa.',
  'To move it anyway, set the stage on the Overview.': 'Para cambiarla de etapa de todos modos, fíjela en Resumen.',
  '{reviewer} stopped a proposal to move the company from {from} to {to}': '{reviewer} detuvo una propuesta de pasar la empresa de {from} a {to}',
  '{reviewer} reviewed it before you and stopped it:': '{reviewer} la revisó antes que usted y la detuvo:',
  'No reason was given.': 'No se dio ningún motivo.',
  'What was proposed:': 'Lo que se propuso:',
  'The company stays in the {stage} stage.': 'La empresa sigue en la etapa {stage}.',
  'The company stays without a stage.': 'La empresa sigue sin etapa.',
  'Move the company from {from} to {to}?': '¿Pasar la empresa de {from} a {to}?',
  'Reviewed by {reviewer} before you:': 'Lo revisó {reviewer} antes que usted:',
  'The schedule "{schedule}" keeps producing the same result': 'La programación «{schedule}» da siempre el mismo resultado',
  'Its last {runs} runs all ended with the same output. That is sometimes exactly right -- a report with nothing new to say -- and often a schedule that stopped doing anything useful while still being paid for. Deny to turn it off; approve to keep it running and not be asked about this result again.': 'Sus últimas {runs} ejecuciones terminaron todas con el mismo resultado. A veces es exactamente lo correcto —un informe sin nada nuevo que contar— y a menudo es una programación que dejó de hacer algo útil y se sigue pagando. Pulse Rechazar para desactivarla, o Aprobar para que siga funcionando y no se le vuelva a preguntar por este resultado.',
  'Capability {capability} failed preflight': 'La capacidad {capability} no superó la comprobación previa',
  'Work that needs it is stopped rather than started: fix the cause, then run that work again. The usual causes are an expired or wrongly scoped credential, a quota used up, or an address that is wrong.': 'El trabajo que la necesita se detiene en lugar de iniciarse: corrija la causa y luego vuelva a ejecutar ese trabajo. Las causas habituales son una credencial caducada o con un alcance incorrecto, una cuota agotada o una dirección equivocada.',
  'Batch guard stopped {capability}': 'El control de lotes detuvo {capability}',
  'It did not match the plan its run recorded. Nothing was sent, and no service was called.': 'No coincidía con el plan que registró su ejecución. No se envió nada ni se llamó a ningún servicio.',
  '{role} was asked first and has had {minutes} minutes.': 'Primero se le pidió a {role}, que ha tenido {minutes} minutos.',
  '{role} is not a role in this company, so this came to you at once.': '{role} no es un rol de esta empresa, así que esto le llegó a usted directamente.',
  '{role} could not be given this: the company has no active goal or project to hang it from.': 'No se le pudo asignar esto a {role}: la empresa no tiene ninguna meta ni ningún proyecto activo al que vincularlo.',
  '{role} could not be given this ({record}), so this came to you at once.': 'No se le pudo asignar esto a {role} ({record}), así que le llegó a usted directamente.',
  '{role} stopped without an account of what it did ({why}).': '{role} se detuvo sin explicar lo que hizo ({why}).',
  '{role} finished without an account of what it did.': '{role} terminó sin explicar lo que hizo.',
  '{role} failed without an account of what it did.': '{role} falló sin explicar lo que hizo.',
  '{role} was stopped without an account of what it did.': 'Se detuvo a {role} sin que explicara lo que hizo.',
  'Proposed change to the {kind} "{goal}"': 'Propuesta de cambio de {kind}: «{goal}»',
  'Currently: {statement}': 'Actualmente: {statement}',
  'Currently: {statement} ({status})': 'Actualmente: {statement} ({status})',
  'Proposed: {statement}': 'Propuesta: {statement}',
  'Proposed status: {status}': 'Estado propuesto: {status}',
  'Reason given: {reason}': 'Motivo indicado: {reason}',
  'Not sent on its own: {reason}': 'No se envió por su cuenta: {reason}',
  'it answers a conversation other than the one this work began with': 'responde a una conversación distinta de la que inició este trabajo',
  'it named no passage of a document for customers': 'no citó ningún pasaje de un documento para clientes',
  'it answers from a document not marked for customers': 'responde desde un documento no marcado para clientes',
  'it says a figure the documents and the customer did not: {detail}': 'dice una cifra que no dan ni los documentos ni el cliente: {detail}',
  'it gives an address or link the documents and the customer did not: {detail}': 'da una dirección o un enlace que no dan ni los documentos ni el cliente: {detail}',
  'there have been six answers on its own in this conversation in the last hour': 'ya hubo seis respuestas por su cuenta en esta conversación en la última hora',
  'the check found it is about a refund': 'la revisión halló que trata de un reembolso',
  'the check found it offers a price or terms of its own': 'la revisión halló que ofrece un precio o condiciones propias',
  'the check found it answers a serious complaint': 'la revisión halló que responde a una queja grave',
  'the check found it touches the law': 'la revisión halló que toca lo legal',
  'the check found it gives or asks for personal data': 'la revisión halló que da o pide datos personales',
  'the check found it promises something the documents do not': 'la revisión halló que promete algo que los documentos no dicen',
  'the check could not judge it': 'la revisión no pudo juzgarla',
  'the check found something in it the documents do not say': 'la revisión halló algo que los documentos no dicen',
  '{role} proposes the schedule {name}': '{role} propone la programación {name}',
  'Each run: {instruction}': 'En cada ejecución: {instruction}',
  'Done by: {role}': 'La hace: {role}',
  'When: {cron} ({timezone}); the next runs are {runs}': 'Cuándo: {cron} ({timezone}); las próximas ejecuciones son {runs}',
  'Approving it makes the schedule and starts it; it can be turned off or changed under Team, Schedules.': 'Aprobarla crea la programación y la pone en marcha; se puede desactivar o cambiar en Equipo, Programaciones.',
  'No schedule is made.': 'No se crea ninguna programación.',
  'Propose a schedule': 'Proponer una programación',
  'Approving it changes the goal; until then the work carries on under the goal as it is.': 'Si lo aprueba, la meta cambia; hasta entonces, el trabajo continúa bajo la meta tal como está.',
  'The goal stays as it is.': 'La meta se queda como está.',
  'mission': 'misión',
  'objective': 'objetivo',
  'key result': 'resultado clave',
  'Active': 'Activa',
  'Met': 'Cumplida',
  'Abandoned': 'Abandonada',
  'This work asked for it at tier {tier}, and policy {policies} requires your approval.': 'Este trabajo lo pidió en el nivel {tier}, y la política {policies} requiere su aprobación.',
  'This work asked for it at tier {tier}, and the task began with content from outside the company.': 'Este trabajo lo pidió en el nivel {tier}, y la tarea empezó con contenido de fuera de la empresa.',
  'This work asked for it at tier {tier}, and the work read content from outside the company before asking.': 'Este trabajo lo pidió en el nivel {tier}, y antes de pedirlo leyó contenido de fuera de la empresa.',
  'This work asked for it at tier {tier}, after the work read content from outside the company, and the guardian asked you first: {reason}': 'Este trabajo lo pidió en el nivel {tier}, después de leer contenido de fuera de la empresa, y el guardián le consultó a usted primero: {reason}',
  'it doubted this call before, and you allowed it once': 'ya había dudado antes de esta llamada, y usted la permitió una vez',
  'This work asked for it at tier {tier}, which cannot be reversed.': 'Este trabajo lo pidió en el nivel {tier}, que no se puede deshacer.',
  'You approved this once already, and the worker carrying it out stopped before it could say whether it happened: it may already have happened. Check before approving it again.': 'Usted ya aprobó esto una vez, y el ejecutor que lo llevaba a cabo se detuvo antes de poder decir si se hizo: puede que ya se haya hecho. Compruébelo antes de volver a aprobarlo.',
  'What this is for — {goals}': 'Para qué sirve — {goals}',
  'The task halts and no external change is made.': 'La tarea se interrumpe y no se hace ningún cambio externo.',
  'Scored against {total} references: {passed} passed, {failed} failed.': 'Evaluado con {total} referencias — superadas: {passed}; no superadas: {failed}.',
  'This role has fewer than {minimum} accepted references, so the change is unscored. That is not the same as passing.': 'Este rol tiene menos de {minimum} referencias aceptadas, así que el cambio queda sin puntuación. Eso no es lo mismo que aprobar.',
  'The role keeps working exactly as it does now.': 'El rol sigue trabajando exactamente como ahora.',
  '{role} asks: {question}': '{role} pregunta: {question}',
  'The run did not say more than the question.': 'La ejecución no dijo nada más que la pregunta.',
  'The task is stopped, and nothing it was going to do happens.': 'La tarea se detiene y no se hace nada de lo que iba a hacer.',
  'You proposed it.': 'La propuso usted.',
  'It came with a bundle.': 'Llegó con un paquete.',
  'An agent proposed it.': 'La propuso un agente.',
  'It was learned from the company\'s work.': 'Se aprendió del trabajo de la empresa.',
  'Skill "{skill}", version {version}': 'Habilidad «{skill}», versión {version}',
  'The reviewer approved it: {note}': 'El revisor la aprobó: {note}',
  'The reviewer approved it.': 'El revisor la aprobó.',
  'Nothing changes; the current version of the skill stays in force.': 'No cambia nada; la versión actual de la habilidad sigue en vigor.',
  'Skills the bundle "{bundle}" brings: {count}': 'Habilidades que trae el paquete «{bundle}»: {count}',
  'The reviewer read them all and approved these:': 'El revisor las leyó todas y aprobó estas:',
  'It turned these down, and they stay off:': 'Rechazó estas, que siguen desactivadas:',
  'Approve to switch them all on, or deny to turn them all down. To decide one at a time, open the Skills page.': 'Pulse Aprobar para activarlas todas, o Rechazar para rechazarlas todas. Para decidir una por una, abra la página Habilidades.',
  'Nothing changes; none of these skills is switched on.': 'No cambia nada; no se activa ninguna de estas habilidades.',
  'I am {ceo}, and I run {company} for you. Three things before we start: what does {company} sell, and to whom? How much may it spend in a month? And what should its first piece of work be -- or shall I suggest one?': 'Soy {ceo} y dirijo {company} para usted. Tres cosas antes de empezar: ¿qué vende {company}, y a quién? ¿Cuánto puede gastar al mes? ¿Y cuál debería ser su primer trabajo —o prefiere que le proponga uno?',
  'Read a customer conversation': 'Leer una conversación con un cliente',
  'Reply to a customer': 'Responder a un cliente',
  'Read a page in the browser': 'Leer una página en el navegador',
  'Fill in a page in the browser': 'Rellenar una página en el navegador',
  'Ask you to take over the browser': 'Pedirle que tome el control del navegador',
};
