/**
 * Français: what the platform itself says to the owner outside the console
 * (src/owner/say.ts), keyed by its English.
 *
 * The words are the console's (console/src/locales/fr.ts): the owner is
 * « vous »; Approuver, Refuser and Poser une question on the buttons;
 * « Cette instance, Outils, Écoute » for the screens it points at; a
 * non-breaking space before : ; ? ! and inside « ». WhatsApp cuts a reply
 * button's title at 20 characters and a list row's at 24, so those stay short.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  "Incident: {title}": "Incident : {title}",
  "Done: {goal}": "Terminée : {goal}",
  "Stopped before finishing: {goal}": "Arrêtée avant la fin : {goal}",
  "Not done: {goal}": "Pas faite : {goal}",
  "Why: {reason}": "Motif : {reason}",
  "a task": "une tâche",
  "Approval needed: {title}": "Approbation requise : {title}",
  "{summary} — if denied: {consequence}": "{summary} — en cas de refus : {consequence}",
  "{role} asks:": "{role} demande :",
  "If denied:": "En cas de refus :",
  "Expires:": "Expire :",
  "This one is decided in the app.": "Cette décision se prend dans l’application.",
  "Open in PALUGADA": "Ouvrir dans PALUGADA",
  "Approve": "Approuver",
  "Deny": "Refuser",
  "Ask": "Poser une question",
  "Approved. Nothing left to press here.": "Approuvé. Il n’y a plus rien à faire ici.",
  "Denied. Nothing left to press here.": "Refusé. Il n’y a plus rien à faire ici.",
  "Expired unanswered. Silence is a refusal, so nothing was done.":
    "Expiré sans réponse. Le silence vaut refus : rien n’a été fait.",
  "This bot only answers to its owner.": "Ce bot ne répond qu’à son propriétaire.",
  "That one has to be approved in the app.": "Celui-ci doit être approuvé dans l’application.",
  "That could not be recorded.": "Impossible d’enregistrer cela.",
  'That item no longer exists.': 'Cet élément n’existe plus.',
  "What do you want to ask about \"{title}\"? Reply to this message.":
    "Que voulez-vous demander à propos de « {title} » ? Répondez à ce message.",
  "Your question": "Votre question",
  "Type your question as a reply.": "Écrivez votre question en réponse à ce message.",
  "Asked. The answer will be on the item in the app.":
    "Question posée. La réponse apparaîtra sur l’élément, dans l’application.",
  "Answer": "Répondre",
  "Answer in words": "Répondre par écrit",
  "That choice is not on this question.": "Ce choix ne fait pas partie de cette question.",
  "Chosen: {choice}.": "Choisi : {choice}.",
  "Stop the task": "Arrêter la tâche",
  "Your answer to \"{question}\"? Reply to this message.":
    "Votre réponse à « {question} » ? Répondez à ce message.",
  "Your answer": "Votre réponse",
  "Type your answer as a reply.": "Écrivez votre réponse en répondant à ce message.",
  "Answered. The task carries on with it.": "Réponse envoyée. La tâche continue avec elle.",
  "That is too long for one question; keep it under {max} characters.":
    "C’est trop long pour une seule question ; restez sous les {max} caractères.",
  "[a key, not kept]": "[une clé, non conservée]",
  "That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.":
    "Cela ressemble à une clé : je ne l’ai donc ni conservée ni envoyée nulle part. Les clés vont dans le champ scellé d’une carte, ou sur leur page dans Cette instance : dites-moi à quoi elle sert et je vous présenterai la carte.",
  "No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.":
    "Aucun modèle n’est encore configuré, je ne peux donc pas réfléchir. Choisissez-en un dans Cette instance, Modèle ; ensuite, je pourrai vous aider pour tout le reste.",
  "The model did not answer: {reason}": "Le modèle n’a pas répondu : {reason}",
  "Here is what I propose.": "Voici ce que je propose.",
  "I have nothing to add.": "Je n’ai rien à ajouter.",
  "{name}, CEO of {company}": "{name}, CEO de {company}",
  "That could not be answered: {reason}": "Impossible de répondre : {reason}",
  "I read text and voice notes.": "Je lis les textes et les notes vocales.",
  "Now talking to {name}.": "Vous parlez maintenant à {name}.",
  "Choose whom to talk to.": "Choisissez votre interlocuteur.",
  "Choose whom to talk to": "Choisir son interlocuteur",
  "Talk to PALUGADA about the whole deployment": "Parler à PALUGADA de toute l’instance",
  "Who you are talking to, and how": "À qui vous parlez, et comment",
  "Stopped.": "Arrêté.",
  "Write here to talk to {name}.": "Écrivez ici pour parler à {name}.",
  "You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.":
    "Vous parlez à {name}. Écrivez, ou envoyez une note vocale. /ceo choisit votre interlocuteur ; /palugada parle à PALUGADA de toute l’instance.",
  "You said: \"{words}\"": "Vous avez dit : « {words} »",
  "in the app": "dans l’application",
  "Apply: {summary}": "Appliquer : {summary}",
  "Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.":
    "Rien n’écoute encore la voix : choisissez un fournisseur dans l’application, dans Cette instance, Outils, Écoute.",
  "That recording is too long; keep a voice note under {max} MB.":
    "Cet enregistrement est trop long ; une note vocale doit faire moins de {max} Mo.",
  "I could not make out any words in that.": "Je n’y ai distingué aucun mot.",
  "Done: {summary}": "Fait : {summary}",
  "That one is applied in the app.": "Celle-ci s’applique dans l’application.",
  "That card no longer exists.": "Cette carte n’existe plus.",
  "That card was already applied.": "Cette carte a déjà été appliquée.",
  "That card was dismissed.": "Cette carte a été ignorée.",
  "That card failed when it was applied.": "Cette carte a échoué lors de son application.",
  "That could not be done: {reason}": "Impossible de le faire : {reason}",
  "Choose": "Choisir",
  "What do you want to ask about \"{title}\"? Reply to this message with your question.":
    "Que voulez-vous demander à propos de « {title} » ? Répondez à ce message avec votre question.",
  "Your answer to \"{question}\"? Reply to this message with your answer.":
    "Votre réponse à « {question} » ? Répondez à ce message avec votre réponse.",
  "I read text messages here.": "Ici, je lis les messages texte.",
  "Apply one of these here:": "Appliquez-en une ici :",
  "Apply {number}": "Appliquer {number}",
  "Signed in to {provider} for the {alias} key": "Connecté à {provider} pour la clé {alias}",
  "Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.":
    "Revenez à PALUGADA : le département détient désormais cette clé, et elle est renouvelée avant son expiration. Vous pouvez fermer cet onglet.",
  "Signed in to {name}": "Connecté à {name}",
  "Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.":
    "Revenez à PALUGADA pour choisir lesquels de ses outils les rôles peuvent utiliser. Vous pouvez fermer cet onglet.",
  "Not signed in": "Non connecté",
  "Recorded: approved.": "Enregistré : approuvé.",
  "Recorded: denied.": "Enregistré : refusé.",
  "Recorded: asked.": "Enregistré : question posée.",
  "Asked. Nothing left to press here.": "Question posée. Il n’y a plus rien à faire ici.",
  "Withdrawn: the task it was asking about has finished.": "Retiré : la tâche concernée est terminée.",
  "Withdrawn: the task it was asking about has failed.": "Retiré : la tâche concernée a échoué.",
  "Withdrawn: the task it was asking about was stopped.": "Retiré : la tâche concernée a été arrêtée.",
  "Withdrawn: the task it was asking about was cancelled.": "Retiré : la tâche concernée a été annulée.",
  'Decided. Nothing left to press here.': 'Tranché. Il n’y a plus rien à faire ici.',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': 'Retiré : l’agent a modifié sa proposition et a soumis la nouvelle à votre décision.',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': 'Retiré : l’entreprise n’est plus dans la phase dont cette proposition devait la faire sortir.',
  'Withdrawn: it was already decided in the app.': 'Retiré : c’était déjà tranché dans l’application.',
  'Withdrawn. Nothing left to press here.': 'Retiré. Il n’y a plus rien à faire ici.',
  'company': 'entreprise',
  'Work stopped: the {account} account is out of tokens': 'Le travail s’est arrêté : le compte {account} n’a plus de jetons',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': '« {work} » s’est arrêté parce que le compte {account} a utilisé {spent} de ses {max} jetons. Relevez son plafond dans Argent, puis ouvrez la tâche et appuyez sur Continuer : elle reprend là où elle s’était arrêtée.',
  'Withdrawn: you continued the task it was about.': 'Retiré : vous avez poursuivi la tâche qu’il concernait.',
  'Broke its contract': 'N’a pas respecté son contrat',
  'Refused by a policy': 'Refusé par une politique',
  'Out of budget': 'Budget épuisé',
  'Handed on too many times': 'Transmise trop de fois',
  'Missed its deadline': 'A manqué son échéance',
  'Its result did not check out': 'Son résultat n’a pas passé la vérification',
  'A capability it needs is down': 'Une capacité dont elle a besoin est indisponible',
  'No runtime could take it': 'Aucun environnement d’exécution n’a pu la prendre en charge',
  'Went in a circle': 'A tourné en rond',
  'Split into too many sub-tasks': 'Divisée en trop de sous-tâches',
  'Wrote more than its role allows one run': 'A écrit plus que son rôle ne le permet en une exécution',
  'Your approval was not given in time': 'Votre approbation n’est pas arrivée à temps',
  'Stopped by you': 'Arrêtée par vous',
  'Cancelled by you': 'Annulée par vous',
  'The company is frozen': 'L’entreprise est gelée',
  'Its record did not match on replay': 'Son enregistrement ne correspondait pas lors de la réexécution',
  'It kept stopping the worker running it': 'Elle a fait planter à plusieurs reprises l’exécutant qui la traitait',
  'Not done': 'Pas faite',
  'Task failed': 'Tâche échouée',
  'Digest for {day}': 'Résumé du {day}',
  'Spent: {amount}': 'Dépensé : {amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': 'Travail — terminées : {done}, échouées : {failed}, arrêtées : {stopped}',
  'Inbox: {open} waiting (incidents: {incidents})': 'Boîte de réception : {open} en attente (incidents : {incidents})',
  'Stopped ({count}): {reason}': 'Arrêtées ({count}) : {reason}',
  'Start an ad campaign': 'Lancer une campagne publicitaire',
  'Block time on the calendar': 'Bloquer un créneau dans l’agenda',
  'Read the calendar': 'Lire l’agenda',
  'Run code': 'Exécuter du code',
  'Add a note to a customer': 'Ajouter une note à une fiche client',
  'Read customer records': 'Lire les fiches clients',
  'Release to the live site': 'Publier sur le site public',
  'Release to the test site': 'Publier sur le site de test',
  'Change a domain\'s nameservers': 'Modifier les serveurs DNS d’un domaine',
  'Read a domain\'s records': 'Lire les enregistrements d’un domaine',
  'Change a domain\'s record': 'Modifier un enregistrement d’un domaine',
  'Write a document': 'Rédiger un document',
  'Sign a document': 'Signer un document',
  'Buy a domain': 'Acheter un domaine',
  'Transfer a domain': 'Transférer un domaine',
  'Draft an email': 'Préparer un brouillon d’e-mail',
  'Send an email': 'Envoyer un e-mail',
  'List files': 'Lister les fichiers',
  'Read a file': 'Lire un fichier',
  'Describe a picture': 'Décrire une image',
  'Calculate in Python': 'Calculer avec Python',
  'Transfer money': 'Effectuer un virement',
  'Propose a goal change': 'Proposer une modification d’objectif',
  'Make a picture': 'Créer une image',
  'Issue an invoice': 'Émettre une facture',
  'Pay an invoice': 'Payer une facture',
  'Read the books': 'Consulter la comptabilité',
  'Read the mailbox': 'Lire la boîte e-mail',
  'Search what the company knows': 'Rechercher dans ce que sait l’entreprise',
  'Record a measure': 'Enregistrer une mesure',
  'Read product numbers': 'Lire les chiffres du produit',
  'Ask you a question': 'Vous poser une question',
  'Write down a plan': 'Mettre un plan par écrit',
  'Delete a record': 'Supprimer un enregistrement',
  'Propose a code change': 'Proposer une modification du code',
  'Read the code': 'Lire le code',
  'Destroy a server': 'Détruire un serveur',
  'Read a skill': 'Lire une compétence',
  'Publish a post': 'Publier un message',
  'Read text aloud': 'Lire un texte à voix haute',
  'Turn speech into text': 'Convertir la parole en texte',
  'Propose a new stage': 'Proposer une nouvelle phase',
  'Wait for work handed on': 'Attendre un travail confié à d’autres',
  'Hand work to another role': 'Confier du travail à un autre rôle',
  'File a ticket': 'Créer une demande',
  'List tickets': 'Lister les demandes',
  'Check a service is up': 'Vérifier qu’un service répond',
  'Read a web page': 'Lire une page web',
  'Open a web page': 'Ouvrir une page web',
  'Search the web': 'Rechercher sur le web',
  'no stage': 'aucune phase',
  'Explore': 'Exploration',
  'Validate': 'Validation',
  'Build': 'Construction',
  'Launch': 'Lancement',
  'Grow': 'Croissance',
  'Wind down': 'Arrêt progressif',
  'Monthly budget reached; the company is paused': 'Budget mensuel atteint ; l’entreprise est en pause',
  '{spent} of {limit} spent since {since}. No new task will start and no external action will run until you raise the ceiling or allow spending past it for a while, under Money.': '{spent} sur {limit} dépensés depuis le {since}. Aucune nouvelle tâche ne démarrera et aucune action externe ne s’exécutera tant que vous n’aurez pas relevé le plafond ou autorisé pour un temps des dépenses au-delà, dans Argent.',
  'Monthly budget is 80% spent': '80 % du budget mensuel est dépensé',
  '{spent} of {limit} spent since {since}. At 100% the company pauses.': '{spent} sur {limit} dépensés depuis le {since}. À 100 %, l’entreprise se met en pause.',
  'Role {role} is paused for spending too fast': 'Le rôle {role} est en pause : il dépense trop vite',
  '{role} spent {spent} in the last hour, {multiple} times its usual {usual} an hour. It is paused before the monthly ceiling is reached, so there is money left to work with once you have found out why. Resume it when you have.': '{role} a dépensé {spent} au cours de la dernière heure, soit {multiple} fois ses {usual} habituels par heure. Le rôle est mis en pause avant que le plafond mensuel soit atteint, pour qu’il reste de l’argent une fois que vous aurez trouvé pourquoi. Reprenez-le quand ce sera fait.',
  'Daily model spend over threshold': 'Dépense quotidienne en modèles au-delà du seuil',
  'Model spend today is {spent}, over the {limit} ceiling.': 'La dépense en modèles aujourd’hui est de {spent}, au-delà du plafond de {limit}.',
  'Task failure rate over threshold': 'Taux d’échec des tâches au-delà du seuil',
  '{failed} of {finished} tasks failed or stopped today ({rate}%), over the {limit}% threshold.': 'Tâches échouées ou arrêtées aujourd’hui : {failed} sur {finished} ({rate} %), au-delà du seuil de {limit} %.',
  'Unusual number of policy refusals': 'Nombre inhabituel de refus par une politique',
  'Actions refused by a policy today: {count}, over the threshold of {limit}. Either an agent is probing its limits or a policy is miscalibrated.': 'Actions refusées par une politique aujourd’hui : {count}, au-delà du seuil de {limit}. Soit un agent teste ses limites, soit une politique est mal calibrée.',
  'External writes failed verification': 'Des écritures externes ont échoué à la relecture',
  'Writes outside that reported success but read back differently: {count}. Something is changing them other than as asked.': 'Écritures externes signalées comme réussies mais relues différemment : {count}. Quelque chose les modifie autrement que ce qui a été demandé.',
  'A capability stopped being usable': 'Une capacité n’est plus utilisable',
  'Tasks that could not start today because a capability their role needs failed its check: {count}. A credential has probably expired or a quota is used up.': 'Tâches qui n’ont pas pu démarrer aujourd’hui parce qu’une capacité nécessaire à leur rôle a échoué à sa vérification : {count}. Un identifiant a probablement expiré ou un quota est épuisé.',
  'A worker stopped reporting mid-run': 'Un exécutant a cessé de répondre en cours d’exécution',
  'Runs that stopped reporting and were taken back today: {count}. The work was picked up again; the tokens they had already spent were not recovered.': 'Exécutions qui ont cessé de donner signe de vie et ont été retirées à leur exécutant aujourd’hui : {count}. Le travail a été repris ; les tokens qu’elles avaient déjà dépensés n’ont pas été récupérés.',
  '{role} was refused {denials} times today, at the limit of {limit}. No task will run as this role until you lift the freeze. The usual causes are a missing capability grant, a policy the role\'s charter does not account for, or work the role was never equipped to do.': 'Refus essuyés par {role} aujourd’hui : {denials}, soit la limite de {limit}. Aucune tâche ne s’exécutera sous ce rôle tant que vous ne l’aurez pas dégelé. Les causes habituelles sont une autorisation de capacité manquante, une politique que la charte du rôle ne prend pas en compte, ou un travail pour lequel le rôle n’a jamais été équipé.',
  'Role {role} is frozen after repeated denials': 'Le rôle {role} est gelé après des refus répétés',
  'What it was refused: {capabilities}': 'Ce qui lui a été refusé : {capabilities}',
  'It is waiting for an approval, and none is open, so nothing you can answer will move it.': 'Elle attend une approbation, et aucune n’est ouverte : rien de ce que vous pourriez répondre ne la fera avancer.',
  'It is waiting for a review, and none is pending, so no reviewer and no decision of yours will move it.': 'Elle attend une revue, et aucune n’est en cours : ni un relecteur ni une décision de votre part ne la feront avancer.',
  'It is parked until a window reopens, and the window never does.': 'Elle est en attente jusqu’à la réouverture d’un créneau, et ce créneau ne se rouvre jamais.',
  'A task is waiting on nothing': 'Une tâche attend quelque chose qui n’existe pas',
  '"{task}" has been waiting since {since}. {why} Approve to run it again from where it stopped, or deny to cancel it.': '« {task} » attend depuis le {since}. {why} Approuvez pour la relancer là où elle s’est arrêtée, ou refusez pour l’annuler.',
  'A task keeps stopping the worker running it': 'Une tâche fait planter à répétition l’exécutant qui la traite',
  '"{task}" lost its worker {lost} times: each time the worker running it stopped answering before the work finished. What it had done is kept. It is halted so it cannot take another worker down; run it again once the cause is found, or cancel it.': '« {task} » a perdu son exécutant {lost} fois : chaque fois, l’exécutant qui la traitait a cessé de répondre avant la fin du travail. Ce qu’elle avait déjà fait est conservé. Elle est interrompue pour ne pas faire tomber un autre exécutant ; relancez-la une fois la cause trouvée, ou annulez-la.',
  '{services} stayed unreachable, and the work that needs it stopped': '{services} : toujours injoignable, et le travail qui en dépend s’est arrêté',
  'The task waited about {minutes} minutes, looking again each time, and has stopped. Once the service answers, run it again.': 'La tâche a attendu environ {minutes} minutes, en réessayant à chaque fois, et s’est arrêtée. Une fois que le service répond, relancez-la.',
  'It was tried {tries} times over about {minutes} minutes.': 'Il y a eu {tries} tentatives en environ {minutes} minutes.',
  'This role can take actions that cannot be undone, so the run was not silently moved to a different model.': 'Ce rôle peut effectuer des actions irréversibles : l’exécution n’a donc pas été basculée en silence sur un autre modèle.',
  'No fallback model is left for this role.': 'Il ne reste aucun modèle de secours pour ce rôle.',
  'Model {model} failed and the run was not moved': 'Le modèle {model} a échoué et l’exécution n’a pas été basculée',
  'External write failed verification': 'Une écriture externe a échoué à la relecture',
  'The task wrote to an outside service and read it back, and what it read did not match. Look at the place it wrote to before you run it again: the write may have happened.': 'La tâche a écrit dans un service externe puis l’a relu, et ce qu’elle a lu ne correspondait pas. Vérifiez l’endroit où elle a écrit avant de la relancer : l’écriture a peut-être eu lieu.',
  'Review deadlocked after {rounds} revisions: {capability}': 'Revue bloquée après {rounds} révisions : {capability}',
  'The role and its reviewer did not agree on {capability}.': 'Le rôle et son relecteur ne sont pas tombés d’accord sur {capability}.',
  'The reviewer\'s last note: {note}': 'Dernière note du relecteur : {note}',
  'The reviewer left no note.': 'Le relecteur n’a laissé aucune note.',
  'What it was judged against: {criteria}': 'Critères d’évaluation : {criteria}',
  'Review produced no usable verdict: {capability}': 'La revue n’a produit aucun verdict exploitable : {capability}',
  'The reviewing task ended without a decision that could be read. The proposed action is still blocked and needs your judgement.': 'La tâche de revue s’est terminée sans décision lisible. L’action proposée reste bloquée et requiert votre jugement.',
  'another stage': 'une autre phase',
  'Either answer only closes this: the company stays in the {stage} stage.': 'Les deux réponses ne font que clore cet élément : l’entreprise reste en phase {stage}.',
  'Either answer only closes this: the company stays without a stage.': 'Les deux réponses ne font que clore cet élément : l’entreprise reste sans phase.',
  'To move it anyway, set the stage on the Overview.': 'Pour changer de phase malgré tout, définissez-la dans Vue d’ensemble.',
  '{reviewer} stopped a proposal to move the company from {from} to {to}': '{reviewer} a bloqué une proposition de changement de phase de l’entreprise : {from} → {to}',
  '{reviewer} reviewed it before you and stopped it:': '{reviewer} l’a relue avant vous et l’a bloquée :',
  'No reason was given.': 'Aucun motif n’a été donné.',
  'What was proposed:': 'Ce qui a été proposé :',
  'The company stays in the {stage} stage.': 'L’entreprise reste en phase {stage}.',
  'The company stays without a stage.': 'L’entreprise reste sans phase.',
  'Move the company from {from} to {to}?': 'Changer la phase de l’entreprise : {from} → {to} ?',
  'Reviewed by {reviewer} before you:': 'Relu par {reviewer} avant vous :',
  'The schedule "{schedule}" keeps producing the same result': 'La planification « {schedule} » produit toujours le même résultat',
  'Its last {runs} runs all ended with the same output. That is sometimes exactly right -- a report with nothing new to say -- and often a schedule that stopped doing anything useful while still being paid for. Deny to turn it off; approve to keep it running and not be asked about this result again.': 'Ses {runs} dernières exécutions se sont toutes terminées par le même résultat. C’est parfois exactement ce qu’il faut – un rapport qui n’a rien de nouveau à dire – et souvent une planification qui ne fait plus rien d’utile tout en restant payée. Refusez pour la désactiver ; approuvez pour la laisser tourner sans que la question vous soit reposée pour ce résultat.',
  'Capability {capability} failed preflight': 'La capacité {capability} a échoué à la vérification préalable',
  'Work that needs it is stopped rather than started: fix the cause, then run that work again. The usual causes are an expired or wrongly scoped credential, a quota used up, or an address that is wrong.': 'Le travail qui en a besoin est arrêté au lieu d’être lancé : corrigez la cause, puis relancez ce travail. Les causes habituelles sont un identifiant expiré ou aux droits mal définis, un quota épuisé, ou une adresse erronée.',
  'Batch guard stopped {capability}': 'Le garde-fou des lots a arrêté {capability}',
  'It did not match the plan its run recorded. Nothing was sent, and no service was called.': 'Cela ne correspondait pas au plan enregistré par son exécution. Rien n’a été envoyé et aucun service n’a été appelé.',
  '{role} was asked first and has had {minutes} minutes.': 'La demande est d’abord allée à {role}, qui a eu {minutes} minutes.',
  '{role} is not a role in this company, so this came to you at once.': '{role} n’est pas un rôle de cette entreprise : cet élément vous est donc parvenu immédiatement.',
  '{role} could not be given this: the company has no active goal or project to hang it from.': 'Impossible de confier ceci à {role} : l’entreprise n’a aucun objectif ni projet actif auquel le rattacher.',
  '{role} could not be given this ({record}), so this came to you at once.': 'Impossible de confier ceci à {role} ({record}) : cet élément vous est donc parvenu immédiatement.',
  '{role} stopped without an account of what it did ({why}).': '{role} a cessé de travailler sans rendre compte de ce qui a été fait ({why}).',
  '{role} finished without an account of what it did.': '{role} a terminé sans rendre compte de ce qui a été fait.',
  '{role} failed without an account of what it did.': '{role} a échoué sans rendre compte de ce qui a été fait.',
  '{role} was stopped without an account of what it did.': 'L’exécution de {role} a été arrêtée sans compte rendu de ce qui a été fait.',
  'Proposed change to the {kind} "{goal}"': 'Modification proposée ({kind}) : « {goal} »',
  'Currently: {statement}': 'Actuellement : {statement}',
  'Currently: {statement} ({status})': 'Actuellement : {statement} ({status})',
  'Proposed: {statement}': 'Proposé : {statement}',
  'Proposed status: {status}': 'Statut proposé : {status}',
  'Reason given: {reason}': 'Motif donné : {reason}',
  'Record an entry in the books': 'Enregistrer une écriture dans les livres',
  'Record a customer or a deal': 'Enregistrer un client ou une affaire',
  'Not sent on its own: {reason}': 'Non envoyé seul : {reason}',
  'it answers a conversation other than the one this work began with': 'elle répond à une autre conversation que celle par laquelle ce travail a commencé',
  'it named no passage of a document for customers': 'elle ne cite aucun passage d’un document pour les clients',
  'it answers from a document not marked for customers': 'elle répond à partir d’un document non marqué pour les clients',
  'it says a figure the documents and the customer did not: {detail}': 'elle donne un chiffre que ni les documents ni le client n’ont donné : {detail}',
  'it gives an address or link the documents and the customer did not: {detail}': 'elle donne une adresse ou un lien que ni les documents ni le client n’ont donné : {detail}',
  'there have been six answers on its own in this conversation in the last hour': 'il y a déjà eu six réponses envoyées seules dans cette conversation au cours de la dernière heure',
  'the check found it is about a refund': 'la vérification a trouvé qu’il s’agit d’un remboursement',
  'the check found it offers a price or terms of its own': 'la vérification a trouvé qu’elle propose un prix ou des conditions à elle',
  'the check found it answers a serious complaint': 'la vérification a trouvé qu’elle répond à une réclamation grave',
  'the check found it touches the law': 'la vérification a trouvé qu’elle touche au juridique',
  'the check found it gives or asks for personal data': 'la vérification a trouvé qu’elle donne ou demande des données personnelles',
  'the check found it promises something the documents do not': 'la vérification a trouvé qu’elle promet ce que les documents ne disent pas',
  'the check could not judge it': 'la vérification n’a pas pu en juger',
  'the check found something in it the documents do not say': 'la vérification y a trouvé ce que les documents ne disent pas',
  '{role} proposes the schedule {name}': '{role} propose la planification {name}',
  'Each run: {instruction}': 'À chaque exécution : {instruction}',
  'Done by: {role}': 'Effectuée par : {role}',
  'When: {cron} ({timezone}); the next runs are {runs}': 'Quand : {cron} ({timezone}) ; les prochaines exécutions sont {runs}',
  'Approving it makes the schedule and starts it; it can be turned off or changed under Team, Schedules.': 'L’approuver crée la planification et la lance ; elle peut être désactivée ou modifiée dans Équipe, Planifications.',
  'No schedule is made.': 'Aucune planification n’est créée.',
  'Propose a schedule': 'Proposer une planification',
  'Approving it changes the goal; until then the work carries on under the goal as it is.': 'L’approuver modifie l’objectif ; d’ici là, le travail continue sous l’objectif tel qu’il est.',
  'The goal stays as it is.': 'L’objectif reste tel qu’il est.',
  'mission': 'mission',
  'objective': 'objectif',
  'key result': 'résultat clé',
  'Active': 'Actif',
  'Met': 'Atteint',
  'Abandoned': 'Abandonné',
  'This work asked for it at tier {tier}, and policy {policies} requires your approval.': 'Ce travail l’a demandé au niveau {tier}, et la politique {policies} exige votre approbation.',
  'This work asked for it at tier {tier}, and the task began with content from outside the company.': 'Ce travail l’a demandé au niveau {tier}, et la tâche a commencé avec du contenu venant de l’extérieur de l’entreprise.',
  'This work asked for it at tier {tier}, and the work read content from outside the company before asking.': 'Ce travail l’a demandé au niveau {tier}, et il avait lu du contenu venant de l’extérieur de l’entreprise avant de le demander.',
  'This work asked for it at tier {tier}, after the work read content from outside the company, and the guardian asked you first: {reason}': 'Ce travail l’a demandé au niveau {tier}, après avoir lu du contenu venant de l’extérieur de l’entreprise, et le gardien a préféré vous le soumettre d’abord : {reason}',
  'it doubted this call before, and you allowed it once': 'il avait déjà douté de cet appel, et vous l’aviez autorisé une fois',
  'This work asked for it at tier {tier}, which cannot be reversed.': 'Ce travail l’a demandé au niveau {tier}, qui est irréversible.',
  'You approved this once already, and the worker carrying it out stopped before it could say whether it happened: it may already have happened. Check before approving it again.': 'Vous avez déjà approuvé ceci une fois, et l’exécutant qui s’en chargeait s’est arrêté avant de pouvoir dire si c’était fait : c’est peut-être déjà fait. Vérifiez avant de l’approuver à nouveau.',
  'What this is for — {goals}': 'À quoi cela sert — {goals}',
  'The task halts and no external change is made.': 'La tâche est interrompue et aucune modification externe n’est faite.',
  'Scored against {total} references: {passed} passed, {failed} failed.': 'Évalué sur {total} références — réussies : {passed}, échouées : {failed}.',
  'This role has fewer than {minimum} accepted references, so the change is unscored. That is not the same as passing.': 'Ce rôle a moins de {minimum} références acceptées : la modification n’est donc pas notée. Ce n’est pas la même chose que réussir.',
  'The role keeps working exactly as it does now.': 'Le rôle continue de travailler exactement comme maintenant.',
  '{role} asks: {question}': '{role} demande : {question}',
  'The run did not say more than the question.': 'L’exécution n’a rien dit de plus que la question.',
  'The task is stopped, and nothing it was going to do happens.': 'La tâche est arrêtée, et rien de ce qu’elle allait faire n’a lieu.',
  'You proposed it.': 'Vous l’avez proposée.',
  'It came with a bundle.': 'Elle vient d’un pack.',
  'An agent proposed it.': 'Un agent l’a proposée.',
  'It was learned from the company\'s work.': 'Elle a été apprise du travail de l’entreprise.',
  'Skill "{skill}", version {version}': 'Compétence « {skill} », version {version}',
  'The reviewer approved it: {note}': 'Le relecteur l’a approuvée : {note}',
  'The reviewer approved it.': 'Le relecteur l’a approuvée.',
  'Nothing changes; the current version of the skill stays in force.': 'Rien ne change ; la version actuelle de la compétence reste en vigueur.',
  'Skills the bundle "{bundle}" brings: {count}': 'Compétences qu’apporte le pack « {bundle} » : {count}',
  'The reviewer read them all and approved these:': 'Le relecteur les a toutes lues et a approuvé celles-ci :',
  'It turned these down, and they stay off:': 'Il a refusé celles-ci, qui restent désactivées :',
  'Approve to switch them all on, or deny to turn them all down. To decide one at a time, open the Skills page.': 'Approuvez pour les activer toutes, ou refusez pour les rejeter toutes. Pour décider une par une, ouvrez la page Compétences.',
  'Nothing changes; none of these skills is switched on.': 'Rien ne change ; aucune de ces compétences n’est activée.',
  'I am {ceo}, and I run {company} for you. Three things before we start: what does {company} sell, and to whom? How much may it spend in a month? And what should its first piece of work be -- or shall I suggest one?': 'Je suis {ceo}, et je dirige {company} pour vous. Trois questions avant de commencer : que vend {company}, et à qui ? Combien l’entreprise peut-elle dépenser par mois ? Et quel doit être son premier travail – ou voulez-vous que j’en propose un ?',
  'Read a customer conversation': 'Lire une discussion avec un client',
  'Reply to a customer': 'Répondre à un client',
  'Read a page in the browser': 'Lire une page dans le navigateur',
  'Fill in a page in the browser': 'Remplir une page dans le navigateur',
  'Ask you to take over the browser': 'Vous demander de prendre la main sur le navigateur',
  '{host} refused the model key ({status}), so nothing that needs the model can run. Open Settings, This deployment, Model, paste a key that works, test it and save.':
    '{host} a refusé la clé du modèle ({status}) : aucun travail qui a besoin du modèle ne peut donc s’exécuter. Ouvrez Paramètres, Cette instance, Modèle, collez une clé qui fonctionne, testez-la et enregistrez.',
  '{host} refused the model key, and work is waiting': '{host} a refusé la clé du modèle, et le travail est en attente',
  'What is waiting for the model carries on by itself once a key that works is in use.':
    'Le travail qui attend le modèle reprend de lui-même dès qu’une clé qui fonctionne est utilisée.',
  'A task ended before it was done: {task}':
    'Une tâche s’est arrêtée avant d’être terminée : {task}',
  'It ended as: {reason}. No other card was raised for it, so it is here rather than silent.':
    'Elle s’est terminée ainsi : {reason}. Aucune autre carte n’a été créée pour elle ; elle est donc ici plutôt que silencieuse.',
  'Where its measures stand, as the platform reads them:':
    'Où en sont ses mesures, telles que la plateforme les lit :',
  '{name}: no value recorded yet, against a target of {target}.':
    '{name} : aucune valeur enregistrée, pour un objectif de {target}.',
  '{name}: {value} against a target of {target}, read back from its source.':
    '{name} : {value} pour un objectif de {target}, relu à sa source.',
  '{name}: {value} against a target of {target}, reported and not checked.':
    '{name} : {value} pour un objectif de {target}, déclaré et non vérifié.',
  'Look at it again later': 'Y revenir plus tard',
  "Deliver what this company sells, reliably and without surprising its owner.":
    "Livrer ce que cette entreprise vend, de façon fiable et sans surprendre son propriétaire.",
  "Ship the work the company has promised, on time and verified.":
    "Livrer le travail promis par l’entreprise, dans les délais et vérifié.",
  "Keep the company solvent, answerable and running without daily attention.":
    "Maintenir l’entreprise solvable, responsable et en marche sans attention quotidienne.",
  "Since we last spoke:":
    "Depuis notre dernier échange :",
  "More finished: {count}":
    "Terminé en plus : {count}",
  "Waiting for you: {count}":
    "En attente de vous : {count}",
};
