/**
 * हिन्दी: what the platform itself says to the owner outside the console
 * (src/owner/say.ts), keyed by its English.
 *
 * The terms are the console's (console/src/locales/hi.ts): its buttons are
 * named as the console names them, and a screen it points to ("यह
 * डिप्लॉयमेंट, टूल, सुनना") is spelled as the console draws it. Whoever is
 * speaking as "I" -- the CEO a company chose, or PALUGADA -- is given no
 * gender: the sentences are turned so that no verb needs one.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'घटना: {title}',
  'Done: {goal}': 'पूरा हुआ: {goal}',
  'Stopped before finishing: {goal}': 'पूरा होने से पहले रुका: {goal}',
  'Not done: {goal}': 'नहीं हुआ: {goal}',
  'Why: {reason}': 'कारण: {reason}',
  'a task': 'एक कार्य',
  'Approval needed: {title}': 'स्वीकृति चाहिए: {title}',
  '{summary} — if denied: {consequence}': '{summary} — अस्वीकार करने पर: {consequence}',
  '{role} asks:': '{role} का सवाल:',
  'If denied:': 'अस्वीकार करने पर:',
  'Expires:': 'समाप्ति:',
  'This one is decided in the app.': 'इस पर निर्णय ऐप में होता है।',
  'Open in PALUGADA': 'PALUGADA में खोलें',
  'Approve': 'स्वीकृत करें',
  'Deny': 'अस्वीकार करें',
  'Ask': 'पूछें',
  'Approved. Nothing left to press here.': 'स्वीकृत। यहाँ अब कुछ दबाना बाकी नहीं है।',
  'Denied. Nothing left to press here.': 'अस्वीकृत। यहाँ अब कुछ दबाना बाकी नहीं है।',
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    'बिना जवाब के समाप्त। चुप रहना इनकार माना जाता है, इसलिए कुछ नहीं किया गया।',
  'This bot only answers to its owner.': 'यह बॉट सिर्फ़ अपने स्वामी को जवाब देता है।',
  'That one has to be approved in the app.': 'इसे ऐप में ही स्वीकृत करना होगा।',
  'That could not be recorded.': 'इसे दर्ज नहीं किया जा सका।',
  'That item no longer exists.': 'वह आइटम अब मौजूद नहीं है।',
  'What do you want to ask about "{title}"? Reply to this message.':
    '"{title}" के बारे में आप क्या पूछना चाहते हैं? इस संदेश पर रिप्लाई करें।',
  'Your question': 'आपका सवाल',
  'Type your question as a reply.': 'अपना सवाल रिप्लाई में टाइप करें।',
  'Asked. The answer will be on the item in the app.': 'पूछ लिया गया। जवाब ऐप में उसी आइटम पर मिलेगा।',
  'Answer': 'जवाब दें',
  'Answer in words': 'शब्दों में जवाब दें',
  'That choice is not on this question.': 'यह विकल्प इस सवाल में नहीं है।',
  'Chosen: {choice}.': 'चुना गया: {choice}।',
  'Stop the task': 'कार्य रोकें',
  'Your answer to "{question}"? Reply to this message.': '"{question}" का आपका जवाब? इस संदेश पर रिप्लाई करें।',
  'Your answer': 'आपका जवाब',
  'Type your answer as a reply.': 'अपना जवाब रिप्लाई में टाइप करें।',
  'Answered. The task carries on with it.': 'जवाब दे दिया गया। कार्य उसी के साथ आगे बढ़ता है।',
  'That is too long for one question; keep it under {max} characters.':
    'एक सवाल के लिए यह बहुत लंबा है; इसे {max} अक्षरों से कम रखें।',
  '[a key, not kept]': '[एक कुंजी, रखी नहीं गई]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    'यह कुंजी जैसा दिखता है, इसलिए मैंने इसे न रखा है, न कहीं भेजा है। कुंजियाँ किसी कार्ड के सील किए गए फ़ील्ड में, या “यह डिप्लॉयमेंट” में उनके अपने पेज पर डाली जाती हैं: मुझे बताइए कि यह किसलिए है, और उसका कार्ड आपके सामने आ जाएगा।',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'अभी कोई मॉडल सेट नहीं है, इसलिए सोचना मेरे बस में नहीं है। “यह डिप्लॉयमेंट, मॉडल” में जाकर एक मॉडल चुनें; उसके बाद बाकी हर काम में मेरी मदद मिल सकेगी।',
  'The model did not answer: {reason}': 'मॉडल ने जवाब नहीं दिया: {reason}',
  'Here is what I propose.': 'मेरा प्रस्ताव यह है।',
  'I have nothing to add.': 'मेरे पास जोड़ने को कुछ नहीं है।',
  '{name}, CEO of {company}': '{name}, {company} में CEO',
  'That could not be answered: {reason}': 'इसका जवाब नहीं दिया जा सका: {reason}',
  'I read text and voice notes.': 'यहाँ टेक्स्ट और वॉइस नोट पढ़े जाते हैं।',
  'Now talking to {name}.': 'अब {name} से बात हो रही है।',
  'Choose whom to talk to.': 'चुनें कि आप किससे बात करना चाहते हैं।',
  'Choose whom to talk to': 'चुनें कि किससे बात करनी है',
  'Talk to PALUGADA about the whole deployment': 'पूरे डिप्लॉयमेंट के बारे में PALUGADA से बात करें',
  'Who you are talking to, and how': 'आप किससे बात कर रहे हैं, और कैसे',
  'Stopped.': 'रोक दिया गया।',
  'Write here to talk to {name}.': '{name} से बात करने के लिए यहाँ लिखें।',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    'आप {name} से बात कर रहे हैं। लिखें, या वॉइस नोट भेजें। /ceo से चुनें कि आप किससे बात करें; /palugada से पूरे डिप्लॉयमेंट के बारे में PALUGADA से बात करें।',
  'You said: "{words}"': 'आपने कहा: "{words}"',
  'in the app': 'ऐप में',
  'Apply: {summary}': 'लागू करें: {summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    'अभी कोई भी आवाज़ नहीं सुन सकता: ऐप में “यह डिप्लॉयमेंट, टूल, सुनना” में जाकर कोई प्रदाता चुनें।',
  'That recording is too long; keep a voice note under {max} MB.': 'वह रिकॉर्डिंग बहुत लंबी है; वॉइस नोट {max} MB से छोटा रखें।',
  'I could not make out any words in that.': 'उसमें मुझे कोई भी शब्द समझ नहीं आया।',
  'Done: {summary}': 'हो गया: {summary}',
  'That one is applied in the app.': 'इसे ऐप में ही लागू किया जाता है।',
  'That card no longer exists.': 'वह कार्ड अब मौजूद नहीं है।',
  'That card was already applied.': 'वह कार्ड पहले ही लागू हो चुका है।',
  'That card was dismissed.': 'वह कार्ड खारिज कर दिया गया था।',
  'That card failed when it was applied.': 'लागू करते समय वह कार्ड विफल रहा।',
  'That could not be done: {reason}': 'यह नहीं किया जा सका: {reason}',
  'Choose': 'चुनें',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    '"{title}" के बारे में आप क्या पूछना चाहते हैं? इस संदेश पर रिप्लाई करके अपना सवाल भेजें।',
  'Your answer to "{question}"? Reply to this message with your answer.':
    '"{question}" का आपका जवाब? इस संदेश पर रिप्लाई करके अपना जवाब भेजें।',
  'I read text messages here.': 'यहाँ टेक्स्ट संदेश पढ़े जाते हैं।',
  'Apply one of these here:': 'इनमें से कोई एक यहाँ लागू करें:',
  'Apply {number}': '{number} लागू करें',
  'Signed in to {provider} for the {alias} key': '{alias} कुंजी के लिए {provider} में साइन इन हो गया',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'PALUGADA पर लौटें: यह कुंजी अब विभाग के पास है, और खत्म होने से पहले अपने आप रिन्यू हो जाती है। यह टैब बंद किया जा सकता है।',
  'Signed in to {name}': '{name} में साइन इन हो गया',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'PALUGADA पर लौटकर चुनें कि भूमिकाएँ इसके कौन-से टूल इस्तेमाल कर सकती हैं। यह टैब बंद किया जा सकता है।',
  'Not signed in': 'साइन इन नहीं हुआ',
  "Recorded: approved.": "दर्ज हुआ: स्वीकृत।",
  "Recorded: denied.": "दर्ज हुआ: अस्वीकृत।",
  "Recorded: asked.": "दर्ज हुआ: सवाल पूछा गया।",
  "Asked. Nothing left to press here.": "पूछ लिया गया। यहाँ अब कुछ दबाना बाकी नहीं है।",
  "Withdrawn: the task it was asking about has finished.": "वापस लिया गया: जिस कार्य के बारे में यह पूछ रहा था, वह पूरा हो चुका है।",
  "Withdrawn: the task it was asking about has failed.": "वापस लिया गया: जिस कार्य के बारे में यह पूछ रहा था, वह विफल हो गया है।",
  "Withdrawn: the task it was asking about was stopped.": "वापस लिया गया: जिस कार्य के बारे में यह पूछ रहा था, उसे रोक दिया गया।",
  "Withdrawn: the task it was asking about was cancelled.": "वापस लिया गया: जिस कार्य के बारे में यह पूछ रहा था, उसे रद्द कर दिया गया।",
  'Decided. Nothing left to press here.': 'निर्णय हो चुका। यहाँ अब कुछ दबाना बाकी नहीं है।',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': 'वापस लिया गया: एजेंट ने अपना प्रस्ताव बदल दिया और नए प्रस्ताव के बारे में फिर से पूछा।',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': 'वापस लिया गया: कंपनी अब उस चरण में नहीं है जिससे यह प्रस्ताव उसे आगे ले जाता।',
  'Withdrawn: it was already decided in the app.': 'वापस लिया गया: ऐप में इसका निर्णय पहले ही हो चुका है।',
  'Withdrawn. Nothing left to press here.': 'वापस लिया गया। यहाँ अब कुछ दबाना बाकी नहीं है।',
  'company': 'कंपनी',
  'Work stopped: the {account} account is out of tokens': 'काम रुक गया: {account} खाते के टोकन खत्म हो गए',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': '“{work}” रुक गया क्योंकि {account} खाता अपने {max} टोकन में से {spent} इस्तेमाल कर चुका है। पैसा पेज पर इसकी सीमा बढ़ाएँ, फिर कार्य खोलकर जारी रखें दबाएँ: यह वहीं से आगे बढ़ेगा जहाँ रुका था।',
  'Withdrawn: you continued the task it was about.': 'वापस लिया गया: आपने इससे जुड़ा कार्य जारी रखा।',
  'Broke its contract': 'अपना अनुबंध तोड़ा',
  'Refused by a policy': 'नीति ने अस्वीकार किया',
  'Out of budget': 'बजट खत्म',
  'Handed on too many times': 'बहुत बार आगे सौंपा गया',
  'Missed its deadline': 'समय-सीमा पार हो गई',
  'Its result did not check out': 'इसका नतीजा जाँच में सही नहीं निकला',
  'A capability it needs is down': 'इसके लिए ज़रूरी एक क्षमता काम नहीं कर रही',
  'No runtime could take it': 'कोई रनटाइम इसे नहीं ले सका',
  'Went in a circle': 'घूमकर वहीं लौट आया',
  'Split into too many sub-tasks': 'बहुत सारे उप-कार्यों में बँट गया',
  'Wrote more than its role allows one run': 'भूमिका के एक रन की अनुमति से ज़्यादा लिखा',
  'Your approval was not given in time': 'आपकी स्वीकृति समय पर नहीं मिली',
  'Stopped by you': 'आपने रोका',
  'Cancelled by you': 'आपने रद्द किया',
  'The company is frozen': 'कंपनी फ़्रीज़ है',
  'Its record did not match on replay': 'दोबारा चलाने पर इसका रिकॉर्ड मेल नहीं खाया',
  'It kept stopping the worker running it': 'इसकी वजह से इसे चलाने वाला वर्कर बार-बार रुकता रहा',
  'Not done': 'नहीं हुआ',
  'Task failed': 'कार्य विफल रहा',
  'Digest for {day}': '{day} का सारांश',
  'Spent: {amount}': 'खर्च हुआ: {amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': 'काम — पूरा हुआ: {done}, विफल: {failed}, रुके हुए: {stopped}',
  'Inbox: {open} waiting (incidents: {incidents})': 'इनबॉक्स: {open} इंतज़ार में (घटनाएँ: {incidents})',
  'Stopped ({count}): {reason}': 'रुके हुए ({count}): {reason}',
  'Start an ad campaign': 'विज्ञापन कैंपेन शुरू करें',
  'Block time on the calendar': 'कैलेंडर में समय ब्लॉक करें',
  'Read the calendar': 'कैलेंडर पढ़ें',
  'Run code': 'कोड चलाएँ',
  'Add a note to a customer': 'ग्राहक के रिकॉर्ड में नोट जोड़ें',
  'Read customer records': 'ग्राहकों के रिकॉर्ड पढ़ें',
  'Release to the live site': 'लाइव साइट पर रिलीज़ करें',
  'Release to the test site': 'टेस्ट साइट पर रिलीज़ करें',
  'Change a domain\'s nameservers': 'किसी डोमेन के नेमसर्वर बदलें',
  'Read a domain\'s records': 'किसी डोमेन के रिकॉर्ड पढ़ें',
  'Change a domain\'s record': 'किसी डोमेन का रिकॉर्ड बदलें',
  'Write a document': 'दस्तावेज़ लिखें',
  'Sign a document': 'दस्तावेज़ पर हस्ताक्षर करें',
  'Buy a domain': 'डोमेन खरीदें',
  'Transfer a domain': 'डोमेन ट्रांसफ़र करें',
  'Draft an email': 'ईमेल का ड्राफ़्ट बनाएँ',
  'Send an email': 'ईमेल भेजें',
  'List files': 'फ़ाइलों की सूची देखें',
  'Transfer money': 'पैसे ट्रांसफ़र करें',
  'Propose a goal change': 'लक्ष्य में बदलाव का प्रस्ताव दें',
  'Make a picture': 'चित्र बनाएँ',
  'Issue an invoice': 'इनवॉइस जारी करें',
  'Pay an invoice': 'इनवॉइस का भुगतान करें',
  'Read the books': 'हिसाब-किताब देखें',
  'Read the mailbox': 'मेलबॉक्स पढ़ें',
  'Search what the company knows': 'कंपनी की जानकारी में खोजें',
  'Record a measure': 'माप दर्ज करें',
  'Read product numbers': 'प्रोडक्ट के आँकड़े पढ़ें',
  'Ask you a question': 'आपसे सवाल पूछना',
  'Write down a plan': 'योजना दर्ज करें',
  'Delete a record': 'रिकॉर्ड मिटाएँ',
  'Propose a code change': 'कोड में बदलाव का प्रस्ताव दें',
  'Read the code': 'कोड पढ़ें',
  'Destroy a server': 'सर्वर नष्ट करें',
  'Read a skill': 'स्किल पढ़ें',
  'Publish a post': 'पोस्ट प्रकाशित करें',
  'Read text aloud': 'टेक्स्ट बोलकर सुनाएँ',
  'Turn speech into text': 'आवाज़ को टेक्स्ट में बदलें',
  'Propose a new stage': 'नए चरण का प्रस्ताव दें',
  'Wait for work handed on': 'आगे सौंपे गए काम का इंतज़ार करें',
  'Hand work to another role': 'काम दूसरी भूमिका को सौंपें',
  'File a ticket': 'टिकट दर्ज करें',
  'List tickets': 'टिकटों की सूची देखें',
  'Check a service is up': 'जाँचें कि सेवा चालू है या नहीं',
  'Read a web page': 'वेब पेज पढ़ें',
  'Open a web page': 'वेब पेज खोलें',
  'Search the web': 'वेब पर खोजें',
};
