/**
 * हिन्दी: what the platform itself says to the owner outside the console
 * (src/owner/say.ts), keyed by its English.
 *
 * The terms are the console's (console/src/locales/hi.ts): its buttons are
 * named as the console names them, and a screen it points to ("यह
 * डिप्लॉयमेंट, टूल, सुनना") is spelled as the console draws it. Whoever is
 * speaking as "I" -- the CEO a company chose, or PALUGADA -- is given no
 * gender: the sentences are turned so that no verb needs one.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'घटना: {title}',
  'Done: {goal}': 'पूरा हुआ: {goal}',
  'Stopped before finishing: {goal}': 'पूरा होने से पहले रुका: {goal}',
  'Not done: {goal}': 'नहीं हुआ: {goal}',
  'Why: {reason}': 'कारण: {reason}',
  'a task': 'एक कार्य',
  'Approval needed: {title}': 'स्वीकृति चाहिए: {title}',
  '{summary} — if denied: {consequence}': '{summary} — अस्वीकार करने पर: {consequence}',
  '{role} asks:': '{role} का सवाल:',
  'If denied:': 'अस्वीकार करने पर:',
  'Expires:': 'समाप्ति:',
  'This one is decided in the app.': 'इस पर निर्णय ऐप में होता है।',
  'Open in PALUGADA': 'PALUGADA में खोलें',
  'Approve': 'स्वीकृत करें',
  'Deny': 'अस्वीकार करें',
  'Ask': 'पूछें',
  'Approved. Nothing left to press here.': 'स्वीकृत। यहाँ अब कुछ दबाना बाकी नहीं है।',
  'Denied. Nothing left to press here.': 'अस्वीकृत। यहाँ अब कुछ दबाना बाकी नहीं है।',
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    'बिना जवाब के समाप्त। चुप रहना इनकार माना जाता है, इसलिए कुछ नहीं किया गया।',
  'This bot only answers to its owner.': 'यह बॉट सिर्फ़ अपने स्वामी को जवाब देता है।',
  'That one has to be approved in the app.': 'इसे ऐप में ही स्वीकृत करना होगा।',
  'That could not be recorded.': 'इसे दर्ज नहीं किया जा सका।',
  'That item no longer exists.': 'वह आइटम अब मौजूद नहीं है।',
  'What do you want to ask about "{title}"? Reply to this message.':
    '"{title}" के बारे में आप क्या पूछना चाहते हैं? इस संदेश पर रिप्लाई करें।',
  'Your question': 'आपका सवाल',
  'Type your question as a reply.': 'अपना सवाल रिप्लाई में टाइप करें।',
  'Asked. The answer will be on the item in the app.': 'पूछ लिया गया। जवाब ऐप में उसी आइटम पर मिलेगा।',
  'Answer': 'जवाब दें',
  'Answer in words': 'शब्दों में जवाब दें',
  'That choice is not on this question.': 'यह विकल्प इस सवाल में नहीं है।',
  'Chosen: {choice}.': 'चुना गया: {choice}।',
  'Stop the task': 'कार्य रोकें',
  'Your answer to "{question}"? Reply to this message.': '"{question}" का आपका जवाब? इस संदेश पर रिप्लाई करें।',
  'Your answer': 'आपका जवाब',
  'Type your answer as a reply.': 'अपना जवाब रिप्लाई में टाइप करें।',
  'Answered. The task carries on with it.': 'जवाब दे दिया गया। कार्य उसी के साथ आगे बढ़ता है।',
  'That is too long for one question; keep it under {max} characters.':
    'एक सवाल के लिए यह बहुत लंबा है; इसे {max} अक्षरों से कम रखें।',
  '[a key, not kept]': '[एक कुंजी, रखी नहीं गई]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    'यह कुंजी जैसा दिखता है, इसलिए मैंने इसे न रखा है, न कहीं भेजा है। कुंजियाँ किसी कार्ड के सील किए गए फ़ील्ड में, या “यह डिप्लॉयमेंट” में उनके अपने पेज पर डाली जाती हैं: मुझे बताइए कि यह किसलिए है, और उसका कार्ड आपके सामने आ जाएगा।',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'अभी कोई मॉडल सेट नहीं है, इसलिए सोचना मेरे बस में नहीं है। “यह डिप्लॉयमेंट, मॉडल” में जाकर एक मॉडल चुनें; उसके बाद बाकी हर काम में मेरी मदद मिल सकेगी।',
  'The model did not answer: {reason}': 'मॉडल ने जवाब नहीं दिया: {reason}',
  'Here is what I propose.': 'मेरा प्रस्ताव यह है।',
  'I have nothing to add.': 'मेरे पास जोड़ने को कुछ नहीं है।',
  '{name}, CEO of {company}': '{name}, {company} में CEO',
  'That could not be answered: {reason}': 'इसका जवाब नहीं दिया जा सका: {reason}',
  'I read text and voice notes.': 'यहाँ टेक्स्ट और वॉइस नोट पढ़े जाते हैं।',
  'Now talking to {name}.': 'अब {name} से बात हो रही है।',
  'Choose whom to talk to.': 'चुनें कि आप किससे बात करना चाहते हैं।',
  'Choose whom to talk to': 'चुनें कि किससे बात करनी है',
  'Talk to PALUGADA about the whole deployment': 'पूरे डिप्लॉयमेंट के बारे में PALUGADA से बात करें',
  'Who you are talking to, and how': 'आप किससे बात कर रहे हैं, और कैसे',
  'Stopped.': 'रोक दिया गया।',
  'Write here to talk to {name}.': '{name} से बात करने के लिए यहाँ लिखें।',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    'आप {name} से बात कर रहे हैं। लिखें, या वॉइस नोट भेजें। /ceo से चुनें कि आप किससे बात करें; /palugada से पूरे डिप्लॉयमेंट के बारे में PALUGADA से बात करें।',
  'You said: "{words}"': 'आपने कहा: "{words}"',
  'in the app': 'ऐप में',
  'Apply: {summary}': 'लागू करें: {summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    'अभी कोई भी आवाज़ नहीं सुन सकता: ऐप में “यह डिप्लॉयमेंट, टूल, सुनना” में जाकर कोई प्रदाता चुनें।',
  'That recording is too long; keep a voice note under {max} MB.': 'वह रिकॉर्डिंग बहुत लंबी है; वॉइस नोट {max} MB से छोटा रखें।',
  'I could not make out any words in that.': 'उसमें मुझे कोई भी शब्द समझ नहीं आया।',
  'Done: {summary}': 'हो गया: {summary}',
  'That one is applied in the app.': 'इसे ऐप में ही लागू किया जाता है।',
  'That card no longer exists.': 'वह कार्ड अब मौजूद नहीं है।',
  'That card was already applied.': 'वह कार्ड पहले ही लागू हो चुका है।',
  'That card was dismissed.': 'वह कार्ड खारिज कर दिया गया था।',
  'That card failed when it was applied.': 'लागू करते समय वह कार्ड विफल रहा।',
  'That could not be done: {reason}': 'यह नहीं किया जा सका: {reason}',
  'Choose': 'चुनें',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    '"{title}" के बारे में आप क्या पूछना चाहते हैं? इस संदेश पर रिप्लाई करके अपना सवाल भेजें।',
  'Your answer to "{question}"? Reply to this message with your answer.':
    '"{question}" का आपका जवाब? इस संदेश पर रिप्लाई करके अपना जवाब भेजें।',
  'I read text messages here.': 'यहाँ टेक्स्ट संदेश पढ़े जाते हैं।',
  'Apply one of these here:': 'इनमें से कोई एक यहाँ लागू करें:',
  'Apply {number}': '{number} लागू करें',
  'Signed in to {provider} for the {alias} key': '{alias} कुंजी के लिए {provider} में साइन इन हो गया',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'PALUGADA पर लौटें: यह कुंजी अब विभाग के पास है, और खत्म होने से पहले अपने आप रिन्यू हो जाती है। यह टैब बंद किया जा सकता है।',
  'Signed in to {name}': '{name} में साइन इन हो गया',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'PALUGADA पर लौटकर चुनें कि भूमिकाएँ इसके कौन-से टूल इस्तेमाल कर सकती हैं। यह टैब बंद किया जा सकता है।',
  'Not signed in': 'साइन इन नहीं हुआ',
  "Recorded: approved.": "दर्ज हुआ: स्वीकृत।",
  "Recorded: denied.": "दर्ज हुआ: अस्वीकृत।",
  "Recorded: asked.": "दर्ज हुआ: सवाल पूछा गया।",
  "Asked. Nothing left to press here.": "पूछ लिया गया। यहाँ अब कुछ दबाना बाकी नहीं है।",
  "Withdrawn: the task it was asking about has finished.": "वापस लिया गया: जिस कार्य के बारे में यह पूछ रहा था, वह पूरा हो चुका है।",
  "Withdrawn: the task it was asking about has failed.": "वापस लिया गया: जिस कार्य के बारे में यह पूछ रहा था, वह विफल हो गया है।",
  "Withdrawn: the task it was asking about was stopped.": "वापस लिया गया: जिस कार्य के बारे में यह पूछ रहा था, उसे रोक दिया गया।",
  "Withdrawn: the task it was asking about was cancelled.": "वापस लिया गया: जिस कार्य के बारे में यह पूछ रहा था, उसे रद्द कर दिया गया।",
  'Decided. Nothing left to press here.': 'निर्णय हो चुका। यहाँ अब कुछ दबाना बाकी नहीं है।',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': 'वापस लिया गया: एजेंट ने अपना प्रस्ताव बदल दिया और नए प्रस्ताव के बारे में फिर से पूछा।',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': 'वापस लिया गया: कंपनी अब उस चरण में नहीं है जिससे यह प्रस्ताव उसे आगे ले जाता।',
  'Withdrawn: it was already decided in the app.': 'वापस लिया गया: ऐप में इसका निर्णय पहले ही हो चुका है।',
  'Withdrawn. Nothing left to press here.': 'वापस लिया गया। यहाँ अब कुछ दबाना बाकी नहीं है।',
  'company': 'कंपनी',
  'Work stopped: the {account} account is out of tokens': 'काम रुक गया: {account} खाते के टोकन खत्म हो गए',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': '“{work}” रुक गया क्योंकि {account} खाता अपने {max} टोकन में से {spent} इस्तेमाल कर चुका है। पैसा पेज पर इसकी सीमा बढ़ाएँ, फिर कार्य खोलकर जारी रखें दबाएँ: यह वहीं से आगे बढ़ेगा जहाँ रुका था।',
  'Withdrawn: you continued the task it was about.': 'वापस लिया गया: आपने इससे जुड़ा कार्य जारी रखा।',
  'Broke its contract': 'अपना अनुबंध तोड़ा',
  'Refused by a policy': 'नीति ने अस्वीकार किया',
  'Out of budget': 'बजट खत्म',
  'Handed on too many times': 'बहुत बार आगे सौंपा गया',
  'Missed its deadline': 'समय-सीमा पार हो गई',
  'Its result did not check out': 'इसका नतीजा जाँच में सही नहीं निकला',
  'A capability it needs is down': 'इसके लिए ज़रूरी एक क्षमता काम नहीं कर रही',
  'No runtime could take it': 'कोई रनटाइम इसे नहीं ले सका',
  'Went in a circle': 'घूमकर वहीं लौट आया',
  'Split into too many sub-tasks': 'बहुत सारे उप-कार्यों में बँट गया',
  'Wrote more than its role allows one run': 'भूमिका के एक रन की अनुमति से ज़्यादा लिखा',
  'Your approval was not given in time': 'आपकी स्वीकृति समय पर नहीं मिली',
  'Stopped by you': 'आपने रोका',
  'Cancelled by you': 'आपने रद्द किया',
  'The company is frozen': 'कंपनी फ़्रीज़ है',
  'Its record did not match on replay': 'दोबारा चलाने पर इसका रिकॉर्ड मेल नहीं खाया',
  'It kept stopping the worker running it': 'इसकी वजह से इसे चलाने वाला वर्कर बार-बार रुकता रहा',
  'Not done': 'नहीं हुआ',
  'Task failed': 'कार्य विफल रहा',
  'Digest for {day}': '{day} का सारांश',
  'Spent: {amount}': 'खर्च हुआ: {amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': 'काम — पूरा हुआ: {done}, विफल: {failed}, रुके हुए: {stopped}',
  'Inbox: {open} waiting (incidents: {incidents})': 'इनबॉक्स: {open} इंतज़ार में (घटनाएँ: {incidents})',
  'Stopped ({count}): {reason}': 'रुके हुए ({count}): {reason}',
  'Start an ad campaign': 'विज्ञापन कैंपेन शुरू करें',
  'Block time on the calendar': 'कैलेंडर में समय ब्लॉक करें',
  'Read the calendar': 'कैलेंडर पढ़ें',
  'Run code': 'कोड चलाएँ',
  'Add a note to a customer': 'ग्राहक के रिकॉर्ड में नोट जोड़ें',
  'Read customer records': 'ग्राहकों के रिकॉर्ड पढ़ें',
  'Release to the live site': 'लाइव साइट पर रिलीज़ करें',
  'Release to the test site': 'टेस्ट साइट पर रिलीज़ करें',
  'Change a domain\'s nameservers': 'किसी डोमेन के नेमसर्वर बदलें',
  'Read a domain\'s records': 'किसी डोमेन के रिकॉर्ड पढ़ें',
  'Change a domain\'s record': 'किसी डोमेन का रिकॉर्ड बदलें',
  'Write a document': 'दस्तावेज़ लिखें',
  'Sign a document': 'दस्तावेज़ पर हस्ताक्षर करें',
  'Buy a domain': 'डोमेन खरीदें',
  'Transfer a domain': 'डोमेन ट्रांसफ़र करें',
  'Draft an email': 'ईमेल का ड्राफ़्ट बनाएँ',
  'Send an email': 'ईमेल भेजें',
  'List files': 'फ़ाइलों की सूची देखें',
  'Read a file': 'कोई फ़ाइल पढ़ें',
  'Describe a picture': 'किसी चित्र का वर्णन करें',
  'Calculate in Python': 'Python से गणना करें',
  'Transfer money': 'पैसे ट्रांसफ़र करें',
  'Propose a goal change': 'लक्ष्य में बदलाव का प्रस्ताव दें',
  'Make a picture': 'चित्र बनाएँ',
  'Issue an invoice': 'इनवॉइस जारी करें',
  'Pay an invoice': 'इनवॉइस का भुगतान करें',
  'Read the books': 'हिसाब-किताब देखें',
  'Read the mailbox': 'मेलबॉक्स पढ़ें',
  'Search what the company knows': 'कंपनी की जानकारी में खोजें',
  'Record a measure': 'माप दर्ज करें',
  'Read product numbers': 'प्रोडक्ट के आँकड़े पढ़ें',
  'Ask you a question': 'आपसे सवाल पूछना',
  'Write down a plan': 'योजना दर्ज करें',
  'Delete a record': 'रिकॉर्ड मिटाएँ',
  'Propose a code change': 'कोड में बदलाव का प्रस्ताव दें',
  'Read the code': 'कोड पढ़ें',
  'Destroy a server': 'सर्वर नष्ट करें',
  'Read a skill': 'स्किल पढ़ें',
  'Publish a post': 'पोस्ट प्रकाशित करें',
  'Read text aloud': 'टेक्स्ट बोलकर सुनाएँ',
  'Turn speech into text': 'आवाज़ को टेक्स्ट में बदलें',
  'Propose a new stage': 'नए चरण का प्रस्ताव दें',
  'Wait for work handed on': 'आगे सौंपे गए काम का इंतज़ार करें',
  'Hand work to another role': 'काम दूसरी भूमिका को सौंपें',
  'File a ticket': 'टिकट दर्ज करें',
  'List tickets': 'टिकटों की सूची देखें',
  'Check a service is up': 'जाँचें कि सेवा चालू है या नहीं',
  'Read a web page': 'वेब पेज पढ़ें',
  'Open a web page': 'वेब पेज खोलें',
  'Search the web': 'वेब पर खोजें',
  'no stage': 'कोई चरण नहीं',
  'Explore': 'खोजबीन',
  'Validate': 'सत्यापन',
  'Build': 'निर्माण',
  'Launch': 'लॉन्च',
  'Grow': 'विकास',
  'Wind down': 'समेटना',
  'Monthly budget reached; the company is paused': 'मासिक बजट पूरा हो गया; कंपनी रोक दी गई है',
  '{spent} of {limit} spent since {since}. No new task will start and no external action will run until you raise the ceiling or allow spending past it for a while, under Money.': '{since} से {limit} में से {spent} खर्च हो चुके हैं। जब तक आप पैसा पेज पर सीमा नहीं बढ़ाते या कुछ समय के लिए उससे ज़्यादा खर्च की अनुमति नहीं देते, तब तक न कोई नया कार्य शुरू होगा और न कोई बाहरी कार्रवाई चलेगी।',
  'Monthly budget is 80% spent': 'मासिक बजट का 80% खर्च हो चुका है',
  '{spent} of {limit} spent since {since}. At 100% the company pauses.': '{since} से {limit} में से {spent} खर्च हो चुके हैं। 100% पर कंपनी रुक जाएगी।',
  'Role {role} is paused for spending too fast': 'भूमिका {role} को बहुत तेज़ी से खर्च करने के कारण रोका गया है',
  '{role} spent {spent} in the last hour, {multiple} times its usual {usual} an hour. It is paused before the monthly ceiling is reached, so there is money left to work with once you have found out why. Resume it when you have.': '{role} ने पिछले एक घंटे में {spent} खर्च किए, जो उसके सामान्य {usual} प्रति घंटे का {multiple} गुना है। इसे मासिक सीमा तक पहुँचने से पहले रोका गया है, ताकि कारण पता चलने के बाद काम करने के लिए पैसा बचा रहे। कारण पता चल जाए, तो इसे फिर शुरू करें।',
  'Daily model spend over threshold': 'मॉडल पर रोज़ का खर्च सीमा से ऊपर',
  'Model spend today is {spent}, over the {limit} ceiling.': 'आज मॉडल पर खर्च {spent} है, जो {limit} की सीमा से ज़्यादा है।',
  'Task failure rate over threshold': 'कार्यों की विफलता दर सीमा से ऊपर',
  '{failed} of {finished} tasks failed or stopped today ({rate}%), over the {limit}% threshold.': 'आज {finished} में से {failed} कार्य विफल हुए या रोके गए ({rate}%), जो {limit}% की सीमा से ज़्यादा है।',
  'Unusual number of policy refusals': 'नीति द्वारा असामान्य संख्या में अस्वीकृतियाँ',
  'Actions refused by a policy today: {count}, over the threshold of {limit}. Either an agent is probing its limits or a policy is miscalibrated.': 'आज किसी नीति द्वारा अस्वीकार की गई कार्रवाइयाँ: {count}, जो {limit} की सीमा से ज़्यादा है। या तो कोई एजेंट अपनी सीमाएँ परख रहा है, या कोई नीति ठीक से तय नहीं है।',
  'External writes failed verification': 'बाहर लिखे गए बदलाव जाँच में विफल',
  'Writes outside that reported success but read back differently: {count}. Something is changing them other than as asked.': 'बाहर लिखे गए ऐसे बदलाव जिन्होंने सफलता बताई, पर वापस पढ़ने पर अलग निकले: {count}। कोई चीज़ उन्हें माँगे गए से अलग तरह से बदल रही है।',
  'A capability stopped being usable': 'एक क्षमता इस्तेमाल लायक नहीं रही',
  'Tasks that could not start today because a capability their role needs failed its check: {count}. A credential has probably expired or a quota is used up.': 'आज जो कार्य इसलिए शुरू नहीं हो सके क्योंकि उनकी भूमिका के लिए ज़रूरी एक क्षमता अपनी जाँच में विफल रही: {count}। शायद कोई क्रेडेंशियल समाप्त हो गया है या कोई कोटा खत्म हो गया है।',
  'A worker stopped reporting mid-run': 'रन के बीच में एक वर्कर ने रिपोर्ट करना बंद कर दिया',
  'Runs that stopped reporting and were taken back today: {count}. The work was picked up again; the tokens they had already spent were not recovered.': 'आज जिन रनों ने रिपोर्ट करना बंद किया और जिन्हें वापस लिया गया: {count}। काम फिर से उठा लिया गया; जो टोकन वे पहले ही खर्च कर चुके थे, वे वापस नहीं मिले।',
  '{role} was refused {denials} times today, at the limit of {limit}. No task will run as this role until you lift the freeze. The usual causes are a missing capability grant, a policy the role\'s charter does not account for, or work the role was never equipped to do.': 'आज {role} को {denials} बार अस्वीकार किया गया, जो {limit} की सीमा है। जब तक आप इसे अनफ़्रीज़ नहीं करते, इस भूमिका से कोई कार्य नहीं चलेगा। आम कारण होते हैं: किसी क्षमता की अनुमति न होना, कोई ऐसी नीति जिसका भूमिका के चार्टर में ध्यान नहीं रखा गया, या ऐसा काम जिसके लिए भूमिका कभी तैयार ही नहीं की गई।',
  'Role {role} is frozen after repeated denials': 'बार-बार अस्वीकृति के बाद भूमिका {role} फ़्रीज़ की गई',
  'What it was refused: {capabilities}': 'जो अस्वीकार किया गया: {capabilities}',
  'It is waiting for an approval, and none is open, so nothing you can answer will move it.': 'यह एक स्वीकृति का इंतज़ार कर रहा है, पर कोई स्वीकृति खुली नहीं है, इसलिए आपका कोई भी जवाब इसे आगे नहीं बढ़ाएगा।',
  'It is waiting for a review, and none is pending, so no reviewer and no decision of yours will move it.': 'यह एक समीक्षा का इंतज़ार कर रहा है, पर कोई समीक्षा बाकी नहीं है, इसलिए न कोई समीक्षक और न आपका कोई निर्णय इसे आगे बढ़ाएगा।',
  'It is parked until a window reopens, and the window never does.': 'यह किसी समय-खिड़की के दोबारा खुलने तक रुका हुआ है, और वह समय-खिड़की कभी नहीं खुलती।',
  'A task is waiting on nothing': 'एक कार्य ऐसी चीज़ का इंतज़ार कर रहा है जो कभी नहीं आएगी',
  '"{task}" has been waiting since {since}. {why} Approve to run it again from where it stopped, or deny to cancel it.': '“{task}” {since} से इंतज़ार कर रहा है। {why} जहाँ यह रुका था, वहीं से इसे फिर चलाने के लिए स्वीकृत करें, या रद्द करने के लिए अस्वीकार करें।',
  'A task keeps stopping the worker running it': 'एक कार्य की वजह से उसे चलाने वाला वर्कर बार-बार रुक रहा है',
  '"{task}" lost its worker {lost} times: each time the worker running it stopped answering before the work finished. What it had done is kept. It is halted so it cannot take another worker down; run it again once the cause is found, or cancel it.': '“{task}” ने अपना वर्कर {lost} बार खोया: हर बार इसे चलाने वाले वर्कर ने काम पूरा होने से पहले जवाब देना बंद कर दिया। इसने जो कर लिया था, वह सुरक्षित है। इसे रोक दिया गया है ताकि यह किसी और वर्कर को न गिराए; कारण मिल जाने पर इसे फिर चलाएँ, या रद्द करें।',
  '{services} stayed unreachable, and the work that needs it stopped': '{services} तक पहुँच नहीं हो पाई, और उस पर निर्भर काम रुक गया',
  'The task waited about {minutes} minutes, looking again each time, and has stopped. Once the service answers, run it again.': 'कार्य ने लगभग {minutes} मिनट इंतज़ार किया, हर बार दोबारा जाँचते हुए, और अब रुक गया है। सेवा जवाब देने लगे, तो इसे फिर चलाएँ।',
  'It was tried {tries} times over about {minutes} minutes.': 'लगभग {minutes} मिनट में {tries} बार प्रयास किया गया।',
  'This role can take actions that cannot be undone, so the run was not silently moved to a different model.': 'यह भूमिका ऐसी कार्रवाइयाँ कर सकती है जिन्हें पलटा न जा सके, इसलिए रन को चुपचाप किसी दूसरे मॉडल पर नहीं ले जाया गया।',
  'No fallback model is left for this role.': 'इस भूमिका के लिए कोई वैकल्पिक मॉडल नहीं बचा है।',
  'Model {model} failed and the run was not moved': 'मॉडल {model} विफल हुआ और रन को दूसरे मॉडल पर नहीं ले जाया गया',
  'External write failed verification': 'बाहर लिखा गया बदलाव जाँच में विफल',
  'The task wrote to an outside service and read it back, and what it read did not match. Look at the place it wrote to before you run it again: the write may have happened.': 'कार्य ने एक बाहरी सेवा में लिखा और उसे वापस पढ़ा, और जो पढ़ा वह मेल नहीं खाया। इसे फिर चलाने से पहले वह जगह देखें जहाँ इसने लिखा था: हो सकता है कि लिखा जा चुका हो।',
  'Review deadlocked after {rounds} revisions: {capability}': '{rounds} संशोधनों के बाद समीक्षा अटक गई: {capability}',
  'The role and its reviewer did not agree on {capability}.': 'भूमिका और उसका समीक्षक {capability} पर सहमत नहीं हुए।',
  'The reviewer\'s last note: {note}': 'समीक्षक का आखिरी नोट: {note}',
  'The reviewer left no note.': 'समीक्षक ने कोई नोट नहीं छोड़ा।',
  'What it was judged against: {criteria}': 'किस आधार पर परखा गया: {criteria}',
  'Review produced no usable verdict: {capability}': 'समीक्षा से कोई इस्तेमाल लायक निर्णय नहीं निकला: {capability}',
  'The reviewing task ended without a decision that could be read. The proposed action is still blocked and needs your judgement.': 'समीक्षा वाला कार्य किसी ऐसे निर्णय के बिना खत्म हुआ जिसे पढ़ा जा सके। प्रस्तावित कार्रवाई अब भी रुकी हुई है और इस पर आपका निर्णय चाहिए।',
  'another stage': 'कोई दूसरा चरण',
  'Either answer only closes this: the company stays in the {stage} stage.': 'दोनों में से कोई भी जवाब बस इसे बंद करता है: कंपनी {stage} चरण में ही रहेगी।',
  'Either answer only closes this: the company stays without a stage.': 'दोनों में से कोई भी जवाब बस इसे बंद करता है: कंपनी बिना चरण के ही रहेगी।',
  'To move it anyway, set the stage on the Overview.': 'फिर भी चरण बदलना हो, तो अवलोकन में चरण तय करें।',
  '{reviewer} stopped a proposal to move the company from {from} to {to}': '{reviewer} ने कंपनी का चरण बदलने का एक प्रस्ताव रोका: {from} → {to}',
  '{reviewer} reviewed it before you and stopped it:': '{reviewer} ने आपसे पहले इसकी समीक्षा की और इसे रोक दिया:',
  'No reason was given.': 'कोई कारण नहीं बताया गया।',
  'What was proposed:': 'क्या प्रस्ताव था:',
  'The company stays in the {stage} stage.': 'कंपनी {stage} चरण में ही रहेगी।',
  'The company stays without a stage.': 'कंपनी बिना चरण के ही रहेगी।',
  'Move the company from {from} to {to}?': 'कंपनी का चरण बदलें: {from} → {to}?',
  'Reviewed by {reviewer} before you:': 'आपसे पहले {reviewer} ने समीक्षा की:',
  'The schedule "{schedule}" keeps producing the same result': 'शेड्यूल “{schedule}” बार-बार एक ही नतीजा दे रहा है',
  'Its last {runs} runs all ended with the same output. That is sometimes exactly right -- a report with nothing new to say -- and often a schedule that stopped doing anything useful while still being paid for. Deny to turn it off; approve to keep it running and not be asked about this result again.': 'इसके पिछले {runs} रन एक ही आउटपुट के साथ खत्म हुए। कभी-कभी यह बिल्कुल सही होता है — जैसे कोई रिपोर्ट जिसमें कहने को कुछ नया नहीं — और अक्सर यह ऐसा शेड्यूल होता है जो कुछ भी काम का करना बंद कर चुका है, पर जिसका भुगतान अब भी हो रहा है। इसे बंद करने के लिए अस्वीकार करें; इसे चलने देने और इस नतीजे के बारे में फिर न पूछे जाने के लिए स्वीकृत करें।',
  'Capability {capability} failed preflight': 'क्षमता {capability} शुरुआती जाँच में विफल रही',
  'Work that needs it is stopped rather than started: fix the cause, then run that work again. The usual causes are an expired or wrongly scoped credential, a quota used up, or an address that is wrong.': 'जिस काम को इसकी ज़रूरत है, उसे शुरू करने के बजाय रोका गया है: कारण ठीक करें, फिर वह काम दोबारा चलाएँ। आम कारण होते हैं: समाप्त या गलत दायरे वाला क्रेडेंशियल, खत्म हो चुका कोटा, या गलत पता।',
  'Batch guard stopped {capability}': 'बैच गार्ड ने {capability} को रोका',
  'It did not match the plan its run recorded. Nothing was sent, and no service was called.': 'यह उस योजना से मेल नहीं खाया जो इसके रन ने दर्ज की थी। कुछ भी नहीं भेजा गया, और किसी सेवा को कॉल नहीं किया गया।',
  '{role} was asked first and has had {minutes} minutes.': 'पहले {role} से कहा गया था, और उसे {minutes} मिनट मिल चुके हैं।',
  '{role} is not a role in this company, so this came to you at once.': '{role} इस कंपनी की कोई भूमिका नहीं है, इसलिए यह सीधे आपके पास आया।',
  '{role} could not be given this: the company has no active goal or project to hang it from.': 'यह {role} को नहीं सौंपा जा सका: कंपनी के पास कोई सक्रिय लक्ष्य या प्रोजेक्ट नहीं है जिसके तहत इसे रखा जाए।',
  '{role} could not be given this ({record}), so this came to you at once.': 'यह {role} को नहीं सौंपा जा सका ({record}), इसलिए यह सीधे आपके पास आया।',
  '{role} stopped without an account of what it did ({why}).': '{role} ने काम रोक दिया, और जो किया उसका कोई ब्योरा नहीं दिया ({why})।',
  '{role} finished without an account of what it did.': '{role} ने काम पूरा किया, पर जो किया उसका कोई ब्योरा नहीं दिया।',
  '{role} failed without an account of what it did.': '{role} का काम विफल हुआ, और जो किया उसका कोई ब्योरा नहीं दिया गया।',
  '{role} was stopped without an account of what it did.': '{role} का काम रोका गया, और जो किया उसका कोई ब्योरा नहीं दिया गया।',
  'Proposed change to the {kind} "{goal}"': '{kind} “{goal}” में प्रस्तावित बदलाव',
  'Currently: {statement}': 'अभी: {statement}',
  'Currently: {statement} ({status})': 'अभी: {statement} ({status})',
  'Proposed: {statement}': 'प्रस्तावित: {statement}',
  'Proposed status: {status}': 'प्रस्तावित स्थिति: {status}',
  'Reason given: {reason}': 'बताया गया कारण: {reason}',
  'Record an entry in the books': 'बहीखातों में प्रविष्टि दर्ज करें',
  'Record a customer or a deal': 'ग्राहक या सौदा दर्ज करें',
  'Not sent on its own: {reason}': 'खुद नहीं भेजा गया: {reason}',
  'it answers a conversation other than the one this work began with': 'यह जवाब किसी दूसरी बातचीत का है, उसका नहीं जिससे यह काम शुरू हुआ',
  'it named no passage of a document for customers': 'इस जवाब में ग्राहकों के लिए किसी दस्तावेज़ का कोई अंश नहीं बताया गया',
  'it answers from a document not marked for customers': 'यह जवाब ऐसे दस्तावेज़ से है जो ग्राहकों के लिए चिह्नित नहीं है',
  'it says a figure the documents and the customer did not: {detail}': 'इस जवाब में ऐसी संख्या है जो न दस्तावेज़ों में है न ग्राहक की बात में: {detail}',
  'it gives an address or link the documents and the customer did not: {detail}': 'इस जवाब में ऐसा पता या लिंक है जो न दस्तावेज़ों में है न ग्राहक की बात में: {detail}',
  'there have been six answers on its own in this conversation in the last hour': 'इस बातचीत में पिछले एक घंटे में पहले ही छह जवाब खुद भेजे जा चुके हैं',
  'the check found it is about a refund': 'जाँच ने पाया कि यह रिफ़ंड के बारे में है',
  'the check found it offers a price or terms of its own': 'जाँच ने पाया कि यह अपनी कीमत या शर्तें पेश करता है',
  'the check found it answers a serious complaint': 'जाँच ने पाया कि यह किसी गंभीर शिकायत का जवाब देता है',
  'the check found it touches the law': 'जाँच ने पाया कि यह क़ानूनी मामलों को छूता है',
  'the check found it gives or asks for personal data': 'जाँच ने पाया कि यह निजी डेटा देता या माँगता है',
  'the check found it promises something the documents do not': 'जाँच ने पाया कि यह ऐसा वादा करता है जो दस्तावेज़ों में नहीं है',
  'the check could not judge it': 'जाँच इसे परख नहीं सकी',
  'the check found something in it the documents do not say': 'जाँच को इसमें ऐसा कुछ मिला जो दस्तावेज़ नहीं कहते',
  '{role} proposes the schedule {name}': '{role} शेड्यूल {name} का प्रस्ताव देता है',
  'Each run: {instruction}': 'हर बार चलने पर: {instruction}',
  'Done by: {role}': 'करने वाला: {role}',
  'When: {cron} ({timezone}); the next runs are {runs}': 'कब: {cron} ({timezone}); अगली बार {runs} पर चलेगा',
  'Approving it makes the schedule and starts it; it can be turned off or changed under Team, Schedules.': 'स्वीकृत करने पर शेड्यूल बनता है और शुरू हो जाता है; इसे टीम, शेड्यूल में बंद या बदला जा सकता है।',
  'No schedule is made.': 'कोई शेड्यूल नहीं बनता।',
  'Propose a schedule': 'शेड्यूल का प्रस्ताव दें',
  'Approving it changes the goal; until then the work carries on under the goal as it is.': 'स्वीकृत करने पर लक्ष्य बदल जाएगा; तब तक काम मौजूदा लक्ष्य के तहत ही चलता रहेगा।',
  'The goal stays as it is.': 'लक्ष्य जैसा है, वैसा ही रहेगा।',
  'mission': 'मिशन',
  'objective': 'उद्देश्य',
  'key result': 'मुख्य परिणाम',
  'Active': 'सक्रिय',
  'Met': 'हासिल हुआ',
  'Abandoned': 'छोड़ दिया गया',
  'This work asked for it at tier {tier}, and policy {policies} requires your approval.': 'इस काम ने इसे स्तर {tier} पर माँगा, और नीति {policies} के लिए आपकी स्वीकृति ज़रूरी है।',
  'This work asked for it at tier {tier}, and the task began with content from outside the company.': 'इस काम ने इसे स्तर {tier} पर माँगा, और कार्य की शुरुआत कंपनी के बाहर की सामग्री से हुई थी।',
  'This work asked for it at tier {tier}, and the work read content from outside the company before asking.': 'इस काम ने इसे स्तर {tier} पर माँगा, और माँगने से पहले इसने कंपनी के बाहर की सामग्री पढ़ी थी।',
  'This work asked for it at tier {tier}, after the work read content from outside the company, and the guardian asked you first: {reason}': 'कंपनी के बाहर की सामग्री पढ़ने के बाद इस काम ने इसे स्तर {tier} पर माँगा, और संरक्षक ने पहले आपसे पूछना ठीक समझा: {reason}',
  'it doubted this call before, and you allowed it once': 'इसे इस कॉल पर पहले भी शक हुआ था, और आपने एक बार इसकी अनुमति दी थी',
  'This work asked for it at tier {tier}, which cannot be reversed.': 'इस काम ने इसे स्तर {tier} पर माँगा, जिसे पलटा नहीं जा सकता।',
  'You approved this once already, and the worker carrying it out stopped before it could say whether it happened: it may already have happened. Check before approving it again.': 'आप इसे एक बार पहले ही स्वीकृत कर चुके हैं, और इसे पूरा कर रहा वर्कर यह बताने से पहले ही रुक गया कि यह हुआ या नहीं: हो सकता है कि यह हो चुका हो। दोबारा स्वीकृत करने से पहले जाँच लें।',
  'What this is for — {goals}': 'यह किसलिए है — {goals}',
  'The task halts and no external change is made.': 'कार्य रुक जाता है और कोई बाहरी बदलाव नहीं किया जाता।',
  'Scored against {total} references: {passed} passed, {failed} failed.': '{total} रेफ़रेंस पर परखा गया: {passed} पास, {failed} विफल।',
  'This role has fewer than {minimum} accepted references, so the change is unscored. That is not the same as passing.': 'इस भूमिका के पास {minimum} से कम स्वीकृत रेफ़रेंस हैं, इसलिए बदलाव का स्कोर नहीं हुआ। इसका मतलब पास होना नहीं है।',
  'The role keeps working exactly as it does now.': 'भूमिका ठीक वैसे ही काम करती रहेगी जैसे अभी करती है।',
  '{role} asks: {question}': '{role} का सवाल: {question}',
  'The run did not say more than the question.': 'रन ने सवाल के अलावा और कुछ नहीं बताया।',
  'The task is stopped, and nothing it was going to do happens.': 'कार्य रोक दिया जाता है, और जो वह करने वाला था, उसमें से कुछ नहीं होता।',
  'You proposed it.': 'इसका प्रस्ताव आपने दिया था।',
  'It came with a bundle.': 'यह एक बंडल के साथ आई।',
  'An agent proposed it.': 'इसका प्रस्ताव एक एजेंट ने दिया था।',
  'It was learned from the company\'s work.': 'यह कंपनी के काम से सीखी गई।',
  'Skill "{skill}", version {version}': 'स्किल “{skill}”, संस्करण {version}',
  'The reviewer approved it: {note}': 'समीक्षक ने इसे स्वीकृत किया: {note}',
  'The reviewer approved it.': 'समीक्षक ने इसे स्वीकृत किया।',
  'Nothing changes; the current version of the skill stays in force.': 'कुछ नहीं बदलेगा; स्किल का मौजूदा संस्करण लागू रहेगा।',
  'Skills the bundle "{bundle}" brings: {count}': 'बंडल “{bundle}” के साथ आने वाली स्किल: {count}',
  'The reviewer read them all and approved these:': 'समीक्षक ने सभी को पढ़ा और इन्हें स्वीकृत किया:',
  'It turned these down, and they stay off:': 'इन्हें उसने ठुकरा दिया, और ये बंद रहेंगी:',
  'Approve to switch them all on, or deny to turn them all down. To decide one at a time, open the Skills page.': 'सभी को चालू करने के लिए स्वीकृत करें, या सभी को ठुकराने के लिए अस्वीकार करें। एक-एक करके तय करने के लिए स्किल पेज खोलें।',
  'Nothing changes; none of these skills is switched on.': 'कुछ नहीं बदलेगा; इनमें से कोई भी स्किल चालू नहीं होगी।',
  'I am {ceo}, and I run {company} for you. Three things before we start: what does {company} sell, and to whom? How much may it spend in a month? And what should its first piece of work be -- or shall I suggest one?': 'मैं {ceo} हूँ, और आपके लिए {company} को चलाने का ज़िम्मा मेरा है। शुरू करने से पहले तीन बातें: {company} क्या बेचती है, और किसे? एक महीने में यह कितना खर्च कर सकती है? और इसका पहला काम क्या हो — या मैं ही कोई काम सुझाऊँ?',
  'Read a customer conversation': 'ग्राहक की बातचीत पढ़ें',
  'Reply to a customer': 'ग्राहक को जवाब दें',
  'Read a page in the browser': 'ब्राउज़र में पेज पढ़ें',
  'Fill in a page in the browser': 'ब्राउज़र में पेज भरें',
  'Ask you to take over the browser': 'आपसे ब्राउज़र अपने हाथ में लेने को कहें',
  '{host} refused the model key ({status}), so nothing that needs the model can run. Open Settings, This deployment, Model, paste a key that works, test it and save.':
    '{host} ने मॉडल की कुंजी अस्वीकार कर दी ({status}), इसलिए मॉडल पर निर्भर कोई भी काम नहीं चल सकता। सेटिंग्स, यह डिप्लॉयमेंट, मॉडल खोलें, काम करने वाली कुंजी चिपकाएँ, उसे जाँचें और सहेजें।',
  '{host} refused the model key, and work is waiting': '{host} ने मॉडल की कुंजी अस्वीकार कर दी, और काम प्रतीक्षा में है',
  'What is waiting for the model carries on by itself once a key that works is in use.':
    'मॉडल की प्रतीक्षा कर रहा काम, काम करने वाली कुंजी इस्तेमाल होते ही अपने-आप आगे बढ़ जाएगा।',
  'A task ended before it was done: {task}':
    'एक काम पूरा होने से पहले ही खत्म हो गया: {task}',
  'It ended as: {reason}. No other card was raised for it, so it is here rather than silent.':
    'वह इस रूप में खत्म हुआ: {reason}। इसके लिए कोई और कार्ड नहीं बना, इसलिए यह यहाँ है, चुपचाप नहीं।',
  'Where its measures stand, as the platform reads them:':
    'प्लेटफ़ॉर्म के पढ़ने के अनुसार इसके मापदंड कहाँ हैं:',
  '{name}: no value recorded yet, against a target of {target}.':
    '{name}: अभी कोई मान दर्ज नहीं, लक्ष्य {target}।',
  '{name}: {value} against a target of {target}, read back from its source.':
    '{name}: {value}, लक्ष्य {target}, स्रोत से दोबारा पढ़कर जाँचा गया।',
  '{name}: {value} against a target of {target}, reported and not checked.':
    '{name}: {value}, लक्ष्य {target}, केवल बताया गया, जाँचा नहीं गया।',
  'Look at it again later': 'बाद में फिर देखें',
  "Deliver what this company sells, reliably and without surprising its owner.":
    "इस कंपनी जो बेचती है उसे भरोसेमंद ढंग से पहुँचाना, और मालिक को चौंकाए बिना।",
  "Ship the work the company has promised, on time and verified.":
    "कंपनी ने जो काम करने का वादा किया है, उसे समय पर और जाँच-परख कर पूरा करना।",
  "Keep the company solvent, answerable and running without daily attention.":
    "कंपनी को आर्थिक रूप से सक्षम, जवाबदेह और रोज़ की निगरानी के बिना चलने लायक बनाए रखना।",
};
