/**
 * Bahasa Indonesia: what the platform itself says to the owner outside the
 * console (src/owner/say.ts), keyed by its English.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'Insiden: {title}',
  'Done: {goal}': 'Selesai: {goal}',
  'Stopped before finishing: {goal}': 'Berhenti sebelum selesai: {goal}',
  'Why: {reason}': 'Sebabnya: {reason}',
  'a task': 'sebuah tugas',
  'Approval needed: {title}': 'Perlu persetujuan: {title}',
  '{summary} — if denied: {consequence}': '{summary} — jika ditolak: {consequence}',
  'If denied:': 'Jika ditolak:',
  'Expires:': 'Kedaluwarsa:',
  'This one is decided in the app.': 'Yang ini diputuskan di aplikasi.',
  'Open in PALUGADA': 'Buka di PALUGADA',
  'Approve': 'Setujui',
  'Deny': 'Tolak',
  'Ask': 'Tanya',
  'Approved. Nothing left to press here.': 'Disetujui. Tidak ada lagi yang perlu ditekan di sini.',
  'Denied. Nothing left to press here.': 'Ditolak. Tidak ada lagi yang perlu ditekan di sini.',
  'Decided ({decision}). Nothing left to press here.': 'Diputuskan ({decision}). Tidak ada lagi yang perlu ditekan di sini.',
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    'Kedaluwarsa tanpa jawaban. Diam berarti menolak, jadi tidak ada yang dijalankan.',
  'Withdrawn: the task it was asking about is {state}.': 'Ditarik: tugas yang ditanyakan sudah {state}.',
  'Withdrawn ({reason}).': 'Ditarik ({reason}).',
  'no reason recorded': 'tanpa alasan tercatat',
  'This bot only answers to its owner.': 'Bot ini hanya menjawab pemiliknya.',
  'Recorded: {decision}.': 'Tercatat: {decision}.',
  'That one has to be approved in the app.': 'Yang itu harus disetujui di aplikasi.',
  'Already closed: {reason}.': 'Sudah ditutup: {reason}.',
  'That could not be recorded.': 'Itu tidak bisa dicatat.',
  'That item no longer exists.': 'Item itu sudah tidak ada.',
  'What do you want to ask about "{title}"? Reply to this message.':
    'Apa yang ingin Anda tanyakan tentang "{title}"? Balas pesan ini.',
  'Your question': 'Pertanyaan Anda',
  'Type your question as a reply.': 'Ketik pertanyaan Anda sebagai balasan.',
  'Asked. The answer will be on the item in the app.': 'Sudah ditanyakan. Jawabannya akan muncul di item itu di aplikasi.',
  'Answer': 'Jawab',
  'Answer in words': 'Jawab dengan kata-kata',
  'That choice is not on this question.': 'Pilihan itu tidak ada di pertanyaan ini.',
  'Chosen: {choice}.': 'Dipilih: {choice}.',
  'Stop the task': 'Hentikan tugas',
  'Your answer to "{question}"? Reply to this message.': 'Jawaban Anda untuk "{question}"? Balas pesan ini.',
  'Your answer': 'Jawaban Anda',
  'Type your answer as a reply.': 'Ketik jawaban Anda sebagai balasan.',
  'Answered. The task carries on with it.': 'Terjawab. Tugas dilanjutkan dengan jawaban itu.',
  'That is too long for one question; keep it under {max} characters.':
    'Terlalu panjang untuk satu pertanyaan; buat di bawah {max} karakter.',
  '[a key, not kept]': '[sebuah kunci, tidak disimpan]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    'Itu tampak seperti kunci, jadi tidak saya simpan dan tidak saya kirim ke mana pun. Kunci diisi di kolom tersegel pada kartu, atau di halamannya di This deployment: katakan untuk apa, lalu saya siapkan kartunya.',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'Belum ada model yang dipasang, jadi saya belum bisa berpikir. Pilih satu di This deployment, Model; setelah itu saya bisa membantu semua yang lain.',
  'The model did not answer: {reason}': 'Model tidak menjawab: {reason}',
  'Here is what I propose.': 'Ini usulan saya.',
  'I have nothing to add.': 'Tidak ada yang perlu saya tambahkan.',
  '{name}, CEO of {company}': '{name}, CEO {company}',
  'That could not be answered: {reason}': 'Itu tidak bisa dijawab: {reason}',
  'I read text and voice notes.': 'Saya membaca teks dan pesan suara.',
  'Now talking to {name}.': 'Sekarang berbicara dengan {name}.',
  'Choose whom to talk to.': 'Pilih lawan bicara Anda.',
  'Choose whom to talk to': 'Pilih lawan bicara Anda',
  'Talk to PALUGADA about the whole deployment': 'Bicara dengan PALUGADA tentang seluruh deployment',
  'Who you are talking to, and how': 'Dengan siapa Anda berbicara, dan caranya',
  'Stopped.': 'Dihentikan.',
  'Write here to talk to {name}.': 'Tulis di sini untuk berbicara dengan {name}.',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    'Anda sedang berbicara dengan {name}. Tulis, atau kirim pesan suara. /ceo memilih lawan bicara; /palugada berbicara dengan PALUGADA tentang seluruh deployment.',
  'You said: "{words}"': 'Anda bilang: "{words}"',
  'in the app': 'di aplikasi',
  'Apply: {summary}': 'Terapkan: {summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    'Belum ada yang bisa mendengar suara: pilih penyedianya di aplikasi, di Deployment ini, Tools, Mendengarkan.',
  'That recording is too long; keep a voice note under {max} MB.': 'Rekaman itu terlalu panjang; buat pesan suara di bawah {max} MB.',
  'I could not make out any words in that.': 'Saya tidak menangkap satu kata pun di situ.',
  'Done: {summary}': 'Selesai: {summary}',
  'That one is applied in the app.': 'Yang itu diterapkan di aplikasi.',
  'That card no longer exists.': 'Kartu itu sudah tidak ada.',
  'That card was already applied.': 'Kartu itu sudah diterapkan.',
  'That card was dismissed.': 'Kartu itu sudah diabaikan.',
  'That card failed when it was applied.': 'Kartu itu gagal saat diterapkan.',
  'That could not be done: {reason}': 'Itu tidak bisa dilakukan: {reason}',
  'Choose': 'Pilih',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    'Apa yang ingin Anda tanyakan tentang "{title}"? Balas pesan ini dengan pertanyaan Anda.',
  'Your answer to "{question}"? Reply to this message with your answer.':
    'Jawaban Anda untuk "{question}"? Balas pesan ini dengan jawaban Anda.',
  'I read text messages here.': 'Di sini saya membaca pesan teks.',
  'Apply one of these here:': 'Terapkan salah satunya di sini:',
  'Apply {number}': 'Terapkan {number}',
  'Signed in to {provider} for the {alias} key': 'Sudah masuk ke {provider} untuk kunci {alias}',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'Kembali ke PALUGADA: divisi itu kini memegang kunci ini, dan diperbarui sendiri sebelum habis. Tab ini boleh ditutup.',
  'Signed in to {name}': 'Sudah masuk ke {name}',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'Kembali ke PALUGADA untuk memilih alat yang boleh dipakai peran. Tab ini boleh ditutup.',
  'Not signed in': 'Tidak masuk',
};
