/**
 * Bahasa Indonesia: what the platform itself says to the owner outside the
 * console (src/owner/say.ts), keyed by its English.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'Insiden: {title}',
  'Done: {goal}': 'Selesai: {goal}',
  'Stopped before finishing: {goal}': 'Berhenti sebelum selesai: {goal}',
  'Not done: {goal}': 'Tidak dikerjakan: {goal}',
  'Why: {reason}': 'Sebabnya: {reason}',
  'a task': 'sebuah tugas',
  'Approval needed: {title}': 'Perlu persetujuan: {title}',
  '{summary} — if denied: {consequence}': '{summary} — jika ditolak: {consequence}',
  '{role} asks:': '{role} bertanya:',
  'If denied:': 'Jika ditolak:',
  'Expires:': 'Kedaluwarsa:',
  'This one is decided in the app.': 'Yang ini diputuskan di aplikasi.',
  'Open in PALUGADA': 'Buka di PALUGADA',
  'Approve': 'Setujui',
  'Deny': 'Tolak',
  'Ask': 'Tanya',
  'Approved. Nothing left to press here.': 'Disetujui. Tidak ada lagi yang perlu ditekan di sini.',
  'Denied. Nothing left to press here.': 'Ditolak. Tidak ada lagi yang perlu ditekan di sini.',
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    'Kedaluwarsa tanpa jawaban. Diam berarti menolak, jadi tidak ada yang dijalankan.',
  'This bot only answers to its owner.': 'Bot ini hanya menjawab pemiliknya.',
  'That one has to be approved in the app.': 'Yang itu harus disetujui di aplikasi.',
  'That could not be recorded.': 'Itu tidak bisa dicatat.',
  'That item no longer exists.': 'Item itu sudah tidak ada.',
  'What do you want to ask about "{title}"? Reply to this message.':
    'Apa yang ingin Anda tanyakan tentang "{title}"? Balas pesan ini.',
  'Your question': 'Pertanyaan Anda',
  'Type your question as a reply.': 'Ketik pertanyaan Anda sebagai balasan.',
  'Asked. The answer will be on the item in the app.': 'Sudah ditanyakan. Jawabannya akan muncul di item itu di aplikasi.',
  'Answer': 'Jawab',
  'Answer in words': 'Jawab dengan kata-kata',
  'That choice is not on this question.': 'Pilihan itu tidak ada di pertanyaan ini.',
  'Chosen: {choice}.': 'Dipilih: {choice}.',
  'Stop the task': 'Hentikan tugas',
  'Your answer to "{question}"? Reply to this message.': 'Jawaban Anda untuk "{question}"? Balas pesan ini.',
  'Your answer': 'Jawaban Anda',
  'Type your answer as a reply.': 'Ketik jawaban Anda sebagai balasan.',
  'Answered. The task carries on with it.': 'Terjawab. Tugas dilanjutkan dengan jawaban itu.',
  'That is too long for one question; keep it under {max} characters.':
    'Terlalu panjang untuk satu pertanyaan; buat di bawah {max} karakter.',
  '[a key, not kept]': '[sebuah kunci, tidak disimpan]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    'Itu tampak seperti kunci, jadi tidak saya simpan dan tidak saya kirim ke mana pun. Kunci diisi di kolom tersegel pada kartu, atau di halamannya di This deployment: katakan untuk apa, lalu saya siapkan kartunya.',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'Belum ada model yang dipasang, jadi saya belum bisa berpikir. Pilih satu di This deployment, Model; setelah itu saya bisa membantu semua yang lain.',
  'The model did not answer: {reason}': 'Model tidak menjawab: {reason}',
  'Here is what I propose.': 'Ini usulan saya.',
  'I have nothing to add.': 'Tidak ada yang perlu saya tambahkan.',
  '{name}, CEO of {company}': '{name}, CEO {company}',
  'That could not be answered: {reason}': 'Itu tidak bisa dijawab: {reason}',
  'I read text and voice notes.': 'Saya membaca teks dan pesan suara.',
  'Now talking to {name}.': 'Sekarang berbicara dengan {name}.',
  'Choose whom to talk to.': 'Pilih lawan bicara Anda.',
  'Choose whom to talk to': 'Pilih lawan bicara Anda',
  'Talk to PALUGADA about the whole deployment': 'Bicara dengan PALUGADA tentang seluruh deployment',
  'Who you are talking to, and how': 'Dengan siapa Anda berbicara, dan caranya',
  'Stopped.': 'Dihentikan.',
  'Write here to talk to {name}.': 'Tulis di sini untuk berbicara dengan {name}.',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    'Anda sedang berbicara dengan {name}. Tulis, atau kirim pesan suara. /ceo memilih lawan bicara; /palugada berbicara dengan PALUGADA tentang seluruh deployment.',
  'You said: "{words}"': 'Anda bilang: "{words}"',
  'in the app': 'di aplikasi',
  'Apply: {summary}': 'Terapkan: {summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    'Belum ada yang bisa mendengar suara: pilih penyedianya di aplikasi, di Deployment ini, Tools, Mendengarkan.',
  'That recording is too long; keep a voice note under {max} MB.': 'Rekaman itu terlalu panjang; buat pesan suara di bawah {max} MB.',
  'I could not make out any words in that.': 'Saya tidak menangkap satu kata pun di situ.',
  'Done: {summary}': 'Selesai: {summary}',
  'That one is applied in the app.': 'Yang itu diterapkan di aplikasi.',
  'That card no longer exists.': 'Kartu itu sudah tidak ada.',
  'That card was already applied.': 'Kartu itu sudah diterapkan.',
  'That card was dismissed.': 'Kartu itu sudah diabaikan.',
  'That card failed when it was applied.': 'Kartu itu gagal saat diterapkan.',
  'That could not be done: {reason}': 'Itu tidak bisa dilakukan: {reason}',
  'Choose': 'Pilih',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    'Apa yang ingin Anda tanyakan tentang "{title}"? Balas pesan ini dengan pertanyaan Anda.',
  'Your answer to "{question}"? Reply to this message with your answer.':
    'Jawaban Anda untuk "{question}"? Balas pesan ini dengan jawaban Anda.',
  'I read text messages here.': 'Di sini saya membaca pesan teks.',
  'Apply one of these here:': 'Terapkan salah satunya di sini:',
  'Apply {number}': 'Terapkan {number}',
  'Signed in to {provider} for the {alias} key': 'Sudah masuk ke {provider} untuk kunci {alias}',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'Kembali ke PALUGADA: divisi itu kini memegang kunci ini, dan diperbarui sendiri sebelum habis. Tab ini boleh ditutup.',
  'Signed in to {name}': 'Sudah masuk ke {name}',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'Kembali ke PALUGADA untuk memilih alat yang boleh dipakai peran. Tab ini boleh ditutup.',
  'Not signed in': 'Tidak masuk',
  'Recorded: approved.': 'Tercatat: disetujui.',
  'Recorded: denied.': 'Tercatat: ditolak.',
  'Recorded: asked.': 'Tercatat: ditanyakan.',
  'Asked. Nothing left to press here.': 'Sudah ditanyakan. Tidak ada lagi yang perlu ditekan di sini.',
  'Withdrawn: the task it was asking about has finished.': 'Ditarik: tugas yang ditanyakan sudah selesai.',
  'Withdrawn: the task it was asking about has failed.': 'Ditarik: tugas yang ditanyakan gagal.',
  'Withdrawn: the task it was asking about was stopped.': 'Ditarik: tugas yang ditanyakan dihentikan.',
  'Withdrawn: the task it was asking about was cancelled.': 'Ditarik: tugas yang ditanyakan dibatalkan.',
  'Decided. Nothing left to press here.': 'Sudah diputuskan. Tidak ada lagi yang perlu ditekan di sini.',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': 'Ditarik: agent mengubah usulannya dan menanyakan lagi usulan yang baru.',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': 'Ditarik: perusahaan sudah tidak berada di tahap yang hendak diubah oleh usulan ini.',
  'Withdrawn: it was already decided in the app.': 'Ditarik: sudah diputuskan di aplikasi.',
  'Withdrawn. Nothing left to press here.': 'Ditarik. Tidak ada lagi yang perlu ditekan di sini.',
  'company': 'perusahaan',
  'Work stopped: the {account} account is out of tokens': 'Pekerjaan berhenti: token akun {account} habis',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': '“{work}” berhenti karena akun {account} sudah memakai {spent} dari {max} token. Naikkan plafonnya di Keuangan, lalu buka tugasnya dan tekan Lanjutkan: tugas meneruskan dari titik berhentinya.',
  'Withdrawn: you continued the task it was about.': 'Ditarik: Anda sudah melanjutkan tugas yang dimaksud.',
  'Broke its contract': 'Melanggar kontraknya',
  'Refused by a policy': 'Ditolak oleh kebijakan',
  'Out of budget': 'Kehabisan anggaran',
  'Handed on too many times': 'Dioper terlalu banyak kali',
  'Missed its deadline': 'Melewati tenggat',
  'Its result did not check out': 'Hasilnya tidak lolos pemeriksaan',
  'A capability it needs is down': 'Kemampuan yang dibutuhkannya sedang mati',
  'No runtime could take it': 'Tidak ada runtime yang bisa mengambilnya',
  'Went in a circle': 'Berputar-putar',
  'Split into too many sub-tasks': 'Dipecah menjadi terlalu banyak sub-tugas',
  'Wrote more than its role allows one run': 'Menulis lebih banyak dari yang diizinkan perannya untuk satu run',
  'Your approval was not given in time': 'Persetujuan Anda tidak datang tepat waktu',
  'Stopped by you': 'Dihentikan oleh Anda',
  'Cancelled by you': 'Dibatalkan oleh Anda',
  'The company is frozen': 'Perusahaan dibekukan',
  'Its record did not match on replay': 'Catatannya tidak cocok saat diputar ulang',
  'It kept stopping the worker running it': 'Tugas ini terus menghentikan worker yang menjalankannya',
  'Not done': 'Tidak dikerjakan',
  'Task failed': 'Tugas gagal',
  'Digest for {day}': 'Ringkasan {day}',
  'Spent: {amount}': 'Terpakai: {amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': 'Pekerjaan: {done} selesai, {failed} gagal, {stopped} berhenti',
  'Inbox: {open} waiting (incidents: {incidents})': 'Kotak masuk: {open} menunggu (insiden: {incidents})',
  'Stopped ({count}): {reason}': 'Berhenti ({count}): {reason}',
  'Start an ad campaign': 'Mulai kampanye iklan',
  'Block time on the calendar': 'Sisihkan waktu di kalender',
  'Read the calendar': 'Baca kalender',
  'Run code': 'Jalankan kode',
  'Add a note to a customer': 'Tambah catatan di data pelanggan',
  'Read customer records': 'Baca data pelanggan',
  'Release to the live site': 'Rilis ke situs publik',
  'Release to the test site': 'Rilis ke situs uji coba',
  'Change a domain\'s nameservers': 'Ubah nameserver domain',
  'Read a domain\'s records': 'Baca catatan DNS domain',
  'Change a domain\'s record': 'Ubah catatan DNS domain',
  'Write a document': 'Tulis dokumen',
  'Sign a document': 'Tanda tangani dokumen',
  'Buy a domain': 'Beli domain',
  'Transfer a domain': 'Pindahkan domain',
  'Draft an email': 'Buat draf email',
  'Send an email': 'Kirim email',
  'List files': 'Lihat daftar file',
  'Transfer money': 'Transfer uang',
  'Propose a goal change': 'Ajukan perubahan sasaran',
  'Make a picture': 'Buat gambar',
  'Issue an invoice': 'Terbitkan tagihan',
  'Pay an invoice': 'Bayar tagihan',
  'Read the books': 'Baca pembukuan',
  'Read the mailbox': 'Baca email masuk',
  'Search what the company knows': 'Cari yang diketahui perusahaan',
  'Record a measure': 'Catat ukuran',
  'Read product numbers': 'Baca statistik produk',
  'Ask you a question': 'Ajukan pertanyaan kepada Anda',
  'Write down a plan': 'Catat rencana',
  'Delete a record': 'Hapus data',
  'Propose a code change': 'Ajukan perubahan kode',
  'Read the code': 'Baca kode',
  'Destroy a server': 'Hapus server selamanya',
  'Read a skill': 'Baca skill',
  'Publish a post': 'Terbitkan unggahan',
  'Read text aloud': 'Bacakan teks',
  'Turn speech into text': 'Ubah suara menjadi teks',
  'Propose a new stage': 'Ajukan tahap baru',
  'Wait for work handed on': 'Tunggu pekerjaan yang diserahkan',
  'Hand work to another role': 'Serahkan pekerjaan ke peran lain',
  'File a ticket': 'Ajukan tiket',
  'List tickets': 'Lihat daftar tiket',
  'Check a service is up': 'Periksa apakah layanan berjalan',
  'Read a web page': 'Baca halaman web',
  'Open a web page': 'Buka halaman web',
  'Search the web': 'Cari di web',
};
