/**
 * Italiano: what the platform itself says to the owner outside the console
 * (src/owner/say.ts), keyed by its English.
 *
 * The words are the console's (console/src/locales/it.ts): Approva, Rifiuta
 * and Chiedi on the buttons, "Questa istanza, Strumenti, Ascolto" for the
 * screens it points at, and "tu" for the owner. WhatsApp cuts a reply
 * button's title at 20 characters and a list row's at 24, so those stay
 * short.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'Incidente: {title}',
  'Done: {goal}': 'Completata: {goal}',
  'Stopped before finishing: {goal}': 'Fermata prima di finire: {goal}',
  'Not done: {goal}': 'Non fatta: {goal}',
  'Why: {reason}': 'Motivo: {reason}',
  'a task': "un'attività",
  'Approval needed: {title}': 'Serve la tua approvazione: {title}',
  '{summary} — if denied: {consequence}': '{summary} — se rifiuti: {consequence}',
  '{role} asks:': '{role} chiede:',
  'If denied:': 'Se rifiuti:',
  'Expires:': 'Scade:',
  'This one is decided in the app.': "Questo si decide nell'app.",
  'Open in PALUGADA': 'Apri in PALUGADA',
  'Approve': 'Approva',
  'Deny': 'Rifiuta',
  'Ask': 'Chiedi',
  'Approved. Nothing left to press here.': "Approvato. Qui non c'è più niente da premere.",
  'Denied. Nothing left to press here.': "Rifiutato. Qui non c'è più niente da premere.",
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    'Scaduto senza risposta. Il silenzio vale come rifiuto, quindi non è stato fatto nulla.',
  'This bot only answers to its owner.': 'Questo bot risponde solo al suo proprietario.',
  'That one has to be approved in the app.': "Questo va approvato nell'app.",
  'That could not be recorded.': 'Non è stato possibile registrarlo.',
  'That item no longer exists.': 'Questo elemento non esiste più.',
  'What do you want to ask about "{title}"? Reply to this message.':
    'Cosa vuoi chiedere su “{title}”? Rispondi a questo messaggio.',
  'Your question': 'La tua domanda',
  'Type your question as a reply.': 'Rispondi a questo messaggio con la tua domanda.',
  'Asked. The answer will be on the item in the app.': "Domanda inviata. La risposta comparirà sull'elemento, nell'app.",
  'Answer': 'Rispondi',
  'Answer in words': 'Rispondi a parole',
  'That choice is not on this question.': 'Questa opzione non fa parte della domanda.',
  'Chosen: {choice}.': 'Scelto: {choice}.',
  'Stop the task': "Ferma l'attività",
  'Your answer to "{question}"? Reply to this message.': 'La tua risposta a “{question}”? Rispondi a questo messaggio.',
  'Your answer': 'La tua risposta',
  'Type your answer as a reply.': 'Rispondi a questo messaggio con la tua risposta.',
  'Answered. The task carries on with it.': "Risposta inviata. L'attività prosegue con quella.",
  'That is too long for one question; keep it under {max} characters.':
    'Troppo lungo per una domanda: resta sotto i {max} caratteri.',
  '[a key, not kept]': '[una chiave, non conservata]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    "Sembra una chiave, quindi non l'ho conservata né inviata da nessuna parte. Le chiavi vanno nel campo sigillato di una scheda, oppure nella loro pagina in Questa istanza: dimmi a cosa serve e ti presento la scheda.",
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'Non è ancora configurato nessun modello, quindi non posso ragionare. Scegline uno in Questa istanza, Modello; poi posso aiutarti con tutto il resto.',
  'The model did not answer: {reason}': 'Il modello non ha risposto: {reason}',
  'Here is what I propose.': 'Ecco cosa propongo.',
  'I have nothing to add.': 'Non ho niente da aggiungere.',
  '{name}, CEO of {company}': '{name}, CEO di {company}',
  'That could not be answered: {reason}': 'Non è stato possibile rispondere: {reason}',
  'I read text and voice notes.': 'Leggo messaggi di testo e vocali.',
  'Now talking to {name}.': 'Ora stai parlando con {name}.',
  'Choose whom to talk to.': 'Scegli con chi parlare.',
  'Choose whom to talk to': 'Scegli con chi parlare',
  'Talk to PALUGADA about the whole deployment': "Parla con PALUGADA dell'intera istanza",
  'Who you are talking to, and how': 'Con chi stai parlando, e come',
  'Stopped.': 'Interrotto.',
  'Write here to talk to {name}.': 'Scrivi qui per parlare con {name}.',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    "Stai parlando con {name}. Scrivi o manda un messaggio vocale. /ceo sceglie con chi parli; /palugada ti fa parlare con PALUGADA dell'intera istanza.",
  'You said: "{words}"': 'Hai detto: “{words}”',
  'in the app': "nell'app",
  'Apply: {summary}': 'Applica: {summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    "Ancora niente ascolta il parlato: scegli un fornitore nell'app, in Questa istanza, Strumenti, Ascolto.",
  'That recording is too long; keep a voice note under {max} MB.': 'Questa registrazione è troppo lunga: un messaggio vocale deve restare sotto i {max} MB.',
  'I could not make out any words in that.': 'Non sono riuscito a distinguere nessuna parola.',
  'Done: {summary}': 'Fatto: {summary}',
  'That one is applied in the app.': "Questa si applica nell'app.",
  'That card no longer exists.': 'Questa scheda non esiste più.',
  'That card was already applied.': 'Questa scheda è già stata applicata.',
  'That card was dismissed.': 'Questa scheda è stata ignorata.',
  'That card failed when it was applied.': "L'applicazione di questa scheda non è riuscita.",
  'That could not be done: {reason}': 'Non è stato possibile farlo: {reason}',
  'Choose': 'Scegli',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    'Cosa vuoi chiedere su “{title}”? Rispondi a questo messaggio con la tua domanda.',
  'Your answer to "{question}"? Reply to this message with your answer.':
    'La tua risposta a “{question}”? Rispondi a questo messaggio con la tua risposta.',
  'I read text messages here.': 'Qui leggo i messaggi di testo.',
  'Apply one of these here:': 'Applica qui una di queste:',
  'Apply {number}': 'Applica {number}',
  'Signed in to {provider} for the {alias} key': 'Accesso a {provider} effettuato per la chiave {alias}',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'Torna a PALUGADA: ora la divisione conserva questa chiave, che viene rinnovata prima della scadenza. Puoi chiudere questa scheda.',
  'Signed in to {name}': 'Accesso a {name} effettuato',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'Torna a PALUGADA per scegliere quali dei suoi strumenti possono usare i ruoli. Puoi chiudere questa scheda.',
  'Not signed in': 'Accesso non effettuato',
  'Recorded: approved.': 'Registrato: approvato.',
  'Recorded: denied.': 'Registrato: rifiutato.',
  'Recorded: asked.': 'Registrato: domanda inviata.',
  'Asked. Nothing left to press here.': "Domanda inviata. Qui non c'è più niente da premere.",
  'Withdrawn: the task it was asking about has finished.': "Ritirato: l'attività a cui si riferiva è stata completata.",
  'Withdrawn: the task it was asking about has failed.': "Ritirato: l'attività a cui si riferiva non è riuscita.",
  'Withdrawn: the task it was asking about was stopped.': "Ritirato: l'attività a cui si riferiva è stata fermata.",
  'Withdrawn: the task it was asking about was cancelled.': "Ritirato: l'attività a cui si riferiva è stata annullata.",
  'Decided. Nothing left to press here.': 'Deciso. Qui non c\'è più niente da premere.',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': 'Ritirato: l\'agente ha cambiato la sua proposta e ha chiesto di nuovo per quella nuova.',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': 'Ritirato: l\'azienda non è più nella fase da cui questa proposta l\'avrebbe spostata.',
  'Withdrawn: it was already decided in the app.': 'Ritirato: era già stato deciso nell\'app.',
  'Withdrawn. Nothing left to press here.': 'Ritirato. Qui non c\'è più niente da premere.',
  'company': 'azienda',
  'Work stopped: the {account} account is out of tokens': 'Il lavoro si è fermato: l’account {account} ha finito i token',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': '«{work}» si è fermato perché l’account {account} ha usato {spent} dei suoi {max} token. Alza il suo tetto in Denaro, poi apri l’attività e premi Continua: riprende da dove si era fermata.',
  'Withdrawn: you continued the task it was about.': 'Ritirato: hai continuato l’attività a cui si riferiva.',
  'Broke its contract': 'Ha violato il suo contratto',
  'Refused by a policy': 'Rifiutata da una policy',
  'Out of budget': 'Budget esaurito',
  'Handed on too many times': 'Passata avanti troppe volte',
  'Missed its deadline': 'Ha mancato la scadenza',
  'Its result did not check out': 'Il suo risultato non ha superato la verifica',
  'A capability it needs is down': 'Una capacità necessaria non è disponibile',
  'No runtime could take it': 'Nessun ambiente di esecuzione ha potuto prenderla in carico',
  'Went in a circle': 'Ha girato in tondo',
  'Split into too many sub-tasks': 'Suddivisa in troppe sottoattività',
  'Wrote more than its role allows one run': 'Ha scritto più di quanto il suo ruolo consenta in un\'esecuzione',
  'Your approval was not given in time': 'La tua approvazione non è arrivata in tempo',
  'Stopped by you': 'Fermata da te',
  'Cancelled by you': 'Annullata da te',
  'The company is frozen': 'L\'azienda è congelata',
  'Its record did not match on replay': 'Il suo registro non corrispondeva durante la riesecuzione',
  'It kept stopping the worker running it': 'Ha fatto fermare più volte l\'esecutore che la eseguiva',
  'Not done': 'Non fatta',
  'Task failed': 'Attività non riuscita',
  'Digest for {day}': 'Riepilogo del {day}',
  'Spent: {amount}': 'Speso: {amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': 'Lavoro — completate: {done}, non riuscite: {failed}, fermate: {stopped}',
  'Inbox: {open} waiting (incidents: {incidents})': 'Posta in arrivo: {open} in attesa (incidenti: {incidents})',
  'Stopped ({count}): {reason}': 'Fermate ({count}): {reason}',
  'Start an ad campaign': 'Avvia una campagna pubblicitaria',
  'Block time on the calendar': 'Blocca del tempo in calendario',
  'Read the calendar': 'Leggi il calendario',
  'Run code': 'Esegui del codice',
  'Add a note to a customer': 'Aggiungi una nota a un cliente',
  'Read customer records': 'Leggi le schede dei clienti',
  'Release to the live site': 'Pubblica sul sito ufficiale',
  'Release to the test site': 'Pubblica sul sito di prova',
  'Change a domain\'s nameservers': 'Modifica i server DNS di un dominio',
  'Read a domain\'s records': 'Leggi i record DNS di un dominio',
  'Change a domain\'s record': 'Modifica un record DNS di un dominio',
  'Write a document': 'Scrivi un documento',
  'Sign a document': 'Firma un documento',
  'Buy a domain': 'Acquista un dominio',
  'Transfer a domain': 'Trasferisci un dominio',
  'Draft an email': 'Scrivi una bozza di e-mail',
  'Send an email': 'Invia un\'e-mail',
  'List files': 'Elenca i file',
  'Read a file': 'Leggi un file',
  'Describe a picture': 'Descrivi un\'immagine',
  'Calculate in Python': 'Calcolare con Python',
  'Transfer money': 'Trasferisci denaro',
  'Propose a goal change': 'Proponi una modifica a un obiettivo',
  'Make a picture': 'Crea un\'immagine',
  'Issue an invoice': 'Emetti una fattura',
  'Pay an invoice': 'Paga una fattura',
  'Read the books': 'Leggi la contabilità',
  'Read the mailbox': 'Leggi la casella di posta',
  'Search what the company knows': 'Cerca in ciò che l\'azienda sa',
  'Record a measure': 'Registra una misurazione',
  'Read product numbers': 'Leggi le statistiche del prodotto',
  'Ask you a question': 'Ti fa una domanda',
  'Write down a plan': 'Registra un piano',
  'Delete a record': 'Elimina un record',
  'Propose a code change': 'Proponi una modifica al codice',
  'Read the code': 'Leggi il codice',
  'Destroy a server': 'Distruggi un server',
  'Read a skill': 'Leggi una competenza',
  'Publish a post': 'Pubblica un post',
  'Read text aloud': 'Leggi un testo ad alta voce',
  'Turn speech into text': 'Trasforma il parlato in testo',
  'Propose a new stage': 'Proponi una nuova fase',
  'Wait for work handed on': 'Aspetta il lavoro affidato ad altri',
  'Hand work to another role': 'Affida lavoro a un altro ruolo',
  'File a ticket': 'Apri un ticket',
  'List tickets': 'Elenca i ticket',
  'Check a service is up': 'Verifica che un servizio sia attivo',
  'Read a web page': 'Leggi una pagina web',
  'Open a web page': 'Apri una pagina web',
  'Search the web': 'Cerca sul web',
  'no stage': 'nessuna fase',
  'Explore': 'Esplorazione',
  'Validate': 'Validazione',
  'Build': 'Sviluppo',
  'Launch': 'Lancio',
  'Grow': 'Crescita',
  'Wind down': 'Chiusura graduale',
  'Monthly budget reached; the company is paused': 'Budget mensile raggiunto; l\'azienda è in pausa',
  '{spent} of {limit} spent since {since}. No new task will start and no external action will run until you raise the ceiling or allow spending past it for a while, under Money.': 'Spesi {spent} su {limit} dal {since}. Nessuna nuova attività partirà e nessuna azione esterna verrà eseguita finché non alzi il tetto o non permetti di spendere oltre il tetto per un periodo, in Denaro.',
  'Monthly budget is 80% spent': 'Budget mensile speso all\'80%',
  '{spent} of {limit} spent since {since}. At 100% the company pauses.': 'Spesi {spent} su {limit} dal {since}. Al 100% l\'azienda va in pausa.',
  'Role {role} is paused for spending too fast': 'Il ruolo {role} è in pausa perché spende troppo in fretta',
  '{role} spent {spent} in the last hour, {multiple} times its usual {usual} an hour. It is paused before the monthly ceiling is reached, so there is money left to work with once you have found out why. Resume it when you have.': '{role} ha speso {spent} nell\'ultima ora, {multiple} volte il suo consueto {usual} all\'ora. Il ruolo è stato messo in pausa prima di raggiungere il tetto mensile, così resta denaro con cui lavorare quando avrai scoperto il perché. A quel punto riprendilo.',
  'Daily model spend over threshold': 'Spesa giornaliera per i modelli oltre la soglia',
  'Model spend today is {spent}, over the {limit} ceiling.': 'La spesa per i modelli oggi è {spent}, oltre il tetto di {limit}.',
  'Task failure rate over threshold': 'Tasso di errore delle attività oltre la soglia',
  '{failed} of {finished} tasks failed or stopped today ({rate}%), over the {limit}% threshold.': 'Oggi {failed} attività su {finished} sono fallite o sono state fermate ({rate}%), oltre la soglia del {limit}%.',
  'Unusual number of policy refusals': 'Numero insolito di rifiuti per policy',
  'Actions refused by a policy today: {count}, over the threshold of {limit}. Either an agent is probing its limits or a policy is miscalibrated.': 'Azioni rifiutate oggi da una policy: {count}, oltre la soglia di {limit}. O un agente sta saggiando i propri limiti, o una policy è tarata male.',
  'External writes failed verification': 'Alcune scritture esterne non hanno superato la verifica',
  'Writes outside that reported success but read back differently: {count}. Something is changing them other than as asked.': 'Scritture all\'esterno riportate come riuscite ma rilette in modo diverso: {count}. Qualcosa le sta modificando in modo diverso da quanto richiesto.',
  'A capability stopped being usable': 'Una capacità non è più utilizzabile',
  'Tasks that could not start today because a capability their role needs failed its check: {count}. A credential has probably expired or a quota is used up.': 'Attività che oggi non sono potute partire perché una capacità richiesta dal loro ruolo non ha superato la verifica: {count}. Probabilmente una credenziale è scaduta o una quota è esaurita.',
  'A worker stopped reporting mid-run': 'Un esecutore ha smesso di dare segnali a metà esecuzione',
  'Runs that stopped reporting and were taken back today: {count}. The work was picked up again; the tokens they had already spent were not recovered.': 'Esecuzioni che oggi hanno smesso di dare segnali e sono state recuperate: {count}. Il lavoro è stato ripreso; i token che avevano già speso sono persi.',
  '{role} was refused {denials} times today, at the limit of {limit}. No task will run as this role until you lift the freeze. The usual causes are a missing capability grant, a policy the role\'s charter does not account for, or work the role was never equipped to do.': 'Il ruolo {role} ha ricevuto oggi {denials} rifiuti, raggiungendo il limite di {limit}. Nessuna attività verrà eseguita con questo ruolo finché non lo scongeli. Le cause più comuni sono un\'autorizzazione mancante per una capacità, una policy di cui lo statuto del ruolo non tiene conto, o un lavoro per cui il ruolo non è mai stato attrezzato.',
  'Role {role} is frozen after repeated denials': 'Il ruolo {role} è congelato dopo ripetuti rifiuti',
  'What it was refused: {capabilities}': 'Cosa gli è stato rifiutato: {capabilities}',
  'It is waiting for an approval, and none is open, so nothing you can answer will move it.': 'L\'attività è in attesa di un\'approvazione, ma non ce n\'è nessuna aperta, quindi nessuna tua risposta potrà sbloccarla.',
  'It is waiting for a review, and none is pending, so no reviewer and no decision of yours will move it.': 'L\'attività è in attesa di una revisione, ma non ce n\'è nessuna in sospeso, quindi né un revisore né una tua decisione potranno sbloccarla.',
  'It is parked until a window reopens, and the window never does.': 'L\'attività è in sospeso finché non si riapre una fascia oraria, ma quella fascia non si riapre mai.',
  'A task is waiting on nothing': 'Un\'attività aspetta qualcosa che non arriverà',
  '"{task}" has been waiting since {since}. {why} Approve to run it again from where it stopped, or deny to cancel it.': 'L\'attività “{task}” è in attesa dal {since}. {why} Scegli “Approva” per eseguirla di nuovo da dove si era fermata, oppure “Rifiuta” per annullarla.',
  'A task keeps stopping the worker running it': 'Un\'attività continua a far fermare l\'esecutore che la esegue',
  '"{task}" lost its worker {lost} times: each time the worker running it stopped answering before the work finished. What it had done is kept. It is halted so it cannot take another worker down; run it again once the cause is found, or cancel it.': 'L\'attività “{task}” ha perso il suo esecutore {lost} volte: ogni volta l\'esecutore che la eseguiva ha smesso di rispondere prima che il lavoro finisse. Ciò che aveva fatto viene conservato. È stata bloccata perché non faccia cadere un altro esecutore; eseguila di nuovo quando avrai trovato la causa, oppure annullala.',
  '{services} stayed unreachable, and the work that needs it stopped': 'Non raggiungibile: {services} – il lavoro che ne ha bisogno si è fermato',
  'The task waited about {minutes} minutes, looking again each time, and has stopped. Once the service answers, run it again.': 'L\'attività ha atteso circa {minutes} minuti, riprovando ogni volta, e si è fermata. Quando il servizio risponde, eseguila di nuovo.',
  'It was tried {tries} times over about {minutes} minutes.': 'Tentativi: {tries} in circa {minutes} minuti.',
  'This role can take actions that cannot be undone, so the run was not silently moved to a different model.': 'Questo ruolo può compiere azioni irreversibili, quindi l\'esecuzione non è stata spostata di nascosto su un altro modello.',
  'No fallback model is left for this role.': 'Per questo ruolo non resta nessun modello di riserva.',
  'Model {model} failed and the run was not moved': 'Il modello {model} non ha funzionato e l\'esecuzione non è stata spostata',
  'External write failed verification': 'Una scrittura esterna non ha superato la verifica',
  'The task wrote to an outside service and read it back, and what it read did not match. Look at the place it wrote to before you run it again: the write may have happened.': 'L\'attività ha scritto su un servizio esterno e ha riletto il dato, e ciò che ha letto non corrispondeva. Controlla il punto in cui ha scritto prima di eseguirla di nuovo: la scrittura potrebbe essere avvenuta.',
  'Review deadlocked after {rounds} revisions: {capability}': 'Revisione in stallo dopo {rounds} rielaborazioni: {capability}',
  'The role and its reviewer did not agree on {capability}.': 'Il ruolo e il suo revisore non si sono trovati d\'accordo su “{capability}”.',
  'The reviewer\'s last note: {note}': 'L\'ultima nota del revisore: {note}',
  'The reviewer left no note.': 'Il revisore non ha lasciato note.',
  'What it was judged against: {criteria}': 'Criteri usati per giudicare: {criteria}',
  'Review produced no usable verdict: {capability}': 'La revisione non ha prodotto un verdetto utilizzabile: {capability}',
  'The reviewing task ended without a decision that could be read. The proposed action is still blocked and needs your judgement.': 'L\'attività di revisione si è conclusa senza una decisione leggibile. L\'azione proposta resta bloccata e richiede il tuo giudizio.',
  'another stage': 'un\'altra fase',
  'Either answer only closes this: the company stays in the {stage} stage.': 'Qualunque risposta chiude solo questo elemento: l\'azienda resta nella fase {stage}.',
  'Either answer only closes this: the company stays without a stage.': 'Qualunque risposta chiude solo questo elemento: l\'azienda resta senza fase.',
  'To move it anyway, set the stage on the Overview.': 'Per spostarla comunque, imposta la fase in Panoramica.',
  '{reviewer} stopped a proposal to move the company from {from} to {to}': '{reviewer} ha fermato una proposta di portare l\'azienda da “{from}” a “{to}”',
  '{reviewer} reviewed it before you and stopped it:': '{reviewer} l\'ha esaminata prima di te e l\'ha fermata:',
  'No reason was given.': 'Non è stato indicato alcun motivo.',
  'What was proposed:': 'Cosa è stato proposto:',
  'The company stays in the {stage} stage.': 'L\'azienda resta nella fase {stage}.',
  'The company stays without a stage.': 'L\'azienda resta senza fase.',
  'Move the company from {from} to {to}?': 'Portare l\'azienda da “{from}” a “{to}”?',
  'Reviewed by {reviewer} before you:': 'Esaminata da {reviewer} prima di te:',
  'The schedule "{schedule}" keeps producing the same result': 'La pianificazione “{schedule}” continua a produrre lo stesso risultato',
  'Its last {runs} runs all ended with the same output. That is sometimes exactly right -- a report with nothing new to say -- and often a schedule that stopped doing anything useful while still being paid for. Deny to turn it off; approve to keep it running and not be asked about this result again.': 'Le sue ultime {runs} esecuzioni si sono concluse tutte con lo stesso output. A volte è esattamente giusto – un report che non ha nulla di nuovo da dire – e spesso è una pianificazione che ha smesso di fare qualcosa di utile ma continua a essere pagata. Scegli “Rifiuta” per disattivarla, oppure “Approva” per lasciarla attiva e non ricevere più domande su questo risultato.',
  'Capability {capability} failed preflight': 'La capacità “{capability}” non ha superato la verifica preliminare',
  'Work that needs it is stopped rather than started: fix the cause, then run that work again. The usual causes are an expired or wrongly scoped credential, a quota used up, or an address that is wrong.': 'Il lavoro che ne ha bisogno viene fermato invece che avviato: risolvi la causa, poi esegui di nuovo quel lavoro. Le cause più comuni sono una credenziale scaduta o con permessi sbagliati, una quota esaurita o un indirizzo errato.',
  'Batch guard stopped {capability}': 'Il controllo sui lotti ha fermato “{capability}”',
  'It did not match the plan its run recorded. Nothing was sent, and no service was called.': 'La chiamata non corrispondeva al piano registrato dalla sua esecuzione. Non è stato inviato nulla e nessun servizio è stato chiamato.',
  '{role} was asked first and has had {minutes} minutes.': 'Il ruolo {role} è stato interpellato per primo e ha avuto {minutes} minuti.',
  '{role} is not a role in this company, so this came to you at once.': '{role} non è un ruolo di questa azienda, quindi questo elemento è arrivato subito a te.',
  '{role} could not be given this: the company has no active goal or project to hang it from.': 'Non è stato possibile affidarlo a {role}: l\'azienda non ha un obiettivo o un progetto attivo a cui collegarlo.',
  '{role} could not be given this ({record}), so this came to you at once.': 'Non è stato possibile affidarlo a {role} ({record}), quindi è arrivato subito a te.',
  '{role} stopped without an account of what it did ({why}).': 'Il ruolo {role} si è fermato senza dire cosa ha fatto ({why}).',
  '{role} finished without an account of what it did.': 'Il ruolo {role} ha finito senza dire cosa ha fatto.',
  '{role} failed without an account of what it did.': 'Il ruolo {role} ha fallito senza dire cosa ha fatto.',
  '{role} was stopped without an account of what it did.': 'Il ruolo {role} è stato fermato senza dire cosa ha fatto.',
  'Proposed change to the {kind} "{goal}"': 'Modifica proposta: {kind} “{goal}”',
  'Currently: {statement}': 'Attualmente: {statement}',
  'Currently: {statement} ({status})': 'Attualmente: {statement} ({status})',
  'Proposed: {statement}': 'Proposta: {statement}',
  'Proposed status: {status}': 'Stato proposto: {status}',
  'Reason given: {reason}': 'Motivo indicato: {reason}',
  'Record an entry in the books': 'Registrare una scrittura nei libri',
  'Record a customer or a deal': 'Registra un cliente o una trattativa',
  'Not sent on its own: {reason}': 'Non inviata da sola: {reason}',
  'it answers a conversation other than the one this work began with': 'risponde a una conversazione diversa da quella con cui è iniziato questo lavoro',
  'it named no passage of a document for customers': 'non ha citato alcun passo di un documento per i clienti',
  'it answers from a document not marked for customers': 'risponde da un documento non segnato per i clienti',
  'it says a figure the documents and the customer did not: {detail}': 'dice una cifra che né i documenti né il cliente hanno dato: {detail}',
  'it gives an address or link the documents and the customer did not: {detail}': 'dà un indirizzo o un link che né i documenti né il cliente hanno dato: {detail}',
  'there have been six answers on its own in this conversation in the last hour': 'in questa conversazione ci sono già state sei risposte inviate da sole nell’ultima ora',
  'the check found it is about a refund': 'il controllo ha trovato che riguarda un rimborso',
  'the check found it offers a price or terms of its own': 'il controllo ha trovato che offre un prezzo o condizioni proprie',
  'the check found it answers a serious complaint': 'il controllo ha trovato che risponde a un reclamo serio',
  'the check found it touches the law': 'il controllo ha trovato che tocca questioni legali',
  'the check found it gives or asks for personal data': 'il controllo ha trovato che dà o chiede dati personali',
  'the check found it promises something the documents do not': 'il controllo ha trovato che promette qualcosa che i documenti non dicono',
  'the check could not judge it': 'il controllo non ha potuto giudicarla',
  'the check found something in it the documents do not say': 'il controllo vi ha trovato qualcosa che i documenti non dicono',
  '{role} proposes the schedule {name}': '{role} propone la pianificazione {name}',
  'Each run: {instruction}': 'A ogni esecuzione: {instruction}',
  'Done by: {role}': 'Svolta da: {role}',
  'When: {cron} ({timezone}); the next runs are {runs}': 'Quando: {cron} ({timezone}); le prossime esecuzioni sono {runs}',
  'Approving it makes the schedule and starts it; it can be turned off or changed under Team, Schedules.': 'Approvarla crea la pianificazione e la avvia; si può disattivare o cambiare in Organizzazione, Pianificazioni.',
  'No schedule is made.': 'Non viene creata nessuna pianificazione.',
  'Propose a schedule': 'Proporre una pianificazione',
  'Approving it changes the goal; until then the work carries on under the goal as it is.': 'Approvarla cambia l\'obiettivo; fino ad allora il lavoro continua con l\'obiettivo così com\'è.',
  'The goal stays as it is.': 'L\'obiettivo resta com\'è.',
  'mission': 'missione',
  'objective': 'obiettivo',
  'key result': 'risultato chiave',
  'Active': 'Attivo',
  'Met': 'Raggiunto',
  'Abandoned': 'Abbandonato',
  'This work asked for it at tier {tier}, and policy {policies} requires your approval.': 'Il lavoro ha fatto questa richiesta al livello {tier}, e la policy {policies} richiede la tua approvazione.',
  'This work asked for it at tier {tier}, and the task began with content from outside the company.': 'Il lavoro ha fatto questa richiesta al livello {tier}, e l\'attività è iniziata con contenuti esterni all\'azienda.',
  'This work asked for it at tier {tier}, and the work read content from outside the company before asking.': 'Il lavoro ha fatto questa richiesta al livello {tier}, e prima di chiedere ha letto contenuti esterni all\'azienda.',
  'This work asked for it at tier {tier}, after the work read content from outside the company, and the guardian asked you first: {reason}': 'Il lavoro ha fatto questa richiesta al livello {tier} dopo aver letto contenuti esterni all\'azienda, e il guardiano ha chiesto prima a te: {reason}',
  'it doubted this call before, and you allowed it once': 'aveva già avuto dubbi su questa chiamata, e tu l\'hai consentita una volta',
  'This work asked for it at tier {tier}, which cannot be reversed.': 'Il lavoro ha fatto questa richiesta al livello {tier}, che è irreversibile.',
  'You approved this once already, and the worker carrying it out stopped before it could say whether it happened: it may already have happened. Check before approving it again.': 'L\'hai già approvata una volta, e l\'esecutore che la stava eseguendo si è fermato prima di poter dire se fosse avvenuta: potrebbe essere già avvenuta. Controlla prima di approvarla di nuovo.',
  'What this is for — {goals}': 'A cosa serve — {goals}',
  'The task halts and no external change is made.': 'L\'attività si interrompe e non viene apportata alcuna modifica esterna.',
  'Scored against {total} references: {passed} passed, {failed} failed.': 'Valutato su {total} riferimenti: {passed} superati, {failed} non superati.',
  'This role has fewer than {minimum} accepted references, so the change is unscored. That is not the same as passing.': 'Questo ruolo ha meno di {minimum} riferimenti accettati, quindi la modifica resta senza punteggio. Non equivale a superare la valutazione.',
  'The role keeps working exactly as it does now.': 'Il ruolo continua a lavorare esattamente come ora.',
  '{role} asks: {question}': '{role} chiede: {question}',
  'The run did not say more than the question.': 'L\'esecuzione non ha detto altro oltre alla domanda.',
  'The task is stopped, and nothing it was going to do happens.': 'L\'attività viene fermata e non succede nulla di ciò che stava per fare.',
  'You proposed it.': 'L\'hai proposta tu.',
  'It came with a bundle.': 'È arrivata con un pacchetto.',
  'An agent proposed it.': 'L\'ha proposta un agente.',
  'It was learned from the company\'s work.': 'È stata appresa dal lavoro dell\'azienda.',
  'Skill "{skill}", version {version}': 'Competenza “{skill}”, versione {version}',
  'The reviewer approved it: {note}': 'Il revisore l\'ha approvata: {note}',
  'The reviewer approved it.': 'Il revisore l\'ha approvata.',
  'Nothing changes; the current version of the skill stays in force.': 'Non cambia nulla; resta in vigore la versione attuale della competenza.',
  'Skills the bundle "{bundle}" brings: {count}': 'Competenze portate dal pacchetto “{bundle}”: {count}',
  'The reviewer read them all and approved these:': 'Il revisore le ha lette tutte e ha approvato queste:',
  'It turned these down, and they stay off:': 'Ha respinto queste, che restano disattivate:',
  'Approve to switch them all on, or deny to turn them all down. To decide one at a time, open the Skills page.': 'Scegli “Approva” per attivarle tutte, oppure “Rifiuta” per respingerle tutte. Per decidere una alla volta, apri la pagina Competenze.',
  'Nothing changes; none of these skills is switched on.': 'Non cambia nulla; nessuna di queste competenze viene attivata.',
  'I am {ceo}, and I run {company} for you. Three things before we start: what does {company} sell, and to whom? How much may it spend in a month? And what should its first piece of work be -- or shall I suggest one?': 'Sono {ceo} e gestisco {company} per te. Tre cose prima di cominciare: cosa vende {company}, e a chi? Quanto può spendere l\'azienda in un mese? E quale dovrebbe essere il suo primo lavoro – o vuoi che te ne proponga uno io?',
  'Read a customer conversation': 'Leggi una conversazione con un cliente',
  'Reply to a customer': 'Rispondi a un cliente',
  'Read a page in the browser': 'Leggi una pagina nel browser',
  'Fill in a page in the browser': 'Compila una pagina nel browser',
  'Ask you to take over the browser': 'Chiederti di prendere il controllo del browser',
  '{host} refused the model key ({status}), so nothing that needs the model can run. Open Settings, This deployment, Model, paste a key that works, test it and save.':
    '{host} ha rifiutato la chiave del modello ({status}), quindi nessun lavoro che richieda il modello può partire. Apri Impostazioni, Questa istanza, Modello, incolla una chiave valida, provala e salva.',
  '{host} refused the model key, and work is waiting': '{host} ha rifiutato la chiave del modello, e il lavoro è in attesa',
  'What is waiting for the model carries on by itself once a key that works is in use.':
    'Il lavoro in attesa del modello riprende da solo non appena è in uso una chiave valida.',
  'A task ended before it was done: {task}':
    'Un compito è terminato prima di essere finito: {task}',
  'It ended as: {reason}. No other card was raised for it, so it is here rather than silent.':
    'È finito così: {reason}. Per esso non è stata creata nessun’altra scheda, quindi compare qui invece di restare in silenzio.',
};
