/**
 * 日本語: what the platform itself says to the owner outside the console
 * (src/owner/say.ts), keyed by its English.
 *
 * The terms are the console's (console/src/locales/ja.ts): an approval is
 * 承認 and a denial 却下, an incident インシデント, a card is applied (適用),
 * and "the app" is the console (コンソール). Screens are named as the console
 * draws them: 「このインスタンス > モデル」. Sentences are polite です・ます;
 * buttons are short labels, within WhatsApp's twenty characters.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'インシデント：{title}',
  'Done: {goal}': '完了：{goal}',
  'Stopped before finishing: {goal}': '完了前に停止：{goal}',
  'Not done: {goal}': '未実施：{goal}',
  'Why: {reason}': '理由：{reason}',
  'a task': 'タスク',
  'Approval needed: {title}': '承認が必要：{title}',
  '{summary} — if denied: {consequence}': '{summary}（却下した場合：{consequence}）',
  '{role} asks:': '{role} からの質問：',
  'If denied:': '却下した場合：',
  'Expires:': '期限：',
  'This one is decided in the app.': 'これはコンソールで決定します。',
  'Open in PALUGADA': 'PALUGADA で開く',
  'Approve': '承認',
  'Deny': '却下',
  'Ask': '質問',
  'Approved. Nothing left to press here.': '承認しました。ここで操作することはもうありません。',
  'Denied. Nothing left to press here.': '却下しました。ここで操作することはもうありません。',
  'Expired unanswered. Silence is a refusal, so nothing was done.': '回答がないまま期限が切れました。返事がないことは拒否とみなされるため、何も実行されていません。',
  'This bot only answers to its owner.': 'このボットはオーナーにのみ応答します。',
  'That one has to be approved in the app.': 'これはコンソールで承認する必要があります。',
  'That could not be recorded.': '記録できませんでした。',
  'That item no longer exists.': 'その項目はもう存在しません。',
  'What do you want to ask about "{title}"? Reply to this message.': '「{title}」について何を質問しますか？このメッセージに返信してください。',
  'Your question': 'あなたの質問',
  'Type your question as a reply.': '返信として質問を入力してください。',
  'Asked. The answer will be on the item in the app.': '質問しました。回答はコンソールの該当項目に表示されます。',
  'Answer': '回答',
  'Answer in words': '言葉で回答',
  'That choice is not on this question.': 'その選択肢はこの質問にはありません。',
  'Chosen: {choice}.': '選択：{choice}。',
  'Stop the task': 'タスクを停止',
  'Your answer to "{question}"? Reply to this message.': '「{question}」への回答は？このメッセージに返信してください。',
  'Your answer': 'あなたの回答',
  'Type your answer as a reply.': '返信として回答を入力してください。',
  'Answered. The task carries on with it.': '回答しました。タスクはそれをもとに続行します。',
  'That is too long for one question; keep it under {max} characters.': '1 つの質問としては長すぎます。{max} 文字未満にしてください。',
  '[a key, not kept]': '[キーのため保存していません]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    'キーのように見えるため、保存も送信もしていません。キーはカードの暗号化フィールドか、「このインスタンス」の該当ページに入力してください。何に使うキーかを教えていただければ、カードをお出しします。',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'まだモデルが設定されていないため、考えることができません。「このインスタンス > モデル」で選んでください。そうすれば、ほかのことはすべてお手伝いできます。',
  'The model did not answer: {reason}': 'モデルが応答しませんでした：{reason}',
  'Here is what I propose.': '提案は次のとおりです。',
  'I have nothing to add.': '付け加えることはありません。',
  '{name}, CEO of {company}': '{company} の CEO、{name}',
  'That could not be answered: {reason}': '回答できませんでした：{reason}',
  'I read text and voice notes.': 'テキストとボイスメッセージを読み取れます。',
  'Now talking to {name}.': '{name} と話しています。',
  'Choose whom to talk to.': '話す相手を選んでください。',
  'Choose whom to talk to': '話す相手を選ぶ',
  'Talk to PALUGADA about the whole deployment': 'インスタンス全体について PALUGADA と話す',
  'Who you are talking to, and how': '話している相手と使い方',
  'Stopped.': '停止しました。',
  'Write here to talk to {name}.': 'ここに書くと {name} と話せます。',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    '{name} と話しています。テキストを書くか、ボイスメッセージを送ってください。/ceo で話す相手を選び、/palugada でインスタンス全体について PALUGADA と話せます。',
  'You said: "{words}"': 'あなたの発言：「{words}」',
  'in the app': 'コンソールで',
  'Apply: {summary}': '適用：{summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    '音声を聞き取るサービスがまだありません。コンソールの「このインスタンス > ツール > 音声認識」でプロバイダーを選んでください。',
  'That recording is too long; keep a voice note under {max} MB.': '録音が長すぎます。ボイスメッセージは {max} MB 未満にしてください。',
  'I could not make out any words in that.': '言葉を聞き取れませんでした。',
  'Done: {summary}': '完了：{summary}',
  'That one is applied in the app.': 'これはコンソールで適用します。',
  'That card no longer exists.': 'そのカードはもう存在しません。',
  'That card was already applied.': 'そのカードはすでに適用済みです。',
  'That card was dismissed.': 'そのカードは見送られました。',
  'That card failed when it was applied.': 'そのカードは適用時に失敗しました。',
  'That could not be done: {reason}': '実行できませんでした：{reason}',
  'Choose': '選択',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    '「{title}」について何を質問しますか？このメッセージに返信して、質問を書いてください。',
  'Your answer to "{question}"? Reply to this message with your answer.': '「{question}」への回答は？このメッセージに返信して、回答を書いてください。',
  'I read text messages here.': 'ここではテキストメッセージを読み取れます。',
  'Apply one of these here:': 'ここで次のいずれかを適用できます：',
  'Apply {number}': '{number} を適用',
  'Signed in to {provider} for the {alias} key': '{alias} キーのために {provider} にサインインしました',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'PALUGADA に戻ってください。このキーは部門が保持し、期限切れになる前に更新されます。このタブは閉じてかまいません。',
  'Signed in to {name}': '{name} にサインインしました',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'PALUGADA に戻り、ロールが使えるツールを選んでください。このタブは閉じてかまいません。',
  'Not signed in': 'サインインしていません',
  'Recorded: approved.': '記録しました：承認。',
  'Recorded: denied.': '記録しました：却下。',
  'Recorded: asked.': '記録しました：質問。',
  'Asked. Nothing left to press here.': '質問しました。ここで操作することはもうありません。',
  'Withdrawn: the task it was asking about has finished.': '取り下げ：問い合わせ対象のタスクは完了しました。',
  'Withdrawn: the task it was asking about has failed.': '取り下げ：問い合わせ対象のタスクは失敗しました。',
  'Withdrawn: the task it was asking about was stopped.': '取り下げ：問い合わせ対象のタスクは停止されました。',
  'Withdrawn: the task it was asking about was cancelled.': '取り下げ：問い合わせ対象のタスクはキャンセルされました。',
  'Decided. Nothing left to press here.': '決定しました。ここで操作することはもうありません。',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': '取り下げ：エージェントが提案内容を変更し、新しい提案について改めて確認を求めました。',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': '取り下げ：会社はすでに、この提案が想定していた移行元のステージにはありません。',
  'Withdrawn: it was already decided in the app.': '取り下げ：すでにコンソールで決定されています。',
  'Withdrawn. Nothing left to press here.': '取り下げられました。ここで操作することはもうありません。',
  'company': '会社',
  'Work stopped: the {account} account is out of tokens': '作業が止まりました：{account} アカウントのトークンが尽きました',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': '「{work}」は、{account} アカウントが {max} トークンのうち {spent} を使い切ったため止まりました。「お金」で上限を引き上げ、タスクを開いて「続ける」を押してください。止まったところから再開します。',
  'Withdrawn: you continued the task it was about.': '取り下げ済み：対象のタスクはあなたが続行しました。',
  'Broke its contract': '契約違反',
  'Refused by a policy': 'ポリシーにより拒否',
  'Out of budget': '予算切れ',
  'Handed on too many times': '引き継ぎの回数が多すぎます',
  'Missed its deadline': '期限に間に合いませんでした',
  'Its result did not check out': '結果の検証に失敗しました',
  'A capability it needs is down': '必要な機能が停止しています',
  'No runtime could take it': '引き受けられるランタイムがありませんでした',
  'Went in a circle': '堂々巡りになりました',
  'Split into too many sub-tasks': 'サブタスクへの分割が多すぎます',
  'Wrote more than its role allows one run': '1 回の実行で、ロールに許された量を超えて書き込みました',
  'Your approval was not given in time': '承認が期限内に得られませんでした',
  'Stopped by you': 'あなたが停止',
  'Cancelled by you': 'あなたがキャンセル',
  'The company is frozen': '会社は凍結中です',
  'Its record did not match on replay': '再実行時に記録が一致しませんでした',
  'It kept stopping the worker running it': '実行中のワーカーを何度も停止させました',
  'Not done': '未実施',
  'Task failed': 'タスクが失敗しました',
  'Digest for {day}': '{day} のまとめ',
  'Spent: {amount}': '支出済み：{amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': '仕事：完了 {done}件、失敗 {failed}件、停止 {stopped}件',
  'Inbox: {open} waiting (incidents: {incidents})': '受信トレイ：{open}件が待ち（うちインシデント {incidents}件）',
  'Stopped ({count}): {reason}': '停止（{count}件）：{reason}',
  'Start an ad campaign': '広告キャンペーンを開始',
  'Block time on the calendar': 'カレンダーで時間を確保',
  'Read the calendar': 'カレンダーを見る',
  'Run code': 'コードを実行',
  'Add a note to a customer': '顧客にメモを追加',
  'Read customer records': '顧客情報を見る',
  'Release to the live site': '本番サイトに公開',
  'Release to the test site': 'テストサイトに公開',
  'Change a domain\'s nameservers': 'ドメインのネームサーバーを変更',
  'Read a domain\'s records': 'ドメインの DNS レコードを見る',
  'Change a domain\'s record': 'ドメインの DNS レコードを変更',
  'Write a document': 'ドキュメントを書く',
  'Sign a document': 'ドキュメントに署名',
  'Buy a domain': 'ドメインを購入',
  'Transfer a domain': 'ドメインを移管',
  'Draft an email': 'メールの下書きを作成',
  'Send an email': 'メールを送信',
  'List files': 'ファイルの一覧を取得',
  'Read a file': 'ファイルを読む',
  'Describe a picture': '画像を説明する',
  'Calculate in Python': 'Python で計算する',
  'Transfer money': '送金する',
  'Propose a goal change': '目標の変更を提案',
  'Make a picture': '画像を生成',
  'Issue an invoice': '請求書を発行',
  'Pay an invoice': '請求書を支払う',
  'Read the books': '帳簿を見る',
  'Read the mailbox': 'メールボックスを見る',
  'Search what the company knows': '会社のナレッジを検索',
  'Record a measure': '指標の値を記録',
  'Read product numbers': '製品の指標を見る',
  'Ask you a question': 'あなたに質問する',
  'Write down a plan': '計画を記録',
  'Delete a record': 'レコードを削除',
  'Propose a code change': 'コードの変更を提案',
  'Read the code': 'コードを読む',
  'Destroy a server': 'サーバーを破棄',
  'Read a skill': 'スキルを読む',
  'Publish a post': '投稿を公開',
  'Read text aloud': 'テキストを読み上げる',
  'Turn speech into text': '音声を文字に起こす',
  'Propose a new stage': '新しいステージを提案',
  'Wait for work handed on': '引き継いだ仕事を待つ',
  'Hand work to another role': '別のロールに仕事を任せる',
  'File a ticket': 'チケットを作成',
  'List tickets': 'チケットの一覧を取得',
  'Check a service is up': 'サービスの稼働を確認',
  'Read a web page': 'ウェブページを読み取る',
  'Open a web page': 'ウェブページを開く',
  'Search the web': 'ウェブを検索',
  'no stage': 'ステージなし',
  'Explore': '探索',
  'Validate': '検証',
  'Build': '構築',
  'Launch': 'ローンチ',
  'Grow': '成長',
  'Wind down': '縮小',
  'Monthly budget reached; the company is paused': '月間予算に達したため、会社を一時停止しました',
  '{spent} of {limit} spent since {since}. No new task will start and no external action will run until you raise the ceiling or allow spending past it for a while, under Money.': '{since} 以降、{limit} のうち {spent} を支出しました。「お金」で上限を引き上げるか、上限を超える支出を期限付きで許可するまで、新しいタスクは始まらず、外部へのアクションも実行されません。',
  'Monthly budget is 80% spent': '月間予算の 80% を支出しました',
  '{spent} of {limit} spent since {since}. At 100% the company pauses.': '{since} 以降、{limit} のうち {spent} を支出しました。100% に達すると会社は一時停止します。',
  'Role {role} is paused for spending too fast': 'ロール {role} は支出が速すぎるため一時停止しました',
  '{role} spent {spent} in the last hour, {multiple} times its usual {usual} an hour. It is paused before the monthly ceiling is reached, so there is money left to work with once you have found out why. Resume it when you have.': '{role} は直近 1 時間で {spent} を支出しました。通常の 1 時間あたり {usual} の {multiple} 倍です。月間の上限に達する前に一時停止したので、原因がわかった後も仕事に使えるお金が残っています。原因がわかったら再開してください。',
  'Daily model spend over threshold': '1 日のモデル支出がしきい値を超えました',
  'Model spend today is {spent}, over the {limit} ceiling.': '今日のモデル支出は {spent} で、上限の {limit} を超えています。',
  'Task failure rate over threshold': 'タスクの失敗率がしきい値を超えました',
  '{failed} of {finished} tasks failed or stopped today ({rate}%), over the {limit}% threshold.': '今日は {finished} 件のタスクのうち {failed} 件が失敗または停止し（{rate}%）、しきい値の {limit}% を超えています。',
  'Unusual number of policy refusals': 'ポリシーによる拒否が異常に多くなっています',
  'Actions refused by a policy today: {count}, over the threshold of {limit}. Either an agent is probing its limits or a policy is miscalibrated.': '今日ポリシーに拒否されたアクション：{count} 件。しきい値の {limit} 件を超えています。エージェントが限界を探っているか、ポリシーの設定が適切でないかのどちらかです。',
  'External writes failed verification': '外部への書き込みが検証に失敗しました',
  'Writes outside that reported success but read back differently: {count}. Something is changing them other than as asked.': '成功と報告されたのに、読み戻すと内容が異なっていた外部への書き込み：{count} 件。指示とは別の形で、何かがそれらを変更しています。',
  'A capability stopped being usable': '機能が使えなくなりました',
  'Tasks that could not start today because a capability their role needs failed its check: {count}. A credential has probably expired or a quota is used up.': 'ロールに必要な機能が稼働チェックで不合格になったため、今日開始できなかったタスク：{count} 件。認証情報の期限切れか、利用枠の使い切りが考えられます。',
  'A worker stopped reporting mid-run': 'ワーカーが実行の途中で応答しなくなりました',
  'Runs that stopped reporting and were taken back today: {count}. The work was picked up again; the tokens they had already spent were not recovered.': '今日、応答が途絶えて回収された実行：{count} 件。作業は改めて引き継がれましたが、すでに使ったトークンは戻りません。',
  '{role} was refused {denials} times today, at the limit of {limit}. No task will run as this role until you lift the freeze. The usual causes are a missing capability grant, a policy the role\'s charter does not account for, or work the role was never equipped to do.': '{role} は今日 {denials} 回拒否され、上限の {limit} 回に達しました。凍結を解除するまで、このロールではタスクが実行されません。よくある原因は、機能の付与漏れ、ロールの憲章が想定していないポリシー、あるいはそのロールにもともと備わっていない仕事です。',
  'Role {role} is frozen after repeated denials': 'ロール {role} は拒否が続いたため凍結されました',
  'What it was refused: {capabilities}': '拒否されたもの：{capabilities}',
  'It is waiting for an approval, and none is open, so nothing you can answer will move it.': '承認を待っていますが、開いている承認がないため、どう回答しても先に進みません。',
  'It is waiting for a review, and none is pending, so no reviewer and no decision of yours will move it.': 'レビューを待っていますが、保留中のレビューがないため、レビュアーもあなたの決定も先に進めることができません。',
  'It is parked until a window reopens, and the window never does.': '時間帯が再び開くまで待機していますが、その時間帯は二度と開きません。',
  'A task is waiting on nothing': '待つ対象のないまま待機しているタスクがあります',
  '"{task}" has been waiting since {since}. {why} Approve to run it again from where it stopped, or deny to cancel it.': '「{task}」は {since} から待機しています。{why}承認すると止まったところから再実行し、却下するとキャンセルします。',
  'A task keeps stopping the worker running it': '実行中のワーカーを何度も停止させるタスクがあります',
  '"{task}" lost its worker {lost} times: each time the worker running it stopped answering before the work finished. What it had done is kept. It is halted so it cannot take another worker down; run it again once the cause is found, or cancel it.': '「{task}」はワーカーを {lost} 回失いました。そのたびに、実行していたワーカーが作業の完了前に応答しなくなりました。ここまでに行った作業は保持されています。別のワーカーまで止めないよう停止しています。原因がわかったら再実行するか、キャンセルしてください。',
  '{services} stayed unreachable, and the work that needs it stopped': '{services} に接続できないままのため、それを必要とする作業が停止しました',
  'The task waited about {minutes} minutes, looking again each time, and has stopped. Once the service answers, run it again.': 'タスクは約 {minutes} 分間、そのつど確認し直しながら待ちましたが、停止しました。サービスが応答するようになったら、再実行してください。',
  'It was tried {tries} times over about {minutes} minutes.': '約 {minutes} 分間に {tries} 回試みました。',
  'This role can take actions that cannot be undone, so the run was not silently moved to a different model.': 'このロールは取り消せないアクションを実行できるため、実行を別のモデルへ黙って切り替えることはしませんでした。',
  'No fallback model is left for this role.': 'このロールに使える代替モデルはもう残っていません。',
  'Model {model} failed and the run was not moved': 'モデル {model} が失敗し、実行は切り替えられませんでした',
  'External write failed verification': '外部への書き込みが検証に失敗しました',
  'The task wrote to an outside service and read it back, and what it read did not match. Look at the place it wrote to before you run it again: the write may have happened.': 'タスクは外部サービスに書き込んで読み戻しましたが、読み取った内容が一致しませんでした。再実行する前に、書き込み先を確認してください。書き込みはすでに行われている可能性があります。',
  'Review deadlocked after {rounds} revisions: {capability}': '{rounds} 回の修正後もレビューが行き詰まりました：{capability}',
  'The role and its reviewer did not agree on {capability}.': 'ロールとそのレビュアーは {capability} について合意に至りませんでした。',
  'The reviewer\'s last note: {note}': 'レビュアーの最後のメモ：{note}',
  'The reviewer left no note.': 'レビュアーはメモを残していません。',
  'What it was judged against: {criteria}': '判断の基準：{criteria}',
  'Review produced no usable verdict: {capability}': 'レビューで使える判定が得られませんでした：{capability}',
  'The reviewing task ended without a decision that could be read. The proposed action is still blocked and needs your judgement.': 'レビューのタスクは、読み取れる決定がないまま終了しました。提案されたアクションは引き続きブロックされており、あなたの判断が必要です。',
  'another stage': '別のステージ',
  'Either answer only closes this: the company stays in the {stage} stage.': 'どちらを選んでも、この項目を閉じるだけです。会社は「{stage}」ステージのままです。',
  'Either answer only closes this: the company stays without a stage.': 'どちらを選んでも、この項目を閉じるだけです。会社はステージがないままです。',
  'To move it anyway, set the stage on the Overview.': 'それでも移す場合は、「概要」でステージを設定してください。',
  '{reviewer} stopped a proposal to move the company from {from} to {to}': '{reviewer} が、会社を「{from}」から「{to}」に移す提案を止めました',
  '{reviewer} reviewed it before you and stopped it:': '{reviewer} があなたより先にレビューし、止めました：',
  'No reason was given.': '理由は示されていません。',
  'What was proposed:': '提案の内容：',
  'The company stays in the {stage} stage.': '会社は「{stage}」ステージのままです。',
  'The company stays without a stage.': '会社はステージがないままです。',
  'Move the company from {from} to {to}?': '会社を「{from}」から「{to}」に移しますか？',
  'Reviewed by {reviewer} before you:': 'あなたより先に {reviewer} がレビューしました：',
  'The schedule "{schedule}" keeps producing the same result': 'スケジュール「{schedule}」が同じ結果を出し続けています',
  'Its last {runs} runs all ended with the same output. That is sometimes exactly right -- a report with nothing new to say -- and often a schedule that stopped doing anything useful while still being paid for. Deny to turn it off; approve to keep it running and not be asked about this result again.': '直近 {runs} 回の実行は、すべて同じ出力で終わりました。それがまさに正しい場合もあります（新しく伝えることのない報告など）が、多くの場合は、費用がかかり続けているのに役に立つことを何もしなくなったスケジュールです。却下するとオフにします。承認すると実行を続け、この結果について再び確認しません。',
  'Capability {capability} failed preflight': '機能 {capability} が稼働チェックで不合格になりました',
  'Work that needs it is stopped rather than started: fix the cause, then run that work again. The usual causes are an expired or wrongly scoped credential, a quota used up, or an address that is wrong.': 'それを必要とする作業は、開始されずに停止しています。原因を直してから、その作業を再実行してください。よくある原因は、認証情報の期限切れや権限範囲の誤り、利用枠の使い切り、アドレスの誤りです。',
  'Batch guard stopped {capability}': 'バッチガードが {capability} を止めました',
  'It did not match the plan its run recorded. Nothing was sent, and no service was called.': '実行が記録した計画と一致しませんでした。何も送信されておらず、どのサービスも呼び出されていません。',
  '{role} was asked first and has had {minutes} minutes.': '{role} が先に依頼を受け、{minutes} 分が経過しています。',
  '{role} is not a role in this company, so this came to you at once.': '{role} はこの会社のロールではないため、すぐにあなたに届きました。',
  '{role} could not be given this: the company has no active goal or project to hang it from.': '{role} に割り当てられませんでした。会社には、紐付けられる有効な目標もプロジェクトもありません。',
  '{role} could not be given this ({record}), so this came to you at once.': '{role} に割り当てられなかったため（{record}）、すぐにあなたに届きました。',
  '{role} stopped without an account of what it did ({why}).': '{role} は何をしたかを報告しないまま停止しました（{why}）。',
  '{role} finished without an account of what it did.': '{role} は何をしたかを報告しないまま完了しました。',
  '{role} failed without an account of what it did.': '{role} は何をしたかを報告しないまま失敗しました。',
  '{role} was stopped without an account of what it did.': '{role} は何をしたかを報告しないまま停止されました。',
  'Proposed change to the {kind} "{goal}"': '{kind}「{goal}」の変更提案',
  'Currently: {statement}': '現在：{statement}',
  'Currently: {statement} ({status})': '現在：{statement}（{status}）',
  'Proposed: {statement}': '提案：{statement}',
  'Proposed status: {status}': '提案するステータス：{status}',
  'Reason given: {reason}': '示された理由：{reason}',
  'Record an entry in the books': '帳簿に仕訳を記録',
  'Record a customer or a deal': '顧客や商談を記録',
  'Not sent on its own: {reason}': '自動では送信されませんでした: {reason}',
  'it answers a conversation other than the one this work began with': 'この作業が始まった会話とは別の会話への返信です',
  'it named no passage of a document for customers': '顧客向け文書の箇所を一つも示していません',
  'it answers from a document not marked for customers': '顧客向けとしてマークされていない文書をもとにしています',
  'it says a figure the documents and the customer did not: {detail}': '文書にも顧客のメッセージにもない数字が含まれています: {detail}',
  'it gives an address or link the documents and the customer did not: {detail}': '文書にも顧客のメッセージにもない住所やリンクが含まれています: {detail}',
  'there have been six answers on its own in this conversation in the last hour': 'この会話では直近1時間にすでに6件の自動返信がありました',
  'the check found it is about a refund': '確認の結果、返金に関する内容でした',
  'the check found it offers a price or terms of its own': '確認の結果、独自の価格や条件を提示していました',
  'the check found it answers a serious complaint': '確認の結果、深刻な苦情への返信でした',
  'the check found it touches the law': '確認の結果、法的な事柄に触れていました',
  'the check found it gives or asks for personal data': '確認の結果、個人データを伝えるか求めていました',
  'the check found it promises something the documents do not': '確認の結果、文書にないことを約束していました',
  'the check could not judge it': '確認で判断できませんでした',
  'the check found something in it the documents do not say': '確認の結果、文書に書かれていない内容がありました',
  '{role} proposes the schedule {name}': '{role} がスケジュール {name} を提案しています',
  'Each run: {instruction}': '各回の実行内容: {instruction}',
  'Done by: {role}': '担当: {role}',
  'When: {cron} ({timezone}); the next runs are {runs}': '実行日時: {cron} ({timezone})。次回以降は {runs}',
  'Approving it makes the schedule and starts it; it can be turned off or changed under Team, Schedules.': '承認するとスケジュールが作成され、開始されます。チーム、スケジュールでオフにしたり変更したりできます。',
  'No schedule is made.': 'スケジュールは作成されません。',
  'Propose a schedule': 'スケジュールを提案',
  'Approving it changes the goal; until then the work carries on under the goal as it is.': '承認すると目標が変更されます。それまでは、現在の目標のまま仕事が続きます。',
  'The goal stays as it is.': '目標は現状のままです。',
  'mission': 'ミッション',
  'objective': '目標（O）',
  'key result': '主要な成果（KR）',
  'Active': 'アクティブ',
  'Met': '達成',
  'Abandoned': '断念',
  'This work asked for it at tier {tier}, and policy {policies} requires your approval.': 'この仕事はティア {tier} でこれを求めており、ポリシー {policies} によりあなたの承認が必要です。',
  'This work asked for it at tier {tier}, and the task began with content from outside the company.': 'この仕事はティア {tier} でこれを求めており、タスクは社外からのコンテンツで始まりました。',
  'This work asked for it at tier {tier}, and the work read content from outside the company before asking.': 'この仕事はティア {tier} でこれを求めており、求める前に社外のコンテンツを読んでいます。',
  'This work asked for it at tier {tier}, after the work read content from outside the company, and the guardian asked you first: {reason}': 'この仕事は社外のコンテンツを読んだ後にティア {tier} でこれを求めており、ガーディアンが先にあなたに確認しています：{reason}',
  'it doubted this call before, and you allowed it once': '以前にもこの呼び出しを疑い、あなたが一度許可しています',
  'This work asked for it at tier {tier}, which cannot be reversed.': 'この仕事はティア {tier} でこれを求めており、これは取り消せません。',
  'You approved this once already, and the worker carrying it out stopped before it could say whether it happened: it may already have happened. Check before approving it again.': 'これは一度承認済みですが、実行していたワーカーが、実行されたかどうかを伝える前に停止しました。すでに実行されている可能性があります。もう一度承認する前に確認してください。',
  'What this is for — {goals}': 'この仕事の目的——{goals}',
  'The task halts and no external change is made.': 'タスクは停止し、外部への変更は行われません。',
  'Scored against {total} references: {passed} passed, {failed} failed.': '{total} 件の参照例で評価：合格 {passed} 件、不合格 {failed} 件。',
  'This role has fewer than {minimum} accepted references, so the change is unscored. That is not the same as passing.': 'このロールの採用済みの参照例は {minimum} 件未満のため、この変更は未評価です。合格と同じではありません。',
  'The role keeps working exactly as it does now.': 'ロールは今とまったく同じように仕事を続けます。',
  '{role} asks: {question}': '{role} からの質問：{question}',
  'The run did not say more than the question.': '実行は質問以上のことを何も伝えていません。',
  'The task is stopped, and nothing it was going to do happens.': 'タスクは停止し、予定していたことは何も行われません。',
  'You proposed it.': 'あなたが提案しました。',
  'It came with a bundle.': 'バンドルに含まれていました。',
  'An agent proposed it.': 'エージェントが提案しました。',
  'It was learned from the company\'s work.': '会社の仕事から学んだものです。',
  'Skill "{skill}", version {version}': 'スキル「{skill}」、バージョン {version}',
  'The reviewer approved it: {note}': 'レビュアーが承認しました：{note}',
  'The reviewer approved it.': 'レビュアーが承認しました。',
  'Nothing changes; the current version of the skill stays in force.': '何も変わりません。スキルの現在のバージョンが引き続き適用されます。',
  'Skills the bundle "{bundle}" brings: {count}': 'バンドル「{bundle}」に含まれるスキル：{count}',
  'The reviewer read them all and approved these:': 'レビュアーがすべてを読み、次のスキルを承認しました：',
  'It turned these down, and they stay off:': '次のスキルは不採用になり、オフのままです：',
  'Approve to switch them all on, or deny to turn them all down. To decide one at a time, open the Skills page.': '承認するとすべて有効にし、却下するとすべて不採用にします。1 つずつ決めるには、「スキル」ページを開いてください。',
  'Nothing changes; none of these skills is switched on.': '何も変わりません。これらのスキルはどれも有効になりません。',
  "I am {ceo}, and I run {company} for you. I know what it is for: “{mission}” Two things before we start: how much may it spend in a month? And what should its first piece of work be -- or shall I suggest one, and the team it would take?":
    "{ceo} です。あなたに代わって {company} を運営します。何のための会社かは把握しています：「{mission}」始める前に 2 つ教えてください。ひと月にいくらまで使ってよいですか？そして、最初の仕事は何にしますか？それとも、必要なチームも含めて私から提案しましょうか？",
  'I am {ceo}, and I run {company} for you. Three things before we start: what does {company} sell, and to whom? How much may it spend in a month? And what should its first piece of work be -- or shall I suggest one?': '{ceo} です。あなたに代わって {company} を運営します。始める前に 3 つ教えてください。{company} は何を誰に売りますか？ひと月にいくらまで使ってよいですか？そして、最初の仕事は何にしますか？それとも私から提案しましょうか？',
  'Read a customer conversation': '顧客との会話を読む',
  'Reply to a customer': '顧客に返信する',
  'Read a page in the browser': 'ブラウザでページを読む',
  'Fill in a page in the browser': 'ブラウザでページに入力する',
  'Ask you to take over the browser': 'ブラウザの引き継ぎを依頼する',
  '{host} refused the model key ({status}), so nothing that needs the model can run. Open Settings, This deployment, Model, paste a key that works, test it and save.':
    '{host} がモデルのキーを拒否しました（{status}）。モデルを必要とする作業は実行できません。設定、このインスタンス、モデルを開き、使えるキーを貼り付け、テストして保存してください。',
  '{host} refused the model key, and work is waiting': '{host} がモデルのキーを拒否したため、作業が待機中です',
  'What is waiting for the model carries on by itself once a key that works is in use.':
    'モデルを待っている作業は、使えるキーに切り替わると自動的に再開します。',
  'A task ended before it was done: {task}':
    '作業が完了前に終了しました：{task}',
  'It ended as: {reason}. No other card was raised for it, so it is here rather than silent.':
    '終了の理由：{reason}。ほかにこの件のカードは作られていないため、黙って見過ごされないようここに出しています。',
  'Where its measures stand, as the platform reads them:':
    'プラットフォームが読み取った指標の現状：',
  '{name}: no value recorded yet, against a target of {target}.':
    '{name}：まだ値がありません（目標 {target}）。',
  '{name}: {value} against a target of {target}, read back from its source.':
    '{name}：{value}（目標 {target}）、取得元から読み直して確認済み。',
  '{name}: {value} against a target of {target}, reported and not checked.':
    '{name}：{value}（目標 {target}）、報告のみで未確認。',
  'Look at it again later': '後でもう一度確認する',
  "Deliver what this company sells, reliably and without surprising its owner.":
    "この会社が販売するものを確実に届け、オーナーを驚かせないこと。",
  "Ship the work the company has promised, on time and verified.":
    "会社が約束した仕事を、期日どおりに、検証済みの状態で出荷すること。",
  "Keep the company solvent, answerable and running without daily attention.":
    "会社の支払い能力を保ち、説明責任を果たし、日々の手間をかけずに動かし続けること。",
  "Since we last spoke:":
    "前回お話ししてから：",
  "More finished: {count}":
    "ほかに完了：{count}",
  "Waiting for you: {count}":
    "あなたの対応待ち：{count}",
};
