/**
 * 日本語: what the platform itself says to the owner outside the console
 * (src/owner/say.ts), keyed by its English.
 *
 * The terms are the console's (console/src/locales/ja.ts): an approval is
 * 承認 and a denial 却下, an incident インシデント, a card is applied (適用),
 * and "the app" is the console (コンソール). Screens are named as the console
 * draws them: 「このインスタンス > モデル」. Sentences are polite です・ます;
 * buttons are short labels, within WhatsApp's twenty characters.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'インシデント：{title}',
  'Done: {goal}': '完了：{goal}',
  'Stopped before finishing: {goal}': '完了前に停止：{goal}',
  'Not done: {goal}': '未実施：{goal}',
  'Why: {reason}': '理由：{reason}',
  'a task': 'タスク',
  'Approval needed: {title}': '承認が必要：{title}',
  '{summary} — if denied: {consequence}': '{summary}（却下した場合：{consequence}）',
  '{role} asks:': '{role} からの質問：',
  'If denied:': '却下した場合：',
  'Expires:': '期限：',
  'This one is decided in the app.': 'これはコンソールで決定します。',
  'Open in PALUGADA': 'PALUGADA で開く',
  'Approve': '承認',
  'Deny': '却下',
  'Ask': '質問',
  'Approved. Nothing left to press here.': '承認しました。ここで操作することはもうありません。',
  'Denied. Nothing left to press here.': '却下しました。ここで操作することはもうありません。',
  'Expired unanswered. Silence is a refusal, so nothing was done.': '回答がないまま期限が切れました。返事がないことは拒否とみなされるため、何も実行されていません。',
  'This bot only answers to its owner.': 'このボットはオーナーにのみ応答します。',
  'That one has to be approved in the app.': 'これはコンソールで承認する必要があります。',
  'That could not be recorded.': '記録できませんでした。',
  'That item no longer exists.': 'その項目はもう存在しません。',
  'What do you want to ask about "{title}"? Reply to this message.': '「{title}」について何を質問しますか？このメッセージに返信してください。',
  'Your question': 'あなたの質問',
  'Type your question as a reply.': '返信として質問を入力してください。',
  'Asked. The answer will be on the item in the app.': '質問しました。回答はコンソールの該当項目に表示されます。',
  'Answer': '回答',
  'Answer in words': '言葉で回答',
  'That choice is not on this question.': 'その選択肢はこの質問にはありません。',
  'Chosen: {choice}.': '選択：{choice}。',
  'Stop the task': 'タスクを停止',
  'Your answer to "{question}"? Reply to this message.': '「{question}」への回答は？このメッセージに返信してください。',
  'Your answer': 'あなたの回答',
  'Type your answer as a reply.': '返信として回答を入力してください。',
  'Answered. The task carries on with it.': '回答しました。タスクはそれをもとに続行します。',
  'That is too long for one question; keep it under {max} characters.': '1 つの質問としては長すぎます。{max} 文字未満にしてください。',
  '[a key, not kept]': '[キーのため保存していません]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    'キーのように見えるため、保存も送信もしていません。キーはカードの暗号化フィールドか、「このインスタンス」の該当ページに入力してください。何に使うキーかを教えていただければ、カードをお出しします。',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'まだモデルが設定されていないため、考えることができません。「このインスタンス > モデル」で選んでください。そうすれば、ほかのことはすべてお手伝いできます。',
  'The model did not answer: {reason}': 'モデルが応答しませんでした：{reason}',
  'Here is what I propose.': '提案は次のとおりです。',
  'I have nothing to add.': '付け加えることはありません。',
  '{name}, CEO of {company}': '{company} の CEO、{name}',
  'That could not be answered: {reason}': '回答できませんでした：{reason}',
  'I read text and voice notes.': 'テキストとボイスメッセージを読み取れます。',
  'Now talking to {name}.': '{name} と話しています。',
  'Choose whom to talk to.': '話す相手を選んでください。',
  'Choose whom to talk to': '話す相手を選ぶ',
  'Talk to PALUGADA about the whole deployment': 'インスタンス全体について PALUGADA と話す',
  'Who you are talking to, and how': '話している相手と使い方',
  'Stopped.': '停止しました。',
  'Write here to talk to {name}.': 'ここに書くと {name} と話せます。',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    '{name} と話しています。テキストを書くか、ボイスメッセージを送ってください。/ceo で話す相手を選び、/palugada でインスタンス全体について PALUGADA と話せます。',
  'You said: "{words}"': 'あなたの発言：「{words}」',
  'in the app': 'コンソールで',
  'Apply: {summary}': '適用：{summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    '音声を聞き取るサービスがまだありません。コンソールの「このインスタンス > ツール > 音声認識」でプロバイダーを選んでください。',
  'That recording is too long; keep a voice note under {max} MB.': '録音が長すぎます。ボイスメッセージは {max} MB 未満にしてください。',
  'I could not make out any words in that.': '言葉を聞き取れませんでした。',
  'Done: {summary}': '完了：{summary}',
  'That one is applied in the app.': 'これはコンソールで適用します。',
  'That card no longer exists.': 'そのカードはもう存在しません。',
  'That card was already applied.': 'そのカードはすでに適用済みです。',
  'That card was dismissed.': 'そのカードは見送られました。',
  'That card failed when it was applied.': 'そのカードは適用時に失敗しました。',
  'That could not be done: {reason}': '実行できませんでした：{reason}',
  'Choose': '選択',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    '「{title}」について何を質問しますか？このメッセージに返信して、質問を書いてください。',
  'Your answer to "{question}"? Reply to this message with your answer.': '「{question}」への回答は？このメッセージに返信して、回答を書いてください。',
  'I read text messages here.': 'ここではテキストメッセージを読み取れます。',
  'Apply one of these here:': 'ここで次のいずれかを適用できます：',
  'Apply {number}': '{number} を適用',
  'Signed in to {provider} for the {alias} key': '{alias} キーのために {provider} にサインインしました',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'PALUGADA に戻ってください。このキーは部門が保持し、期限切れになる前に更新されます。このタブは閉じてかまいません。',
  'Signed in to {name}': '{name} にサインインしました',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'PALUGADA に戻り、ロールが使えるツールを選んでください。このタブは閉じてかまいません。',
  'Not signed in': 'サインインしていません',
  'Recorded: approved.': '記録しました：承認。',
  'Recorded: denied.': '記録しました：却下。',
  'Recorded: asked.': '記録しました：質問。',
  'Asked. Nothing left to press here.': '質問しました。ここで操作することはもうありません。',
  'Withdrawn: the task it was asking about has finished.': '取り下げ：問い合わせ対象のタスクは完了しました。',
  'Withdrawn: the task it was asking about has failed.': '取り下げ：問い合わせ対象のタスクは失敗しました。',
  'Withdrawn: the task it was asking about was stopped.': '取り下げ：問い合わせ対象のタスクは停止されました。',
  'Withdrawn: the task it was asking about was cancelled.': '取り下げ：問い合わせ対象のタスクはキャンセルされました。',
  'Decided. Nothing left to press here.': '決定しました。ここで操作することはもうありません。',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': '取り下げ：エージェントが提案内容を変更し、新しい提案について改めて確認を求めました。',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': '取り下げ：会社はすでに、この提案が想定していた移行元のステージにはありません。',
  'Withdrawn: it was already decided in the app.': '取り下げ：すでにコンソールで決定されています。',
  'Withdrawn. Nothing left to press here.': '取り下げられました。ここで操作することはもうありません。',
  'Work stopped: the {account} account is out of tokens': '作業が止まりました：{account} アカウントのトークンが尽きました',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': '「{work}」は、{account} アカウントが {max} トークンのうち {spent} を使い切ったため止まりました。「お金」で上限を引き上げ、タスクを開いて「続ける」を押してください。止まったところから再開します。',
  'Withdrawn: you continued the task it was about.': '取り下げ済み：対象のタスクはあなたが続行しました。',
};
