/**
 * Basa Jawa: what the platform itself says to the owner outside the console
 * (src/owner/say.ts), keyed by its English.
 *
 * Krama, the owner addressed as "panjenengan", with the terms of the
 * console's glossary (console/src/locales/jv.ts), so a button on the phone
 * says what the same button says in the panel: Setujoni, Tolak, Taken.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'Insiden: {title}',
  'Done: {goal}': 'Rampung: {goal}',
  'Stopped before finishing: {goal}': 'Kendel saderengipun rampung: {goal}',
  'Not done: {goal}': 'Boten dipunlampahi: {goal}',
  'Why: {reason}': 'Sababipun: {reason}',
  'a task': 'setunggal tugas',
  'Approval needed: {title}': 'Mbetahaken persetujuan: {title}',
  '{summary} — if denied: {consequence}': '{summary} — menawi dipuntolak: {consequence}',
  '{role} asks:': '{role} takon:',
  'If denied:': 'Menawi dipuntolak:',
  'Expires:': 'Kadaluwarsa:',
  'This one is decided in the app.': 'Ingkang punika dipunputusaken wonten ing aplikasi.',
  'Open in PALUGADA': 'Bikak ing PALUGADA',
  'Approve': 'Setujoni',
  'Deny': 'Tolak',
  'Ask': 'Taken',
  'Approved. Nothing left to press here.': 'Dipunsetujoni. Mboten wonten ingkang kedah dipunpencet malih wonten ing ngriki.',
  'Denied. Nothing left to press here.': 'Dipuntolak. Mboten wonten ingkang kedah dipunpencet malih wonten ing ngriki.',
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    'Kadaluwarsa tanpa wangsulan. Mboten mangsuli ateges nolak, pramila mboten wonten ingkang dipunlampahaken.',
  'This bot only answers to its owner.': 'Bot punika namung mangsuli pamilikipun.',
  'That one has to be approved in the app.': 'Ingkang punika kedah dipunsetujoni wonten ing aplikasi.',
  'That could not be recorded.': 'Punika mboten saged dipuncathet.',
  'That item no longer exists.': 'Item punika sampun mboten wonten.',
  'What do you want to ask about "{title}"? Reply to this message.':
    'Punapa ingkang badhe panjenengan takenaken bab "{title}"? Bales pesen punika.',
  'Your question': 'Pitakenan panjenengan',
  'Type your question as a reply.': 'Ketik pitakenan panjenengan minangka balesan.',
  'Asked. The answer will be on the item in the app.': 'Sampun dipuntakenaken. Wangsulanipun badhe wonten ing item punika ing aplikasi.',
  'Answer': 'Wangsuli',
  'Answer in words': 'Wangsuli mawi tembung',
  'That choice is not on this question.': 'Pilihan punika mboten wonten ing pitakenan punika.',
  'Chosen: {choice}.': 'Dipunpilih: {choice}.',
  'Stop the task': 'Kendelaken tugas',
  'Your answer to "{question}"? Reply to this message.': 'Wangsulan panjenengan kangge "{question}"? Bales pesen punika.',
  'Your answer': 'Wangsulan panjenengan',
  'Type your answer as a reply.': 'Ketik wangsulan panjenengan minangka balesan.',
  'Answered. The task carries on with it.': 'Sampun dipunwangsuli. Tugas lajeng mlampah mawi wangsulan punika.',
  'That is too long for one question; keep it under {max} characters.':
    'Punika kepanjangen kangge setunggal pitakenan; damel kirang saking {max} aksara.',
  '[a key, not kept]': '[setunggal kunci, mboten dipunsimpen]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    'Punika katingalipun kunci, pramila mboten kula simpen lan mboten kula kintun dhateng pundi kemawon. Kunci dipunisi ing kolom kasegel ing kertu, utawi ing kacanipun ing Pamasangan punika: ngendikakaken kangge punapa, lajeng kertunipun kula aturaken ing ngarsa panjenengan.',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'Dereng wonten model ingkang dipunsetel, pramila kula dereng saged mikir. Pilih setunggal ing Pamasangan punika, Model AI; sasampunipun punika kula saged mbiyantu sedaya ingkang sanes.',
  'The model did not answer: {reason}': 'Model mboten mangsuli: {reason}',
  'Here is what I propose.': 'Punika usul kula.',
  'I have nothing to add.': 'Mboten wonten ingkang perlu kula tambahaken.',
  '{name}, CEO of {company}': '{name}, CEO {company}',
  'That could not be answered: {reason}': 'Punika mboten saged dipunwangsuli: {reason}',
  'I read text and voice notes.': 'Kula maos teks lan pesen swanten.',
  'Now talking to {name}.': 'Sapunika ngendikan kaliyan {name}.',
  'Choose whom to talk to.': 'Pilih kanca wicanten panjenengan.',
  'Choose whom to talk to': 'Pilih kanca wicanten panjenengan',
  'Talk to PALUGADA about the whole deployment': 'Ngendikan kaliyan PALUGADA bab pamasangan sawetahipun',
  'Who you are talking to, and how': 'Sinten kanca wicanten panjenengan, lan caranipun',
  'Stopped.': 'Sampun kendel.',
  'Write here to talk to {name}.': 'Serat wonten ing ngriki kangge ngendikan kaliyan {name}.',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    'Panjenengan saweg ngendikan kaliyan {name}. Serat, utawi kintun pesen swanten. /ceo kangge milih kanca wicanten; /palugada kangge ngendikan kaliyan PALUGADA bab pamasangan sawetahipun.',
  'You said: "{words}"': 'Panjenengan ngendika: "{words}"',
  'in the app': 'ing aplikasi',
  'Apply: {summary}': 'Trapaken: {summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    'Dereng wonten ingkang saged mireng swanten: pilih panyedhiya ing aplikasi, ing Pamasangan punika, Alat, Mirengaken.',
  'That recording is too long; keep a voice note under {max} MB.': 'Rekaman punika kepanjangen; damel pesen swanten kirang saking {max} MB.',
  'I could not make out any words in that.': 'Kula mboten saged nangkep tembung punapa-punapa ing ngriku.',
  'Done: {summary}': 'Rampung: {summary}',
  'That one is applied in the app.': 'Ingkang punika dipuntrapaken wonten ing aplikasi.',
  'That card no longer exists.': 'Kertu punika sampun mboten wonten.',
  'That card was already applied.': 'Kertu punika sampun dipuntrapaken.',
  'That card was dismissed.': 'Kertu punika sampun dipunsingkiraken.',
  'That card failed when it was applied.': 'Kertu punika gagal nalika dipuntrapaken.',
  'That could not be done: {reason}': 'Punika mboten saged dipuntindakaken: {reason}',
  'Choose': 'Pilih',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    'Punapa ingkang badhe panjenengan takenaken bab "{title}"? Bales pesen punika mawi pitakenan panjenengan.',
  'Your answer to "{question}"? Reply to this message with your answer.':
    'Wangsulan panjenengan kangge "{question}"? Bales pesen punika mawi wangsulan panjenengan.',
  'I read text messages here.': 'Wonten ing ngriki kula maos pesen teks.',
  'Apply one of these here:': 'Trapaken salah satunggal saking punika wonten ing ngriki:',
  'Apply {number}': 'Trapaken {number}',
  'Signed in to {provider} for the {alias} key': 'Sampun mlebet dhateng {provider} kangge kunci {alias}',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'Wangsul dhateng PALUGADA: divisi punika sapunika nyepeng kunci punika, lan kunci dipunenggalaken saderengipun telas. Tab punika saged dipuntutup.',
  'Signed in to {name}': 'Sampun mlebet dhateng {name}',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'Wangsul dhateng PALUGADA kangge milih alat pundi ingkang angsal dipunginakaken peran. Tab punika saged dipuntutup.',
  'Not signed in': 'Dereng mlebet',
  'Recorded: approved.': 'Kacathet: dipunsetujoni.',
  'Recorded: denied.': 'Kacathet: dipuntolak.',
  'Recorded: asked.': 'Kacathet: dipuntakenaken.',
  'Asked. Nothing left to press here.': 'Sampun dipuntakenaken. Mboten wonten ingkang kedah dipunpencet malih wonten ing ngriki.',
  'Withdrawn: the task it was asking about has finished.': 'Dipuntarik: tugas ingkang dipuntakenaken sampun rampung.',
  'Withdrawn: the task it was asking about has failed.': 'Dipuntarik: tugas ingkang dipuntakenaken gagal.',
  'Withdrawn: the task it was asking about was stopped.': 'Dipuntarik: tugas ingkang dipuntakenaken sampun dipunkendelaken.',
  'Withdrawn: the task it was asking about was cancelled.': 'Dipuntarik: tugas ingkang dipuntakenaken sampun dipunbatalaken.',
  'Decided. Nothing left to press here.': 'Dipunputusaken. Mboten wonten ingkang kedah dipunpencet malih wonten ing ngriki.',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': 'Dipuntarik: agen ngewahi usulipun lan nyuwun persetujuan malih kangge usul ingkang enggal.',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': 'Dipuntarik: perusahaan sampun mboten wonten ing tataran ingkang badhe dipuntilar miturut usul punika.',
  'Withdrawn: it was already decided in the app.': 'Dipuntarik: sampun dipunputusaken wonten ing aplikasi.',
  'Withdrawn. Nothing left to press here.': 'Dipuntarik. Mboten wonten ingkang kedah dipunpencet malih wonten ing ngriki.',
  'company': 'perusahaan',
  'Work stopped: the {account} account is out of tokens': 'Pakaryan kendel: token akun {account} sampun telas',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': '“{work}” kendel amargi akun {account} sampun ngginakaken {spent} saking {max} token. Inggahaken watesipun ing Arta, lajeng bikak tugas punika lan pencet Lajengaken: tugas nglajengaken saking papan kendelipun.',
  'Withdrawn: you continued the task it was about.': 'Dipunwangsulaken: panjenengan sampun nglajengaken tugas ingkang dipunrembag.',
  'Broke its contract': 'Nerak kontrakipun',
  'Refused by a policy': 'Dipuntolak kawicaksanan',
  'Out of budget': 'Anggaran telas',
  'Handed on too many times': 'Kakathahen anggenipun dipunpasrahaken',
  'Missed its deadline': 'Kaliwatan wates wekdalipun',
  'Its result did not check out': 'Asilipun mboten lulus pamriksan',
  'A capability it needs is down': 'Kasagedan ingkang dipunbetahaken saweg mati',
  'No runtime could take it': 'Mboten wonten pangolah ingkang saged nampi',
  'Went in a circle': 'Muter-muter',
  'Split into too many sub-tasks': 'Dipunpecah dados subtugas ingkang kakathahen',
  'Wrote more than its role allows one run': 'Nyerat langkung kathah tinimbang ingkang dipunparengaken peranipun kangge setunggal lampahan',
  'Your approval was not given in time': 'Persetujuan panjenengan mboten dumugi ing wekdalipun',
  'Stopped by you': 'Dipunkendelaken panjenengan',
  'Cancelled by you': 'Dipunbatalaken dening panjenengan',
  'The company is frozen': 'Perusahaan dipunbekokaken',
  'Its record did not match on replay': 'Cathetanipun mboten cocog nalika dipunputer malih',
  'It kept stopping the worker running it': 'Tugas punika bola-bali ndadosaken pekerja ingkang nglampahaken kendel',
  'Not done': 'Boten dipunlampahi',
  'Task failed': 'Tugas gagal',
  'Digest for {day}': 'Ringkesan {day}',
  'Spent: {amount}': 'Kaginakaken: {amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': 'Pakaryan: {done} rampung, {failed} gagal, {stopped} kendel',
  'Inbox: {open} waiting (incidents: {incidents})': 'Kothak mlebet: {open} nengga (insiden: {incidents})',
  'Stopped ({count}): {reason}': 'Kendel ({count}): {reason}',
  'Start an ad campaign': 'Wiwiti kampanye iklan',
  'Block time on the calendar': 'Cadhangaken wekdal ing kalender',
  'Read the calendar': 'Waos kalender',
  'Run code': 'Lampahaken kode',
  'Add a note to a customer': 'Tambah cathetan ing data pelanggan',
  'Read customer records': 'Waos data pelanggan',
  'Release to the live site': 'Luncuraken dhateng situs umum',
  'Release to the test site': 'Luncuraken dhateng situs uji',
  'Change a domain\'s nameservers': 'Ewahi nameserver domain',
  'Read a domain\'s records': 'Waos cathetan DNS domain',
  'Change a domain\'s record': 'Ewahi cathetan DNS domain',
  'Write a document': 'Serat dokumen',
  'Sign a document': 'Tandhatangani dokumen',
  'Buy a domain': 'Tumbas domain',
  'Transfer a domain': 'Pindhahaken domain',
  'Draft an email': 'Damel draf email',
  'Send an email': 'Kintun email',
  'List files': 'Tampilaken daftar file',
  'Transfer money': 'Kintun arta',
  'Propose a goal change': 'Usulaken ewahan ancas',
  'Make a picture': 'Damel gambar',
  'Issue an invoice': 'Terbitaken tagihan',
  'Pay an invoice': 'Bayar tagihan',
  'Read the books': 'Waos pembukuan',
  'Read the mailbox': 'Waos email ingkang mlebet',
  'Search what the company knows': 'Pados kawruh perusahaan',
  'Record a measure': 'Cathet ukuran',
  'Read product numbers': 'Waos statistik produk',
  'Ask you a question': 'Nyuwun pirsa dhateng panjenengan',
  'Write down a plan': 'Cathet rancangan',
  'Delete a record': 'Busak data',
  'Propose a code change': 'Usulaken ewahan kode',
  'Read the code': 'Waos kode',
  'Destroy a server': 'Busak server kanthi permanen',
  'Read a skill': 'Waos kaprigelan',
  'Publish a post': 'Terbitaken kiriman',
  'Read text aloud': 'Waosaken teks kanthi swanten',
  'Turn speech into text': 'Ewahi wicara dados teks',
  'Propose a new stage': 'Usulaken tataran enggal',
  'Wait for work handed on': 'Entosi pakaryan ingkang dipunpasrahaken',
  'Hand work to another role': 'Pasrahaken pakaryan dhateng peran sanes',
  'File a ticket': 'Damel tiket',
  'List tickets': 'Tampilaken daftar tiket',
  'Check a service is up': 'Priksa punapa layanan taksih mlampah',
  'Read a web page': 'Waos kaca web',
  'Open a web page': 'Bikak kaca web',
  'Search the web': 'Pados ing web',
};
