/**
 * Basa Jawa: what the platform itself says to the owner outside the console
 * (src/owner/say.ts), keyed by its English.
 *
 * Krama, the owner addressed as "panjenengan", with the terms of the
 * console's glossary (console/src/locales/jv.ts), so a button on the phone
 * says what the same button says in the panel: Setujoni, Tolak, Taken.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'Insiden: {title}',
  'Done: {goal}': 'Rampung: {goal}',
  'Stopped before finishing: {goal}': 'Kendel saderengipun rampung: {goal}',
  'Not done: {goal}': 'Boten dipunlampahi: {goal}',
  'Why: {reason}': 'Sababipun: {reason}',
  'a task': 'setunggal tugas',
  'Approval needed: {title}': 'Mbetahaken persetujuan: {title}',
  '{summary} — if denied: {consequence}': '{summary} — menawi dipuntolak: {consequence}',
  '{role} asks:': '{role} takon:',
  'If denied:': 'Menawi dipuntolak:',
  'Expires:': 'Kadaluwarsa:',
  'This one is decided in the app.': 'Ingkang punika dipunputusaken wonten ing aplikasi.',
  'Open in PALUGADA': 'Bikak ing PALUGADA',
  'Approve': 'Setujoni',
  'Deny': 'Tolak',
  'Ask': 'Taken',
  'Approved. Nothing left to press here.': 'Dipunsetujoni. Mboten wonten ingkang kedah dipunpencet malih wonten ing ngriki.',
  'Denied. Nothing left to press here.': 'Dipuntolak. Mboten wonten ingkang kedah dipunpencet malih wonten ing ngriki.',
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    'Kadaluwarsa tanpa wangsulan. Mboten mangsuli ateges nolak, pramila mboten wonten ingkang dipunlampahaken.',
  'This bot only answers to its owner.': 'Bot punika namung mangsuli pamilikipun.',
  'That one has to be approved in the app.': 'Ingkang punika kedah dipunsetujoni wonten ing aplikasi.',
  'That could not be recorded.': 'Punika mboten saged dipuncathet.',
  'That item no longer exists.': 'Item punika sampun mboten wonten.',
  'What do you want to ask about "{title}"? Reply to this message.':
    'Punapa ingkang badhe panjenengan takenaken bab "{title}"? Bales pesen punika.',
  'Your question': 'Pitakenan panjenengan',
  'Type your question as a reply.': 'Ketik pitakenan panjenengan minangka balesan.',
  'Asked. The answer will be on the item in the app.': 'Sampun dipuntakenaken. Wangsulanipun badhe wonten ing item punika ing aplikasi.',
  'Answer': 'Wangsuli',
  'Answer in words': 'Wangsuli mawi tembung',
  'That choice is not on this question.': 'Pilihan punika mboten wonten ing pitakenan punika.',
  'Chosen: {choice}.': 'Dipunpilih: {choice}.',
  'Stop the task': 'Kendelaken tugas',
  'Your answer to "{question}"? Reply to this message.': 'Wangsulan panjenengan kangge "{question}"? Bales pesen punika.',
  'Your answer': 'Wangsulan panjenengan',
  'Type your answer as a reply.': 'Ketik wangsulan panjenengan minangka balesan.',
  'Answered. The task carries on with it.': 'Sampun dipunwangsuli. Tugas lajeng mlampah mawi wangsulan punika.',
  'That is too long for one question; keep it under {max} characters.':
    'Punika kepanjangen kangge setunggal pitakenan; damel kirang saking {max} aksara.',
  '[a key, not kept]': '[setunggal kunci, mboten dipunsimpen]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    'Punika katingalipun kunci, pramila mboten kula simpen lan mboten kula kintun dhateng pundi kemawon. Kunci dipunisi ing kolom kasegel ing kertu, utawi ing kacanipun ing Pamasangan punika: ngendikakaken kangge punapa, lajeng kertunipun kula aturaken ing ngarsa panjenengan.',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'Dereng wonten model ingkang dipunsetel, pramila kula dereng saged mikir. Pilih setunggal ing Pamasangan punika, Model AI; sasampunipun punika kula saged mbiyantu sedaya ingkang sanes.',
  'The model did not answer: {reason}': 'Model mboten mangsuli: {reason}',
  'Here is what I propose.': 'Punika usul kula.',
  'I have nothing to add.': 'Mboten wonten ingkang perlu kula tambahaken.',
  '{name}, CEO of {company}': '{name}, CEO {company}',
  'That could not be answered: {reason}': 'Punika mboten saged dipunwangsuli: {reason}',
  'I read text and voice notes.': 'Kula maos teks lan pesen swanten.',
  'Now talking to {name}.': 'Sapunika ngendikan kaliyan {name}.',
  'Choose whom to talk to.': 'Pilih kanca wicanten panjenengan.',
  'Choose whom to talk to': 'Pilih kanca wicanten panjenengan',
  'Talk to PALUGADA about the whole deployment': 'Ngendikan kaliyan PALUGADA bab pamasangan sawetahipun',
  'Who you are talking to, and how': 'Sinten kanca wicanten panjenengan, lan caranipun',
  'Stopped.': 'Sampun kendel.',
  'Write here to talk to {name}.': 'Serat wonten ing ngriki kangge ngendikan kaliyan {name}.',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    'Panjenengan saweg ngendikan kaliyan {name}. Serat, utawi kintun pesen swanten. /ceo kangge milih kanca wicanten; /palugada kangge ngendikan kaliyan PALUGADA bab pamasangan sawetahipun.',
  'You said: "{words}"': 'Panjenengan ngendika: "{words}"',
  'in the app': 'ing aplikasi',
  'Apply: {summary}': 'Trapaken: {summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    'Dereng wonten ingkang saged mireng swanten: pilih panyedhiya ing aplikasi, ing Pamasangan punika, Alat, Mirengaken.',
  'That recording is too long; keep a voice note under {max} MB.': 'Rekaman punika kepanjangen; damel pesen swanten kirang saking {max} MB.',
  'I could not make out any words in that.': 'Kula mboten saged nangkep tembung punapa-punapa ing ngriku.',
  'Done: {summary}': 'Rampung: {summary}',
  'That one is applied in the app.': 'Ingkang punika dipuntrapaken wonten ing aplikasi.',
  'That card no longer exists.': 'Kertu punika sampun mboten wonten.',
  'That card was already applied.': 'Kertu punika sampun dipuntrapaken.',
  'That card was dismissed.': 'Kertu punika sampun dipunsingkiraken.',
  'That card failed when it was applied.': 'Kertu punika gagal nalika dipuntrapaken.',
  'That could not be done: {reason}': 'Punika mboten saged dipuntindakaken: {reason}',
  'Choose': 'Pilih',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    'Punapa ingkang badhe panjenengan takenaken bab "{title}"? Bales pesen punika mawi pitakenan panjenengan.',
  'Your answer to "{question}"? Reply to this message with your answer.':
    'Wangsulan panjenengan kangge "{question}"? Bales pesen punika mawi wangsulan panjenengan.',
  'I read text messages here.': 'Wonten ing ngriki kula maos pesen teks.',
  'Apply one of these here:': 'Trapaken salah satunggal saking punika wonten ing ngriki:',
  'Apply {number}': 'Trapaken {number}',
  'Signed in to {provider} for the {alias} key': 'Sampun mlebet dhateng {provider} kangge kunci {alias}',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'Wangsul dhateng PALUGADA: divisi punika sapunika nyepeng kunci punika, lan kunci dipunenggalaken saderengipun telas. Tab punika saged dipuntutup.',
  'Signed in to {name}': 'Sampun mlebet dhateng {name}',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'Wangsul dhateng PALUGADA kangge milih alat pundi ingkang angsal dipunginakaken peran. Tab punika saged dipuntutup.',
  'Not signed in': 'Dereng mlebet',
  'Recorded: approved.': 'Kacathet: dipunsetujoni.',
  'Recorded: denied.': 'Kacathet: dipuntolak.',
  'Recorded: asked.': 'Kacathet: dipuntakenaken.',
  'Asked. Nothing left to press here.': 'Sampun dipuntakenaken. Mboten wonten ingkang kedah dipunpencet malih wonten ing ngriki.',
  'Withdrawn: the task it was asking about has finished.': 'Dipuntarik: tugas ingkang dipuntakenaken sampun rampung.',
  'Withdrawn: the task it was asking about has failed.': 'Dipuntarik: tugas ingkang dipuntakenaken gagal.',
  'Withdrawn: the task it was asking about was stopped.': 'Dipuntarik: tugas ingkang dipuntakenaken sampun dipunkendelaken.',
  'Withdrawn: the task it was asking about was cancelled.': 'Dipuntarik: tugas ingkang dipuntakenaken sampun dipunbatalaken.',
  'Decided. Nothing left to press here.': 'Dipunputusaken. Mboten wonten ingkang kedah dipunpencet malih wonten ing ngriki.',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': 'Dipuntarik: agen ngewahi usulipun lan nyuwun persetujuan malih kangge usul ingkang enggal.',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': 'Dipuntarik: perusahaan sampun mboten wonten ing tataran ingkang badhe dipuntilar miturut usul punika.',
  'Withdrawn: it was already decided in the app.': 'Dipuntarik: sampun dipunputusaken wonten ing aplikasi.',
  'Withdrawn. Nothing left to press here.': 'Dipuntarik. Mboten wonten ingkang kedah dipunpencet malih wonten ing ngriki.',
  'company': 'perusahaan',
  'Work stopped: the {account} account is out of tokens': 'Pakaryan kendel: token akun {account} sampun telas',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': '“{work}” kendel amargi akun {account} sampun ngginakaken {spent} saking {max} token. Inggahaken watesipun ing Arta, lajeng bikak tugas punika lan pencet Lajengaken: tugas nglajengaken saking papan kendelipun.',
  'Withdrawn: you continued the task it was about.': 'Dipunwangsulaken: panjenengan sampun nglajengaken tugas ingkang dipunrembag.',
  'Broke its contract': 'Nerak kontrakipun',
  'Refused by a policy': 'Dipuntolak kawicaksanan',
  'Out of budget': 'Anggaran telas',
  'Handed on too many times': 'Kakathahen anggenipun dipunpasrahaken',
  'Missed its deadline': 'Kaliwatan wates wekdalipun',
  'Its result did not check out': 'Asilipun mboten lulus pamriksan',
  'A capability it needs is down': 'Kasagedan ingkang dipunbetahaken saweg mati',
  'No runtime could take it': 'Mboten wonten pangolah ingkang saged nampi',
  'Went in a circle': 'Muter-muter',
  'Split into too many sub-tasks': 'Dipunpecah dados subtugas ingkang kakathahen',
  'Wrote more than its role allows one run': 'Nyerat langkung kathah tinimbang ingkang dipunparengaken peranipun kangge setunggal lampahan',
  'Your approval was not given in time': 'Persetujuan panjenengan mboten dumugi ing wekdalipun',
  'Stopped by you': 'Dipunkendelaken panjenengan',
  'Cancelled by you': 'Dipunbatalaken dening panjenengan',
  'The company is frozen': 'Perusahaan dipunbekokaken',
  'Its record did not match on replay': 'Cathetanipun mboten cocog nalika dipunputer malih',
  'It kept stopping the worker running it': 'Tugas punika bola-bali ndadosaken pekerja ingkang nglampahaken kendel',
  'Not done': 'Boten dipunlampahi',
  'Task failed': 'Tugas gagal',
  'Digest for {day}': 'Ringkesan {day}',
  'Spent: {amount}': 'Kaginakaken: {amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': 'Pakaryan: {done} rampung, {failed} gagal, {stopped} kendel',
  'Inbox: {open} waiting (incidents: {incidents})': 'Kothak mlebet: {open} nengga (insiden: {incidents})',
  'Stopped ({count}): {reason}': 'Kendel ({count}): {reason}',
  'Start an ad campaign': 'Wiwiti kampanye iklan',
  'Block time on the calendar': 'Cadhangaken wekdal ing kalender',
  'Read the calendar': 'Waos kalender',
  'Run code': 'Lampahaken kode',
  'Add a note to a customer': 'Tambah cathetan ing data pelanggan',
  'Read customer records': 'Waos data pelanggan',
  'Release to the live site': 'Luncuraken dhateng situs umum',
  'Release to the test site': 'Luncuraken dhateng situs uji',
  'Change a domain\'s nameservers': 'Ewahi nameserver domain',
  'Read a domain\'s records': 'Waos cathetan DNS domain',
  'Change a domain\'s record': 'Ewahi cathetan DNS domain',
  'Write a document': 'Serat dokumen',
  'Sign a document': 'Tandhatangani dokumen',
  'Buy a domain': 'Tumbas domain',
  'Transfer a domain': 'Pindhahaken domain',
  'Draft an email': 'Damel draf email',
  'Send an email': 'Kintun email',
  'List files': 'Tampilaken daftar file',
  'Transfer money': 'Kintun arta',
  'Propose a goal change': 'Usulaken ewahan ancas',
  'Make a picture': 'Damel gambar',
  'Issue an invoice': 'Terbitaken tagihan',
  'Pay an invoice': 'Bayar tagihan',
  'Read the books': 'Waos pembukuan',
  'Read the mailbox': 'Waos email ingkang mlebet',
  'Search what the company knows': 'Pados kawruh perusahaan',
  'Record a measure': 'Cathet ukuran',
  'Read product numbers': 'Waos statistik produk',
  'Ask you a question': 'Nyuwun pirsa dhateng panjenengan',
  'Write down a plan': 'Cathet rancangan',
  'Delete a record': 'Busak data',
  'Propose a code change': 'Usulaken ewahan kode',
  'Read the code': 'Waos kode',
  'Destroy a server': 'Busak server kanthi permanen',
  'Read a skill': 'Waos kaprigelan',
  'Publish a post': 'Terbitaken kiriman',
  'Read text aloud': 'Waosaken teks kanthi swanten',
  'Turn speech into text': 'Ewahi wicara dados teks',
  'Propose a new stage': 'Usulaken tataran enggal',
  'Wait for work handed on': 'Entosi pakaryan ingkang dipunpasrahaken',
  'Hand work to another role': 'Pasrahaken pakaryan dhateng peran sanes',
  'File a ticket': 'Damel tiket',
  'List tickets': 'Tampilaken daftar tiket',
  'Check a service is up': 'Priksa punapa layanan taksih mlampah',
  'Read a web page': 'Waos kaca web',
  'Open a web page': 'Bikak kaca web',
  'Search the web': 'Pados ing web',
  'no stage': 'tanpa tataran',
  'Explore': 'Njajagi',
  'Validate': 'Nguji',
  'Build': 'Mbangun',
  'Launch': 'Ngluncuraken',
  'Grow': 'Ngrembaka',
  'Wind down': 'Mungkasi usaha',
  'Monthly budget reached; the company is paused': 'Anggaran wulanan sampun telas; perusahaan dipunendheg',
  '{spent} of {limit} spent since {since}. No new task will start and no external action will run until you raise the ceiling or allow spending past it for a while, under Money.': '{spent} saking {limit} sampun kaginakaken wiwit {since}. Mboten wonten tugas enggal ingkang badhe kawiwitan lan mboten wonten tumindak ing njawi ingkang badhe mlampah ngantos panjenengan nginggilaken watesipun utawi marengaken wragad nglangkungi wates punika sawetawis, ing Arta.',
  'Monthly budget is 80% spent': 'Anggaran wulanan sampun kaginakaken 80%',
  '{spent} of {limit} spent since {since}. At 100% the company pauses.': '{spent} saking {limit} sampun kaginakaken wiwit {since}. Ing 100%, perusahaan badhe dipunendheg.',
  'Role {role} is paused for spending too fast': 'Peran {role} dipunendheg amargi ngginakaken arta kanthi rikat sanget',
  '{role} spent {spent} in the last hour, {multiple} times its usual {usual} an hour. It is paused before the monthly ceiling is reached, so there is money left to work with once you have found out why. Resume it when you have.': '{role} ngginakaken {spent} ing sejam pungkasan, kaping {multiple} saking limrahipun, inggih punika {usual} saben jam. Peran punika dipunendheg saderengipun wates wulanan kagayuh, supados taksih wonten arta kangge nyambut damel sasampunipun panjenengan pirsa sababipun. Lajengaken peran punika sasampunipun panjenengan pirsa.',
  'Daily model spend over threshold': 'Wragad model saben dinten nglangkungi wates',
  'Model spend today is {spent}, over the {limit} ceiling.': 'Wragad model dinten punika {spent}, nglangkungi wates {limit}.',
  'Task failure rate over threshold': 'Rasio gagal tugas nglangkungi wates',
  '{failed} of {finished} tasks failed or stopped today ({rate}%), over the {limit}% threshold.': '{failed} saking {finished} tugas gagal utawi kendel dinten punika ({rate}%), nglangkungi wates {limit}%.',
  'Unusual number of policy refusals': 'Cacahipun panolakan kawicaksanan mboten limrah',
  'Actions refused by a policy today: {count}, over the threshold of {limit}. Either an agent is probing its limits or a policy is miscalibrated.': 'Tumindak ingkang dipuntolak kawicaksanan dinten punika: {count}, nglangkungi wates {limit}. Saged ugi wonten agen ingkang saweg nyobi watesipun, utawi wonten kawicaksanan ingkang setelanipun mboten leres.',
  'External writes failed verification': 'Panyeratan ing njawi mboten lulus verifikasi',
  'Writes outside that reported success but read back differently: {count}. Something is changing them other than as asked.': 'Panyeratan ing njawi ingkang kalapuraken kasil nanging benten nalika dipunwaos malih: {count}. Wonten ingkang ngewahi panyeratan punika, mboten kados ingkang dipunsuwun.',
  'A capability stopped being usable': 'Setunggal kasagedan sampun mboten saged dipunginakaken',
  'Tasks that could not start today because a capability their role needs failed its check: {count}. A credential has probably expired or a quota is used up.': 'Tugas ingkang mboten saged kawiwitan dinten punika amargi kasagedan ingkang dipunbetahaken peranipun mboten lulus pamriksan: {count}. Saged ugi wonten kredensial ingkang sampun kadaluwarsa utawi kuota ingkang sampun telas.',
  'A worker stopped reporting mid-run': 'Setunggal pekerja kendel lapur ing satengahing lampahan',
  'Runs that stopped reporting and were taken back today: {count}. The work was picked up again; the tokens they had already spent were not recovered.': 'Lampahan ingkang kendel lapur lan dipunpendhet wangsul dinten punika: {count}. Pakaryanipun sampun dipunlajengaken malih; token ingkang sampun kaginakaken mboten wangsul.',
  '{role} was refused {denials} times today, at the limit of {limit}. No task will run as this role until you lift the freeze. The usual causes are a missing capability grant, a policy the role\'s charter does not account for, or work the role was never equipped to do.': '{role} dipuntolak ping {denials} dinten punika, dumugi wates {limit}. Mboten wonten tugas ingkang mlampah minangka peran punika ngantos panjenengan nyairaken. Sabab ingkang limrah: palilah kasagedan ingkang dereng wonten, kawicaksanan ingkang mboten dipunetang wonten ing piagam peran punika, utawi pakaryan ingkang mboten nate dipuncawisaken kangge peran punika.',
  'Role {role} is frozen after repeated denials': 'Peran {role} dipunbekokaken sasampunipun bola-bali dipuntolak',
  'What it was refused: {capabilities}': 'Ingkang dipuntolak: {capabilities}',
  'It is waiting for an approval, and none is open, so nothing you can answer will move it.': 'Tugas punika ngentosi persetujuan, nanging mboten wonten ingkang kabikak, pramila mboten wonten wangsulan panjenengan ingkang saged ngobahaken.',
  'It is waiting for a review, and none is pending, so no reviewer and no decision of yours will move it.': 'Tugas punika ngentosi panliten, nanging mboten wonten panliten ingkang saweg dipuntindakaken, pramila mboten wonten panliti utawi putusan panjenengan ingkang saged ngobahaken.',
  'It is parked until a window reopens, and the window never does.': 'Tugas punika kasisihaken ngantos wekdal ingkang dipuntemtokaken kabikak malih, nanging wekdal punika mboten nate kabikak.',
  'A task is waiting on nothing': 'Setunggal tugas ngentosi ingkang mboten wonten',
  '"{task}" has been waiting since {since}. {why} Approve to run it again from where it stopped, or deny to cancel it.': '“{task}” sampun ngentosi wiwit {since}. {why} Setujoni kangge nglampahaken malih saking papan kendelipun, utawi Tolak kangge mbatalaken.',
  'A task keeps stopping the worker running it': 'Setunggal tugas bola-bali ndadosaken pekerja ingkang nglampahaken kendel',
  '"{task}" lost its worker {lost} times: each time the worker running it stopped answering before the work finished. What it had done is kept. It is halted so it cannot take another worker down; run it again once the cause is found, or cancel it.': '“{task}” kecalan pekerjanipun ping {lost}: saben-saben, pekerja ingkang nglampahaken kendel mangsuli saderengipun pakaryan rampung. Punapa ingkang sampun dipuntindakaken tetep dipunsimpen. Tugas punika dipunkandhegaken supados mboten ndadosaken pekerja sanes ambruk; lampahaken malih sasampunipun sababipun kapanggih, utawi batalaken.',
  '{services} stayed unreachable, and the work that needs it stopped': '{services} tetep mboten saged dipunhubungi, lan pakaryan ingkang mbetahaken kendel',
  'The task waited about {minutes} minutes, looking again each time, and has stopped. Once the service answers, run it again.': 'Tugas punika ngentosi kinten-kinten {minutes} menit, mriksa malih saben wekdal, lan sapunika kendel. Sasampunipun layanan punika mangsuli, lampahaken malih.',
  'It was tried {tries} times over about {minutes} minutes.': 'Sampun dipuncobi ping {tries} salebeting kinten-kinten {minutes} menit.',
  'This role can take actions that cannot be undone, so the run was not silently moved to a different model.': 'Peran punika saged nindakaken tumindak ingkang mboten saged dipunwangsulaken, pramila lampahan punika mboten dipunpindhah kanthi meneng dhateng model sanes.',
  'No fallback model is left for this role.': 'Sampun mboten wonten model cadhangan kangge peran punika.',
  'Model {model} failed and the run was not moved': 'Model {model} gagal lan lampahanipun mboten dipunpindhah',
  'External write failed verification': 'Panyeratan ing njawi mboten lulus verifikasi',
  'The task wrote to an outside service and read it back, and what it read did not match. Look at the place it wrote to before you run it again: the write may have happened.': 'Tugas punika nyerat dhateng layanan ing njawi lajeng maos malih, lan ingkang kawaos mboten cocog. Pirsani papan ingkang dipunserati saderengipun panjenengan nglampahaken malih: seratan punika saged ugi sampun kelampahan.',
  'Review deadlocked after {rounds} revisions: {capability}': 'Panliten buntu sasampunipun {rounds} revisi: {capability}',
  'The role and its reviewer did not agree on {capability}.': 'Peran punika lan panlitinipun mboten sarujuk bab {capability}.',
  'The reviewer\'s last note: {note}': 'Cathetan pungkasan panliti: {note}',
  'The reviewer left no note.': 'Panliti mboten ninggal cathetan.',
  'What it was judged against: {criteria}': 'Ingkang dados pathokan pambijinipun: {criteria}',
  'Review produced no usable verdict: {capability}': 'Panliten mboten ngasilaken putusan ingkang saged dipunginakaken: {capability}',
  'The reviewing task ended without a decision that could be read. The proposed action is still blocked and needs your judgement.': 'Tugas panliten rampung tanpa putusan ingkang saged dipunwaos. Tumindak ingkang dipunusulaken taksih kaalang lan mbetahaken timbangan panjenengan.',
  'another stage': 'tataran sanes',
  'Either answer only closes this: the company stays in the {stage} stage.': 'Wangsulan punapa kemawon namung nutup punika: perusahaan tetep wonten ing tataran {stage}.',
  'Either answer only closes this: the company stays without a stage.': 'Wangsulan punapa kemawon namung nutup punika: perusahaan tetep tanpa tataran.',
  'To move it anyway, set the stage on the Overview.': 'Menawi tetep badhe mindhahaken, setel tataranipun ing Ringkesan.',
  '{reviewer} stopped a proposal to move the company from {from} to {to}': '{reviewer} ngendelaken usul mindhahaken perusahaan saking {from} dhateng {to}',
  '{reviewer} reviewed it before you and stopped it:': '{reviewer} sampun nliti punika saderengipun panjenengan lan ngendelaken:',
  'No reason was given.': 'Mboten wonten sabab ingkang dipunaturaken.',
  'What was proposed:': 'Ingkang dipunusulaken:',
  'The company stays in the {stage} stage.': 'Perusahaan tetep wonten ing tataran {stage}.',
  'The company stays without a stage.': 'Perusahaan tetep tanpa tataran.',
  'Move the company from {from} to {to}?': 'Pindhahaken perusahaan saking {from} dhateng {to}?',
  'Reviewed by {reviewer} before you:': 'Dipunteliti dening {reviewer} saderengipun panjenengan:',
  'The schedule "{schedule}" keeps producing the same result': 'Jadwal “{schedule}” tansah ngasilaken asil ingkang sami',
  'Its last {runs} runs all ended with the same output. That is sometimes exactly right -- a report with nothing new to say -- and often a schedule that stopped doing anything useful while still being paid for. Deny to turn it off; approve to keep it running and not be asked about this result again.': '{runs} lampahan pungkasanipun sedaya rampung kanthi asil ingkang sami. Kadhangkala punika pancen leres — laporan ingkang mboten wonten kabar enggal — lan asring punika jadwal ingkang sampun mboten nindakaken punapa-punapa ingkang migunani nanging taksih dipunbayar. Tolak kangge mejahi jadwal punika; Setujoni kangge tetep nglampahaken lan panjenengan mboten badhe dipuntakeni malih bab asil punika.',
  'Capability {capability} failed preflight': 'Kasagedan {capability} mboten lulus pamriksan wiwitan',
  'Work that needs it is stopped rather than started: fix the cause, then run that work again. The usual causes are an expired or wrongly scoped credential, a quota used up, or an address that is wrong.': 'Pakaryan ingkang mbetahaken kasagedan punika dipunkendelaken, mboten dipunwiwiti: leresaken sababipun, lajeng lampahaken malih pakaryan punika. Sabab ingkang limrah: kredensial ingkang kadaluwarsa utawi wewenangipun lepat, kuota ingkang sampun telas, utawi alamat ingkang lepat.',
  'Batch guard stopped {capability}': 'Pangaman tumindak massal ngendelaken {capability}',
  'It did not match the plan its run recorded. Nothing was sent, and no service was called.': 'Punika mboten cocog kaliyan rancangan ingkang dipuncathet dening lampahanipun. Mboten wonten ingkang dipunkintun, lan mboten wonten layanan ingkang dipunpanggil.',
  '{role} was asked first and has had {minutes} minutes.': '{role} dipuntakeni rumiyin lan sampun pikantuk {minutes} menit.',
  '{role} is not a role in this company, so this came to you at once.': '{role} sanes peran ing perusahaan punika, pramila punika langsung dumugi dhateng panjenengan.',
  '{role} could not be given this: the company has no active goal or project to hang it from.': 'Punika mboten saged dipunpasrahaken dhateng {role}: perusahaan mboten gadhah ancas utawi proyek aktif ingkang saged dados papanipun.',
  '{role} could not be given this ({record}), so this came to you at once.': 'Punika mboten saged dipunpasrahaken dhateng {role} ({record}), pramila punika langsung dumugi dhateng panjenengan.',
  '{role} stopped without an account of what it did ({why}).': '{role} kendel tanpa laporan bab punapa ingkang dipuntindakaken ({why}).',
  '{role} finished without an account of what it did.': '{role} rampung tanpa laporan bab punapa ingkang dipuntindakaken.',
  '{role} failed without an account of what it did.': '{role} gagal tanpa laporan bab punapa ingkang dipuntindakaken.',
  '{role} was stopped without an account of what it did.': '{role} dipunkendelaken tanpa laporan bab punapa ingkang dipuntindakaken.',
  'Proposed change to the {kind} "{goal}"': 'Usul ewahan kangge {kind} “{goal}”',
  'Currently: {statement}': 'Sapunika: {statement}',
  'Currently: {statement} ({status})': 'Sapunika: {statement} ({status})',
  'Proposed: {statement}': 'Dipunusulaken: {statement}',
  'Proposed status: {status}': 'Status ingkang dipunusulaken: {status}',
  'Reason given: {reason}': 'Sabab ingkang dipunaturaken: {reason}',
  'Approving it changes the goal; until then the work carries on under the goal as it is.': 'Nyetujoni punika badhe ngewahi ancas; ngantos wekdal punika pakaryan lajeng mlampah miturut ancas ingkang wonten sapunika.',
  'The goal stays as it is.': 'Ancas tetep kados sapunika.',
  'mission': 'misi',
  'objective': 'gegayuhan',
  'key result': 'asil utami',
  'Active': 'Aktif',
  'Met': 'Kagayuh',
  'Abandoned': 'Dipuntilar',
  'This work asked for it at tier {tier}, and policy {policies} requires your approval.': 'Pakaryan punika nyuwun tumindak punika ing tingkat {tier}, lan kawicaksanan {policies} mbetahaken persetujuan panjenengan.',
  'This work asked for it at tier {tier}, and the task began with content from outside the company.': 'Pakaryan punika nyuwun tumindak punika ing tingkat {tier}, lan tugasipun kawiwitan mawi isi saking njawi perusahaan.',
  'This work asked for it at tier {tier}, and the work read content from outside the company before asking.': 'Pakaryan punika nyuwun tumindak punika ing tingkat {tier}, lan pakaryan punika maos isi saking njawi perusahaan saderengipun nyuwun.',
  'This work asked for it at tier {tier}, after the work read content from outside the company, and the guardian asked you first: {reason}': 'Pakaryan punika nyuwun tumindak punika ing tingkat {tier}, sasampunipun pakaryan punika maos isi saking njawi perusahaan, lan pangreksa nyuwun persetujuan panjenengan rumiyin: {reason}',
  'it doubted this call before, and you allowed it once': 'sampun nate mangu-mangu bab panggilan punika, lan panjenengan marengaken sapisan',
  'This work asked for it at tier {tier}, which cannot be reversed.': 'Pakaryan punika nyuwun tumindak punika ing tingkat {tier}, ingkang mboten saged dipunwangsulaken.',
  'You approved this once already, and the worker carrying it out stopped before it could say whether it happened: it may already have happened. Check before approving it again.': 'Panjenengan sampun nate nyetujoni punika, lan pekerja ingkang nglampahaken kendel saderengipun saged matur punapa tumindak punika kelampahan: saged ugi sampun kelampahan. Pirsani rumiyin saderengipun nyetujoni malih.',
  'What this is for — {goals}': 'Kangge punapa punika — {goals}',
  'The task halts and no external change is made.': 'Tugas kandheg lan mboten wonten ewahan ing njawi ingkang dipuntindakaken.',
  'Scored against {total} references: {passed} passed, {failed} failed.': 'Dipunbiji mawi {total} referensi: {passed} lulus, {failed} gagal.',
  'This role has fewer than {minimum} accepted references, so the change is unscored. That is not the same as passing.': 'Peran punika gadhah referensi ingkang dipuntampi kirang saking {minimum}, pramila ewahan punika dereng dipunbiji. Punika mboten sami kaliyan lulus.',
  'The role keeps working exactly as it does now.': 'Peran punika tetep nyambut damel persis kados sapunika.',
  '{role} asks: {question}': '{role} takon: {question}',
  'The run did not say more than the question.': 'Lampahan punika mboten matur punapa-punapa malih kejawi pitakenanipun.',
  'The task is stopped, and nothing it was going to do happens.': 'Tugas dipunkendelaken, lan punapa ingkang badhe dipuntindakaken mboten kelampahan.',
  'You proposed it.': 'Panjenengan ingkang ngusulaken.',
  'It came with a bundle.': 'Kaprigelan punika dipunbekta dening satunggaling paket.',
  'An agent proposed it.': 'Satunggaling agen ingkang ngusulaken.',
  'It was learned from the company\'s work.': 'Kaprigelan punika asil sinau saking pakaryan perusahaan.',
  'Skill "{skill}", version {version}': 'Kaprigelan “{skill}”, versi {version}',
  'The reviewer approved it: {note}': 'Panliti sampun nyetujoni: {note}',
  'The reviewer approved it.': 'Panliti sampun nyetujoni.',
  'Nothing changes; the current version of the skill stays in force.': 'Mboten wonten ingkang ewah; versi kaprigelan ingkang sapunika tetep lumampah.',
  'Skills the bundle "{bundle}" brings: {count}': 'Kaprigelan ingkang dipunbekta paket “{bundle}”: {count}',
  'The reviewer read them all and approved these:': 'Panliti sampun maos sedaya lan nyetujoni punika:',
  'It turned these down, and they stay off:': 'Ingkang punika dipuntampik, lan tetep mati:',
  'Approve to switch them all on, or deny to turn them all down. To decide one at a time, open the Skills page.': 'Setujoni kangge ngurupaken sedaya, utawi Tolak kangge nampik sedaya. Kangge mutusaken setunggal-setunggal, bikak kaca Kaprigelan.',
  'Nothing changes; none of these skills is switched on.': 'Mboten wonten ingkang ewah; mboten wonten kaprigelan punika ingkang dipunurupaken.',
  'I am {ceo}, and I run {company} for you. Three things before we start: what does {company} sell, and to whom? How much may it spend in a month? And what should its first piece of work be -- or shall I suggest one?': 'Kula {ceo}, ingkang nglampahaken {company} kagem panjenengan. Tigang prekawis rumiyin saderengipun kita wiwit: {company} sade punapa, saha dhateng sinten? Pinten wragad ingkang kenging dipunginakaken ing sawulan? Lan punapa pakaryanipun ingkang sepisanan — utawi kula ingkang ngaturaken usul?',
  'Read a customer conversation': 'Waos obrolan pelanggan',
  'Reply to a customer': 'Wangsuli pelanggan',
};
