/**
 * 한국어: what the platform itself says to the owner outside the console
 * (src/owner/say.ts), keyed by its English.
 *
 * The terms are the console's (console/src/locales/ko.ts): an approval is
 * 승인 and a denial 거절, an incident 인시던트, an item the platform takes
 * back 회수됨, a card is applied (적용), and "the app" is the console (콘솔).
 * Screens are named as the console draws them: '이 인스턴스 > 모델'.
 * Sentences are polite 해요체; buttons are short labels, within WhatsApp's
 * twenty characters.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': '인시던트: {title}',
  'Done: {goal}': '완료: {goal}',
  'Stopped before finishing: {goal}': '완료 전에 중지됨: {goal}',
  'Not done: {goal}': '하지 못함: {goal}',
  'Why: {reason}': '이유: {reason}',
  'a task': '작업',
  'Approval needed: {title}': '승인 필요: {title}',
  '{summary} — if denied: {consequence}': '{summary} — 거절하면: {consequence}',
  '{role} asks:': '{role}의 질문:',
  'If denied:': '거절하면:',
  'Expires:': '만료:',
  'This one is decided in the app.': '이 항목은 콘솔에서 결정해요.',
  'Open in PALUGADA': 'PALUGADA에서 열기',
  'Approve': '승인',
  'Deny': '거절',
  'Ask': '질문',
  'Approved. Nothing left to press here.': '승인했어요. 여기서 더 누를 것은 없어요.',
  'Denied. Nothing left to press here.': '거절했어요. 여기서 더 누를 것은 없어요.',
  'Expired unanswered. Silence is a refusal, so nothing was done.': '응답 없이 만료됐어요. 응답이 없으면 거절로 보므로 아무것도 실행하지 않았어요.',
  'This bot only answers to its owner.': '이 봇은 소유자에게만 응답해요.',
  'That one has to be approved in the app.': '이 항목은 콘솔에서 승인해야 해요.',
  'That could not be recorded.': '기록하지 못했어요.',
  'That item no longer exists.': '그 항목은 더 이상 없어요.',
  'What do you want to ask about "{title}"? Reply to this message.': '\'{title}\'에 대해 무엇을 묻고 싶나요? 이 메시지에 답장하세요.',
  'Your question': '내 질문',
  'Type your question as a reply.': '답장으로 질문을 입력하세요.',
  'Asked. The answer will be on the item in the app.': '질문했어요. 답변은 콘솔의 해당 항목에 표시돼요.',
  'Answer': '답변',
  'Answer in words': '글로 답변',
  'That choice is not on this question.': '이 질문에 없는 선택지예요.',
  'Chosen: {choice}.': '선택함: {choice}.',
  'Stop the task': '작업 중지',
  'Your answer to "{question}"? Reply to this message.': '\'{question}\'에 대한 답변은요? 이 메시지에 답장하세요.',
  'Your answer': '내 답변',
  'Type your answer as a reply.': '답장으로 답변을 입력하세요.',
  'Answered. The task carries on with it.': '답변했어요. 작업은 이 답변으로 계속 진행돼요.',
  'That is too long for one question; keep it under {max} characters.': '질문 하나로는 너무 길어요. {max}자 이내로 써 주세요.',
  '[a key, not kept]': '[키라서 보관하지 않음]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    '키처럼 보여서 보관하지도, 어디에도 보내지도 않았어요. 키는 카드의 암호화 필드나 \'이 인스턴스\'의 해당 페이지에 넣어야 해요. 어디에 쓰는 키인지 알려 주면 카드를 보여 드릴게요.',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    '아직 모델이 설정되지 않아서 생각할 수 없어요. \'이 인스턴스 > 모델\'에서 하나 고르세요. 그러면 나머지는 모두 도와 드릴 수 있어요.',
  'The model did not answer: {reason}': '모델이 응답하지 않았어요: {reason}',
  'Here is what I propose.': '이렇게 제안해요.',
  'I have nothing to add.': '더 덧붙일 말은 없어요.',
  '{name}, CEO of {company}': '{company}의 CEO {name}',
  'That could not be answered: {reason}': '답변할 수 없었어요: {reason}',
  'I read text and voice notes.': '글과 음성 메시지를 읽을 수 있어요.',
  'Now talking to {name}.': '이제 {name}와(과) 대화해요.',
  'Choose whom to talk to.': '대화할 상대를 고르세요.',
  'Choose whom to talk to': '대화 상대 고르기',
  'Talk to PALUGADA about the whole deployment': '인스턴스 전체에 대해 PALUGADA와 대화',
  'Who you are talking to, and how': '지금 대화 상대와 사용 방법',
  'Stopped.': '중지했어요.',
  'Write here to talk to {name}.': '여기에 쓰면 {name}와(과) 대화할 수 있어요.',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    '지금 {name}와(과) 대화하고 있어요. 글을 쓰거나 음성 메시지를 보내세요. /ceo로 대화 상대를 고르고, /palugada로 인스턴스 전체에 대해 PALUGADA와 대화해요.',
  'You said: "{words}"': '내가 한 말: \'{words}\'',
  'in the app': '콘솔에서',
  'Apply: {summary}': '적용: {summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    '아직 음성을 듣는 서비스가 없어요. 콘솔의 \'이 인스턴스 > 도구 > 음성 인식\'에서 제공업체를 고르세요.',
  'That recording is too long; keep a voice note under {max} MB.': '녹음이 너무 길어요. 음성 메시지는 {max}MB 이내로 보내 주세요.',
  'I could not make out any words in that.': '알아들을 수 있는 말이 없었어요.',
  'Done: {summary}': '완료: {summary}',
  'That one is applied in the app.': '이 카드는 콘솔에서 적용해요.',
  'That card no longer exists.': '그 카드는 더 이상 없어요.',
  'That card was already applied.': '그 카드는 이미 적용됐어요.',
  'That card was dismissed.': '그 카드는 적용하지 않기로 했어요.',
  'That card failed when it was applied.': '그 카드는 적용할 때 실패했어요.',
  'That could not be done: {reason}': '할 수 없었어요: {reason}',
  'Choose': '선택',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    '\'{title}\'에 대해 무엇을 묻고 싶나요? 이 메시지에 답장으로 질문을 쓰세요.',
  'Your answer to "{question}"? Reply to this message with your answer.':
    '\'{question}\'에 대한 답변은요? 이 메시지에 답장으로 답변을 쓰세요.',
  'I read text messages here.': '여기서는 글 메시지를 읽어요.',
  'Apply one of these here:': '여기서 다음 중 하나를 적용하세요:',
  'Apply {number}': '{number}번 적용',
  'Signed in to {provider} for the {alias} key': '{alias} 키를 위해 {provider}에 로그인했어요',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'PALUGADA로 돌아가세요. 이제 부서가 이 키를 가지고 있으며, 만료되기 전에 갱신돼요. 이 탭은 닫아도 돼요.',
  'Signed in to {name}': '{name}에 로그인했어요',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'PALUGADA로 돌아가 역할이 쓸 수 있는 도구를 고르세요. 이 탭은 닫아도 돼요.',
  'Not signed in': '로그인되지 않음',
  'Recorded: approved.': '기록함: 승인.',
  'Recorded: denied.': '기록함: 거절.',
  'Recorded: asked.': '기록함: 질문.',
  'Asked. Nothing left to press here.': '질문했어요. 여기서 더 누를 것은 없어요.',
  'Withdrawn: the task it was asking about has finished.': '회수됨: 질문 대상 작업이 완료됐어요.',
  'Withdrawn: the task it was asking about has failed.': '회수됨: 질문 대상 작업이 실패했어요.',
  'Withdrawn: the task it was asking about was stopped.': '회수됨: 질문 대상 작업이 중지됐어요.',
  'Withdrawn: the task it was asking about was cancelled.': '회수됨: 질문 대상 작업이 취소됐어요.',
  'Decided. Nothing left to press here.': '결정됐어요. 여기서 더 누를 것은 없어요.',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': '회수됨: 에이전트가 제안 내용을 바꿔서 새 제안으로 다시 확인을 요청했어요.',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': '회수됨: 회사가 더 이상 이 제안의 출발점인 사업 단계에 있지 않아요.',
  'Withdrawn: it was already decided in the app.': '회수됨: 이미 콘솔에서 결정됐어요.',
  'Withdrawn. Nothing left to press here.': '회수됐어요. 여기서 더 누를 것은 없어요.',
  'company': '회사',
  'Work stopped: the {account} account is out of tokens': '작업이 멈췄습니다: {account} 계정의 토큰이 모두 소진되었습니다',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': '“{work}”이(가) 멈췄습니다. {account} 계정이 {max} 토큰 중 {spent}을(를) 사용했기 때문입니다. 금액에서 한도를 올린 다음, 작업을 열고 계속을 누르세요. 멈춘 곳부터 이어서 진행합니다.',
  'Withdrawn: you continued the task it was about.': '철회됨: 관련 작업을 계속 진행했습니다.',
  'Broke its contract': '계약 위반',
  'Refused by a policy': '정책에 의해 거부됨',
  'Out of budget': '예산 소진',
  'Handed on too many times': '너무 여러 번 넘겨짐',
  'Missed its deadline': '마감 기한을 놓침',
  'Its result did not check out': '결과 검증 실패',
  'A capability it needs is down': '필요한 기능이 중단됨',
  'No runtime could take it': '맡을 수 있는 런타임이 없음',
  'Went in a circle': '순환에 빠짐',
  'Split into too many sub-tasks': '하위 작업으로 너무 많이 나눔',
  'Wrote more than its role allows one run': '실행 한 번에 역할이 허용하는 양보다 많이 씀',
  'Your approval was not given in time': '승인이 제때 이루어지지 않음',
  'Stopped by you': '직접 중지함',
  'Cancelled by you': '직접 취소함',
  'The company is frozen': '회사가 동결됐어요',
  'Its record did not match on replay': '재실행 시 기록이 일치하지 않음',
  'It kept stopping the worker running it': '실행 중인 워커를 계속 멈추게 했어요',
  'Not done': '하지 못함',
  'Task failed': '작업 실패함',
  'Digest for {day}': '{day} 요약',
  'Spent: {amount}': '지출액: {amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': '작업: 완료 {done}건, 실패 {failed}건, 중지 {stopped}건',
  'Inbox: {open} waiting (incidents: {incidents})': '수신함: {open}건 대기 중 (인시던트: {incidents}건)',
  'Stopped ({count}): {reason}': '중지됨 ({count}건): {reason}',
  'Start an ad campaign': '광고 캠페인 시작',
  'Block time on the calendar': '캘린더에 시간 잡아 두기',
  'Read the calendar': '캘린더 보기',
  'Run code': '코드 실행',
  'Add a note to a customer': '고객 메모 추가',
  'Read customer records': '고객 기록 보기',
  'Release to the live site': '실제 사이트에 배포',
  'Release to the test site': '테스트 사이트에 배포',
  'Change a domain\'s nameservers': '도메인 네임서버 변경',
  'Read a domain\'s records': '도메인 DNS 레코드 보기',
  'Change a domain\'s record': '도메인 DNS 레코드 변경',
  'Write a document': '문서 작성',
  'Sign a document': '문서에 서명',
  'Buy a domain': '도메인 구매',
  'Transfer a domain': '도메인 이전',
  'Draft an email': '이메일 초안 작성',
  'Send an email': '이메일 보내기',
  'List files': '파일 목록 보기',
  'Read a file': '파일 읽기',
  'Describe a picture': '이미지 설명하기',
  'Calculate in Python': 'Python으로 계산하기',
  'Transfer money': '송금하기',
  'Propose a goal change': '목표 변경 제안',
  'Make a picture': '이미지 생성',
  'Issue an invoice': '청구서 발행',
  'Pay an invoice': '청구서 결제',
  'Read the books': '회계 장부 보기',
  'Read the mailbox': '메일함 보기',
  'Search what the company knows': '회사 지식 검색',
  'Record a measure': '지표 값 기록',
  'Read product numbers': '제품 지표 보기',
  'Ask you a question': '본인에게 질문하기',
  'Write down a plan': '계획 기록',
  'Delete a record': '레코드 삭제',
  'Propose a code change': '코드 변경 제안',
  'Read the code': '코드 읽기',
  'Destroy a server': '서버 완전 삭제',
  'Read a skill': '스킬 읽기',
  'Publish a post': '게시물 올리기',
  'Read text aloud': '텍스트 소리 내어 읽기',
  'Turn speech into text': '음성을 텍스트로 바꾸기',
  'Propose a new stage': '새 사업 단계 제안',
  'Wait for work handed on': '넘겨준 일 기다리기',
  'Hand work to another role': '다른 역할에게 일 맡기기',
  'File a ticket': '티켓 만들기',
  'List tickets': '티켓 목록 보기',
  'Check a service is up': '서비스 작동 확인',
  'Read a web page': '웹 페이지 읽기',
  'Open a web page': '웹 페이지 열기',
  'Search the web': '웹 검색',
  'no stage': '단계 없음',
  'Explore': '탐색',
  'Validate': '검증',
  'Build': '구축',
  'Launch': '출시',
  'Grow': '성장',
  'Wind down': '정리',
  'Monthly budget reached; the company is paused': '월 예산에 도달해 회사가 일시 중지됨',
  '{spent} of {limit} spent since {since}. No new task will start and no external action will run until you raise the ceiling or allow spending past it for a while, under Money.': '{since} 이후 {limit} 중 {spent}을(를) 지출했어요. \'금액\'에서 한도를 올리거나 한도를 넘는 지출을 한시적으로 허용하기 전까지는 새 작업이 시작되지 않고 외부 조치도 실행되지 않아요.',
  'Monthly budget is 80% spent': '월 예산의 80%를 지출함',
  '{spent} of {limit} spent since {since}. At 100% the company pauses.': '{since} 이후 {limit} 중 {spent}을(를) 지출했어요. 100%에 도달하면 회사가 일시 중지돼요.',
  'Role {role} is paused for spending too fast': '역할 {role}이(가) 지출 속도가 너무 빨라 일시 중지됨',
  '{role} spent {spent} in the last hour, {multiple} times its usual {usual} an hour. It is paused before the monthly ceiling is reached, so there is money left to work with once you have found out why. Resume it when you have.': '{role}이(가) 지난 1시간 동안 {spent}을(를) 지출했어요. 평소 시간당 {usual}의 {multiple}배예요. 월 한도에 도달하기 전에 일시 중지했으므로, 원인을 찾은 뒤에도 일에 쓸 돈이 남아 있어요. 원인을 찾으면 재개하세요.',
  'Daily model spend over threshold': '일일 모델 지출이 임계값을 넘음',
  'Model spend today is {spent}, over the {limit} ceiling.': '오늘 모델 지출이 {spent}(으)로, 한도 {limit}을(를) 넘었어요.',
  'Task failure rate over threshold': '작업 실패율이 임계값을 넘음',
  '{failed} of {finished} tasks failed or stopped today ({rate}%), over the {limit}% threshold.': '오늘 작업 {finished}건 중 {failed}건이 실패하거나 중지되어({rate}%) 임계값 {limit}%를 넘었어요.',
  'Unusual number of policy refusals': '정책 거부 횟수가 비정상적으로 많음',
  'Actions refused by a policy today: {count}, over the threshold of {limit}. Either an agent is probing its limits or a policy is miscalibrated.': '오늘 정책에 거부된 조치: {count}건으로, 임계값 {limit}건을 넘었어요. 에이전트가 한계를 시험하고 있거나 정책이 잘못 설정되어 있어요.',
  'External writes failed verification': '외부 쓰기가 검증에 실패함',
  'Writes outside that reported success but read back differently: {count}. Something is changing them other than as asked.': '성공으로 보고됐지만 다시 읽으니 내용이 달랐던 외부 쓰기: {count}건. 요청과 다른 방식으로 무언가가 이를 바꾸고 있어요.',
  'A capability stopped being usable': '기능을 더 이상 쓸 수 없음',
  'Tasks that could not start today because a capability their role needs failed its check: {count}. A credential has probably expired or a quota is used up.': '역할에 필요한 기능이 검사를 통과하지 못해 오늘 시작하지 못한 작업: {count}건. 자격 증명이 만료되었거나 할당량을 다 썼을 가능성이 커요.',
  'A worker stopped reporting mid-run': '워커가 실행 도중 응답을 멈춤',
  'Runs that stopped reporting and were taken back today: {count}. The work was picked up again; the tokens they had already spent were not recovered.': '오늘 응답이 끊겨 회수된 실행: {count}건. 일은 다시 맡겨졌지만, 이미 쓴 토큰은 돌려받지 못했어요.',
  '{role} was refused {denials} times today, at the limit of {limit}. No task will run as this role until you lift the freeze. The usual causes are a missing capability grant, a policy the role\'s charter does not account for, or work the role was never equipped to do.': '{role}이(가) 오늘 {denials}회 거부되어 한도인 {limit}회에 도달했어요. 동결을 해제하기 전까지 이 역할로는 어떤 작업도 실행되지 않아요. 흔한 원인은 기능 권한 부여 누락, 역할의 헌장이 고려하지 않은 정책, 또는 역할이 애초에 할 수 있도록 갖춰지지 않은 일이에요.',
  'Role {role} is frozen after repeated denials': '역할 {role}이(가) 반복된 거부로 동결됨',
  'What it was refused: {capabilities}': '거부된 항목: {capabilities}',
  'It is waiting for an approval, and none is open, so nothing you can answer will move it.': '승인을 기다리고 있지만 열려 있는 승인이 없어서, 어떻게 답해도 진행되지 않아요.',
  'It is waiting for a review, and none is pending, so no reviewer and no decision of yours will move it.': '검토를 기다리고 있지만 대기 중인 검토가 없어서, 검토자도 직접 내리는 결정도 이 작업을 진행시킬 수 없어요.',
  'It is parked until a window reopens, and the window never does.': '시간대가 다시 열릴 때까지 대기 중이지만, 그 시간대는 다시 열리지 않아요.',
  'A task is waiting on nothing': '기다릴 대상이 없는데 기다리는 작업이 있음',
  '"{task}" has been waiting since {since}. {why} Approve to run it again from where it stopped, or deny to cancel it.': '\'{task}\'이(가) {since}부터 기다리고 있어요. {why} 승인하면 멈춘 곳부터 다시 실행하고, 거절하면 취소해요.',
  'A task keeps stopping the worker running it': '작업이 실행 중인 워커를 계속 멈추게 함',
  '"{task}" lost its worker {lost} times: each time the worker running it stopped answering before the work finished. What it had done is kept. It is halted so it cannot take another worker down; run it again once the cause is found, or cancel it.': '\'{task}\'이(가) 워커를 {lost}회 잃었어요. 매번 실행 중이던 워커가 일이 끝나기 전에 응답을 멈췄어요. 지금까지 한 일은 보존돼요. 다른 워커까지 멈추게 하지 않도록 작업을 중지했어요. 원인을 찾은 뒤 다시 실행하거나 취소하세요.',
  '{services} stayed unreachable, and the work that needs it stopped': '{services}에 계속 연결할 수 없어 이를 필요로 하는 일이 중지됨',
  'The task waited about {minutes} minutes, looking again each time, and has stopped. Once the service answers, run it again.': '작업이 약 {minutes}분 동안 매번 다시 확인하며 기다렸지만 결국 중지됐어요. 서비스가 응답하면 다시 실행하세요.',
  'It was tried {tries} times over about {minutes} minutes.': '약 {minutes}분 동안 {tries}회 시도했어요.',
  'This role can take actions that cannot be undone, so the run was not silently moved to a different model.': '이 역할은 되돌릴 수 없는 조치를 할 수 있어서, 실행을 다른 모델로 몰래 옮기지 않았어요.',
  'No fallback model is left for this role.': '이 역할에 남은 대체 모델이 없어요.',
  'Model {model} failed and the run was not moved': '모델 {model}이(가) 실패했지만 실행을 옮기지 않음',
  'External write failed verification': '외부 쓰기가 검증에 실패함',
  'The task wrote to an outside service and read it back, and what it read did not match. Look at the place it wrote to before you run it again: the write may have happened.': '작업이 외부 서비스에 쓴 뒤 다시 읽었는데, 읽은 내용이 일치하지 않았어요. 다시 실행하기 전에 쓴 곳을 확인하세요. 쓰기가 이미 이루어졌을 수 있어요.',
  'Review deadlocked after {rounds} revisions: {capability}': '{rounds}회 수정 후에도 검토가 교착 상태: {capability}',
  'The role and its reviewer did not agree on {capability}.': '역할과 검토자가 {capability}에 대해 합의하지 못했어요.',
  'The reviewer\'s last note: {note}': '검토자의 마지막 메모: {note}',
  'The reviewer left no note.': '검토자가 메모를 남기지 않았어요.',
  'What it was judged against: {criteria}': '판단 기준: {criteria}',
  'Review produced no usable verdict: {capability}': '검토에서 쓸 수 있는 판정이 나오지 않음: {capability}',
  'The reviewing task ended without a decision that could be read. The proposed action is still blocked and needs your judgement.': '검토 작업이 읽을 수 있는 결정 없이 끝났어요. 제안된 조치는 여전히 막혀 있으며 직접 판단해야 해요.',
  'another stage': '다른 사업 단계',
  'Either answer only closes this: the company stays in the {stage} stage.': '어느 쪽으로 답해도 이 항목만 닫혀요. 회사는 \'{stage}\' 단계에 그대로 있어요.',
  'Either answer only closes this: the company stays without a stage.': '어느 쪽으로 답해도 이 항목만 닫혀요. 회사는 사업 단계가 없는 상태로 남아요.',
  'To move it anyway, set the stage on the Overview.': '그래도 옮기려면 \'개요\'에서 사업 단계를 설정하세요.',
  '{reviewer} stopped a proposal to move the company from {from} to {to}': '{reviewer}이(가) 회사의 사업 단계를 \'{from}\'에서 \'{to}\'(으)로 옮기자는 제안을 막음',
  '{reviewer} reviewed it before you and stopped it:': '{reviewer}이(가) 먼저 검토하고 막았어요:',
  'No reason was given.': '이유가 제시되지 않았어요.',
  'What was proposed:': '제안 내용:',
  'The company stays in the {stage} stage.': '회사는 \'{stage}\' 단계에 그대로 있어요.',
  'The company stays without a stage.': '회사는 사업 단계가 없는 상태로 남아요.',
  'Move the company from {from} to {to}?': '회사의 사업 단계를 \'{from}\'에서 \'{to}\'(으)로 옮길까요?',
  'Reviewed by {reviewer} before you:': '직접 보기 전에 {reviewer}이(가) 검토했어요:',
  'The schedule "{schedule}" keeps producing the same result': '일정 \'{schedule}\'이(가) 계속 같은 결과를 냄',
  'Its last {runs} runs all ended with the same output. That is sometimes exactly right -- a report with nothing new to say -- and often a schedule that stopped doing anything useful while still being paid for. Deny to turn it off; approve to keep it running and not be asked about this result again.': '최근 실행 {runs}회가 모두 같은 출력으로 끝났어요. 이것이 딱 맞는 경우도 있지만(새로 알릴 것이 없는 보고서처럼), 비용은 계속 나가는데 더 이상 쓸모 있는 일을 하지 않는 일정인 경우가 많아요. 거절하면 끄고, 승인하면 계속 실행하며 이 결과에 대해 다시 묻지 않아요.',
  'Capability {capability} failed preflight': '기능 {capability}이(가) 검사를 통과하지 못함',
  'Work that needs it is stopped rather than started: fix the cause, then run that work again. The usual causes are an expired or wrongly scoped credential, a quota used up, or an address that is wrong.': '이를 필요로 하는 일은 시작되지 않고 중지돼요. 원인을 고친 다음 그 일을 다시 실행하세요. 흔한 원인은 만료되었거나 범위가 잘못 지정된 자격 증명, 다 쓴 할당량, 잘못된 주소예요.',
  'Batch guard stopped {capability}': '일괄 처리 가드가 {capability}을(를) 중지함',
  'It did not match the plan its run recorded. Nothing was sent, and no service was called.': '실행이 기록한 계획과 일치하지 않았어요. 아무것도 보내지 않았고, 어떤 서비스도 호출하지 않았어요.',
  '{role} was asked first and has had {minutes} minutes.': '{role}에게 먼저 요청했고 {minutes}분이 지났어요.',
  '{role} is not a role in this company, so this came to you at once.': '{role}은(는) 이 회사의 역할이 아니어서 바로 전달됐어요.',
  '{role} could not be given this: the company has no active goal or project to hang it from.': '{role}에게 맡길 수 없었어요. 회사에 연결할 활성 목표나 프로젝트가 없어요.',
  '{role} could not be given this ({record}), so this came to you at once.': '{role}에게 맡길 수 없어서({record}) 바로 전달됐어요.',
  '{role} stopped without an account of what it did ({why}).': '{role}이(가) 무엇을 했는지 보고하지 않고 멈췄어요({why}).',
  '{role} finished without an account of what it did.': '{role}이(가) 무엇을 했는지 보고하지 않고 완료했어요.',
  '{role} failed without an account of what it did.': '{role}이(가) 무엇을 했는지 보고하지 않고 실패했어요.',
  '{role} was stopped without an account of what it did.': '{role}이(가) 무엇을 했는지 보고하지 않은 채 중지됐어요.',
  'Proposed change to the {kind} "{goal}"': '{kind} \'{goal}\' 변경 제안',
  'Currently: {statement}': '현재: {statement}',
  'Currently: {statement} ({status})': '현재: {statement} ({status})',
  'Proposed: {statement}': '제안: {statement}',
  'Proposed status: {status}': '제안된 상태: {status}',
  'Reason given: {reason}': '제시된 이유: {reason}',
  'Record an entry in the books': '장부에 분개 기록',
  'Record a customer or a deal': '고객이나 거래 기록',
  'Not sent on its own: {reason}': '스스로 보내지 않음: {reason}',
  'it answers a conversation other than the one this work began with': '이 작업이 시작된 대화가 아닌 다른 대화에 대한 답이에요',
  'it named no passage of a document for customers': '고객용 문서의 어떤 부분도 밝히지 않았어요',
  'it answers from a document not marked for customers': '고객용으로 표시되지 않은 문서로 답해요',
  'it says a figure the documents and the customer did not: {detail}': '문서에도 고객의 말에도 없는 숫자가 있어요: {detail}',
  'it gives an address or link the documents and the customer did not: {detail}': '문서에도 고객의 말에도 없는 주소나 링크가 있어요: {detail}',
  'there have been six answers on its own in this conversation in the last hour': '이 대화에서 지난 1시간 동안 이미 여섯 번 스스로 답했어요',
  'the check found it is about a refund': '확인 결과 환불에 관한 내용이에요',
  'the check found it offers a price or terms of its own': '확인 결과 자체 가격이나 조건을 제시해요',
  'the check found it answers a serious complaint': '확인 결과 심각한 불만에 답하는 내용이에요',
  'the check found it touches the law': '확인 결과 법적 문제에 닿아 있어요',
  'the check found it gives or asks for personal data': '확인 결과 개인정보를 주거나 요청해요',
  'the check found it promises something the documents do not': '확인 결과 문서에 없는 것을 약속해요',
  'the check could not judge it': '확인으로 판단할 수 없었어요',
  'the check found something in it the documents do not say': '확인 결과 문서에 없는 내용이 있어요',
  '{role} proposes the schedule {name}': '{role}이(가) 일정 {name}을(를) 제안해요',
  'Each run: {instruction}': '매 실행: {instruction}',
  'Done by: {role}': '담당: {role}',
  'When: {cron} ({timezone}); the next runs are {runs}': '시기: {cron} ({timezone}); 다음 실행은 {runs}',
  'Approving it makes the schedule and starts it; it can be turned off or changed under Team, Schedules.': '승인하면 일정이 만들어지고 시작돼요. 팀, 일정에서 끄거나 바꿀 수 있어요.',
  'No schedule is made.': '일정이 만들어지지 않아요.',
  'Propose a schedule': '일정 제안',
  'Approving it changes the goal; until then the work carries on under the goal as it is.': '승인하면 목표가 변경돼요. 그 전까지는 현재 목표대로 일이 계속돼요.',
  'The goal stays as it is.': '목표는 그대로 유지돼요.',
  'mission': '미션',
  'objective': '목표(O)',
  'key result': '핵심 결과(KR)',
  'Active': '활성',
  'Met': '달성',
  'Abandoned': '포기',
  'This work asked for it at tier {tier}, and policy {policies} requires your approval.': '이 일은 이를 등급 {tier} 조치로 요청했고, 정책 {policies}에 따라 직접 승인해야 해요.',
  'This work asked for it at tier {tier}, and the task began with content from outside the company.': '이 일은 이를 등급 {tier} 조치로 요청했고, 작업이 회사 외부의 콘텐츠로 시작됐어요.',
  'This work asked for it at tier {tier}, and the work read content from outside the company before asking.': '이 일은 이를 등급 {tier} 조치로 요청했고, 요청하기 전에 회사 외부의 콘텐츠를 읽었어요.',
  'This work asked for it at tier {tier}, after the work read content from outside the company, and the guardian asked you first: {reason}': '이 일은 회사 외부의 콘텐츠를 읽은 뒤 이를 등급 {tier} 조치로 요청했고, 가디언이 먼저 확인을 요청했어요: {reason}',
  'it doubted this call before, and you allowed it once': '이전에도 이 호출을 의심했고, 직접 한 번 허용했어요',
  'This work asked for it at tier {tier}, which cannot be reversed.': '이 일은 이를 등급 {tier} 조치로 요청했고, 이 조치는 되돌릴 수 없어요.',
  'You approved this once already, and the worker carrying it out stopped before it could say whether it happened: it may already have happened. Check before approving it again.': '이미 한 번 승인했지만, 이를 실행하던 워커가 실제로 실행됐는지 알리기 전에 멈췄어요. 이미 실행됐을 수 있어요. 다시 승인하기 전에 확인하세요.',
  'What this is for — {goals}': '목적 — {goals}',
  'The task halts and no external change is made.': '작업이 중지되고 외부에는 아무 변경도 일어나지 않아요.',
  'Scored against {total} references: {passed} passed, {failed} failed.': '참고 사례 {total}개로 평가: 통과 {passed}개, 실패 {failed}개.',
  'This role has fewer than {minimum} accepted references, so the change is unscored. That is not the same as passing.': '이 역할은 채택된 참고 사례가 {minimum}개 미만이라 이 변경은 점수가 없어요. 통과와 같은 뜻이 아니에요.',
  'The role keeps working exactly as it does now.': '역할은 지금과 똑같이 계속 일해요.',
  '{role} asks: {question}': '{role}의 질문: {question}',
  'The run did not say more than the question.': '실행이 질문 외에는 더 말하지 않았어요.',
  'The task is stopped, and nothing it was going to do happens.': '작업이 중지되고, 하려던 일은 아무것도 일어나지 않아요.',
  'You proposed it.': '직접 제안한 스킬이에요.',
  'It came with a bundle.': '번들에 포함되어 들어온 스킬이에요.',
  'An agent proposed it.': '에이전트가 제안한 스킬이에요.',
  'It was learned from the company\'s work.': '회사의 일에서 배운 스킬이에요.',
  'Skill "{skill}", version {version}': '스킬 \'{skill}\', 버전 {version}',
  'The reviewer approved it: {note}': '검토자가 승인했어요: {note}',
  'The reviewer approved it.': '검토자가 승인했어요.',
  'Nothing changes; the current version of the skill stays in force.': '아무것도 바뀌지 않아요. 스킬의 현재 버전이 계속 적용돼요.',
  'Skills the bundle "{bundle}" brings: {count}': '번들 \'{bundle}\'에 들어 있는 스킬: {count}',
  'The reviewer read them all and approved these:': '검토자가 모두 읽고 다음 스킬을 승인했어요:',
  'It turned these down, and they stay off:': '다음 스킬은 반려되어 꺼진 상태로 남아요:',
  'Approve to switch them all on, or deny to turn them all down. To decide one at a time, open the Skills page.': '승인하면 모두 켜고, 거절하면 모두 반려해요. 하나씩 결정하려면 \'스킬\' 페이지를 여세요.',
  'Nothing changes; none of these skills is switched on.': '아무것도 바뀌지 않아요. 이 스킬은 하나도 켜지지 않아요.',
  'I am {ceo}, and I run {company} for you. Three things before we start: what does {company} sell, and to whom? How much may it spend in a month? And what should its first piece of work be -- or shall I suggest one?': '저는 {ceo}(이)에요. 제가 {company}을(를) 맡아 운영할게요. 시작하기 전에 세 가지만 여쭤볼게요. {company}은(는) 무엇을 누구에게 파나요? 한 달에 얼마까지 쓸 수 있나요? 그리고 첫 번째 일은 무엇으로 할까요? 아니면 제가 하나 제안할까요?',
  'Read a customer conversation': '고객 대화 읽기',
  'Reply to a customer': '고객에게 답장하기',
  'Read a page in the browser': '브라우저에서 페이지 읽기',
  'Fill in a page in the browser': '브라우저에서 페이지 작성하기',
  'Ask you to take over the browser': '브라우저를 넘겨받아 달라고 요청하기',
  '{host} refused the model key ({status}), so nothing that needs the model can run. Open Settings, This deployment, Model, paste a key that works, test it and save.':
    '{host}이(가) 모델 키를 거부했습니다({status}). 모델이 필요한 작업은 실행할 수 없습니다. 설정, 이 인스턴스, 모델을 열어 사용할 수 있는 키를 붙여넣고 테스트한 뒤 저장하세요.',
  '{host} refused the model key, and work is waiting': '{host}이(가) 모델 키를 거부해 작업이 대기 중입니다',
  'What is waiting for the model carries on by itself once a key that works is in use.':
    '모델을 기다리던 작업은 사용할 수 있는 키가 적용되면 자동으로 이어집니다.',
  'A task ended before it was done: {task}':
    '작업이 끝나지 못한 채 종료되었습니다: {task}',
  'It ended as: {reason}. No other card was raised for it, so it is here rather than silent.':
    '종료 사유: {reason}. 이 건에 대해 다른 카드가 만들어지지 않아, 조용히 지나가지 않도록 여기에 올렸습니다.',
  'Where its measures stand, as the platform reads them:':
    '플랫폼이 읽은 지표의 현재 상태:',
  '{name}: no value recorded yet, against a target of {target}.':
    '{name}: 아직 기록된 값이 없습니다(목표 {target}).',
  '{name}: {value} against a target of {target}, read back from its source.':
    '{name}: {value}(목표 {target}), 출처에서 다시 읽어 확인했습니다.',
  '{name}: {value} against a target of {target}, reported and not checked.':
    '{name}: {value}(목표 {target}), 보고만 되었고 확인되지 않았습니다.',
  'Look at it again later': '나중에 다시 확인하기',
  "Deliver what this company sells, reliably and without surprising its owner.":
    "이 회사가 파는 것을 믿을 수 있게 전달하고, 소유자를 놀라게 하지 않는다.",
  "Ship the work the company has promised, on time and verified.":
    "회사가 약속한 일을 기한에 맞춰, 검증된 상태로 내보낸다.",
  "Keep the company solvent, answerable and running without daily attention.":
    "회사의 지급 능력을 지키고, 책임질 수 있게 하며, 매일 신경 쓰지 않아도 돌아가게 한다.",
};
