/**
 * Bahasa Melayu: what the platform itself says to the owner outside the
 * console (src/owner/say.ts), keyed by its English.
 *
 * The terms are the console's (console/src/locales/ms.ts), so a button on
 * the phone says what the same button says in the panel: Luluskan, Tolak,
 * Tanya; "Pemasangan ini, Alatan, Mendengar" is the page it names there. The
 * app the owner is sent to is "apl", as Malaysian software writes it.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'Insiden: {title}',
  'Done: {goal}': 'Selesai: {goal}',
  'Stopped before finishing: {goal}': 'Berhenti sebelum selesai: {goal}',
  'Not done: {goal}': 'Tidak dibuat: {goal}',
  'Why: {reason}': 'Sebab: {reason}',
  'a task': 'satu tugasan',
  'Approval needed: {title}': 'Kelulusan diperlukan: {title}',
  '{summary} — if denied: {consequence}': '{summary} — jika ditolak: {consequence}',
  '{role} asks:': '{role} bertanya:',
  'If denied:': 'Jika ditolak:',
  'Expires:': 'Tamat tempoh:',
  'This one is decided in the app.': 'Yang ini diputuskan dalam apl.',
  'Open in PALUGADA': 'Buka dalam PALUGADA',
  'Approve': 'Luluskan',
  'Deny': 'Tolak',
  'Ask': 'Tanya',
  'Approved. Nothing left to press here.': 'Diluluskan. Tiada apa-apa lagi untuk ditekan di sini.',
  'Denied. Nothing left to press here.': 'Ditolak. Tiada apa-apa lagi untuk ditekan di sini.',
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    'Tamat tempoh tanpa jawapan. Berdiam diri bermaksud menolak, jadi tiada apa-apa yang dilakukan.',
  'This bot only answers to its owner.': 'Bot ini hanya menjawab pemiliknya.',
  'That one has to be approved in the app.': 'Yang itu mesti diluluskan dalam apl.',
  'That could not be recorded.': 'Itu tidak dapat direkodkan.',
  'That item no longer exists.': 'Item itu tidak wujud lagi.',
  'What do you want to ask about "{title}"? Reply to this message.':
    'Apa yang anda mahu tanya tentang "{title}"? Balas mesej ini.',
  'Your question': 'Soalan anda',
  'Type your question as a reply.': 'Taip soalan anda sebagai balasan.',
  'Asked. The answer will be on the item in the app.': 'Soalan dihantar. Jawapannya akan ada pada item itu dalam apl.',
  'Answer': 'Jawab',
  'Answer in words': 'Jawab dengan kata-kata',
  'That choice is not on this question.': 'Pilihan itu tiada dalam soalan ini.',
  'Chosen: {choice}.': 'Dipilih: {choice}.',
  'Stop the task': 'Hentikan tugasan',
  'Your answer to "{question}"? Reply to this message.': 'Jawapan anda untuk "{question}"? Balas mesej ini.',
  'Your answer': 'Jawapan anda',
  'Type your answer as a reply.': 'Taip jawapan anda sebagai balasan.',
  'Answered. The task carries on with it.': 'Dijawab. Tugasan diteruskan dengan jawapan itu.',
  'That is too long for one question; keep it under {max} characters.':
    'Itu terlalu panjang untuk satu soalan; pastikan kurang daripada {max} aksara.',
  '[a key, not kept]': '[satu kunci, tidak disimpan]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    'Itu kelihatan seperti kunci, jadi saya tidak menyimpannya atau menghantarnya ke mana-mana. Kunci dimasukkan dalam medan yang dimeterai pada kad, atau pada halamannya di Pemasangan ini: beritahu saya kegunaannya dan saya akan letakkan kad itu di hadapan anda.',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'Belum ada model yang disediakan, jadi saya tidak boleh berfikir. Pilih satu di bawah Pemasangan ini, Model; kemudian saya boleh membantu dengan semua perkara lain.',
  'The model did not answer: {reason}': 'Model tidak menjawab: {reason}',
  'Here is what I propose.': 'Ini cadangan saya.',
  'I have nothing to add.': 'Saya tiada apa-apa untuk ditambah.',
  '{name}, CEO of {company}': '{name}, CEO {company}',
  'That could not be answered: {reason}': 'Itu tidak dapat dijawab: {reason}',
  'I read text and voice notes.': 'Saya membaca teks dan mesej suara.',
  'Now talking to {name}.': 'Kini bercakap dengan {name}.',
  'Choose whom to talk to.': 'Pilih siapa yang anda mahu ajak bercakap.',
  'Choose whom to talk to': 'Pilih siapa yang anda ajak bercakap',
  'Talk to PALUGADA about the whole deployment': 'Bercakap dengan PALUGADA tentang keseluruhan pemasangan',
  'Who you are talking to, and how': 'Dengan siapa anda bercakap, dan caranya',
  'Stopped.': 'Dihentikan.',
  'Write here to talk to {name}.': 'Tulis di sini untuk bercakap dengan {name}.',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    'Anda sedang bercakap dengan {name}. Tulis, atau hantar mesej suara. /ceo memilih siapa yang anda ajak bercakap; /palugada bercakap dengan PALUGADA tentang keseluruhan pemasangan.',
  'You said: "{words}"': 'Anda berkata: "{words}"',
  'in the app': 'dalam apl',
  'Apply: {summary}': 'Laksanakan: {summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    'Belum ada yang boleh mendengar pertuturan: pilih penyedia dalam apl, di bawah Pemasangan ini, Alatan, Mendengar.',
  'That recording is too long; keep a voice note under {max} MB.': 'Rakaman itu terlalu panjang; pastikan mesej suara kurang daripada {max} MB.',
  'I could not make out any words in that.': 'Saya tidak dapat menangkap sebarang perkataan daripadanya.',
  'Done: {summary}': 'Selesai: {summary}',
  'That one is applied in the app.': 'Yang itu dilaksanakan dalam apl.',
  'That card no longer exists.': 'Kad itu tidak wujud lagi.',
  'That card was already applied.': 'Kad itu sudah dilaksanakan.',
  'That card was dismissed.': 'Kad itu telah diketepikan.',
  'That card failed when it was applied.': 'Kad itu gagal semasa dilaksanakan.',
  'That could not be done: {reason}': 'Itu tidak dapat dilakukan: {reason}',
  'Choose': 'Pilih',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    'Apa yang anda mahu tanya tentang "{title}"? Balas mesej ini dengan soalan anda.',
  'Your answer to "{question}"? Reply to this message with your answer.':
    'Jawapan anda untuk "{question}"? Balas mesej ini dengan jawapan anda.',
  'I read text messages here.': 'Di sini saya membaca mesej teks.',
  'Apply one of these here:': 'Laksanakan salah satu daripada ini di sini:',
  'Apply {number}': 'Laksanakan {number}',
  'Signed in to {provider} for the {alias} key': 'Telah log masuk ke {provider} untuk kunci {alias}',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'Kembali ke PALUGADA: bahagian itu kini memegang kunci ini, dan ia diperbaharui sebelum tamat tempoh. Tab ini boleh ditutup.',
  'Signed in to {name}': 'Telah log masuk ke {name}',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'Kembali ke PALUGADA untuk memilih alatnya yang boleh digunakan oleh peranan. Tab ini boleh ditutup.',
  'Not signed in': 'Tidak dapat log masuk',
  "Recorded: approved.": "Direkodkan: diluluskan.",
  "Recorded: denied.": "Direkodkan: ditolak.",
  "Recorded: asked.": "Direkodkan: ditanya.",
  "Asked. Nothing left to press here.": "Soalan dihantar. Tiada apa-apa lagi untuk ditekan di sini.",
  "Withdrawn: the task it was asking about has finished.": "Ditarik balik: tugasan yang ditanyakannya telah selesai.",
  "Withdrawn: the task it was asking about has failed.": "Ditarik balik: tugasan yang ditanyakannya telah gagal.",
  "Withdrawn: the task it was asking about was stopped.": "Ditarik balik: tugasan yang ditanyakannya telah dihentikan.",
  "Withdrawn: the task it was asking about was cancelled.": "Ditarik balik: tugasan yang ditanyakannya telah dibatalkan.",
  'Decided. Nothing left to press here.': 'Sudah diputuskan. Tiada apa-apa lagi untuk ditekan di sini.',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': 'Ditarik balik: ejen mengubah cadangannya dan bertanya semula tentang cadangan yang baharu.',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': 'Ditarik balik: syarikat tidak lagi berada di peringkat yang hendak diubah oleh cadangan ini.',
  'Withdrawn: it was already decided in the app.': 'Ditarik balik: sudah diputuskan dalam apl.',
  'Withdrawn. Nothing left to press here.': 'Ditarik balik. Tiada apa-apa lagi untuk ditekan di sini.',
  'company': 'syarikat',
  'Work stopped: the {account} account is out of tokens': 'Kerja terhenti: token akaun {account} sudah habis',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': '“{work}” terhenti kerana akaun {account} telah menggunakan {spent} daripada {max} token. Naikkan silingnya di Wang, kemudian buka tugasan itu dan tekan Teruskan: ia bersambung dari tempat ia terhenti.',
  'Withdrawn: you continued the task it was about.': 'Ditarik: anda telah meneruskan tugasan yang berkaitan.',
  'Withdrawn: the budget had room again, and the work went on by itself.': 'Ditarik: bajet sudah ada ruang semula, dan kerja diteruskan dengan sendirinya.',
  'Broke its contract': 'Melanggar kontraknya',
  'Refused by a policy': 'Ditolak oleh dasar',
  'Out of budget': 'Kehabisan belanjawan',
  'Handed on too many times': 'Diserahkan terlalu banyak kali',
  'Missed its deadline': 'Terlepas tarikh akhirnya',
  'Its result did not check out': 'Hasilnya gagal disahkan',
  'A capability it needs is down': 'Keupayaan yang diperlukannya tidak berfungsi',
  'No runtime could take it': 'Tiada masa jalan yang dapat mengambilnya',
  'Went in a circle': 'Berpusing dalam bulatan',
  'Split into too many sub-tasks': 'Dipecahkan kepada terlalu banyak subtugasan',
  'Wrote more than its role allows one run': 'Menulis lebih banyak daripada yang dibenarkan oleh peranannya bagi satu larian',
  'Your approval was not given in time': 'Kelulusan anda tidak diberikan dalam masa',
  'Stopped by you': 'Dihentikan oleh anda',
  'Cancelled by you': 'Dibatalkan oleh anda',
  'The company is frozen': 'Syarikat dibekukan',
  'Its record did not match on replay': 'Rekodnya tidak sepadan semasa dimainkan semula',
  'It kept stopping the worker running it': 'Ia berulang kali menghentikan pekerja yang menjalankannya',
  'Not done': 'Tidak dibuat',
  'Task failed': 'Tugasan gagal',
  'Digest for {day}': 'Ringkasan {day}',
  'Spent: {amount}': 'Dibelanjakan: {amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': 'Kerja: {done} selesai, {failed} gagal, {stopped} terhenti',
  'Inbox: {open} waiting (incidents: {incidents})': 'Peti masuk: {open} menunggu (insiden: {incidents})',
  'Stopped ({count}): {reason}': 'Terhenti ({count}): {reason}',
  'Start an ad campaign': 'Mulakan kempen iklan',
  'Block time on the calendar': 'Khaskan masa dalam kalendar',
  'Read the calendar': 'Baca kalendar',
  'Run code': 'Jalankan kod',
  'Add a note to a customer': 'Tambah nota pada rekod pelanggan',
  'Read customer records': 'Baca rekod pelanggan',
  'Release to the live site': 'Lancarkan ke laman web langsung',
  'Release to the test site': 'Lancarkan ke laman web ujian',
  'Change a domain\'s nameservers': 'Tukar pelayan nama domain',
  'Read a domain\'s records': 'Baca rekod domain',
  'Change a domain\'s record': 'Tukar rekod domain',
  'Write a document': 'Tulis dokumen',
  'Sign a document': 'Tandatangani dokumen',
  'Buy a domain': 'Beli domain',
  'Transfer a domain': 'Pindahkan domain',
  'Draft an email': 'Buat draf e-mel',
  'Send an email': 'Hantar e-mel',
  'List files': 'Senaraikan fail',
  'Read a file': 'Baca fail',
  'Describe a picture': 'Terangkan gambar',
  'Calculate in Python': 'Kira dengan Python',
  'Transfer money': 'Pindahkan wang',
  'Propose a goal change': 'Cadangkan perubahan matlamat',
  'Make a picture': 'Buat gambar',
  'Issue an invoice': 'Keluarkan invois',
  'Pay an invoice': 'Bayar invois',
  'Read the books': 'Baca buku akaun',
  'Read the mailbox': 'Baca peti mel',
  'Search what the company knows': 'Cari apa yang diketahui syarikat',
  'Record a measure': 'Rekod ukuran',
  'Read product numbers': 'Baca angka produk',
  'Ask you a question': 'Tanya soalan kepada anda',
  'Write down a plan': 'Catat rancangan',
  'Delete a record': 'Padam rekod',
  'Propose a code change': 'Cadangkan perubahan kod',
  'Read the code': 'Baca kod',
  'Destroy a server': 'Musnahkan pelayan',
  'Read a skill': 'Baca kemahiran',
  'Publish a post': 'Terbitkan hantaran',
  'Read text aloud': 'Bacakan teks dengan kuat',
  'Turn speech into text': 'Tukar pertuturan kepada teks',
  'Propose a new stage': 'Cadangkan peringkat baharu',
  'Wait for work handed on': 'Tunggu kerja yang diserahkan',
  'Hand work to another role': 'Serahkan kerja kepada peranan lain',
  'File a ticket': 'Buka tiket',
  'List tickets': 'Senaraikan tiket',
  'Check a service is up': 'Semak sama ada perkhidmatan berfungsi',
  'Read a web page': 'Baca halaman web',
  'Open a web page': 'Buka halaman web',
  'Search the web': 'Cari di web',
  'no stage': 'tiada peringkat',
  'Explore': 'Teroka',
  'Validate': 'Sahkan',
  'Build': 'Bina',
  'Launch': 'Lancarkan',
  'Grow': 'Kembangkan',
  'Wind down': 'Hentikan operasi',
  'Monthly budget reached; the company is paused': 'Belanjawan bulanan telah habis; syarikat dijeda',
  '{spent} of {limit} spent since {since}. No new task will start and no external action will run until you raise the ceiling or allow spending past it for a while, under Money.': '{spent} daripada {limit} dibelanjakan sejak {since}. Tiada tugasan baharu akan bermula dan tiada tindakan luaran akan dijalankan sehingga anda menaikkan had atau membenarkan perbelanjaan melebihinya buat sementara, di Wang.',
  'Monthly budget is 80% spent': 'Belanjawan bulanan telah 80% dibelanjakan',
  '{spent} of {limit} spent since {since}. At 100% the company pauses.': '{spent} daripada {limit} dibelanjakan sejak {since}. Pada 100%, syarikat akan dijeda.',
  'Role {role} is paused for spending too fast': 'Peranan {role} dijeda kerana berbelanja terlalu cepat',
  '{role} spent {spent} in the last hour, {multiple} times its usual {usual} an hour. It is paused before the monthly ceiling is reached, so there is money left to work with once you have found out why. Resume it when you have.': '{role} membelanjakan {spent} dalam sejam yang lalu, {multiple} kali ganda kebiasaannya, iaitu {usual} sejam. Ia dijeda sebelum had bulanan dicapai, supaya masih ada wang untuk bekerja setelah anda mengetahui puncanya. Sambung semula peranan ini apabila anda sudah mengetahuinya.',
  'Daily model spend over threshold': 'Perbelanjaan model harian melebihi ambang',
  'Model spend today is {spent}, over the {limit} ceiling.': 'Perbelanjaan model hari ini ialah {spent}, melebihi had {limit}.',
  'Task failure rate over threshold': 'Kadar kegagalan tugasan melebihi ambang',
  '{failed} of {finished} tasks failed or stopped today ({rate}%), over the {limit}% threshold.': '{failed} daripada {finished} tugasan gagal atau terhenti hari ini ({rate}%), melebihi ambang {limit}%.',
  'Unusual number of policy refusals': 'Bilangan penolakan dasar yang luar biasa',
  'Actions refused by a policy today: {count}, over the threshold of {limit}. Either an agent is probing its limits or a policy is miscalibrated.': 'Tindakan yang ditolak oleh dasar hari ini: {count}, melebihi ambang {limit}. Sama ada ejen sedang menguji hadnya, atau ada dasar yang tidak ditetapkan dengan betul.',
  'External writes failed verification': 'Penulisan luaran gagal pengesahan',
  'Writes outside that reported success but read back differently: {count}. Something is changing them other than as asked.': 'Penulisan di luar yang melaporkan kejayaan tetapi berbeza apabila dibaca semula: {count}. Ada sesuatu yang mengubahnya, bukan seperti yang diminta.',
  'A capability stopped being usable': 'Satu keupayaan tidak lagi boleh digunakan',
  'Tasks that could not start today because a capability their role needs failed its check: {count}. A credential has probably expired or a quota is used up.': 'Tugasan yang tidak dapat bermula hari ini kerana keupayaan yang diperlukan oleh peranannya gagal semakan: {count}. Mungkin bukti kelayakan telah tamat tempoh atau kuota telah habis.',
  'A worker stopped reporting mid-run': 'Pekerja berhenti melapor di tengah larian',
  'Runs that stopped reporting and were taken back today: {count}. The work was picked up again; the tokens they had already spent were not recovered.': 'Larian yang berhenti melapor dan diambil semula hari ini: {count}. Kerja itu telah disambung semula; token yang telah dibelanjakan tidak dapat dipulihkan.',
  '{role} was refused {denials} times today, at the limit of {limit}. No task will run as this role until you lift the freeze. The usual causes are a missing capability grant, a policy the role\'s charter does not account for, or work the role was never equipped to do.': '{role} ditolak {denials} kali hari ini, mencapai had {limit}. Tiada tugasan akan berjalan sebagai peranan ini sehingga anda menyahbekukannya. Punca biasa ialah kebenaran keupayaan yang tiada, dasar yang tidak diambil kira oleh piagam peranan itu, atau kerja yang peranan itu tidak pernah dilengkapi untuk melakukannya.',
  'Role {role} is frozen after repeated denials': 'Peranan {role} dibekukan selepas ditolak berulang kali',
  'What it was refused: {capabilities}': 'Apa yang ditolak: {capabilities}',
  'It is waiting for an approval, and none is open, so nothing you can answer will move it.': 'Ia menunggu kelulusan, tetapi tiada yang terbuka, jadi tiada jawapan anda yang dapat menggerakkannya.',
  'It is waiting for a review, and none is pending, so no reviewer and no decision of yours will move it.': 'Ia menunggu semakan, tetapi tiada yang belum selesai, jadi tiada penyemak dan tiada keputusan anda yang dapat menggerakkannya.',
  'It is parked until a window reopens, and the window never does.': 'Ia ditangguhkan sehingga satu tetingkap waktu dibuka semula, dan tetingkap itu tidak pernah dibuka.',
  'A task is waiting on nothing': 'Satu tugasan menunggu sesuatu yang tiada',
  '"{task}" has been waiting since {since}. {why} Approve to run it again from where it stopped, or deny to cancel it.': '“{task}” telah menunggu sejak {since}. {why} Luluskan untuk menjalankannya semula dari tempat ia terhenti, atau Tolak untuk membatalkannya.',
  'A task keeps stopping the worker running it': 'Satu tugasan terus menghentikan pekerja yang menjalankannya',
  '"{task}" lost its worker {lost} times: each time the worker running it stopped answering before the work finished. What it had done is kept. It is halted so it cannot take another worker down; run it again once the cause is found, or cancel it.': '“{task}” kehilangan pekerjanya {lost} kali: setiap kali, pekerja yang menjalankannya berhenti menjawab sebelum kerja selesai. Apa yang telah dibuatnya disimpan. Ia dihentikan supaya tidak menjatuhkan pekerja lain; jalankannya semula setelah puncanya ditemui, atau batalkannya.',
  '{services} stayed unreachable, and the work that needs it stopped': '{services} kekal tidak dapat dihubungi, dan kerja yang memerlukannya terhenti',
  'The task waited about {minutes} minutes, looking again each time, and has stopped. Once the service answers, run it again.': 'Tugasan ini menunggu kira-kira {minutes} minit, menyemak semula setiap kali, dan kini terhenti. Setelah perkhidmatan itu menjawab, jalankannya semula.',
  'It was tried {tries} times over about {minutes} minutes.': 'Ia dicuba {tries} kali dalam tempoh kira-kira {minutes} minit.',
  'This role can take actions that cannot be undone, so the run was not silently moved to a different model.': 'Peranan ini boleh mengambil tindakan yang tidak boleh diundur, jadi larian ini tidak dipindahkan secara senyap kepada model lain.',
  'No fallback model is left for this role.': 'Tiada lagi model sandaran untuk peranan ini.',
  'Model {model} failed and the run was not moved': 'Model {model} gagal dan larian tidak dipindahkan',
  'External write failed verification': 'Penulisan luaran gagal pengesahan',
  'The task wrote to an outside service and read it back, and what it read did not match. Look at the place it wrote to before you run it again: the write may have happened.': 'Tugasan ini menulis kepada perkhidmatan luar dan membacanya semula, dan apa yang dibacanya tidak sepadan. Semak tempat ia menulis itu sebelum anda menjalankannya semula: penulisan itu mungkin sudah berlaku.',
  'Review deadlocked after {rounds} revisions: {capability}': 'Semakan buntu selepas {rounds} pindaan: {capability}',
  'The role and its reviewer did not agree on {capability}.': 'Peranan itu dan penyemaknya tidak bersetuju tentang {capability}.',
  'The reviewer\'s last note: {note}': 'Nota terakhir penyemak: {note}',
  'The reviewer left no note.': 'Penyemak tidak meninggalkan nota.',
  'What it was judged against: {criteria}': 'Kriteria yang digunakan untuk menilainya: {criteria}',
  'Review produced no usable verdict: {capability}': 'Semakan tidak menghasilkan keputusan yang boleh digunakan: {capability}',
  'The reviewing task ended without a decision that could be read. The proposed action is still blocked and needs your judgement.': 'Tugasan semakan berakhir tanpa keputusan yang boleh dibaca. Tindakan yang dicadangkan masih disekat dan memerlukan pertimbangan anda.',
  'another stage': 'peringkat lain',
  'Either answer only closes this: the company stays in the {stage} stage.': 'Mana-mana jawapan hanya menutup perkara ini: syarikat kekal di peringkat {stage}.',
  'Either answer only closes this: the company stays without a stage.': 'Mana-mana jawapan hanya menutup perkara ini: syarikat kekal tanpa peringkat.',
  'To move it anyway, set the stage on the Overview.': 'Untuk memindahkannya juga, tetapkan peringkat di Gambaran keseluruhan.',
  '{reviewer} stopped a proposal to move the company from {from} to {to}': '{reviewer} menghentikan cadangan untuk memindahkan syarikat dari {from} ke {to}',
  '{reviewer} reviewed it before you and stopped it:': '{reviewer} menyemaknya sebelum anda dan menghentikannya:',
  'No reason was given.': 'Tiada sebab diberikan.',
  'What was proposed:': 'Apa yang dicadangkan:',
  'The company stays in the {stage} stage.': 'Syarikat kekal di peringkat {stage}.',
  'The company stays without a stage.': 'Syarikat kekal tanpa peringkat.',
  'Move the company from {from} to {to}?': 'Pindahkan syarikat dari {from} ke {to}?',
  'Reviewed by {reviewer} before you:': 'Disemak oleh {reviewer} sebelum anda:',
  'The schedule "{schedule}" keeps producing the same result': 'Jadual “{schedule}” terus memberikan hasil yang sama',
  'Its last {runs} runs all ended with the same output. That is sometimes exactly right -- a report with nothing new to say -- and often a schedule that stopped doing anything useful while still being paid for. Deny to turn it off; approve to keep it running and not be asked about this result again.': '{runs} larian terakhirnya semua berakhir dengan hasil yang sama. Kadangkala itu memang betul — laporan yang tiada perkara baharu untuk disampaikan — dan selalunya itu jadual yang sudah tidak melakukan apa-apa yang berguna tetapi masih dibayar. Tolak untuk mematikannya; Luluskan untuk terus menjalankannya dan tidak ditanya lagi tentang hasil ini.',
  'Capability {capability} failed preflight': 'Keupayaan {capability} gagal semakan awal',
  'Work that needs it is stopped rather than started: fix the cause, then run that work again. The usual causes are an expired or wrongly scoped credential, a quota used up, or an address that is wrong.': 'Kerja yang memerlukannya dihentikan dan bukan dimulakan: betulkan puncanya, kemudian jalankan semula kerja itu. Punca biasa ialah bukti kelayakan yang tamat tempoh atau salah skop, kuota yang telah habis, atau alamat yang salah.',
  'Batch guard stopped {capability}': 'Kawalan tindakan pukal menghentikan {capability}',
  'It did not match the plan its run recorded. Nothing was sent, and no service was called.': 'Ia tidak sepadan dengan rancangan yang direkodkan oleh lariannya. Tiada apa-apa dihantar, dan tiada perkhidmatan dipanggil.',
  '{role} was asked first and has had {minutes} minutes.': '{role} ditanya dahulu dan telah diberi {minutes} minit.',
  '{role} is not a role in this company, so this came to you at once.': '{role} bukan peranan dalam syarikat ini, jadi perkara ini terus sampai kepada anda.',
  '{role} could not be given this: the company has no active goal or project to hang it from.': 'Perkara ini tidak dapat diberikan kepada {role}: syarikat tiada matlamat atau projek aktif untuk meletakkannya.',
  '{role} could not be given this ({record}), so this came to you at once.': 'Perkara ini tidak dapat diberikan kepada {role} ({record}), jadi ia terus sampai kepada anda.',
  '{role} stopped without an account of what it did ({why}).': '{role} berhenti tanpa laporan tentang apa yang dibuatnya ({why}).',
  '{role} finished without an account of what it did.': '{role} selesai tanpa laporan tentang apa yang dibuatnya.',
  '{role} failed without an account of what it did.': '{role} gagal tanpa laporan tentang apa yang dibuatnya.',
  '{role} was stopped without an account of what it did.': '{role} dihentikan tanpa laporan tentang apa yang dibuatnya.',
  'Proposed change to the {kind} "{goal}"': 'Cadangan perubahan pada {kind} “{goal}”',
  'Currently: {statement}': 'Sekarang: {statement}',
  'Currently: {statement} ({status})': 'Sekarang: {statement} ({status})',
  'Proposed: {statement}': 'Dicadangkan: {statement}',
  'Proposed status: {status}': 'Status yang dicadangkan: {status}',
  'Reason given: {reason}': 'Sebab yang diberikan: {reason}',
  'Record an entry in the books': 'Merekod catatan dalam buku',
  'Record a customer or a deal': 'Rekod pelanggan atau urus niaga',
  'Not sent on its own: {reason}': 'Tidak dihantar secara automatik: {reason}',
  'it answers a conversation other than the one this work began with': 'balasan ini untuk perbualan lain, bukan yang memulakan kerja ini',
  'it named no passage of a document for customers': 'balasan ini tidak menyebut mana-mana bahagian dokumen untuk pelanggan',
  'it answers from a document not marked for customers': 'balasan ini menjawab daripada dokumen yang tidak ditanda untuk pelanggan',
  'it says a figure the documents and the customer did not: {detail}': 'balasan ini menyebut angka yang tiada dalam dokumen mahupun mesej pelanggan: {detail}',
  'it gives an address or link the documents and the customer did not: {detail}': 'balasan ini memberi alamat atau pautan yang tiada dalam dokumen mahupun mesej pelanggan: {detail}',
  'there have been six answers on its own in this conversation in the last hour': 'sudah ada enam jawapan automatik dalam perbualan ini dalam sejam yang lalu',
  'the check found it is about a refund': 'semakan mendapati ia mengenai bayaran balik',
  'the check found it offers a price or terms of its own': 'semakan mendapati balasan ini menawarkan harga atau syarat sendiri',
  'the check found it answers a serious complaint': 'semakan mendapati balasan ini menjawab aduan serius',
  'the check found it touches the law': 'semakan mendapati balasan ini menyentuh undang-undang',
  'the check found it gives or asks for personal data': 'semakan mendapati balasan ini memberi atau meminta data peribadi',
  'the check found it promises something the documents do not': 'semakan mendapati balasan ini menjanjikan sesuatu yang tiada dalam dokumen',
  'the check could not judge it': 'semakan tidak dapat menilainya',
  'the check found something in it the documents do not say': 'semakan menemui sesuatu yang tidak dinyatakan dalam dokumen',
  '{role} proposes the schedule {name}': '{role} mencadangkan jadual {name}',
  'Each run: {instruction}': 'Setiap kali berjalan: {instruction}',
  'Done by: {role}': 'Dilakukan oleh: {role}',
  'When: {cron} ({timezone}); the next runs are {runs}': 'Bila: {cron} ({timezone}); larian seterusnya {runs}',
  'Approving it makes the schedule and starts it; it can be turned off or changed under Team, Schedules.': 'Meluluskannya membuat jadual itu dan memulakannya; ia boleh dimatikan atau diubah di Pasukan, Jadual.',
  'No schedule is made.': 'Tiada jadual dibuat.',
  'Propose a schedule': 'Cadangkan jadual',
  'Approving it changes the goal; until then the work carries on under the goal as it is.': 'Meluluskannya akan mengubah matlamat; sehingga itu kerja diteruskan di bawah matlamat yang sedia ada.',
  'The goal stays as it is.': 'Matlamat kekal seperti sedia ada.',
  'mission': 'misi',
  'objective': 'objektif',
  'key result': 'hasil utama',
  'Active': 'Aktif',
  'Met': 'Tercapai',
  'Abandoned': 'Ditinggalkan',
  'This work asked for it at tier {tier}, and policy {policies} requires your approval.': 'Kerja ini memintanya pada tahap {tier}, dan dasar {policies} memerlukan kelulusan anda.',
  'This work asked for it at tier {tier}, and the task began with content from outside the company.': 'Kerja ini memintanya pada tahap {tier}, dan tugasan ini bermula dengan kandungan dari luar syarikat.',
  'This work asked for it at tier {tier}, and the work read content from outside the company before asking.': 'Kerja ini memintanya pada tahap {tier}, dan kerja ini membaca kandungan dari luar syarikat sebelum meminta.',
  'This work asked for it at tier {tier}, after the work read content from outside the company, and the guardian asked you first: {reason}': 'Kerja ini memintanya pada tahap {tier}, selepas kerja ini membaca kandungan dari luar syarikat, dan penjaga bertanya kepada anda dahulu: {reason}',
  'it doubted this call before, and you allowed it once': 'ia pernah meragui panggilan ini, dan anda membenarkannya sekali',
  'This work asked for it at tier {tier}, which cannot be reversed.': 'Kerja ini memintanya pada tahap {tier}, yang tidak boleh diundur.',
  'You approved this once already, and the worker carrying it out stopped before it could say whether it happened: it may already have happened. Check before approving it again.': 'Anda sudah meluluskan ini sekali, dan pekerja yang melaksanakannya berhenti sebelum sempat memberitahu sama ada ia berlaku: ia mungkin sudah berlaku. Semak dahulu sebelum meluluskannya semula.',
  'What this is for — {goals}': 'Tujuannya — {goals}',
  'The task halts and no external change is made.': 'Tugasan terhenti dan tiada perubahan luaran dibuat.',
  'Scored against {total} references: {passed} passed, {failed} failed.': 'Dinilai berdasarkan {total} rujukan: {passed} lulus, {failed} gagal.',
  'This role has fewer than {minimum} accepted references, so the change is unscored. That is not the same as passing.': 'Peranan ini mempunyai kurang daripada {minimum} rujukan yang diterima, jadi perubahan ini belum dinilai. Itu tidak sama dengan lulus.',
  'The role keeps working exactly as it does now.': 'Peranan ini terus bekerja sama seperti sekarang.',
  '{role} asks: {question}': '{role} bertanya: {question}',
  'The run did not say more than the question.': 'Larian tidak menyatakan apa-apa selain soalan itu.',
  'The task is stopped, and nothing it was going to do happens.': 'Tugasan dihentikan, dan apa yang akan dibuatnya tidak berlaku.',
  'You proposed it.': 'Anda yang mencadangkannya.',
  'It came with a bundle.': 'Ia dibawa oleh satu pakej.',
  'An agent proposed it.': 'Satu ejen mencadangkannya.',
  'It was learned from the company\'s work.': 'Ia dipelajari daripada kerja syarikat.',
  'Skill "{skill}", version {version}': 'Kemahiran “{skill}”, versi {version}',
  'The reviewer approved it: {note}': 'Penyemak meluluskannya: {note}',
  'The reviewer approved it.': 'Penyemak meluluskannya.',
  'Nothing changes; the current version of the skill stays in force.': 'Tiada apa-apa yang berubah; versi semasa kemahiran ini kekal berkuat kuasa.',
  'Skills the bundle "{bundle}" brings: {count}': 'Kemahiran yang dibawa oleh pakej “{bundle}”: {count}',
  'The reviewer read them all and approved these:': 'Penyemak membaca kesemuanya dan meluluskan yang berikut:',
  'It turned these down, and they stay off:': 'Ia menolak yang berikut, dan kemahiran itu kekal dimatikan:',
  'Approve to switch them all on, or deny to turn them all down. To decide one at a time, open the Skills page.': 'Luluskan untuk menghidupkan kesemuanya, atau Tolak untuk menolak kesemuanya. Untuk membuat keputusan satu demi satu, buka halaman Kemahiran.',
  'Nothing changes; none of these skills is switched on.': 'Tiada apa-apa yang berubah; tiada satu pun kemahiran ini dihidupkan.',
  "I am {ceo}, and I run {company} for you. I know what it is for: “{mission}” Two things before we start: how much may it spend in a month? And what should its first piece of work be -- or shall I suggest one, and the team it would take?":
    "Saya {ceo}, dan saya menguruskan {company} untuk anda. Saya sudah tahu untuk apa syarikat ini: “{mission}” Dua perkara sebelum kita mula: berapakah yang boleh dibelanjakannya dalam sebulan? Dan apakah kerja pertamanya — atau patutkah saya cadangkan satu, bersama pasukan yang diperlukan?",
  'I am {ceo}, and I run {company} for you. Three things before we start: what does {company} sell, and to whom? How much may it spend in a month? And what should its first piece of work be -- or shall I suggest one?': 'Saya {ceo}, dan saya menguruskan {company} untuk anda. Tiga perkara sebelum kita mula: apakah yang dijual oleh {company}, dan kepada siapa? Berapakah yang boleh dibelanjakannya dalam sebulan? Dan apakah kerja pertamanya — atau patutkah saya cadangkan satu?',
  'Read a customer conversation': 'Baca perbualan pelanggan',
  'Reply to a customer': 'Balas pelanggan',
  'Read a page in the browser': 'Baca halaman dalam pelayar',
  'Fill in a page in the browser': 'Isi halaman dalam pelayar',
  'Ask you to take over the browser': 'Meminta anda mengambil alih pelayar',
  '{host} refused the model key ({status}), so nothing that needs the model can run. Open Settings, This deployment, Model, paste a key that works, test it and save.':
    '{host} menolak kunci model ({status}), jadi tiada kerja yang memerlukan model dapat berjalan. Buka Tetapan, Pemasangan ini, Model, tampal kunci yang berfungsi, uji dan simpan.',
  '{host} refused the model key, and work is waiting': '{host} menolak kunci model, dan kerja sedang menunggu',
  'What is waiting for the model carries on by itself once a key that works is in use.':
    'Kerja yang menunggu model akan diteruskan sendiri sebaik sahaja kunci yang berfungsi digunakan.',
  'A task ended before it was done: {task}':
    'Satu tugas berakhir sebelum siap: {task}',
  'It ended as: {reason}. No other card was raised for it, so it is here rather than silent.':
    'Ia berakhir sebagai: {reason}. Tiada kad lain dibuat untuknya, jadi ia ada di sini dan bukan senyap.',
  'Where its measures stand, as the platform reads them:':
    'Kedudukan ukurannya, seperti yang dibaca platform:',
  '{name}: no value recorded yet, against a target of {target}.':
    '{name}: belum ada nilai, dengan sasaran {target}.',
  '{name}: {value} against a target of {target}, read back from its source.':
    '{name}: {value} dengan sasaran {target}, dibaca semula daripada puncanya.',
  '{name}: {value} against a target of {target}, reported and not checked.':
    '{name}: {value} dengan sasaran {target}, dilaporkan dan belum disemak.',
  'Look at it again later': 'Lihat semula kemudian',
  "Deliver what this company sells, reliably and without surprising its owner.":
    "Menyampaikan apa yang dijual oleh syarikat ini dengan boleh dipercayai dan tanpa mengejutkan pemiliknya.",
  "Ship the work the company has promised, on time and verified.":
    "Menyiapkan kerja yang telah dijanjikan syarikat, tepat pada masanya dan telah disahkan.",
  "Keep the company solvent, answerable and running without daily attention.":
    "Memastikan kewangan syarikat kukuh, boleh dipertanggungjawabkan dan berjalan tanpa perhatian harian.",
  "Since we last spoke:":
    "Sejak kali terakhir kita berbual:",
  "More finished: {count}":
    "Lain-lain selesai: {count}",
  "Waiting for you: {count}":
    "Menunggu anda: {count}",
  'This is the third time in a day, so it does not go on by itself.':
    'Ini kali ketiga dalam sehari, jadi ia tidak diteruskan sendiri.',
  'Invoice {number} needs you: {customer} has not paid':
    'Invois {number} memerlukan anda: {customer} belum membayar',
  '{customer} still owes {amount} on invoice {number}, due {due}, after the last reminder. The platform has stopped writing to them. What comes next is yours: a call, a final notice, or letting it go.':
    '{customer} masih berhutang {amount} pada invois {number}, tarikh akhir {due}, selepas peringatan terakhir. Platform telah berhenti menulis kepada mereka. Langkah seterusnya milik anda: panggilan, notis akhir, atau melepaskannya.',
  'Invoice {number} ({amount}, {customer}) has been overdue since {due}, and no reminder was ever sent, so the platform did not send a form letter this late. Follow it up yourself, or tell the CEO what you want done.':
    'Invois {number} ({amount}, {customer}) lewat tempoh sejak {due}, dan tiada peringatan pernah dihantar, jadi platform tidak menghantar surat templat sebegini lewat. Susuli sendiri, atau beritahu CEO apa yang anda mahu dilakukan.',
  'Invoice {number} ({amount}, {customer}) has been overdue since {due}, and there is no email address to send a reminder to. Add one to the customer, or follow it up yourself.':
    'Invois {number} ({amount}, {customer}) lewat tempoh sejak {due}, dan tiada alamat e-mel untuk menghantar peringatan. Tambahkan pada pelanggan, atau susuli sendiri.',
  'Nobody is set to remind customers about overdue invoices':
    'Tiada sesiapa ditetapkan untuk mengingatkan pelanggan tentang invois lewat tempoh',
  'Reminded the customers of: {invoices}.':
    'Pelanggan diingatkan tentang: {invoices}.',
  'No reminder was due.':
    'Tiada peringatan yang perlu dihantar.',
  'Remind a customer about an invoice':
    'Mengingatkan pelanggan tentang sebuah invois',
  'Some invoices are past their due date, and no role can send the reminders. Turn on automatic reminders under Books, Invoices: the company then sends them on the days you set.':
    'Beberapa invois sudah melepasi tarikh akhir, dan tiada peranan yang boleh menghantar peringatan. Hidupkan peringatan automatik di Buku akaun, Invois: syarikat kemudian menghantarnya pada hari yang anda tetapkan.',
  'Reminders for overdue invoices need a mailbox to send them from. Give this division its mailbox.':
    'Peringatan untuk invois lewat tempoh memerlukan peti mel untuk menghantarnya. Berikan peti mel bahagian ini.',
  'Remind the customers whose invoices are overdue':
    'Mengingatkan pelanggan yang invoisnya lewat tempoh',
  'each customer whose next reminder is due has been written to once':
    'setiap pelanggan yang peringatan seterusnya sudah tiba masa telah dihantar sekali',
};
