/**
 * Nederlands: what the platform itself says to the owner outside the console
 * (src/owner/say.ts), keyed by its English.
 *
 * The words are the console's (console/src/locales/nl.ts): the owner is
 * "je/jij"; Goedkeuren, Afwijzen and Vraag stellen on the buttons; “Deze
 * installatie, Tools, Spraakherkenning” for the screens it points at.
 * WhatsApp cuts a reply button's title at 20 characters and a list row's at
 * 24, so those stay short.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'Incident: {title}',
  'Done: {goal}': 'Klaar: {goal}',
  'Stopped before finishing: {goal}': 'Gestopt voor het klaar was: {goal}',
  'Not done: {goal}': 'Niet gedaan: {goal}',
  'Why: {reason}': 'Reden: {reason}',
  'a task': 'een taak',
  'Approval needed: {title}': 'Goedkeuring nodig: {title}',
  '{summary} — if denied: {consequence}': '{summary} – bij afwijzing: {consequence}',
  '{role} asks:': '{role} vraagt:',
  'If denied:': 'Bij afwijzing:',
  'Expires:': 'Verloopt:',
  'This one is decided in the app.': 'Hierover wordt in de app beslist.',
  'Open in PALUGADA': 'Openen in PALUGADA',
  'Approve': 'Goedkeuren',
  'Deny': 'Afwijzen',
  'Ask': 'Vraag stellen',
  'Approved. Nothing left to press here.': 'Goedgekeurd. Hier valt niets meer aan te tikken.',
  'Denied. Nothing left to press here.': 'Afgewezen. Hier valt niets meer aan te tikken.',
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    'Onbeantwoord verlopen. Stilte is een weigering, dus er is niets gedaan.',
  'This bot only answers to its owner.': 'Deze bot antwoordt alleen zijn eigenaar.',
  'That one has to be approved in the app.': 'Dit moet in de app worden goedgekeurd.',
  'That could not be recorded.': 'Dat kon niet worden vastgelegd.',
  'That item no longer exists.': 'Dat item bestaat niet meer.',
  'What do you want to ask about "{title}"? Reply to this message.':
    'Wat wil je vragen over “{title}”? Antwoord op dit bericht.',
  'Your question': 'Je vraag',
  'Type your question as a reply.': 'Typ je vraag als antwoord op dit bericht.',
  'Asked. The answer will be on the item in the app.': 'Gevraagd. Het antwoord verschijnt bij het item in de app.',
  'Answer': 'Antwoorden',
  'Answer in words': 'Met eigen woorden',
  'That choice is not on this question.': 'Die keuze hoort niet bij deze vraag.',
  'Chosen: {choice}.': 'Gekozen: {choice}.',
  'Stop the task': 'Taak stoppen',
  'Your answer to "{question}"? Reply to this message.': 'Je antwoord op “{question}”? Antwoord op dit bericht.',
  'Your answer': 'Je antwoord',
  'Type your answer as a reply.': 'Typ je antwoord als reactie op dit bericht.',
  'Answered. The task carries on with it.': 'Beantwoord. De taak gaat ermee verder.',
  'That is too long for one question; keep it under {max} characters.':
    'Dat is te lang voor één vraag; blijf onder de {max} tekens.',
  '[a key, not kept]': '[een sleutel, niet bewaard]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    'Dat lijkt op een sleutel, dus ik heb hem niet bewaard en nergens heen gestuurd. Sleutels horen in het verzegelde veld op een kaart, of op hun pagina onder “Deze installatie”: vertel me waar hij voor is en ik leg de kaart aan je voor.',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'Er is nog geen model ingesteld, dus ik kan niet denken. Kies er een onder “Deze installatie, Model”; dan kan ik met al het andere helpen.',
  'The model did not answer: {reason}': 'Het model antwoordde niet: {reason}',
  'Here is what I propose.': 'Dit stel ik voor.',
  'I have nothing to add.': 'Ik heb niets toe te voegen.',
  '{name}, CEO of {company}': '{name}, CEO van {company}',
  'That could not be answered: {reason}': 'Daar kon geen antwoord op worden gegeven: {reason}',
  'I read text and voice notes.': 'Ik lees tekst en spraakberichten.',
  'Now talking to {name}.': 'Je praat nu met {name}.',
  'Choose whom to talk to.': 'Kies met wie je wilt praten.',
  'Choose whom to talk to': 'Kiezen met wie je praat',
  'Talk to PALUGADA about the whole deployment': 'Met PALUGADA praten over de hele installatie',
  'Who you are talking to, and how': 'Met wie je praat, en hoe',
  'Stopped.': 'Gestopt.',
  'Write here to talk to {name}.': 'Schrijf hier om met {name} te praten.',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    'Je praat met {name}. Schrijf, of stuur een spraakbericht. Met /ceo kies je met wie je praat; met /palugada praat je met PALUGADA over de hele installatie.',
  'You said: "{words}"': 'Je zei: “{words}”',
  'in the app': 'in de app',
  'Apply: {summary}': 'Toepassen: {summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    'Er luistert nog niets naar spraak: kies in de app een aanbieder onder “Deze installatie, Tools, Spraakherkenning”.',
  'That recording is too long; keep a voice note under {max} MB.': 'Die opname is te lang; houd een spraakbericht onder de {max} MB.',
  'I could not make out any words in that.': 'Ik kon daar geen woorden in verstaan.',
  'Done: {summary}': 'Gedaan: {summary}',
  'That one is applied in the app.': 'Deze kaart wordt in de app toegepast.',
  'That card no longer exists.': 'Die kaart bestaat niet meer.',
  'That card was already applied.': 'Die kaart is al toegepast.',
  'That card was dismissed.': 'Die kaart is genegeerd.',
  'That card failed when it was applied.': 'Die kaart is mislukt bij het toepassen.',
  'That could not be done: {reason}': 'Dat kon niet worden gedaan: {reason}',
  'Choose': 'Kiezen',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    'Wat wil je vragen over “{title}”? Antwoord op dit bericht met je vraag.',
  'Your answer to "{question}"? Reply to this message with your answer.':
    'Je antwoord op “{question}”? Reageer op dit bericht met je antwoord.',
  'I read text messages here.': 'Hier lees ik tekstberichten.',
  'Apply one of these here:': 'Pas hier een van deze toe:',
  'Apply {number}': '{number} toepassen',
  'Signed in to {provider} for the {alias} key': 'Ingelogd bij {provider} voor de sleutel {alias}',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'Ga terug naar PALUGADA: de afdeling heeft deze sleutel nu, en hij wordt vernieuwd voordat hij verloopt. Je kunt dit tabblad sluiten.',
  'Signed in to {name}': 'Ingelogd bij {name}',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'Ga terug naar PALUGADA om te kiezen welke tools rollen mogen gebruiken. Je kunt dit tabblad sluiten.',
  'Not signed in': 'Niet ingelogd',
  'Recorded: approved.': 'Vastgelegd: goedgekeurd.',
  'Recorded: denied.': 'Vastgelegd: afgewezen.',
  'Recorded: asked.': 'Vastgelegd: vraag gesteld.',
  'Asked. Nothing left to press here.': 'Vraag gesteld. Hier valt niets meer aan te tikken.',
  'Withdrawn: the task it was asking about has finished.': 'Ingetrokken: de taak waar het om ging, is afgerond.',
  'Withdrawn: the task it was asking about has failed.': 'Ingetrokken: de taak waar het om ging, is mislukt.',
  'Withdrawn: the task it was asking about was stopped.': 'Ingetrokken: de taak waar het om ging, is stilgezet.',
  'Withdrawn: the task it was asking about was cancelled.': 'Ingetrokken: de taak waar het om ging, is geannuleerd.',
  'Decided. Nothing left to press here.': 'Beslist. Hier valt niets meer aan te tikken.',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': 'Ingetrokken: de agent stelt nu iets anders voor en heeft daar opnieuw om gevraagd.',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': 'Ingetrokken: het bedrijf zit niet meer in de fase waaruit dit voorstel het zou verplaatsen.',
  'Withdrawn: it was already decided in the app.': 'Ingetrokken: hierover is al in de app beslist.',
  'Withdrawn. Nothing left to press here.': 'Ingetrokken. Hier valt niets meer aan te tikken.',
  'company': 'bedrijf',
  'Work stopped: the {account} account is out of tokens': 'Werk gestopt: het account {account} heeft geen tokens meer',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': '‘{work}’ is gestopt omdat het account {account} {spent} van zijn {max} tokens heeft gebruikt. Verhoog het plafond onder Financiën, open dan de taak en druk op Doorgaan: die gaat verder waar hij stopte.',
  'Withdrawn: you continued the task it was about.': 'Ingetrokken: u hebt de taak waar het over ging voortgezet.',
  'Broke its contract': 'Contract geschonden',
  'Refused by a policy': 'Geweigerd door een beleidsregel',
  'Out of budget': 'Budget op',
  'Handed on too many times': 'Te vaak doorgegeven',
  'Missed its deadline': 'Deadline gemist',
  'Its result did not check out': 'Het resultaat doorstond de controle niet',
  'A capability it needs is down': 'Een mogelijkheid die ze nodig heeft, is uitgevallen',
  'No runtime could take it': 'Geen uitvoeromgeving kon haar oppakken',
  'Went in a circle': 'Draaide in een kringetje',
  'Split into too many sub-tasks': 'In te veel subtaken opgesplitst',
  'Wrote more than its role allows one run': 'Schreef meer dan haar rol per uitvoering toestaat',
  'Your approval was not given in time': 'Je goedkeuring kwam niet op tijd',
  'Stopped by you': 'Door jou gestopt',
  'Cancelled by you': 'Door jou geannuleerd',
  'The company is frozen': 'Het bedrijf is bevroren',
  'Its record did not match on replay': 'Het logboek kwam bij herhaling niet overeen',
  'It kept stopping the worker running it': 'Ze liet haar worker steeds vastlopen',
  'Not done': 'Niet gedaan',
  'Task failed': 'Taak mislukt',
  'Digest for {day}': 'Overzicht van {day}',
  'Spent: {amount}': 'Uitgegeven: {amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': 'Werk: {done} klaar, {failed} mislukt, {stopped} gestopt',
  'Inbox: {open} waiting (incidents: {incidents})': 'Inbox: {open} wachtend (incidenten: {incidents})',
  'Stopped ({count}): {reason}': 'Gestopt ({count}): {reason}',
  'Start an ad campaign': 'Advertentiecampagne starten',
  'Block time on the calendar': 'Tijd blokkeren in de agenda',
  'Read the calendar': 'Agenda lezen',
  'Run code': 'Code uitvoeren',
  'Add a note to a customer': 'Notitie bij een klant toevoegen',
  'Read customer records': 'Klantgegevens lezen',
  'Release to the live site': 'Op de livesite zetten',
  'Release to the test site': 'Op de testsite zetten',
  'Change a domain\'s nameservers': 'Nameservers van een domein wijzigen',
  'Read a domain\'s records': 'Domeinrecords lezen',
  'Change a domain\'s record': 'Domeinrecord wijzigen',
  'Write a document': 'Document schrijven',
  'Sign a document': 'Document ondertekenen',
  'Buy a domain': 'Domein kopen',
  'Transfer a domain': 'Domein overdragen',
  'Draft an email': 'E-mail als concept opstellen',
  'Send an email': 'E-mail versturen',
  'List files': 'Bestanden weergeven',
  'Read a file': 'Een bestand lezen',
  'Describe a picture': 'Een afbeelding beschrijven',
  'Calculate in Python': 'Berekenen met Python',
  'Transfer money': 'Geld overmaken',
  'Propose a goal change': 'Doelwijziging voorstellen',
  'Make a picture': 'Afbeelding maken',
  'Issue an invoice': 'Factuur uitschrijven',
  'Pay an invoice': 'Factuur betalen',
  'Read the books': 'Boekhouding lezen',
  'Read the mailbox': 'Mailbox lezen',
  'Search what the company knows': 'Kennis van het bedrijf doorzoeken',
  'Record a measure': 'Meetwaarde vastleggen',
  'Read product numbers': 'Productcijfers lezen',
  'Ask you a question': 'Jou een vraag stellen',
  'Write down a plan': 'Plan opschrijven',
  'Delete a record': 'Record verwijderen',
  'Propose a code change': 'Codewijziging voorstellen',
  'Read the code': 'Code lezen',
  'Destroy a server': 'Server vernietigen',
  'Read a skill': 'Vaardigheid lezen',
  'Publish a post': 'Bericht publiceren',
  'Read text aloud': 'Tekst voorlezen',
  'Turn speech into text': 'Spraak omzetten in tekst',
  'Propose a new stage': 'Nieuwe fase voorstellen',
  'Wait for work handed on': 'Wachten op doorgegeven werk',
  'Hand work to another role': 'Werk doorgeven aan een andere rol',
  'File a ticket': 'Ticket aanmaken',
  'List tickets': 'Tickets weergeven',
  'Check a service is up': 'Controleren of een dienst bereikbaar is',
  'Read a web page': 'Webpagina lezen',
  'Open a web page': 'Webpagina openen',
  'Search the web': 'Zoeken op het web',
  'no stage': 'geen fase',
  'Explore': 'Verkennen',
  'Validate': 'Valideren',
  'Build': 'Bouwen',
  'Launch': 'Lanceren',
  'Grow': 'Groeien',
  'Wind down': 'Afbouwen',
  'Monthly budget reached; the company is paused': 'Maandbudget bereikt; het bedrijf is gepauzeerd',
  '{spent} of {limit} spent since {since}. No new task will start and no external action will run until you raise the ceiling or allow spending past it for a while, under Money.': 'Sinds {since} is {spent} van {limit} uitgegeven. Er start geen nieuwe taak en er wordt geen externe actie uitgevoerd totdat je onder Financiën het plafond verhoogt of tijdelijk uitgaven boven het plafond toestaat.',
  'Monthly budget is 80% spent': '80% van het maandbudget is uitgegeven',
  '{spent} of {limit} spent since {since}. At 100% the company pauses.': 'Sinds {since} is {spent} van {limit} uitgegeven. Bij 100% wordt het bedrijf gepauzeerd.',
  'Role {role} is paused for spending too fast': 'Rol {role} is gepauzeerd wegens te snelle uitgaven',
  '{role} spent {spent} in the last hour, {multiple} times its usual {usual} an hour. It is paused before the monthly ceiling is reached, so there is money left to work with once you have found out why. Resume it when you have.': '{role} heeft het afgelopen uur {spent} uitgegeven, {multiple} keer zoveel als de gebruikelijke {usual} per uur. De rol is gepauzeerd voordat het maandplafond is bereikt, zodat er nog geld over is om mee te werken zodra je hebt uitgezocht waarom. Hervat haar als je dat weet.',
  'Daily model spend over threshold': 'Dagelijkse modeluitgaven boven de drempel',
  'Model spend today is {spent}, over the {limit} ceiling.': 'De modeluitgaven van vandaag zijn {spent}, boven het plafond van {limit}.',
  'Task failure rate over threshold': 'Foutpercentage van taken boven de drempel',
  '{failed} of {finished} tasks failed or stopped today ({rate}%), over the {limit}% threshold.': '{failed} van de {finished} taken zijn vandaag mislukt of gestopt ({rate}%), boven de drempel van {limit}%.',
  'Unusual number of policy refusals': 'Ongewoon veel weigeringen door beleidsregels',
  'Actions refused by a policy today: {count}, over the threshold of {limit}. Either an agent is probing its limits or a policy is miscalibrated.': 'Acties die vandaag door een beleidsregel zijn geweigerd: {count}, boven de drempel van {limit}. Óf een agent tast zijn grenzen af, óf een beleidsregel is verkeerd afgesteld.',
  'External writes failed verification': 'Externe schrijfacties kwamen niet door de controle',
  'Writes outside that reported success but read back differently: {count}. Something is changing them other than as asked.': 'Schrijfacties naar buiten die als geslaagd werden gemeld, maar bij teruglezen anders bleken: {count}. Iets wijzigt ze anders dan gevraagd.',
  'A capability stopped being usable': 'Een mogelijkheid is niet meer bruikbaar',
  'Tasks that could not start today because a capability their role needs failed its check: {count}. A credential has probably expired or a quota is used up.': 'Taken die vandaag niet konden starten omdat een mogelijkheid die hun rol nodig heeft niet door de controle kwam: {count}. Waarschijnlijk zijn inloggegevens verlopen of is een quotum op.',
  'A worker stopped reporting mid-run': 'Een worker meldde zich halverwege een uitvoering niet meer',
  'Runs that stopped reporting and were taken back today: {count}. The work was picked up again; the tokens they had already spent were not recovered.': 'Uitvoeringen die zich vandaag niet meer meldden en zijn teruggehaald: {count}. Het werk is weer opgepakt; de tokens die ze al hadden uitgegeven, zijn verloren.',
  '{role} was refused {denials} times today, at the limit of {limit}. No task will run as this role until you lift the freeze. The usual causes are a missing capability grant, a policy the role\'s charter does not account for, or work the role was never equipped to do.': '{role} is vandaag {denials} keer afgewezen en zit daarmee op de limiet van {limit}. Er draait geen taak als deze rol totdat je haar ontdooit. Gebruikelijke oorzaken zijn een ontbrekende machtiging voor een mogelijkheid, een beleidsregel waar het handvest van de rol geen rekening mee houdt, of werk waarvoor de rol nooit is toegerust.',
  'Role {role} is frozen after repeated denials': 'Rol {role} bevroren na herhaalde afwijzingen',
  'What it was refused: {capabilities}': 'Wat werd geweigerd: {capabilities}',
  'It is waiting for an approval, and none is open, so nothing you can answer will move it.': 'De taak wacht op een goedkeuring, maar er staat er geen open, dus geen enkel antwoord van jou brengt haar verder.',
  'It is waiting for a review, and none is pending, so no reviewer and no decision of yours will move it.': 'De taak wacht op een beoordeling, maar er staat er geen klaar, dus geen beoordelaar en geen beslissing van jou brengt haar verder.',
  'It is parked until a window reopens, and the window never does.': 'De taak is geparkeerd tot een tijdvenster weer opengaat, en dat venster gaat nooit open.',
  'A task is waiting on nothing': 'Een taak wacht op niets',
  '"{task}" has been waiting since {since}. {why} Approve to run it again from where it stopped, or deny to cancel it.': '“{task}” wacht sinds {since}. {why} Kies “Goedkeuren” om haar opnieuw uit te voeren vanaf waar ze stopte, of “Afwijzen” om haar te annuleren.',
  'A task keeps stopping the worker running it': 'Een taak laat haar worker steeds vastlopen',
  '"{task}" lost its worker {lost} times: each time the worker running it stopped answering before the work finished. What it had done is kept. It is halted so it cannot take another worker down; run it again once the cause is found, or cancel it.': '“{task}” is haar worker {lost} keer kwijtgeraakt: elke keer stopte de worker die haar uitvoerde met antwoorden voordat het werk klaar was. Wat ze al had gedaan, blijft bewaard. Ze is stilgezet zodat ze geen andere worker onderuit kan halen; voer haar opnieuw uit zodra de oorzaak is gevonden, of annuleer haar.',
  '{services} stayed unreachable, and the work that needs it stopped': 'Onbereikbaar gebleven: {services} – het werk dat ervan afhangt is gestopt',
  'The task waited about {minutes} minutes, looking again each time, and has stopped. Once the service answers, run it again.': 'De taak heeft ongeveer {minutes} min. gewacht, telkens opnieuw gekeken, en is gestopt. Voer haar opnieuw uit zodra de dienst antwoordt.',
  'It was tried {tries} times over about {minutes} minutes.': 'Het is {tries} keer geprobeerd in ongeveer {minutes} min.',
  'This role can take actions that cannot be undone, so the run was not silently moved to a different model.': 'Deze rol kan acties uitvoeren die niet ongedaan kunnen worden gemaakt, dus de uitvoering is niet stilletjes naar een ander model verplaatst.',
  'No fallback model is left for this role.': 'Er is geen uitwijkmodel meer over voor deze rol.',
  'Model {model} failed and the run was not moved': 'Model {model} is mislukt en de uitvoering is niet verplaatst',
  'External write failed verification': 'Externe schrijfactie kwam niet door de controle',
  'The task wrote to an outside service and read it back, and what it read did not match. Look at the place it wrote to before you run it again: the write may have happened.': 'De taak schreef naar een externe dienst en las het terug, en wat ze las kwam niet overeen. Kijk op de plek waar ze naartoe schreef voordat je de taak opnieuw uitvoert: de schrijfactie kan al gebeurd zijn.',
  'Review deadlocked after {rounds} revisions: {capability}': 'Beoordeling vastgelopen na {rounds} herzieningen: {capability}',
  'The role and its reviewer did not agree on {capability}.': 'De rol en haar beoordelaar zijn het niet eens geworden over “{capability}”.',
  'The reviewer\'s last note: {note}': 'Laatste opmerking van de beoordelaar: {note}',
  'The reviewer left no note.': 'De beoordelaar heeft geen opmerking achtergelaten.',
  'What it was judged against: {criteria}': 'Waaraan het werd getoetst: {criteria}',
  'Review produced no usable verdict: {capability}': 'Beoordeling leverde geen bruikbaar oordeel op: {capability}',
  'The reviewing task ended without a decision that could be read. The proposed action is still blocked and needs your judgement.': 'De beoordelende taak eindigde zonder een leesbare beslissing. De voorgestelde actie blijft geblokkeerd en heeft jouw oordeel nodig.',
  'another stage': 'een andere fase',
  'Either answer only closes this: the company stays in the {stage} stage.': 'Beide antwoorden sluiten alleen dit item: het bedrijf blijft in de fase {stage}.',
  'Either answer only closes this: the company stays without a stage.': 'Beide antwoorden sluiten alleen dit item: het bedrijf blijft zonder fase.',
  'To move it anyway, set the stage on the Overview.': 'Wil je het toch verplaatsen, stel de fase dan in onder Overzicht.',
  '{reviewer} stopped a proposal to move the company from {from} to {to}': '{reviewer} heeft een voorstel tegengehouden om het bedrijf van “{from}” naar “{to}” te verplaatsen',
  '{reviewer} reviewed it before you and stopped it:': '{reviewer} heeft het vóór jou beoordeeld en tegengehouden:',
  'No reason was given.': 'Er is geen reden gegeven.',
  'What was proposed:': 'Wat werd voorgesteld:',
  'The company stays in the {stage} stage.': 'Het bedrijf blijft in de fase {stage}.',
  'The company stays without a stage.': 'Het bedrijf blijft zonder fase.',
  'Move the company from {from} to {to}?': 'Het bedrijf van “{from}” naar “{to}” verplaatsen?',
  'Reviewed by {reviewer} before you:': 'Vóór jou beoordeeld door {reviewer}:',
  'The schedule "{schedule}" keeps producing the same result': 'Het schema “{schedule}” levert steeds hetzelfde resultaat op',
  'Its last {runs} runs all ended with the same output. That is sometimes exactly right -- a report with nothing new to say -- and often a schedule that stopped doing anything useful while still being paid for. Deny to turn it off; approve to keep it running and not be asked about this result again.': 'De laatste {runs} uitvoeringen eindigden allemaal met dezelfde uitvoer. Soms is dat precies goed – een rapport dat niets nieuws te melden heeft – maar vaak is het een schema dat niets nuttigs meer doet terwijl er nog voor wordt betaald. Kies “Afwijzen” om het uit te zetten, of “Goedkeuren” om het te laten doorlopen en over dit resultaat niet meer gevraagd te worden.',
  'Capability {capability} failed preflight': 'Mogelijkheid “{capability}” kwam niet door de controle vooraf',
  'Work that needs it is stopped rather than started: fix the cause, then run that work again. The usual causes are an expired or wrongly scoped credential, a quota used up, or an address that is wrong.': 'Werk dat haar nodig heeft, wordt gestopt in plaats van gestart: los de oorzaak op en voer dat werk daarna opnieuw uit. Gebruikelijke oorzaken zijn verlopen inloggegevens of inloggegevens met de verkeerde rechten, een quotum dat op is, of een verkeerd adres.',
  'Batch guard stopped {capability}': 'Batchcontrole heeft “{capability}” gestopt',
  'It did not match the plan its run recorded. Nothing was sent, and no service was called.': 'De aanroep kwam niet overeen met het plan dat de uitvoering had vastgelegd. Er is niets verzonden en er is geen dienst aangeroepen.',
  '{role} was asked first and has had {minutes} minutes.': '{role} werd eerst gevraagd en heeft {minutes} min. gehad.',
  '{role} is not a role in this company, so this came to you at once.': '{role} is geen rol in dit bedrijf, dus dit kwam meteen bij jou.',
  '{role} could not be given this: the company has no active goal or project to hang it from.': 'Dit kon niet aan {role} worden gegeven: het bedrijf heeft geen actief doel of project om het aan te koppelen.',
  '{role} could not be given this ({record}), so this came to you at once.': 'Dit kon niet aan {role} worden gegeven ({record}), dus het kwam meteen bij jou.',
  '{role} stopped without an account of what it did ({why}).': '{role} stopte zonder verslag van wat er is gedaan ({why}).',
  '{role} finished without an account of what it did.': '{role} is klaar zonder verslag van wat er is gedaan.',
  '{role} failed without an account of what it did.': '{role} is mislukt zonder verslag van wat er is gedaan.',
  '{role} was stopped without an account of what it did.': '{role} werd gestopt zonder verslag van wat er is gedaan.',
  'Proposed change to the {kind} "{goal}"': 'Voorgestelde wijziging van {kind} “{goal}”',
  'Currently: {statement}': 'Nu: {statement}',
  'Currently: {statement} ({status})': 'Nu: {statement} ({status})',
  'Proposed: {statement}': 'Voorgesteld: {statement}',
  'Proposed status: {status}': 'Voorgestelde status: {status}',
  'Reason given: {reason}': 'Opgegeven reden: {reason}',
  'Record a customer or a deal': 'Een klant of een deal vastleggen',
  'Not sent on its own: {reason}': 'Niet zelf verstuurd: {reason}',
  'it answers a conversation other than the one this work began with': 'het antwoordt in een ander gesprek dan het gesprek waarmee dit werk begon',
  'it named no passage of a document for customers': 'het noemde geen passage van een document voor klanten',
  'it answers from a document not marked for customers': 'het antwoordt uit een document dat niet voor klanten gemarkeerd is',
  'it says a figure the documents and the customer did not: {detail}': 'het noemt een getal dat de documenten en de klant niet gaven: {detail}',
  'it gives an address or link the documents and the customer did not: {detail}': 'het geeft een adres of link die de documenten en de klant niet gaven: {detail}',
  'there have been six answers on its own in this conversation in the last hour': 'er waren in dit gesprek het afgelopen uur al zes zelf verstuurde antwoorden',
  'the check found it is about a refund': 'de controle vond dat het over een terugbetaling gaat',
  'the check found it offers a price or terms of its own': 'de controle vond dat het een eigen prijs of eigen voorwaarden aanbiedt',
  'the check found it answers a serious complaint': 'de controle vond dat het op een ernstige klacht antwoordt',
  'the check found it touches the law': 'de controle vond dat het juridische zaken raakt',
  'the check found it gives or asks for personal data': 'de controle vond dat het persoonsgegevens geeft of vraagt',
  'the check found it promises something the documents do not': 'de controle vond dat het iets belooft wat de documenten niet zeggen',
  'the check could not judge it': 'de controle kon het niet beoordelen',
  'the check found something in it the documents do not say': 'de controle vond er iets in wat de documenten niet zeggen',
  '{role} proposes the schedule {name}': '{role} stelt het schema {name} voor',
  'Each run: {instruction}': 'Bij elke run: {instruction}',
  'Done by: {role}': 'Uitgevoerd door: {role}',
  'When: {cron} ({timezone}); the next runs are {runs}': 'Wanneer: {cron} ({timezone}); de volgende runs zijn {runs}',
  'Approving it makes the schedule and starts it; it can be turned off or changed under Team, Schedules.': 'Goedkeuren maakt het schema aan en start het; je kunt het uitzetten of wijzigen onder Team, Schema’s.',
  'No schedule is made.': 'Er wordt geen schema aangemaakt.',
  'Propose a schedule': 'Een schema voorstellen',
  'Approving it changes the goal; until then the work carries on under the goal as it is.': 'Goedkeuren wijzigt het doel; tot die tijd gaat het werk door onder het doel zoals het is.',
  'The goal stays as it is.': 'Het doel blijft zoals het is.',
  'mission': 'missie',
  'objective': 'doelstelling',
  'key result': 'kernresultaat',
  'Active': 'Actief',
  'Met': 'Behaald',
  'Abandoned': 'Opgegeven',
  'This work asked for it at tier {tier}, and policy {policies} requires your approval.': 'Dit werk vroeg erom op niveau {tier}, en beleidsregel {policies} vereist jouw goedkeuring.',
  'This work asked for it at tier {tier}, and the task began with content from outside the company.': 'Dit werk vroeg erom op niveau {tier}, en de taak begon met inhoud van buiten het bedrijf.',
  'This work asked for it at tier {tier}, and the work read content from outside the company before asking.': 'Dit werk vroeg erom op niveau {tier}, en het werk las inhoud van buiten het bedrijf voordat het erom vroeg.',
  'This work asked for it at tier {tier}, after the work read content from outside the company, and the guardian asked you first: {reason}': 'Dit werk vroeg erom op niveau {tier}, nadat het inhoud van buiten het bedrijf had gelezen, en de bewaker legt het eerst aan jou voor: {reason}',
  'it doubted this call before, and you allowed it once': 'hij twijfelde eerder al aan deze aanroep, en jij hebt hem één keer toegestaan',
  'This work asked for it at tier {tier}, which cannot be reversed.': 'Dit werk vroeg erom op niveau {tier}, en dat is onomkeerbaar.',
  'You approved this once already, and the worker carrying it out stopped before it could say whether it happened: it may already have happened. Check before approving it again.': 'Je hebt dit al een keer goedgekeurd, en de worker die het uitvoerde stopte voordat hij kon melden of het is gebeurd: het kan dus al gebeurd zijn. Controleer dat voordat je het opnieuw goedkeurt.',
  'What this is for — {goals}': 'Waar dit voor is – {goals}',
  'The task halts and no external change is made.': 'De taak wordt stilgezet en er wordt geen externe wijziging gedaan.',
  'Scored against {total} references: {passed} passed, {failed} failed.': 'Beoordeeld aan de hand van {total} referenties: {passed} geslaagd, {failed} niet geslaagd.',
  'This role has fewer than {minimum} accepted references, so the change is unscored. That is not the same as passing.': 'Deze rol heeft minder dan {minimum} geaccepteerde referenties, dus de wijziging heeft geen score. Dat is niet hetzelfde als geslaagd.',
  'The role keeps working exactly as it does now.': 'De rol blijft precies zo werken als nu.',
  '{role} asks: {question}': '{role} vraagt: {question}',
  'The run did not say more than the question.': 'De uitvoering zei niets meer dan de vraag.',
  'The task is stopped, and nothing it was going to do happens.': 'De taak wordt gestopt, en niets van wat ze ging doen gebeurt.',
  'You proposed it.': 'Je hebt deze zelf voorgesteld.',
  'It came with a bundle.': 'Deze kwam mee met een bundel.',
  'An agent proposed it.': 'Een agent heeft deze voorgesteld.',
  'It was learned from the company\'s work.': 'Deze is geleerd uit het werk van het bedrijf.',
  'Skill "{skill}", version {version}': 'Vaardigheid “{skill}”, versie {version}',
  'The reviewer approved it: {note}': 'De beoordelaar heeft deze goedgekeurd: {note}',
  'The reviewer approved it.': 'De beoordelaar heeft deze goedgekeurd.',
  'Nothing changes; the current version of the skill stays in force.': 'Er verandert niets; de huidige versie van de vaardigheid blijft van kracht.',
  'Skills the bundle "{bundle}" brings: {count}': 'Vaardigheden die de bundel “{bundle}” meebrengt: {count}',
  'The reviewer read them all and approved these:': 'De beoordelaar heeft ze allemaal gelezen en deze goedgekeurd:',
  'It turned these down, and they stay off:': 'Deze heeft hij afgewezen; ze blijven uitgeschakeld:',
  'Approve to switch them all on, or deny to turn them all down. To decide one at a time, open the Skills page.': 'Kies “Goedkeuren” om ze allemaal in te schakelen, of “Afwijzen” om ze allemaal af te wijzen. Wil je per vaardigheid beslissen, open dan de pagina Vaardigheden.',
  'Nothing changes; none of these skills is switched on.': 'Er verandert niets; geen van deze vaardigheden wordt ingeschakeld.',
  'I am {ceo}, and I run {company} for you. Three things before we start: what does {company} sell, and to whom? How much may it spend in a month? And what should its first piece of work be -- or shall I suggest one?': 'Ik ben {ceo}, en ik leid {company} voor je. Drie dingen voordat we beginnen: wat verkoopt {company}, en aan wie? Hoeveel mag het bedrijf per maand uitgeven? En wat moet de eerste klus zijn – of zal ik er een voorstellen?',
  'Read a customer conversation': 'Een klantgesprek lezen',
  'Reply to a customer': 'Een klant antwoorden',
  'Read a page in the browser': 'Een pagina in de browser lezen',
  'Fill in a page in the browser': 'Een pagina in de browser invullen',
  'Ask you to take over the browser': 'Je vragen de browser over te nemen',
};
