/**
 * Português (Brasil): what the platform itself says to the owner outside the
 * console (src/owner/say.ts), keyed by its English.
 *
 * The words are the console's (console/src/locales/pt-BR.ts): Aprovar,
 * Recusar and Perguntar on the buttons, "Esta instância, Ferramentas, Escuta"
 * for the screens it points at. WhatsApp cuts a reply button's title at 20
 * characters and a list row's at 24, so those stay short.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'Incidente: {title}',
  'Done: {goal}': 'Concluído: {goal}',
  'Stopped before finishing: {goal}': 'Parou antes de concluir: {goal}',
  'Not done: {goal}': 'Não feito: {goal}',
  'Why: {reason}': 'Motivo: {reason}',
  'a task': 'uma tarefa',
  'Approval needed: {title}': 'Aprovação necessária: {title}',
  '{summary} — if denied: {consequence}': '{summary} — se recusado: {consequence}',
  '{role} asks:': '{role} pergunta:',
  'If denied:': 'Se recusado:',
  'Expires:': 'Expira:',
  'This one is decided in the app.': 'Este item é decidido no app.',
  'Open in PALUGADA': 'Abrir no PALUGADA',
  'Approve': 'Aprovar',
  'Deny': 'Recusar',
  'Ask': 'Perguntar',
  'Approved. Nothing left to press here.': 'Aprovado. Não há mais nada para tocar aqui.',
  'Denied. Nothing left to press here.': 'Recusado. Não há mais nada para tocar aqui.',
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    'Expirou sem resposta. Silêncio é recusa, então nada foi feito.',
  'This bot only answers to its owner.': 'Este bot só responde ao proprietário.',
  'That one has to be approved in the app.': 'Este precisa ser aprovado no app.',
  'That could not be recorded.': 'Não foi possível registrar isso.',
  'That item no longer exists.': 'Esse item não existe mais.',
  'What do you want to ask about "{title}"? Reply to this message.':
    'O que você quer perguntar sobre “{title}”? Responda a esta mensagem.',
  'Your question': 'Sua pergunta',
  'Type your question as a reply.': 'Responda a esta mensagem com a sua pergunta.',
  'Asked. The answer will be on the item in the app.': 'Pergunta enviada. A resposta vai aparecer no item, no app.',
  'Answer': 'Responder',
  'Answer in words': 'Responder por escrito',
  'That choice is not on this question.': 'Essa opção não faz parte desta pergunta.',
  'Chosen: {choice}.': 'Escolhido: {choice}.',
  'Stop the task': 'Parar a tarefa',
  'Your answer to "{question}"? Reply to this message.': 'Qual é a sua resposta para “{question}”? Responda a esta mensagem.',
  'Your answer': 'Sua resposta',
  'Type your answer as a reply.': 'Responda a esta mensagem com a sua resposta.',
  'Answered. The task carries on with it.': 'Respondido. A tarefa segue com a sua resposta.',
  'That is too long for one question; keep it under {max} characters.':
    'Longo demais para uma pergunta; use menos de {max} caracteres.',
  '[a key, not kept]': '[uma chave, não guardada]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    'Isso parece uma chave, então não guardei nem enviei para lugar nenhum. As chaves vão no campo selado de um cartão, ou na página delas em Esta instância: diga para que ela serve e eu coloco o cartão diante de você.',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'Nenhum modelo foi configurado ainda, então não consigo pensar. Escolha um em Esta instância, Modelo; depois posso ajudar com todo o resto.',
  'The model did not answer: {reason}': 'O modelo não respondeu: {reason}',
  'Here is what I propose.': 'Esta é a minha proposta.',
  'I have nothing to add.': 'Não tenho nada a acrescentar.',
  '{name}, CEO of {company}': '{name}, CEO de {company}',
  'That could not be answered: {reason}': 'Não foi possível responder: {reason}',
  'I read text and voice notes.': 'Eu leio textos e mensagens de voz.',
  'Now talking to {name}.': 'Agora você está falando com {name}.',
  'Choose whom to talk to.': 'Escolha com quem falar.',
  'Choose whom to talk to': 'Escolher com quem falar',
  'Talk to PALUGADA about the whole deployment': 'Falar com o PALUGADA sobre a instância inteira',
  'Who you are talking to, and how': 'Com quem você está falando, e como',
  'Stopped.': 'Interrompido.',
  'Write here to talk to {name}.': 'Escreva aqui para falar com {name}.',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    'Você está falando com {name}. Escreva ou mande uma mensagem de voz. /ceo escolhe com quem você fala; /palugada fala com o PALUGADA sobre a instância inteira.',
  'You said: "{words}"': 'Você disse: “{words}”',
  'in the app': 'no app',
  'Apply: {summary}': 'Aplicar: {summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    'Ainda não há nada que ouça voz: escolha um provedor no app, em Esta instância, Ferramentas, Escuta.',
  'That recording is too long; keep a voice note under {max} MB.': 'Essa gravação é longa demais; mantenha a mensagem de voz abaixo de {max} MB.',
  'I could not make out any words in that.': 'Não consegui entender nenhuma palavra nisso.',
  'Done: {summary}': 'Feito: {summary}',
  'That one is applied in the app.': 'Esse cartão é aplicado no app.',
  'That card no longer exists.': 'Esse cartão não existe mais.',
  'That card was already applied.': 'Esse cartão já foi aplicado.',
  'That card was dismissed.': 'Esse cartão foi descartado.',
  'That card failed when it was applied.': 'Esse cartão falhou ao ser aplicado.',
  'That could not be done: {reason}': 'Não foi possível fazer isso: {reason}',
  'Choose': 'Escolher',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    'O que você quer perguntar sobre “{title}”? Responda a esta mensagem com a sua pergunta.',
  'Your answer to "{question}"? Reply to this message with your answer.':
    'Qual é a sua resposta para “{question}”? Responda a esta mensagem com a sua resposta.',
  'I read text messages here.': 'Aqui eu leio mensagens de texto.',
  'Apply one of these here:': 'Aplique um destes aqui:',
  'Apply {number}': 'Aplicar {number}',
  'Signed in to {provider} for the {alias} key': 'Conectado a {provider} para a chave {alias}',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'Volte ao PALUGADA: a divisão agora guarda esta chave, e ela é renovada antes de expirar. Você pode fechar esta aba.',
  'Signed in to {name}': 'Conectado a {name}',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'Volte ao PALUGADA para escolher quais ferramentas dele os cargos podem usar. Você pode fechar esta aba.',
  'Not signed in': 'Não conectado',
  "Recorded: approved.": "Registrado: aprovado.",
  "Recorded: denied.": "Registrado: recusado.",
  "Recorded: asked.": "Registrado: pergunta enviada.",
  "Asked. Nothing left to press here.": "Pergunta enviada. Não há mais nada para tocar aqui.",
  "Withdrawn: the task it was asking about has finished.": "Retirado: a tarefa a que ele se referia foi concluída.",
  "Withdrawn: the task it was asking about has failed.": "Retirado: a tarefa a que ele se referia falhou.",
  "Withdrawn: the task it was asking about was stopped.": "Retirado: a tarefa a que ele se referia foi interrompida.",
  "Withdrawn: the task it was asking about was cancelled.": "Retirado: a tarefa a que ele se referia foi cancelada.",
  'Decided. Nothing left to press here.': 'Decidido. Não há mais nada para tocar aqui.',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': 'Retirado: o agente mudou o que propõe e perguntou de novo sobre a nova proposta.',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': 'Retirado: a empresa não está mais na fase de onde esta proposta a tiraria.',
  'Withdrawn: it was already decided in the app.': 'Retirado: já foi decidido no app.',
  'Withdrawn. Nothing left to press here.': 'Retirado. Não há mais nada para tocar aqui.',
  'company': 'empresa',
  'Work stopped: the {account} account is out of tokens': 'O trabalho parou: a conta {account} ficou sem tokens',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': '“{work}” parou porque a conta {account} usou {spent} de seus {max} tokens. Aumente o limite dela em Finanças, depois abra a tarefa e toque em Continuar: ela segue de onde parou.',
  'Withdrawn: you continued the task it was about.': 'Retirado: você continuou a tarefa a que se referia.',
  'Broke its contract': 'Violou o contrato',
  'Refused by a policy': 'Recusado por uma política',
  'Out of budget': 'Sem orçamento',
  'Handed on too many times': 'Repassada vezes demais',
  'Missed its deadline': 'Perdeu o prazo',
  'Its result did not check out': 'O resultado não passou na verificação',
  'A capability it needs is down': 'Uma capacidade necessária está fora do ar',
  'No runtime could take it': 'Nenhum ambiente de execução pôde assumi-la',
  'Went in a circle': 'Andou em círculos',
  'Split into too many sub-tasks': 'Dividida em subtarefas demais',
  'Wrote more than its role allows one run': 'Escreveu mais do que o cargo permite em uma execução',
  'Your approval was not given in time': 'A sua aprovação não veio a tempo',
  'Stopped by you': 'Parada por você',
  'Cancelled by you': 'Cancelada por você',
  'The company is frozen': 'A empresa está congelada',
  'Its record did not match on replay': 'O registro não bateu na reexecução',
  'It kept stopping the worker running it': 'Derrubou várias vezes o executor que a processava',
  'Not done': 'Não feita',
  'Task failed': 'A tarefa falhou',
  'Digest for {day}': 'Resumo de {day}',
  'Spent: {amount}': 'Gasto: {amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': 'Trabalho — concluídas: {done}, com falha: {failed}, paradas: {stopped}',
  'Inbox: {open} waiting (incidents: {incidents})': 'Caixa de entrada: {open} aguardando (incidentes: {incidents})',
  'Stopped ({count}): {reason}': 'Paradas ({count}): {reason}',
  'Start an ad campaign': 'Iniciar uma campanha de anúncios',
  'Block time on the calendar': 'Bloquear um horário na agenda',
  'Read the calendar': 'Ler a agenda',
  'Run code': 'Executar código',
  'Add a note to a customer': 'Adicionar uma anotação ao cliente',
  'Read customer records': 'Ler os registros de clientes',
  'Release to the live site': 'Colocar a nova versão no ar',
  'Release to the test site': 'Publicar no site de teste',
  'Change a domain\'s nameservers': 'Alterar os servidores DNS de um domínio',
  'Read a domain\'s records': 'Ler os registros de um domínio',
  'Change a domain\'s record': 'Alterar um registro do domínio',
  'Write a document': 'Escrever um documento',
  'Sign a document': 'Assinar um documento',
  'Buy a domain': 'Comprar um domínio',
  'Transfer a domain': 'Transferir um domínio',
  'Draft an email': 'Criar um rascunho de e-mail',
  'Send an email': 'Enviar um e-mail',
  'List files': 'Listar arquivos',
  'Read a file': 'Ler um arquivo',
  'Describe a picture': 'Descrever uma imagem',
  'Calculate in Python': 'Calcular com Python',
  'Transfer money': 'Transferir dinheiro',
  'Propose a goal change': 'Propor uma alteração de meta',
  'Make a picture': 'Criar uma imagem',
  'Issue an invoice': 'Emitir uma fatura',
  'Pay an invoice': 'Pagar uma fatura',
  'Read the books': 'Ler a contabilidade',
  'Read the mailbox': 'Ler a caixa de e-mail',
  'Search what the company knows': 'Buscar no que a empresa sabe',
  'Record a measure': 'Registrar uma medição',
  'Read product numbers': 'Ler os números do produto',
  'Ask you a question': 'Fazer uma pergunta a você',
  'Write down a plan': 'Anotar um plano',
  'Delete a record': 'Excluir um registro',
  'Propose a code change': 'Propor uma alteração no código',
  'Read the code': 'Ler o código',
  'Destroy a server': 'Destruir um servidor',
  'Read a skill': 'Ler uma habilidade',
  'Publish a post': 'Publicar um post',
  'Read text aloud': 'Ler um texto em voz alta',
  'Turn speech into text': 'Transformar fala em texto',
  'Propose a new stage': 'Propor uma nova fase',
  'Wait for work handed on': 'Aguardar o trabalho repassado',
  'Hand work to another role': 'Repassar trabalho a outro cargo',
  'File a ticket': 'Abrir chamado',
  'List tickets': 'Listar chamados',
  'Check a service is up': 'Verificar se um serviço está no ar',
  'Read a web page': 'Ler uma página web',
  'Open a web page': 'Abrir uma página web',
  'Search the web': 'Buscar na web',
  'no stage': 'nenhuma fase',
  'Explore': 'Exploração',
  'Validate': 'Validação',
  'Build': 'Construção',
  'Launch': 'Lançamento',
  'Grow': 'Crescimento',
  'Wind down': 'Encerramento',
  'Monthly budget reached; the company is paused': 'Orçamento mensal atingido; a empresa está pausada',
  '{spent} of {limit} spent since {since}. No new task will start and no external action will run until you raise the ceiling or allow spending past it for a while, under Money.': '{spent} de {limit} gastos desde {since}. Nenhuma tarefa nova vai começar e nenhuma ação externa vai ser executada até você aumentar o teto ou permitir, por um tempo, gastos acima dele, em Finanças.',
  'Monthly budget is 80% spent': '80% do orçamento mensal já foi gasto',
  '{spent} of {limit} spent since {since}. At 100% the company pauses.': '{spent} de {limit} gastos desde {since}. Ao chegar a 100%, a empresa é pausada.',
  'Role {role} is paused for spending too fast': 'O cargo {role} foi pausado por gastar rápido demais',
  '{role} spent {spent} in the last hour, {multiple} times its usual {usual} an hour. It is paused before the monthly ceiling is reached, so there is money left to work with once you have found out why. Resume it when you have.': '{role} gastou {spent} na última hora, {multiple} vezes o seu habitual de {usual} por hora. O cargo foi pausado antes de o teto mensal ser atingido, para que ainda sobre dinheiro para trabalhar quando você descobrir o motivo. Retome o cargo depois disso.',
  'Daily model spend over threshold': 'Gasto diário com modelos acima do limite',
  'Model spend today is {spent}, over the {limit} ceiling.': 'O gasto com modelos hoje é de {spent}, acima do teto de {limit}.',
  'Task failure rate over threshold': 'Taxa de falha de tarefas acima do limite',
  '{failed} of {finished} tasks failed or stopped today ({rate}%), over the {limit}% threshold.': '{failed} de {finished} tarefas falharam ou pararam hoje ({rate}%), acima do limite de {limit}%.',
  'Unusual number of policy refusals': 'Número incomum de recusas por política',
  'Actions refused by a policy today: {count}, over the threshold of {limit}. Either an agent is probing its limits or a policy is miscalibrated.': 'Ações recusadas por uma política hoje: {count}, acima do limite de {limit}. Ou um agente está testando os próprios limites, ou uma política está mal calibrada.',
  'External writes failed verification': 'Gravações externas não passaram na conferência',
  'Writes outside that reported success but read back differently: {count}. Something is changing them other than as asked.': 'Gravações externas que relataram sucesso, mas divergiram na conferência: {count}. Algo está alterando esses dados de um jeito diferente do que foi pedido.',
  'A capability stopped being usable': 'Uma capacidade deixou de funcionar',
  'Tasks that could not start today because a capability their role needs failed its check: {count}. A credential has probably expired or a quota is used up.': 'Tarefas que não puderam começar hoje porque uma capacidade de que o cargo delas precisa não passou na verificação: {count}. Provavelmente uma credencial expirou ou uma cota acabou.',
  'A worker stopped reporting mid-run': 'Um executor parou de dar sinal no meio de uma execução',
  'Runs that stopped reporting and were taken back today: {count}. The work was picked up again; the tokens they had already spent were not recovered.': 'Execuções que pararam de dar sinal e foram dadas como perdidas hoje: {count}. O trabalho foi retomado; os tokens que elas já tinham gastado não foram recuperados.',
  '{role} was refused {denials} times today, at the limit of {limit}. No task will run as this role until you lift the freeze. The usual causes are a missing capability grant, a policy the role\'s charter does not account for, or work the role was never equipped to do.': '{role} teve {denials} recusas hoje, chegando ao limite de {limit}. Nenhuma tarefa vai ser executada com este cargo até você descongelá-lo. As causas mais comuns são uma permissão de capacidade que falta, uma política que as diretrizes do cargo não preveem, ou um trabalho para o qual o cargo nunca foi preparado.',
  'Role {role} is frozen after repeated denials': 'O cargo {role} foi congelado após recusas repetidas',
  'What it was refused: {capabilities}': 'O que foi recusado: {capabilities}',
  'It is waiting for an approval, and none is open, so nothing you can answer will move it.': 'Ela está esperando uma aprovação, e não há nenhuma aberta; então nada que você responda vai fazê-la andar.',
  'It is waiting for a review, and none is pending, so no reviewer and no decision of yours will move it.': 'Ela está esperando uma revisão, e não há nenhuma pendente; então nenhum revisor e nenhuma decisão sua vão fazê-la andar.',
  'It is parked until a window reopens, and the window never does.': 'Ela está aguardando a reabertura de um horário, e esse horário nunca reabre.',
  'A task is waiting on nothing': 'Uma tarefa está esperando algo que não existe',
  '"{task}" has been waiting since {since}. {why} Approve to run it again from where it stopped, or deny to cancel it.': '“{task}” está esperando desde {since}. {why} Aprovar executa a tarefa de novo a partir de onde ela parou; Recusar a cancela.',
  'A task keeps stopping the worker running it': 'Uma tarefa continua derrubando o executor que a processa',
  '"{task}" lost its worker {lost} times: each time the worker running it stopped answering before the work finished. What it had done is kept. It is halted so it cannot take another worker down; run it again once the cause is found, or cancel it.': '“{task}” perdeu o executor {lost} vezes: em cada uma, o executor que a processava parou de responder antes de o trabalho terminar. O que ela já tinha feito foi mantido. Ela foi interrompida para não derrubar outro executor; execute-a de novo quando a causa for encontrada, ou cancele-a.',
  '{services} stayed unreachable, and the work that needs it stopped': '{services} continuou fora do ar, e o trabalho que depende disso parou',
  'The task waited about {minutes} minutes, looking again each time, and has stopped. Once the service answers, run it again.': 'A tarefa esperou cerca de {minutes} minutos, verificando de novo a cada tentativa, e parou. Quando o serviço responder, execute-a de novo.',
  'It was tried {tries} times over about {minutes} minutes.': 'Foram {tries} tentativas em cerca de {minutes} minutos.',
  'This role can take actions that cannot be undone, so the run was not silently moved to a different model.': 'Este cargo pode tomar ações que não podem ser desfeitas, então a execução não foi transferida em silêncio para outro modelo.',
  'No fallback model is left for this role.': 'Não resta nenhum modelo alternativo para este cargo.',
  'Model {model} failed and the run was not moved': 'O modelo {model} falhou e a execução não foi transferida',
  'External write failed verification': 'Uma gravação externa não passou na conferência',
  'The task wrote to an outside service and read it back, and what it read did not match. Look at the place it wrote to before you run it again: the write may have happened.': 'A tarefa gravou em um serviço externo e conferiu o resultado, e o que leu não bateu. Verifique o lugar onde ela gravou antes de executá-la de novo: a gravação pode ter acontecido.',
  'Review deadlocked after {rounds} revisions: {capability}': 'Revisão travada após {rounds} rodadas de correção: {capability}',
  'The role and its reviewer did not agree on {capability}.': 'O cargo e o revisor dele não chegaram a um acordo sobre {capability}.',
  'The reviewer\'s last note: {note}': 'Última nota do revisor: {note}',
  'The reviewer left no note.': 'O revisor não deixou nenhuma nota.',
  'What it was judged against: {criteria}': 'Critérios usados na avaliação: {criteria}',
  'Review produced no usable verdict: {capability}': 'A revisão não chegou a um veredito utilizável: {capability}',
  'The reviewing task ended without a decision that could be read. The proposed action is still blocked and needs your judgement.': 'A tarefa de revisão terminou sem uma decisão legível. A ação proposta continua bloqueada e precisa do seu julgamento.',
  'another stage': 'outra fase',
  'Either answer only closes this: the company stays in the {stage} stage.': 'Qualquer uma das respostas apenas encerra este item: a empresa continua na fase {stage}.',
  'Either answer only closes this: the company stays without a stage.': 'Qualquer uma das respostas apenas encerra este item: a empresa continua sem fase.',
  'To move it anyway, set the stage on the Overview.': 'Para mudar de fase mesmo assim, defina a fase na Visão geral.',
  '{reviewer} stopped a proposal to move the company from {from} to {to}': '{reviewer} barrou uma proposta de mover a empresa de {from} para {to}',
  '{reviewer} reviewed it before you and stopped it:': '{reviewer} revisou a proposta antes de você e a barrou:',
  'No reason was given.': 'Nenhum motivo foi informado.',
  'What was proposed:': 'O que foi proposto:',
  'The company stays in the {stage} stage.': 'A empresa continua na fase {stage}.',
  'The company stays without a stage.': 'A empresa continua sem fase.',
  'Move the company from {from} to {to}?': 'Mover a empresa de {from} para {to}?',
  'Reviewed by {reviewer} before you:': 'Revisado por {reviewer} antes de você:',
  'The schedule "{schedule}" keeps producing the same result': 'O agendamento “{schedule}” continua produzindo o mesmo resultado',
  'Its last {runs} runs all ended with the same output. That is sometimes exactly right -- a report with nothing new to say -- and often a schedule that stopped doing anything useful while still being paid for. Deny to turn it off; approve to keep it running and not be asked about this result again.': 'As últimas {runs} execuções terminaram todas com o mesmo resultado. Às vezes isso é exatamente o certo — um relatório sem nada de novo a dizer — e muitas vezes é um agendamento que deixou de fazer algo útil e continua sendo pago. Recusar desativa o agendamento; Aprovar o mantém em execução, sem novas perguntas sobre este resultado.',
  'Capability {capability} failed preflight': 'A capacidade {capability} não passou na verificação prévia',
  'Work that needs it is stopped rather than started: fix the cause, then run that work again. The usual causes are an expired or wrongly scoped credential, a quota used up, or an address that is wrong.': 'O trabalho que precisa dela é interrompido em vez de iniciado: corrija a causa e depois execute esse trabalho de novo. As causas mais comuns são uma credencial expirada ou com escopo errado, uma cota esgotada ou um endereço errado.',
  'Batch guard stopped {capability}': 'O controle de lote barrou {capability}',
  'It did not match the plan its run recorded. Nothing was sent, and no service was called.': 'Não correspondia ao plano que a execução registrou. Nada foi enviado e nenhum serviço foi chamado.',
  '{role} was asked first and has had {minutes} minutes.': 'Isto foi passado primeiro para {role}, que já teve {minutes} minutos.',
  '{role} is not a role in this company, so this came to you at once.': '{role} não é um cargo desta empresa, então isto veio direto para você.',
  '{role} could not be given this: the company has no active goal or project to hang it from.': 'Não foi possível passar isto para {role}: a empresa não tem nenhuma meta ou projeto ativo a que vinculá-lo.',
  '{role} could not be given this ({record}), so this came to you at once.': 'Não foi possível passar isto para {role} ({record}), então isto veio direto para você.',
  '{role} stopped without an account of what it did ({why}).': '{role} parou sem relatar o que fez ({why}).',
  '{role} finished without an account of what it did.': '{role} terminou sem relatar o que fez.',
  '{role} failed without an account of what it did.': '{role} falhou sem relatar o que fez.',
  '{role} was stopped without an account of what it did.': '{role} teve a execução interrompida sem relatar o que fez.',
  'Proposed change to the {kind} "{goal}"': 'Proposta de alteração de {kind}: “{goal}”',
  'Currently: {statement}': 'Atualmente: {statement}',
  'Currently: {statement} ({status})': 'Atualmente: {statement} ({status})',
  'Proposed: {statement}': 'Proposta: {statement}',
  'Proposed status: {status}': 'Situação proposta: {status}',
  'Reason given: {reason}': 'Motivo informado: {reason}',
  'Record an entry in the books': 'Registrar um lançamento nos livros',
  'Record a customer or a deal': 'Registrar um cliente ou um negócio',
  'Not sent on its own: {reason}': 'Não enviado sozinho: {reason}',
  'it answers a conversation other than the one this work began with': 'responde a uma conversa diferente daquela com que este trabalho começou',
  'it named no passage of a document for customers': 'não citou nenhum trecho de um documento para clientes',
  'it answers from a document not marked for customers': 'responde a partir de um documento não marcado para clientes',
  'it says a figure the documents and the customer did not: {detail}': 'diz um número que nem os documentos nem o cliente deram: {detail}',
  'it gives an address or link the documents and the customer did not: {detail}': 'dá um endereço ou link que nem os documentos nem o cliente deram: {detail}',
  'there have been six answers on its own in this conversation in the last hour': 'já houve seis respostas enviadas sozinhas nesta conversa na última hora',
  'the check found it is about a refund': 'a verificação achou que se trata de um reembolso',
  'the check found it offers a price or terms of its own': 'a verificação achou que oferece um preço ou condições próprias',
  'the check found it answers a serious complaint': 'a verificação achou que responde a uma reclamação séria',
  'the check found it touches the law': 'a verificação achou que toca em questões legais',
  'the check found it gives or asks for personal data': 'a verificação achou que dá ou pede dados pessoais',
  'the check found it promises something the documents do not': 'a verificação achou que promete algo que os documentos não dizem',
  'the check could not judge it': 'a verificação não conseguiu julgá-la',
  'the check found something in it the documents do not say': 'a verificação achou nela algo que os documentos não dizem',
  '{role} proposes the schedule {name}': '{role} propõe o agendamento {name}',
  'Each run: {instruction}': 'Em cada execução: {instruction}',
  'Done by: {role}': 'Feito por: {role}',
  'When: {cron} ({timezone}); the next runs are {runs}': 'Quando: {cron} ({timezone}); as próximas execuções são {runs}',
  'Approving it makes the schedule and starts it; it can be turned off or changed under Team, Schedules.': 'Aprovar cria o agendamento e o inicia; ele pode ser desligado ou alterado em Equipe, Agendamentos.',
  'No schedule is made.': 'Nenhum agendamento é criado.',
  'Propose a schedule': 'Propor um agendamento',
  'Approving it changes the goal; until then the work carries on under the goal as it is.': 'Aprovar altera a meta; até lá, o trabalho continua sob a meta como ela está.',
  'The goal stays as it is.': 'A meta continua como está.',
  'mission': 'missão',
  'objective': 'objetivo',
  'key result': 'resultado-chave',
  'Active': 'Ativa',
  'Met': 'Atingida',
  'Abandoned': 'Abandonada',
  'This work asked for it at tier {tier}, and policy {policies} requires your approval.': 'Este trabalho pediu isto no nível {tier}, e a política {policies} exige a sua aprovação.',
  'This work asked for it at tier {tier}, and the task began with content from outside the company.': 'Este trabalho pediu isto no nível {tier}, e a tarefa começou com conteúdo de fora da empresa.',
  'This work asked for it at tier {tier}, and the work read content from outside the company before asking.': 'Este trabalho pediu isto no nível {tier}, e, antes de pedir, leu conteúdo de fora da empresa.',
  'This work asked for it at tier {tier}, after the work read content from outside the company, and the guardian asked you first: {reason}': 'Este trabalho pediu isto no nível {tier}, depois de ler conteúdo de fora da empresa, e o guardião consultou você primeiro: {reason}',
  'it doubted this call before, and you allowed it once': 'ele já tinha desconfiado desta chamada antes, e você a permitiu uma vez',
  'This work asked for it at tier {tier}, which cannot be reversed.': 'Este trabalho pediu isto no nível {tier}, que não pode ser desfeito.',
  'You approved this once already, and the worker carrying it out stopped before it could say whether it happened: it may already have happened. Check before approving it again.': 'Você já aprovou isto uma vez, e o executor que estava realizando a ação parou antes de dizer se ela aconteceu: ela pode já ter acontecido. Verifique antes de aprovar de novo.',
  'What this is for — {goals}': 'Para que serve — {goals}',
  'The task halts and no external change is made.': 'A tarefa é interrompida e nenhuma alteração externa é feita.',
  'Scored against {total} references: {passed} passed, {failed} failed.': 'Avaliado com {total} referências — aprovadas: {passed}; reprovadas: {failed}.',
  'This role has fewer than {minimum} accepted references, so the change is unscored. That is not the same as passing.': 'Este cargo tem menos de {minimum} referências aceitas, então a alteração fica sem nota. Isso não é o mesmo que ser aprovada.',
  'The role keeps working exactly as it does now.': 'O cargo continua trabalhando exatamente como agora.',
  '{role} asks: {question}': '{role} pergunta: {question}',
  'The run did not say more than the question.': 'A execução não disse nada além da pergunta.',
  'The task is stopped, and nothing it was going to do happens.': 'A tarefa é interrompida, e nada do que ela ia fazer acontece.',
  'You proposed it.': 'Foi você quem a propôs.',
  'It came with a bundle.': 'Veio com um pacote.',
  'An agent proposed it.': 'Um agente a propôs.',
  'It was learned from the company\'s work.': 'Foi aprendida no trabalho da empresa.',
  'Skill "{skill}", version {version}': 'Habilidade “{skill}”, versão {version}',
  'The reviewer approved it: {note}': 'O revisor a aprovou: {note}',
  'The reviewer approved it.': 'O revisor a aprovou.',
  'Nothing changes; the current version of the skill stays in force.': 'Nada muda; a versão atual da habilidade continua em vigor.',
  'Skills the bundle "{bundle}" brings: {count}': 'Habilidades que o pacote “{bundle}” traz: {count}',
  'The reviewer read them all and approved these:': 'O revisor leu todas e aprovou estas:',
  'It turned these down, and they stay off:': 'Ele recusou estas, que continuam desativadas:',
  'Approve to switch them all on, or deny to turn them all down. To decide one at a time, open the Skills page.': 'Aprovar ativa todas; Recusar recusa todas. Para decidir uma a uma, abra a página Habilidades.',
  'Nothing changes; none of these skills is switched on.': 'Nada muda; nenhuma destas habilidades é ativada.',
  'I am {ceo}, and I run {company} for you. Three things before we start: what does {company} sell, and to whom? How much may it spend in a month? And what should its first piece of work be -- or shall I suggest one?': 'Sou {ceo} e administro {company} para você. Três coisas antes de começarmos: o que {company} vende, e para quem? Quanto a empresa pode gastar por mês? E qual deve ser o primeiro trabalho dela — ou prefere que eu sugira um?',
  'Read a customer conversation': 'Ler uma conversa com um cliente',
  'Reply to a customer': 'Responder a um cliente',
  'Read a page in the browser': 'Ler uma página no navegador',
  'Fill in a page in the browser': 'Preencher uma página no navegador',
  'Ask you to take over the browser': 'Pedir que você assuma o navegador',
  '{host} refused the model key ({status}), so nothing that needs the model can run. Open Settings, This deployment, Model, paste a key that works, test it and save.':
    '{host} recusou a chave do modelo ({status}), então nenhum trabalho que dependa do modelo consegue rodar. Abra Configurações, Esta instância, Modelo, cole uma chave que funcione, teste e salve.',
  '{host} refused the model key, and work is waiting': '{host} recusou a chave do modelo e o trabalho está em espera',
  'What is waiting for the model carries on by itself once a key that works is in use.':
    'O trabalho que espera o modelo continua sozinho assim que uma chave que funcione estiver em uso.',
  'A task ended before it was done: {task}':
    'Uma tarefa terminou antes de ficar pronta: {task}',
  'It ended as: {reason}. No other card was raised for it, so it is here rather than silent.':
    'Terminou assim: {reason}. Nenhum outro cartão foi criado para ela, então ela aparece aqui em vez de ficar em silêncio.',
  'Where its measures stand, as the platform reads them:':
    'Como estão suas medidas, segundo a leitura da plataforma:',
  '{name}: no value recorded yet, against a target of {target}.':
    '{name}: ainda sem valor registrado, com meta de {target}.',
  '{name}: {value} against a target of {target}, read back from its source.':
    '{name}: {value} contra uma meta de {target}, relido da sua fonte.',
  '{name}: {value} against a target of {target}, reported and not checked.':
    '{name}: {value} contra uma meta de {target}, informado e não verificado.',
  'Look at it again later': 'Rever mais tarde',
  "Deliver what this company sells, reliably and without surprising its owner.":
    "Entregar o que esta empresa vende, com confiabilidade e sem surpreender o dono.",
  "Ship the work the company has promised, on time and verified.":
    "Entregar o trabalho que a empresa prometeu, no prazo e verificado.",
  "Keep the company solvent, answerable and running without daily attention.":
    "Manter a empresa solvente, responsável e funcionando sem exigir atenção diária.",
  "Since we last spoke:":
    "Desde a nossa última conversa:",
  "More finished: {count}":
    "Concluído além disso: {count}",
  "Waiting for you: {count}":
    "Aguardando você: {count}",
};
