/**
 * Русский: what the platform itself says to the owner outside the console
 * (src/owner/say.ts), keyed by its English.
 *
 * The terms are the console's (console/src/locales/ru.ts, whose header holds
 * the glossary): одобрить and отклонить, входящие, установка, «Эта установка»
 * for the page. A name in a placeholder sits where its case does not matter
 * («Ваш собеседник — {name}»). Telegram and WhatsApp buttons stay short:
 * WhatsApp cuts a button at 20 characters and a list row at 24.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'Инцидент: {title}',
  'Done: {goal}': 'Готово: {goal}',
  'Stopped before finishing: {goal}': 'Остановлено до завершения: {goal}',
  'Not done: {goal}': 'Не сделано: {goal}',
  'Why: {reason}': 'Причина: {reason}',
  'a task': 'задача',
  'Approval needed: {title}': 'Нужно одобрение: {title}',
  '{summary} — if denied: {consequence}': '{summary} — если отклонить: {consequence}',
  '{role} asks:': '{role} спрашивает:',
  'If denied:': 'Если отклонить:',
  'Expires:': 'Истекает:',
  'This one is decided in the app.': 'Это решается в приложении.',
  'Open in PALUGADA': 'Открыть в PALUGADA',
  'Approve': 'Одобрить',
  'Deny': 'Отклонить',
  'Ask': 'Спросить',
  'Approved. Nothing left to press here.': 'Одобрено. Здесь больше ничего нажимать не нужно.',
  'Denied. Nothing left to press here.': 'Отклонено. Здесь больше ничего нажимать не нужно.',
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    'Срок истёк без ответа. Молчание — это отказ, поэтому ничего не сделано.',
  'This bot only answers to its owner.': 'Этот бот отвечает только своему владельцу.',
  'That one has to be approved in the app.': 'Это нужно одобрить в приложении.',
  'That could not be recorded.': 'Не удалось это записать.',
  'That item no longer exists.': 'Этого элемента больше нет.',
  'What do you want to ask about "{title}"? Reply to this message.':
    'Что вы хотите спросить о «{title}»? Ответьте на это сообщение.',
  'Your question': 'Ваш вопрос',
  'Type your question as a reply.': 'Напишите вопрос, ответив на это сообщение.',
  'Asked. The answer will be on the item in the app.': 'Вопрос задан. Ответ появится у этого элемента в приложении.',
  'Answer': 'Ответить',
  'Answer in words': 'Ответить словами',
  'That choice is not on this question.': 'Такого варианта в этом вопросе нет.',
  'Chosen: {choice}.': 'Выбрано: {choice}.',
  'Stop the task': 'Остановить задачу',
  'Your answer to "{question}"? Reply to this message.': 'Ваш ответ на «{question}»? Ответьте на это сообщение.',
  'Your answer': 'Ваш ответ',
  'Type your answer as a reply.': 'Напишите ответ, ответив на это сообщение.',
  'Answered. The task carries on with it.': 'Ответ принят. Задача продолжится с его учётом.',
  'That is too long for one question; keep it under {max} characters.':
    'Слишком длинно для одного вопроса: уложитесь в {max} символов.',
  '[a key, not kept]': '[ключ, не сохранён]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    'Похоже на ключ, поэтому он не сохранён и никуда не отправлен. Ключи вводятся в защищённое поле на карточке или на своей странице в разделе «Эта установка»: скажите, для чего этот ключ, и я покажу вам карточку.',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'Модель ещё не настроена, поэтому я не могу думать. Выберите её в разделе «Эта установка» → «Модель»; после этого я смогу помочь со всем остальным.',
  'The model did not answer: {reason}': 'Модель не ответила: {reason}',
  'Here is what I propose.': 'Вот что я предлагаю.',
  'I have nothing to add.': 'Мне нечего добавить.',
  '{name}, CEO of {company}': '{name}, CEO компании {company}',
  'That could not be answered: {reason}': 'Не удалось ответить: {reason}',
  'I read text and voice notes.': 'Я читаю текст и голосовые сообщения.',
  'Now talking to {name}.': 'Теперь ваш собеседник — {name}.',
  'Choose whom to talk to.': 'Выберите собеседника.',
  'Choose whom to talk to': 'Выбрать собеседника',
  'Talk to PALUGADA about the whole deployment': 'Поговорить с PALUGADA обо всей установке',
  'Who you are talking to, and how': 'С кем вы говорите и как',
  'Stopped.': 'Остановлено.',
  'Write here to talk to {name}.': 'Пишите здесь — вам ответит {name}.',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    'Ваш собеседник — {name}. Пишите или отправьте голосовое сообщение. /ceo — выбрать собеседника; /palugada — поговорить с PALUGADA обо всей установке.',
  'You said: "{words}"': 'Вы сказали: «{words}»',
  'in the app': 'в приложении',
  'Apply: {summary}': 'Применить: {summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    'Распознавание речи ещё не настроено: выберите провайдера в приложении, в разделе «Эта установка» → «Инструменты» → «Распознавание речи».',
  'That recording is too long; keep a voice note under {max} MB.': 'Запись слишком длинная: голосовое сообщение должно быть меньше {max} МБ.',
  'I could not make out any words in that.': 'Не удалось разобрать ни одного слова.',
  'Done: {summary}': 'Готово: {summary}',
  'That one is applied in the app.': 'Это применяется в приложении.',
  'That card no longer exists.': 'Этой карточки больше нет.',
  'That card was already applied.': 'Эта карточка уже применена.',
  'That card was dismissed.': 'Эта карточка отклонена.',
  'That card failed when it was applied.': 'При применении этой карточки произошла ошибка.',
  'That could not be done: {reason}': 'Не удалось это сделать: {reason}',
  'Choose': 'Выбрать',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    'Что вы хотите спросить о «{title}»? Напишите вопрос в ответ на это сообщение.',
  'Your answer to "{question}"? Reply to this message with your answer.':
    'Ваш ответ на «{question}»? Напишите его в ответ на это сообщение.',
  'I read text messages here.': 'Здесь я читаю текстовые сообщения.',
  'Apply one of these here:': 'Здесь можно применить одну из них:',
  'Apply {number}': 'Применить {number}',
  'Signed in to {provider} for the {alias} key': 'Вход в {provider} для ключа {alias} выполнен',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'Вернитесь в PALUGADA: теперь этот ключ хранится у отдела и будет обновляться до истечения срока. Эту вкладку можно закрыть.',
  'Signed in to {name}': 'Вход в {name} выполнен',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'Вернитесь в PALUGADA, чтобы выбрать, какие из его инструментов могут использовать роли. Эту вкладку можно закрыть.',
  'Not signed in': 'Вход не выполнен',
  "Recorded: approved.": "Записано: одобрено.",
  "Recorded: denied.": "Записано: отклонено.",
  "Recorded: asked.": "Записано: вопрос задан.",
  "Asked. Nothing left to press here.": "Вопрос задан. Здесь больше ничего нажимать не нужно.",
  "Withdrawn: the task it was asking about has finished.": "Отозвано: задача, о которой шла речь, выполнена.",
  "Withdrawn: the task it was asking about has failed.": "Отозвано: задача, о которой шла речь, завершилась ошибкой.",
  "Withdrawn: the task it was asking about was stopped.": "Отозвано: задача, о которой шла речь, остановлена.",
  "Withdrawn: the task it was asking about was cancelled.": "Отозвано: задача, о которой шла речь, отменена.",
  'Decided. Nothing left to press here.': 'Решено. Здесь больше ничего нажимать не нужно.',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': 'Отозвано: агент изменил своё предложение и снова спросил о новом.',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': 'Отозвано: компания уже не на том этапе, с которого её переводило это предложение.',
  'Withdrawn: it was already decided in the app.': 'Отозвано: решение уже принято в приложении.',
  'Withdrawn. Nothing left to press here.': 'Отозвано. Здесь больше ничего нажимать не нужно.',
  'company': '«Компания»',
  'Work stopped: the {account} account is out of tokens': 'Работа остановлена: у счёта {account} закончились токены',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': '«{work}» остановлена: счёт {account} израсходовал {spent} из {max} токенов. Поднимите его потолок в разделе «Деньги», затем откройте задачу и нажмите «Продолжить»: она продолжится с того места, где остановилась.',
  'Withdrawn: you continued the task it was about.': 'Отозвано: вы продолжили задачу, о которой шла речь.',
  'Broke its contract': 'Нарушен контракт',
  'Refused by a policy': 'Отклонено политикой',
  'Out of budget': 'Бюджет исчерпан',
  'Handed on too many times': 'Слишком много передач',
  'Missed its deadline': 'Пропущен срок',
  'Its result did not check out': 'Результат не прошёл проверку',
  'A capability it needs is down': 'Нужная возможность недоступна',
  'No runtime could take it': 'Ни одна среда выполнения не смогла её взять',
  'Went in a circle': 'Работа пошла по кругу',
  'Split into too many sub-tasks': 'Разбита на слишком много подзадач',
  'Wrote more than its role allows one run': 'Написано больше, чем роли разрешено за один запуск',
  'Your approval was not given in time': 'Ваше одобрение не пришло вовремя',
  'Stopped by you': 'Остановлена вами',
  'Cancelled by you': 'Отменена вами',
  'The company is frozen': 'Компания заморожена',
  'Its record did not match on replay': 'Запись не совпала при воспроизведении',
  'It kept stopping the worker running it': 'Задача раз за разом приводила к сбою воркера, который её выполнял',
  'Not done': 'Не сделано',
  'Task failed': 'Задача завершилась ошибкой',
  'Digest for {day}': 'Сводка за {day}',
  'Spent: {amount}': 'Потрачено: {amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': 'Работа — выполнено: {done}, не удалось: {failed}, остановлено: {stopped}',
  'Inbox: {open} waiting (incidents: {incidents})': 'Входящие: в ожидании {open} (инциденты: {incidents})',
  'Stopped ({count}): {reason}': 'Остановлено ({count}): {reason}',
  'Start an ad campaign': 'Запустить рекламную кампанию',
  'Block time on the calendar': 'Занять время в календаре',
  'Read the calendar': 'Просмотреть календарь',
  'Run code': 'Выполнить код',
  'Add a note to a customer': 'Добавить заметку о клиенте',
  'Read customer records': 'Просмотреть данные клиентов',
  'Release to the live site': 'Опубликовать на основном сайте',
  'Release to the test site': 'Опубликовать на тестовом сайте',
  'Change a domain\'s nameservers': 'Сменить DNS-серверы домена',
  'Read a domain\'s records': 'Прочитать записи домена',
  'Change a domain\'s record': 'Изменить запись домена',
  'Write a document': 'Написать документ',
  'Sign a document': 'Подписать документ',
  'Buy a domain': 'Купить домен',
  'Transfer a domain': 'Передать домен',
  'Draft an email': 'Подготовить черновик письма',
  'Send an email': 'Отправить письмо',
  'List files': 'Просмотреть список файлов',
  'Read a file': 'Прочитать файл',
  'Describe a picture': 'Описать изображение',
  'Calculate in Python': 'Вычислить на Python',
  'Transfer money': 'Перевести деньги',
  'Propose a goal change': 'Предложить изменение цели',
  'Make a picture': 'Создать изображение',
  'Issue an invoice': 'Выставить счёт',
  'Pay an invoice': 'Оплатить счёт',
  'Read the books': 'Просмотреть бухгалтерию',
  'Read the mailbox': 'Прочитать почту',
  'Search what the company knows': 'Искать в знаниях компании',
  'Record a measure': 'Записать значение показателя',
  'Read product numbers': 'Просмотреть показатели продукта',
  'Ask you a question': 'Задать вам вопрос',
  'Write down a plan': 'Записать план',
  'Delete a record': 'Удалить запись',
  'Propose a code change': 'Предложить изменение кода',
  'Read the code': 'Прочитать код',
  'Destroy a server': 'Уничтожить сервер',
  'Read a skill': 'Прочитать навык',
  'Publish a post': 'Опубликовать пост',
  'Read text aloud': 'Прочитать текст вслух',
  'Turn speech into text': 'Преобразовать речь в текст',
  'Propose a new stage': 'Предложить новый этап',
  'Wait for work handed on': 'Дождаться переданной работы',
  'Hand work to another role': 'Передать работу другой роли',
  'File a ticket': 'Создать заявку',
  'List tickets': 'Просмотреть список заявок',
  'Check a service is up': 'Проверить, работает ли сервис',
  'Read a web page': 'Прочитать веб-страницу',
  'Open a web page': 'Открыть веб-страницу',
  'Search the web': 'Искать в вебе',
  'no stage': 'без этапа',
  'Explore': 'Исследование',
  'Validate': 'Проверка спроса',
  'Build': 'Разработка',
  'Launch': 'Выход на рынок',
  'Grow': 'Рост',
  'Wind down': 'Свернуть деятельность',
  'Monthly budget reached; the company is paused': 'Месячный бюджет исчерпан; компания на паузе',
  '{spent} of {limit} spent since {since}. No new task will start and no external action will run until you raise the ceiling or allow spending past it for a while, under Money.': 'С {since} потрачено {spent} из {limit}. Новые задачи не начнутся и внешние действия не будут выполняться, пока вы не поднимете лимит или не разрешите на время расходы сверх него в разделе «Деньги».',
  'Monthly budget is 80% spent': 'Месячный бюджет израсходован на 80%',
  '{spent} of {limit} spent since {since}. At 100% the company pauses.': 'С {since} потрачено {spent} из {limit}. При 100% компания встанет на паузу.',
  'Role {role} is paused for spending too fast': 'Роль {role} поставлена на паузу: слишком быстрые расходы',
  '{role} spent {spent} in the last hour, {multiple} times its usual {usual} an hour. It is paused before the monthly ceiling is reached, so there is money left to work with once you have found out why. Resume it when you have.': 'Роль {role} потратила за последний час {spent} — это {multiple}-кратное превышение её обычных {usual} в час. Она поставлена на паузу до того, как достигнут месячный лимит, чтобы, когда вы выясните причину, оставались деньги на работу. Выяснив её, возобновите роль.',
  'Daily model spend over threshold': 'Дневные расходы на модели выше порога',
  'Model spend today is {spent}, over the {limit} ceiling.': 'Расходы на модели сегодня — {spent}, это выше лимита {limit}.',
  'Task failure rate over threshold': 'Доля сбоев задач выше порога',
  '{failed} of {finished} tasks failed or stopped today ({rate}%), over the {limit}% threshold.': 'Задач, которые сегодня завершились сбоем или были остановлены: {failed} из {finished} ({rate}%) — это выше порога {limit}%.',
  'Unusual number of policy refusals': 'Необычно много отказов по политикам',
  'Actions refused by a policy today: {count}, over the threshold of {limit}. Either an agent is probing its limits or a policy is miscalibrated.': 'Действий, отклонённых политикой сегодня: {count} — это выше порога {limit}. Либо агент прощупывает границы дозволенного, либо политика настроена неверно.',
  'External writes failed verification': 'Внешние записи не прошли проверку',
  'Writes outside that reported success but read back differently: {count}. Something is changing them other than as asked.': 'Записей во внешние системы, которые сообщили об успехе, но при перечитывании оказались другими: {count}. Что-то меняет их не так, как было запрошено.',
  'A capability stopped being usable': 'Возможность перестала работать',
  'Tasks that could not start today because a capability their role needs failed its check: {count}. A credential has probably expired or a quota is used up.': 'Задач, которые сегодня не смогли начаться, потому что нужная их роли возможность не прошла проверку: {count}. Вероятно, истёк срок учётных данных или закончилась квота.',
  'A worker stopped reporting mid-run': 'Воркер перестал выходить на связь посреди запуска',
  'Runs that stopped reporting and were taken back today: {count}. The work was picked up again; the tokens they had already spent were not recovered.': 'Запусков, которые сегодня перестали выходить на связь и были возвращены: {count}. Работа подхвачена заново; уже потраченные ими токены не вернуть.',
  '{role} was refused {denials} times today, at the limit of {limit}. No task will run as this role until you lift the freeze. The usual causes are a missing capability grant, a policy the role\'s charter does not account for, or work the role was never equipped to do.': 'Роль {role} сегодня получила отказов: {denials} — это предел ({limit}). Ни одна задача не будет выполняться от имени этой роли, пока вы её не разморозите. Обычные причины: не выдано разрешение на возможность, политика, которую устав роли не учитывает, или работа, к которой роль никогда не была готова.',
  'Role {role} is frozen after repeated denials': 'Роль {role} заморожена после повторных отказов',
  'What it was refused: {capabilities}': 'В чём ей отказали: {capabilities}',
  'It is waiting for an approval, and none is open, so nothing you can answer will move it.': 'Задача ждёт одобрения, но открытого одобрения нет, так что никакой ваш ответ её не сдвинет.',
  'It is waiting for a review, and none is pending, so no reviewer and no decision of yours will move it.': 'Задача ждёт проверки, но ожидающей проверки нет, так что её не сдвинут ни проверяющий, ни ваше решение.',
  'It is parked until a window reopens, and the window never does.': 'Задача отложена до открытия окна, но окно так и не открывается.',
  'A task is waiting on nothing': 'Задача ждёт того, чего не будет',
  '"{task}" has been waiting since {since}. {why} Approve to run it again from where it stopped, or deny to cancel it.': 'Задача «{task}» ждёт с {since}. {why} Нажмите «Одобрить», чтобы снова запустить её с того места, где она остановилась, или «Отклонить», чтобы её отменить.',
  'A task keeps stopping the worker running it': 'Задача раз за разом выводит из строя воркер, который её выполняет',
  '"{task}" lost its worker {lost} times: each time the worker running it stopped answering before the work finished. What it had done is kept. It is halted so it cannot take another worker down; run it again once the cause is found, or cancel it.': 'Задача «{task}» теряла воркер уже несколько раз (всего: {lost}): каждый раз воркер, выполнявший её, переставал отвечать до завершения работы. Сделанное сохранено. Задача остановлена, чтобы не вывести из строя другой воркер; запустите её снова, когда найдёте причину, или отмените.',
  '{services} stayed unreachable, and the work that needs it stopped': 'Нет связи: {services} — работа, которой это нужно, остановлена',
  'The task waited about {minutes} minutes, looking again each time, and has stopped. Once the service answers, run it again.': 'Задача ждала около {minutes} мин, каждый раз проверяя снова, и остановилась. Когда сервис ответит, запустите её снова.',
  'It was tried {tries} times over about {minutes} minutes.': 'Попыток: {tries} примерно за {minutes} мин.',
  'This role can take actions that cannot be undone, so the run was not silently moved to a different model.': 'Эта роль может выполнять необратимые действия, поэтому запуск не был молча переведён на другую модель.',
  'No fallback model is left for this role.': 'Для этой роли не осталось резервной модели.',
  'Model {model} failed and the run was not moved': 'Модель {model} дала сбой, а запуск не был переведён на другую',
  'External write failed verification': 'Внешняя запись не прошла проверку',
  'The task wrote to an outside service and read it back, and what it read did not match. Look at the place it wrote to before you run it again: the write may have happened.': 'Задача записала данные во внешний сервис и прочитала их обратно, но прочитанное не совпало. Прежде чем запускать её снова, проверьте место, куда она писала: запись могла пройти.',
  'Review deadlocked after {rounds} revisions: {capability}': 'Проверка зашла в тупик (доработок: {rounds}): {capability}',
  'The role and its reviewer did not agree on {capability}.': 'Роль и её проверяющий не пришли к согласию по «{capability}».',
  'The reviewer\'s last note: {note}': 'Последнее замечание проверяющего: {note}',
  'The reviewer left no note.': 'Проверяющий не оставил замечаний.',
  'What it was judged against: {criteria}': 'Критерии оценки: {criteria}',
  'Review produced no usable verdict: {capability}': 'Проверка не дала пригодного вердикта: {capability}',
  'The reviewing task ended without a decision that could be read. The proposed action is still blocked and needs your judgement.': 'Проверяющая задача завершилась без решения, которое можно прочитать. Предложенное действие по-прежнему заблокировано и ждёт вашего решения.',
  'another stage': 'другой этап',
  'Either answer only closes this: the company stays in the {stage} stage.': 'Любой ответ лишь закроет этот элемент: компания останется на этапе «{stage}».',
  'Either answer only closes this: the company stays without a stage.': 'Любой ответ лишь закроет этот элемент: компания останется без этапа.',
  'To move it anyway, set the stage on the Overview.': 'Чтобы всё же перевести компанию, задайте этап на странице «Обзор».',
  '{reviewer} stopped a proposal to move the company from {from} to {to}': 'Проверяющий {reviewer} остановил предложение перевести компанию с «{from}» на «{to}»',
  '{reviewer} reviewed it before you and stopped it:': 'Проверяющий {reviewer} рассмотрел его раньше вас и остановил:',
  'No reason was given.': 'Причина не указана.',
  'What was proposed:': 'Что было предложено:',
  'The company stays in the {stage} stage.': 'Компания останется на этапе «{stage}».',
  'The company stays without a stage.': 'Компания останется без этапа.',
  'Move the company from {from} to {to}?': 'Перевести компанию с «{from}» на «{to}»?',
  'Reviewed by {reviewer} before you:': 'Проверяющий {reviewer} рассмотрел это раньше вас:',
  'The schedule "{schedule}" keeps producing the same result': 'Расписание «{schedule}» раз за разом даёт один и тот же результат',
  'Its last {runs} runs all ended with the same output. That is sometimes exactly right -- a report with nothing new to say -- and often a schedule that stopped doing anything useful while still being paid for. Deny to turn it off; approve to keep it running and not be asked about this result again.': 'Все последние запуски (их {runs}) завершились одним и тем же результатом. Иногда это ровно то, что нужно, — отчёт, которому нечего добавить, — но часто это расписание, которое перестало делать что-то полезное, хотя за него всё ещё платят. «Отклонить» — выключить его; «Одобрить» — оставить работать и больше не спрашивать об этом результате.',
  'Capability {capability} failed preflight': 'Возможность «{capability}» не прошла предварительную проверку',
  'Work that needs it is stopped rather than started: fix the cause, then run that work again. The usual causes are an expired or wrongly scoped credential, a quota used up, or an address that is wrong.': 'Работа, которой она нужна, останавливается, а не запускается: устраните причину, затем запустите эту работу снова. Обычные причины: истёкшие или выданные с неверными правами учётные данные, исчерпанная квота или неверный адрес.',
  'Batch guard stopped {capability}': 'Контроль пакетных вызовов остановил «{capability}»',
  'It did not match the plan its run recorded. Nothing was sent, and no service was called.': 'Вызов не совпал с планом, записанным его запуском. Ничего не отправлено, ни один сервис не вызван.',
  '{role} was asked first and has had {minutes} minutes.': 'Сначала спросили роль {role}; у неё было {minutes} мин.',
  '{role} is not a role in this company, so this came to you at once.': 'Роли {role} в этой компании нет, поэтому это сразу пришло к вам.',
  '{role} could not be given this: the company has no active goal or project to hang it from.': 'Это не удалось передать роли {role}: у компании нет активной цели или проекта, к которым это можно привязать.',
  '{role} could not be given this ({record}), so this came to you at once.': 'Это не удалось передать роли {role} ({record}), поэтому это сразу пришло к вам.',
  '{role} stopped without an account of what it did ({why}).': 'Роль {role} остановилась без отчёта о сделанном ({why}).',
  '{role} finished without an account of what it did.': 'Роль {role} завершила работу без отчёта о сделанном.',
  '{role} failed without an account of what it did.': 'Роль {role} дала сбой без отчёта о сделанном.',
  '{role} was stopped without an account of what it did.': 'Роль {role} остановили без отчёта о сделанном.',
  'Proposed change to the {kind} "{goal}"': 'Предложено изменение: {kind} «{goal}»',
  'Currently: {statement}': 'Сейчас: {statement}',
  'Currently: {statement} ({status})': 'Сейчас: {statement} ({status})',
  'Proposed: {statement}': 'Предлагается: {statement}',
  'Proposed status: {status}': 'Предлагаемый статус: {status}',
  'Reason given: {reason}': 'Указанная причина: {reason}',
  'Record an entry in the books': 'Внести проводку в книги',
  'Record a customer or a deal': 'Записать клиента или сделку',
  'Not sent on its own: {reason}': 'Не отправлено само: {reason}',
  'it answers a conversation other than the one this work began with': 'ответ относится к другому разговору, а не к тому, с которого началась эта работа',
  'it named no passage of a document for customers': 'в ответе не указан ни один фрагмент документа для клиентов',
  'it answers from a document not marked for customers': 'ответ основан на документе, не отмеченном для клиентов',
  'it says a figure the documents and the customer did not: {detail}': 'в ответе есть число, которого нет ни в документах, ни у клиента: {detail}',
  'it gives an address or link the documents and the customer did not: {detail}': 'в ответе есть адрес или ссылка, которых нет ни в документах, ни у клиента: {detail}',
  'there have been six answers on its own in this conversation in the last hour': 'в этом разговоре за последний час уже было шесть ответов, отправленных самостоятельно',
  'the check found it is about a refund': 'проверка нашла, что речь о возврате денег',
  'the check found it offers a price or terms of its own': 'проверка нашла, что ответ предлагает собственную цену или условия',
  'the check found it answers a serious complaint': 'проверка нашла, что ответ касается серьёзной жалобы',
  'the check found it touches the law': 'проверка нашла, что ответ затрагивает юридические вопросы',
  'the check found it gives or asks for personal data': 'проверка нашла, что ответ сообщает или запрашивает персональные данные',
  'the check found it promises something the documents do not': 'проверка нашла, что ответ обещает то, чего нет в документах',
  'the check could not judge it': 'проверка не смогла его оценить',
  'the check found something in it the documents do not say': 'проверка нашла в ответе то, чего не говорят документы',
  '{role} proposes the schedule {name}': '{role} предлагает расписание {name}',
  'Each run: {instruction}': 'Каждый запуск: {instruction}',
  'Done by: {role}': 'Выполняет: {role}',
  'When: {cron} ({timezone}); the next runs are {runs}': 'Когда: {cron} ({timezone}); следующие запуски — {runs}',
  'Approving it makes the schedule and starts it; it can be turned off or changed under Team, Schedules.': 'Одобрение создаёт расписание и запускает его; его можно выключить или изменить в разделе Команда, Расписания.',
  'No schedule is made.': 'Расписание не создаётся.',
  'Propose a schedule': 'Предложить расписание',
  'Approving it changes the goal; until then the work carries on under the goal as it is.': 'Одобрение изменит цель; до тех пор работа идёт по цели в её нынешнем виде.',
  'The goal stays as it is.': 'Цель остаётся прежней.',
  'mission': 'миссия',
  'objective': 'цель',
  'key result': 'ключевой результат',
  'Active': 'Действует',
  'Met': 'Достигнута',
  'Abandoned': 'Снята',
  'This work asked for it at tier {tier}, and policy {policies} requires your approval.': 'Работа запросила это действие на уровне {tier}, а политика {policies} требует вашего одобрения.',
  'This work asked for it at tier {tier}, and the task began with content from outside the company.': 'Работа запросила это действие на уровне {tier}, а задача началась с контента извне компании.',
  'This work asked for it at tier {tier}, and the work read content from outside the company before asking.': 'Работа запросила это действие на уровне {tier}, а перед этим прочитала контент извне компании.',
  'This work asked for it at tier {tier}, after the work read content from outside the company, and the guardian asked you first: {reason}': 'Работа запросила это действие на уровне {tier} после того, как прочитала контент извне компании, и страж сначала спросил вас: {reason}',
  'it doubted this call before, and you allowed it once': 'он уже сомневался в этом вызове, и вы один раз его разрешили',
  'This work asked for it at tier {tier}, which cannot be reversed.': 'Работа запросила это действие на уровне {tier} — такие действия необратимы.',
  'You approved this once already, and the worker carrying it out stopped before it could say whether it happened: it may already have happened. Check before approving it again.': 'Вы уже одобряли это один раз, но воркер, который это выполнял, остановился, не успев сообщить, произошло ли это: возможно, это уже произошло. Проверьте, прежде чем одобрять снова.',
  'What this is for — {goals}': 'Для чего это — {goals}',
  'The task halts and no external change is made.': 'Задача остановится, и никаких внешних изменений не будет.',
  'Scored against {total} references: {passed} passed, {failed} failed.': 'Оценка по эталонам ({total}): пройдено — {passed}, не пройдено — {failed}.',
  'This role has fewer than {minimum} accepted references, so the change is unscored. That is not the same as passing.': 'У этой роли меньше {minimum} принятых эталонов, поэтому изменение не оценивается. Это не то же самое, что «пройдено».',
  'The role keeps working exactly as it does now.': 'Роль продолжит работать ровно так же, как сейчас.',
  '{role} asks: {question}': '{role} спрашивает: {question}',
  'The run did not say more than the question.': 'Запуск не сказал ничего, кроме самого вопроса.',
  'The task is stopped, and nothing it was going to do happens.': 'Задача остановлена, и ничего из того, что она собиралась сделать, не произойдёт.',
  'You proposed it.': 'Его предложили вы.',
  'It came with a bundle.': 'Он пришёл в составе пакета.',
  'An agent proposed it.': 'Его предложил агент.',
  'It was learned from the company\'s work.': 'Он извлечён из работы компании.',
  'Skill "{skill}", version {version}': 'Навык «{skill}», версия {version}',
  'The reviewer approved it: {note}': 'Проверяющий одобрил его: {note}',
  'The reviewer approved it.': 'Проверяющий одобрил его.',
  'Nothing changes; the current version of the skill stays in force.': 'Ничего не изменится; текущая версия навыка остаётся в силе.',
  'Skills the bundle "{bundle}" brings: {count}': 'Навыки, которые приносит пакет «{bundle}»: {count}',
  'The reviewer read them all and approved these:': 'Проверяющий прочёл их все и одобрил эти:',
  'It turned these down, and they stay off:': 'Эти он отклонил, и они остаются выключенными:',
  'Approve to switch them all on, or deny to turn them all down. To decide one at a time, open the Skills page.': '«Одобрить» — включить их все; «Отклонить» — отклонить их все. Чтобы решить по каждому отдельно, откройте раздел «Навыки».',
  'Nothing changes; none of these skills is switched on.': 'Ничего не изменится; ни один из этих навыков не будет включён.',
  'I am {ceo}, and I run {company} for you. Three things before we start: what does {company} sell, and to whom? How much may it spend in a month? And what should its first piece of work be -- or shall I suggest one?': 'Я {ceo}, и я веду компанию {company} для вас. Три вопроса, прежде чем начнём: что продаёт компания {company} и кому? Сколько она может тратить в месяц? И какой должна быть её первая задача — или мне предложить свою?',
  'Read a customer conversation': 'Прочитать переписку с клиентом',
  'Reply to a customer': 'Ответить клиенту',
  'Read a page in the browser': 'Прочитать страницу в браузере',
  'Fill in a page in the browser': 'Заполнить страницу в браузере',
  'Ask you to take over the browser': 'Попросить вас взять браузер под управление',
};
