/**
 * Basa Sunda: what the platform itself says to the owner outside the console
 * (src/owner/say.ts), keyed by its English.
 *
 * Lemes, the owner addressed as "anjeun", with the terms of the console's
 * glossary (console/src/locales/su.ts), so a button on the phone says what
 * the same button says in the panel: Satujuan, Tolak, Naros.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'Insidén: {title}',
  'Done: {goal}': 'Réngsé: {goal}',
  'Stopped before finishing: {goal}': 'Eureun sateuacan réngsé: {goal}',
  'Not done: {goal}': 'Teu dilaksanakeun: {goal}',
  'Why: {reason}': 'Alesanana: {reason}',
  'a task': 'hiji tugas',
  'Approval needed: {title}': 'Meryogikeun persetujuan: {title}',
  '{summary} — if denied: {consequence}': '{summary} — upami ditolak: {consequence}',
  '{role} asks:': '{role} naros:',
  'If denied:': 'Upami ditolak:',
  'Expires:': 'Kadaluwarsa:',
  'This one is decided in the app.': 'Anu ieu diputuskeun dina aplikasi.',
  'Open in PALUGADA': 'Buka di PALUGADA',
  'Approve': 'Satujuan',
  'Deny': 'Tolak',
  'Ask': 'Naros',
  'Approved. Nothing left to press here.': 'Disatujuan. Henteu aya deui anu kedah dipencét di dieu.',
  'Denied. Nothing left to press here.': 'Ditolak. Henteu aya deui anu kedah dipencét di dieu.',
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    'Kadaluwarsa tanpa waleran. Henteu ngawaler hartosna nolak, janten henteu aya anu dilaksanakeun.',
  'This bot only answers to its owner.': 'Bot ieu mung ngawaler pamilikna.',
  'That one has to be approved in the app.': 'Anu éta kedah disatujuan dina aplikasi.',
  'That could not be recorded.': 'Éta henteu tiasa dicatet.',
  'That item no longer exists.': 'Item éta parantos henteu aya.',
  'What do you want to ask about "{title}"? Reply to this message.':
    'Naon anu badé ditaroskeun ku anjeun ngeunaan "{title}"? Bales pesen ieu.',
  'Your question': 'Patarosan anjeun',
  'Type your question as a reply.': 'Ketik patarosan anjeun minangka balesan.',
  'Asked. The answer will be on the item in the app.': 'Parantos ditaroskeun. Waleranana bakal aya dina item éta di aplikasi.',
  'Answer': 'Waler',
  'Answer in words': 'Waler ku kecap',
  'That choice is not on this question.': 'Pilihan éta henteu aya dina patarosan ieu.',
  'Chosen: {choice}.': 'Dipilih: {choice}.',
  'Stop the task': 'Eureunkeun tugas',
  'Your answer to "{question}"? Reply to this message.': 'Waleran anjeun kanggo "{question}"? Bales pesen ieu.',
  'Your answer': 'Waleran anjeun',
  'Type your answer as a reply.': 'Ketik waleran anjeun minangka balesan.',
  'Answered. The task carries on with it.': 'Parantos diwaler. Tugas diteraskeun nganggo waleran éta.',
  'That is too long for one question; keep it under {max} characters.':
    'Éta kapanjangan kanggo hiji patarosan; damel kirang ti {max} aksara.',
  '[a key, not kept]': '[hiji konci, henteu disimpen]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    'Éta katingalna konci, janten ku abdi henteu disimpen sareng henteu dikintun ka mana waé. Konci dieusian dina kolom anu disegel dina kartu, atanapi dina kacana di Pamasangan ieu: sebatkeun kanggo naon, teras kartuna ku abdi dihaturkeun ka payuneun anjeun.',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'Teu acan aya modél anu disetél, janten abdi teu acan tiasa mikir. Pilih hiji di Pamasangan ieu, Modél AI; saparantos éta abdi tiasa ngabantos sadaya anu sanés.',
  'The model did not answer: {reason}': 'Modél henteu ngawaler: {reason}',
  'Here is what I propose.': 'Ieu usul abdi.',
  'I have nothing to add.': 'Henteu aya anu kedah ditambihkeun ku abdi.',
  '{name}, CEO of {company}': '{name}, CEO {company}',
  'That could not be answered: {reason}': 'Éta henteu tiasa diwaler: {reason}',
  'I read text and voice notes.': 'Abdi maos téks sareng pesen soanten.',
  'Now talking to {name}.': 'Ayeuna nyarios sareng {name}.',
  'Choose whom to talk to.': 'Pilih batur nyarios anjeun.',
  'Choose whom to talk to': 'Pilih batur nyarios anjeun',
  'Talk to PALUGADA about the whole deployment': 'Nyarios sareng PALUGADA ngeunaan sakumna pamasangan',
  'Who you are talking to, and how': 'Saha batur nyarios anjeun, sareng carana',
  'Stopped.': 'Parantos eureun.',
  'Write here to talk to {name}.': 'Serat di dieu kanggo nyarios sareng {name}.',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    'Anjeun nuju nyarios sareng {name}. Serat, atanapi kintun pesen soanten. /ceo kanggo milih batur nyarios; /palugada kanggo nyarios sareng PALUGADA ngeunaan sakumna pamasangan.',
  'You said: "{words}"': 'Anjeun nyarios: "{words}"',
  'in the app': 'dina aplikasi',
  'Apply: {summary}': 'Terapkeun: {summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    'Teu acan aya anu tiasa ngadangu soanten: pilih panyadia dina aplikasi, di Pamasangan ieu, Pakakas, Ngadangukeun.',
  'That recording is too long; keep a voice note under {max} MB.': 'Rékaman éta kapanjangan; damel pesen soanten kirang ti {max} MB.',
  'I could not make out any words in that.': 'Abdi henteu tiasa nangkep kecap naon waé dina éta.',
  'Done: {summary}': 'Réngsé: {summary}',
  'That one is applied in the app.': 'Anu éta diterapkeun dina aplikasi.',
  'That card no longer exists.': 'Kartu éta parantos henteu aya.',
  'That card was already applied.': 'Kartu éta parantos diterapkeun.',
  'That card was dismissed.': 'Kartu éta parantos disisihkeun.',
  'That card failed when it was applied.': 'Kartu éta gagal nalika diterapkeun.',
  'That could not be done: {reason}': 'Éta henteu tiasa dilaksanakeun: {reason}',
  'Choose': 'Pilih',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    'Naon anu badé ditaroskeun ku anjeun ngeunaan "{title}"? Bales pesen ieu nganggo patarosan anjeun.',
  'Your answer to "{question}"? Reply to this message with your answer.':
    'Waleran anjeun kanggo "{question}"? Bales pesen ieu nganggo waleran anjeun.',
  'I read text messages here.': 'Di dieu abdi maos pesen téks.',
  'Apply one of these here:': 'Terapkeun salah sahiji tina ieu di dieu:',
  'Apply {number}': 'Terapkeun {number}',
  'Signed in to {provider} for the {alias} key': 'Parantos lebet ka {provider} kanggo konci {alias}',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'Wangsul ka PALUGADA: divisi éta ayeuna nyepeng konci ieu, sareng konci diénggalkeun sateuacan séép. Tab ieu tiasa ditutup.',
  'Signed in to {name}': 'Parantos lebet ka {name}',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'Wangsul ka PALUGADA kanggo milih pakakas mana anu kénging dianggé ku peran. Tab ieu tiasa ditutup.',
  'Not signed in': 'Teu acan lebet',
  'Recorded: approved.': 'Kacatet: disatujuan.',
  'Recorded: denied.': 'Kacatet: ditolak.',
  'Recorded: asked.': 'Kacatet: ditaroskeun.',
  'Asked. Nothing left to press here.': 'Parantos ditaroskeun. Henteu aya deui anu kedah dipencét di dieu.',
  'Withdrawn: the task it was asking about has finished.': 'Ditarik: tugas anu ditaroskeun parantos réngsé.',
  'Withdrawn: the task it was asking about has failed.': 'Ditarik: tugas anu ditaroskeun gagal.',
  'Withdrawn: the task it was asking about was stopped.': 'Ditarik: tugas anu ditaroskeun parantos dieureunkeun.',
  'Withdrawn: the task it was asking about was cancelled.': 'Ditarik: tugas anu ditaroskeun parantos dibolaykeun.',
  'Decided. Nothing left to press here.': 'Diputuskeun. Henteu aya deui anu kedah dipencét di dieu.',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': 'Ditarik: agén ngarobih usulna sareng nyuhunkeun persetujuan deui kanggo usul énggal éta.',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': 'Ditarik: pausahaan parantos henteu aya dina tahapan anu badé ditinggalkeun numutkeun usul ieu.',
  'Withdrawn: it was already decided in the app.': 'Ditarik: parantos diputuskeun dina aplikasi.',
  'Withdrawn. Nothing left to press here.': 'Ditarik. Henteu aya deui anu kedah dipencét di dieu.',
  'company': 'perusahaan',
  'Work stopped: the {account} account is out of tokens': 'Padamelan eureun: token akun {account} parantos seep',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': '“{work}” eureun margi akun {account} parantos nganggo {spent} tina {max} token. Naékkeun watesna di Artos, teras buka tugasna sareng pencét Teraskeun: tugas neraskeun ti tempat eureunna.',
  'Withdrawn: you continued the task it was about.': 'Ditarik: anjeun parantos neraskeun tugas anu dimaksud.',
  'Broke its contract': 'Ngalanggar kontrakna',
  'Refused by a policy': 'Ditolak ku kawijakan',
  'Out of budget': 'Anggaran séép',
  'Handed on too many times': 'Kaseueuran dipasrahkeun',
  'Missed its deadline': 'Kaliwat wates waktosna',
  'Its result did not check out': 'Hasilna henteu lulus pamariksaan',
  'A capability it needs is down': 'Kamampuh anu diperyogikeun nuju pareum',
  'No runtime could take it': 'Henteu aya pangolah anu tiasa nampi',
  'Went in a circle': 'Muter-muter',
  'Split into too many sub-tasks': 'Dibagi janten subtugas anu kaseueuran',
  'Wrote more than its role allows one run': 'Nyerat langkung seueur tibatan anu diidinan ku peranna kanggo hiji palaksanaan',
  'Your approval was not given in time': 'Persetujuan anjeun henteu dugi dina waktosna',
  'Stopped by you': 'Dieureunkeun ku anjeun',
  'Cancelled by you': 'Dibolaykeun ku anjeun',
  'The company is frozen': 'Pausahaan dibekukeun',
  'Its record did not match on replay': 'Catetanana henteu cocog nalika diputer deui',
  'It kept stopping the worker running it': 'Tugas ieu terus-terusan ngajantenkeun pagawé anu ngajalankeunana eureun',
  'Not done': 'Teu dilaksanakeun',
  'Task failed': 'Tugas gagal',
  'Digest for {day}': 'Kasimpulan {day}',
  'Spent: {amount}': 'Kaanggé: {amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': 'Padamelan: {done} réngsé, {failed} gagal, {stopped} eureun',
  'Inbox: {open} waiting (incidents: {incidents})': 'Kotak asup: {open} ngantosan (insidén: {incidents})',
  'Stopped ({count}): {reason}': 'Eureun ({count}): {reason}',
  'Start an ad campaign': 'Mimitian kampanye iklan',
  'Block time on the calendar': 'Cadangkeun waktos dina kalénder',
  'Read the calendar': 'Aos kalénder',
  'Run code': 'Jalankeun kode',
  'Add a note to a customer': 'Tambihkeun catetan kana data palanggan',
  'Read customer records': 'Aos data palanggan',
  'Release to the live site': 'Luncurkeun ka situs utama',
  'Release to the test site': 'Luncurkeun ka situs uji',
  'Change a domain\'s nameservers': 'Robih server DNS domain',
  'Read a domain\'s records': 'Aos catetan domain',
  'Change a domain\'s record': 'Robih catetan domain',
  'Write a document': 'Serat dokumén',
  'Sign a document': 'Tandatanganan dokumén',
  'Buy a domain': 'Mésér domain',
  'Transfer a domain': 'Pindahkeun domain',
  'Draft an email': 'Damel draf email',
  'Send an email': 'Kintun email',
  'List files': 'Témbongkeun daptar file',
  'Read a file': 'Maca file',
  'Describe a picture': 'Ngajelaskeun gambar',
  'Calculate in Python': 'Ngitung ku Python',
  'Transfer money': 'Kintun artos',
  'Propose a goal change': 'Usulkeun parobihan udagan',
  'Make a picture': 'Damel gambar',
  'Issue an invoice': 'Kaluarkeun tagihan',
  'Pay an invoice': 'Bayar tagihan',
  'Read the books': 'Aos catetan keuangan',
  'Read the mailbox': 'Aos kotak email',
  'Search what the company knows': 'Milarian pangaweruh pausahaan',
  'Record a measure': 'Catet ukuran',
  'Read product numbers': 'Aos angka produk',
  'Ask you a question': 'Naros ka anjeun',
  'Write down a plan': 'Catet rencana',
  'Delete a record': 'Pupus catetan',
  'Propose a code change': 'Usulkeun parobihan kode',
  'Read the code': 'Aos kode',
  'Destroy a server': 'Ancurkeun server',
  'Read a skill': 'Aos kaparigelan',
  'Publish a post': 'Medalkeun kiriman',
  'Read text aloud': 'Aoskeun téks kalayan soanten',
  'Turn speech into text': 'Robih ucapan janten téks',
  'Propose a new stage': 'Usulkeun tahapan énggal',
  'Wait for work handed on': 'Antosan padamelan anu dipasrahkeun',
  'Hand work to another role': 'Pasrahkeun padamelan ka peran sanés',
  'File a ticket': 'Damel tikét',
  'List tickets': 'Témbongkeun daptar tikét',
  'Check a service is up': 'Pariksa naha layanan jalan',
  'Read a web page': 'Aos kaca wéb',
  'Open a web page': 'Buka kaca wéb',
  'Search the web': 'Milarian di wéb',
  'no stage': 'tanpa tahapan',
  'Explore': 'Ngajajah',
  'Validate': 'Nguji',
  'Build': 'Ngawangun',
  'Launch': 'Ngaluncurkeun',
  'Grow': 'Mekarkeun',
  'Wind down': 'Nutup usaha',
  'Monthly budget reached; the company is paused': 'Anggaran bulanan parantos séép; pausahaan direureuhkeun',
  '{spent} of {limit} spent since {since}. No new task will start and no external action will run until you raise the ceiling or allow spending past it for a while, under Money.': '{spent} tina {limit} parantos kaanggé ti saprak {since}. Moal aya tugas énggal anu dimimitian sareng moal aya tindakan ka luar anu dijalankeun dugi ka anjeun naékkeun watesna atanapi ngidinan waragad ngaleuwihan wates éta samentawis, di Artos.',
  'Monthly budget is 80% spent': 'Anggaran bulanan parantos kaanggé 80%',
  '{spent} of {limit} spent since {since}. At 100% the company pauses.': '{spent} tina {limit} parantos kaanggé ti saprak {since}. Dina 100%, pausahaan bakal direureuhkeun.',
  'Role {role} is paused for spending too fast': 'Peran {role} direureuhkeun kusabab waragadna gancang teuing',
  '{role} spent {spent} in the last hour, {multiple} times its usual {usual} an hour. It is paused before the monthly ceiling is reached, so there is money left to work with once you have found out why. Resume it when you have.': '{role} nganggé {spent} dina sajam pamungkas, {multiple} kali lipet tina biasana, nyaéta {usual} sajam. Peran ieu direureuhkeun sateuacan wates bulanan kahontal, supados masih aya artos kanggo damel saparantos anjeun terang sababna. Teraskeun peran ieu saparantos anjeun terang.',
  'Daily model spend over threshold': 'Waragad modél sapopoé ngaleuwihan wates',
  'Model spend today is {spent}, over the {limit} ceiling.': 'Waragad modél dinten ieu {spent}, ngaleuwihan wates {limit}.',
  'Task failure rate over threshold': 'Rasio gagal tugas ngaleuwihan wates',
  '{failed} of {finished} tasks failed or stopped today ({rate}%), over the {limit}% threshold.': '{failed} tina {finished} tugas gagal atanapi eureun dinten ieu ({rate}%), ngaleuwihan wates {limit}%.',
  'Unusual number of policy refusals': 'Jumlah panolakan kawijakan teu biasa',
  'Actions refused by a policy today: {count}, over the threshold of {limit}. Either an agent is probing its limits or a policy is miscalibrated.': 'Tindakan anu ditolak ku kawijakan dinten ieu: {count}, ngaleuwihan wates {limit}. Boh aya agén anu nuju nguji watesna, boh aya kawijakan anu setélanana teu leres.',
  'External writes failed verification': 'Panyeratan ka luar teu lulus verifikasi',
  'Writes outside that reported success but read back differently: {count}. Something is changing them other than as asked.': 'Panyeratan di luar anu dilaporkeun hasil nanging béda nalika diaos deui: {count}. Aya anu ngarobihna, henteu sapertos anu disuhunkeun.',
  'A capability stopped being usable': 'Hiji kamampuh teu tiasa dianggé deui',
  'Tasks that could not start today because a capability their role needs failed its check: {count}. A credential has probably expired or a quota is used up.': 'Tugas anu teu tiasa dimimitian dinten ieu kusabab kamampuh anu diperyogikeun ku peranna teu lulus pamariksaan: {count}. Panginten aya kredénsial anu kadaluwarsa atanapi kuota anu séép.',
  'A worker stopped reporting mid-run': 'Hiji pagawé eureun ngalaporkeun di tengah palaksanaan',
  'Runs that stopped reporting and were taken back today: {count}. The work was picked up again; the tokens they had already spent were not recovered.': 'Palaksanaan anu eureun ngalaporkeun sareng dicandak deui dinten ieu: {count}. Padamelanana parantos diteraskeun deui; token anu parantos kaanggé henteu wangsul.',
  '{role} was refused {denials} times today, at the limit of {limit}. No task will run as this role until you lift the freeze. The usual causes are a missing capability grant, a policy the role\'s charter does not account for, or work the role was never equipped to do.': '{role} ditolak {denials} kali dinten ieu, dugi ka wates {limit}. Moal aya tugas anu jalan minangka peran ieu dugi ka anjeun ngacairkeunana. Sabab anu biasa nyaéta idin kamampuh anu teu acan dipasihkeun, kawijakan anu henteu diitung dina piagam peran ieu, atanapi padamelan anu peran ieu henteu kantos disayagikeun pikeun ngalaksanakeunana.',
  'Role {role} is frozen after repeated denials': 'Peran {role} dibekukeun saparantos ditolak sababaraha kali',
  'What it was refused: {capabilities}': 'Anu ditolak: {capabilities}',
  'It is waiting for an approval, and none is open, so nothing you can answer will move it.': 'Tugas ieu ngantosan persetujuan, nanging henteu aya anu kabuka, janten henteu aya waleran anjeun anu tiasa ngagerakkeunana.',
  'It is waiting for a review, and none is pending, so no reviewer and no decision of yours will move it.': 'Tugas ieu ngantosan tilikan, nanging henteu aya tilikan anu nuju dilaksanakeun, janten henteu aya panilik atanapi putusan anjeun anu tiasa ngagerakkeunana.',
  'It is parked until a window reopens, and the window never does.': 'Tugas ieu disisihkeun dugi ka waktos anu ditangtoskeun dibuka deui, nanging waktos éta henteu kantos dibuka.',
  'A task is waiting on nothing': 'Hiji tugas ngantosan anu teu aya',
  '"{task}" has been waiting since {since}. {why} Approve to run it again from where it stopped, or deny to cancel it.': '“{task}” parantos ngantosan ti saprak {since}. {why} Satujuan kanggo ngajalankeunana deui ti tempat eureunna, atanapi Tolak kanggo ngabolaykeunana.',
  'A task keeps stopping the worker running it': 'Hiji tugas terus-terusan ngajantenkeun pagawé anu ngajalankeunana eureun',
  '"{task}" lost its worker {lost} times: each time the worker running it stopped answering before the work finished. What it had done is kept. It is halted so it cannot take another worker down; run it again once the cause is found, or cancel it.': '“{task}” kaleungitan pagawéna {lost} kali: unggal kali, pagawé anu ngajalankeunana eureun ngawaler sateuacan padamelan réngsé. Naon anu parantos dilakukeun tetep disimpen. Tugas ieu dimandegkeun supados henteu ngajantenkeun pagawé sanés eureun; jalankeun deui saparantos sababna kapendak, atanapi bolaykeun.',
  '{services} stayed unreachable, and the work that needs it stopped': '{services} tetep teu tiasa dihubungi, sareng padamelan anu meryogikeunana eureun',
  'The task waited about {minutes} minutes, looking again each time, and has stopped. Once the service answers, run it again.': 'Tugas ieu ngantosan kirang langkung {minutes} menit, mariksa deui unggal waktos, sareng ayeuna parantos eureun. Saparantos layanan éta ngawaler, jalankeun deui.',
  'It was tried {tries} times over about {minutes} minutes.': 'Parantos dicobian {tries} kali salami kirang langkung {minutes} menit.',
  'This role can take actions that cannot be undone, so the run was not silently moved to a different model.': 'Peran ieu tiasa ngalakukeun tindakan anu teu tiasa dibalikeun, janten palaksanaan ieu henteu dipindahkeun cicingeun ka modél sanés.',
  'No fallback model is left for this role.': 'Teu aya deui modél cadangan kanggo peran ieu.',
  'Model {model} failed and the run was not moved': 'Modél {model} gagal sareng palaksanaanana henteu dipindahkeun',
  'External write failed verification': 'Panyeratan ka luar teu lulus verifikasi',
  'The task wrote to an outside service and read it back, and what it read did not match. Look at the place it wrote to before you run it again: the write may have happened.': 'Tugas ieu nyerat ka layanan luar teras maos deui, sareng naon anu dibaca henteu cocog. Tingali heula tempat anu diserat sateuacan anjeun ngajalankeunana deui: panyeratan éta panginten parantos kajantenan.',
  'Review deadlocked after {rounds} revisions: {capability}': 'Tilikan buntu saparantos {rounds} révisi: {capability}',
  'The role and its reviewer did not agree on {capability}.': 'Peran sareng panilikna henteu satuju ngeunaan {capability}.',
  'The reviewer\'s last note: {note}': 'Catetan pamungkas panilik: {note}',
  'The reviewer left no note.': 'Panilik henteu ninggalkeun catetan.',
  'What it was judged against: {criteria}': 'Anu dijantenkeun patokan peunteunna: {criteria}',
  'Review produced no usable verdict: {capability}': 'Tilikan henteu ngahasilkeun putusan anu tiasa dianggé: {capability}',
  'The reviewing task ended without a decision that could be read. The proposed action is still blocked and needs your judgement.': 'Tugas tilikan réngsé tanpa putusan anu tiasa diaos. Tindakan anu diusulkeun masih ditahan sareng meryogikeun pertimbangan anjeun.',
  'another stage': 'tahapan sanés',
  'Either answer only closes this: the company stays in the {stage} stage.': 'Waleran mana waé ngan ukur nutup ieu: pausahaan tetep dina tahapan {stage}.',
  'Either answer only closes this: the company stays without a stage.': 'Waleran mana waé ngan ukur nutup ieu: pausahaan tetep tanpa tahapan.',
  'To move it anyway, set the stage on the Overview.': 'Upami tetep badé mindahkeun, setél tahapanana di Ringkesan.',
  '{reviewer} stopped a proposal to move the company from {from} to {to}': '{reviewer} ngeureunkeun usul pikeun mindahkeun pausahaan ti {from} ka {to}',
  '{reviewer} reviewed it before you and stopped it:': '{reviewer} parantos nilik ieu sateuacan anjeun sareng ngeureunkeunana:',
  'No reason was given.': 'Henteu aya alesan anu dipasihkeun.',
  'What was proposed:': 'Anu diusulkeun:',
  'The company stays in the {stage} stage.': 'Pausahaan tetep dina tahapan {stage}.',
  'The company stays without a stage.': 'Pausahaan tetep tanpa tahapan.',
  'Move the company from {from} to {to}?': 'Pindahkeun pausahaan ti {from} ka {to}?',
  'Reviewed by {reviewer} before you:': 'Ditilik ku {reviewer} sateuacan anjeun:',
  'The schedule "{schedule}" keeps producing the same result': 'Jadwal “{schedule}” terus-terusan masihan hasil anu sami',
  'Its last {runs} runs all ended with the same output. That is sometimes exactly right -- a report with nothing new to say -- and often a schedule that stopped doing anything useful while still being paid for. Deny to turn it off; approve to keep it running and not be asked about this result again.': '{runs} palaksanaan pamungkasna sadayana réngsé kalayan hasil anu sami. Sakapeung éta memang leres — laporan anu teu aya béja énggal — sareng sering éta jadwal anu parantos henteu ngalakukeun nanaon anu mangpaat nanging masih dibayar. Tolak kanggo mareuman jadwal ieu; Satujuan kanggo tetep ngajalankeunana sareng anjeun moal ditaroskeun deui ngeunaan hasil ieu.',
  'Capability {capability} failed preflight': 'Kamampuh {capability} teu lulus pamariksaan awal',
  'Work that needs it is stopped rather than started: fix the cause, then run that work again. The usual causes are an expired or wrongly scoped credential, a quota used up, or an address that is wrong.': 'Padamelan anu meryogikeunana dieureunkeun, sanés dimimitian: lereskeun sababna, teras jalankeun deui padamelan éta. Sabab anu biasa nyaéta kredénsial anu kadaluwarsa atanapi cakupanana lepat, kuota anu séép, atanapi alamat anu lepat.',
  'Batch guard stopped {capability}': 'Pangaman tindakan massal ngeureunkeun {capability}',
  'It did not match the plan its run recorded. Nothing was sent, and no service was called.': 'Ieu henteu cocog sareng rencana anu dicatet ku palaksanaanana. Henteu aya anu dikintun, sareng henteu aya layanan anu digero.',
  '{role} was asked first and has had {minutes} minutes.': '{role} ditaroskeun heula sareng parantos dipasihan {minutes} menit.',
  '{role} is not a role in this company, so this came to you at once.': '{role} sanés peran di pausahaan ieu, janten ieu langsung dugi ka anjeun.',
  '{role} could not be given this: the company has no active goal or project to hang it from.': 'Ieu teu tiasa dipasrahkeun ka {role}: pausahaan teu gaduh udagan atanapi proyék aktif anu tiasa janten wadahna.',
  '{role} could not be given this ({record}), so this came to you at once.': 'Ieu teu tiasa dipasrahkeun ka {role} ({record}), janten ieu langsung dugi ka anjeun.',
  '{role} stopped without an account of what it did ({why}).': '{role} eureun tanpa laporan ngeunaan naon anu dilakukeunana ({why}).',
  '{role} finished without an account of what it did.': '{role} réngsé tanpa laporan ngeunaan naon anu dilakukeunana.',
  '{role} failed without an account of what it did.': '{role} gagal tanpa laporan ngeunaan naon anu dilakukeunana.',
  '{role} was stopped without an account of what it did.': '{role} dieureunkeun tanpa laporan ngeunaan naon anu dilakukeunana.',
  'Proposed change to the {kind} "{goal}"': 'Usul parobihan kanggo {kind} “{goal}”',
  'Currently: {statement}': 'Ayeuna: {statement}',
  'Currently: {statement} ({status})': 'Ayeuna: {statement} ({status})',
  'Proposed: {statement}': 'Diusulkeun: {statement}',
  'Proposed status: {status}': 'Status anu diusulkeun: {status}',
  'Reason given: {reason}': 'Alesan anu dipasihkeun: {reason}',
  'Record an entry in the books': 'Nyatet éntri dina pembukuan',
  'Record a customer or a deal': 'Nyatet palanggan atanapi kasapukan',
  'Not sent on its own: {reason}': 'Teu dikintun nyalira: {reason}',
  'it answers a conversation other than the one this work began with': 'waleran ieu kanggo obrolan séjén, sanés anu ngamimitian padamelan ieu',
  'it named no passage of a document for customers': 'waleran ieu teu nyebatkeun bagian dokumén pikeun palanggan',
  'it answers from a document not marked for customers': 'waleran ieu ngawaler tina dokumén anu teu ditandaan pikeun palanggan',
  'it says a figure the documents and the customer did not: {detail}': 'waleran ieu nyebatkeun angka anu teu aya dina dokumén atanapi pesen palanggan: {detail}',
  'it gives an address or link the documents and the customer did not: {detail}': 'waleran ieu masihan alamat atanapi tautan anu teu aya dina dokumén atanapi pesen palanggan: {detail}',
  'there have been six answers on its own in this conversation in the last hour': 'parantos aya genep waleran nyalira dina obrolan ieu dina sajam ka tukang',
  'the check found it is about a refund': 'pamariksaan mendakan ieu perkawis mulangkeun artos',
  'the check found it offers a price or terms of its own': 'pamariksaan mendakan waleran ieu nawiskeun harga atanapi sarat nyalira',
  'the check found it answers a serious complaint': 'pamariksaan mendakan waleran ieu nanggapan keluhan anu serius',
  'the check found it touches the law': 'pamariksaan mendakan waleran ieu patali sareng hukum',
  'the check found it gives or asks for personal data': 'pamariksaan mendakan waleran ieu masihan atanapi nyuhunkeun data pribadi',
  'the check found it promises something the documents do not': 'pamariksaan mendakan waleran ieu ngajangjikeun hal anu teu aya dina dokumén',
  'the check could not judge it': 'pamariksaan teu tiasa meunteun ieu',
  'the check found something in it the documents do not say': 'pamariksaan mendakan eusi anu teu disebatkeun ku dokumén',
  '{role} proposes the schedule {name}': '{role} ngusulkeun jadwal {name}',
  'Each run: {instruction}': 'Unggal jalan: {instruction}',
  'Done by: {role}': 'Dipigawé ku: {role}',
  'When: {cron} ({timezone}); the next runs are {runs}': 'Iraha: {cron} ({timezone}); jalan salajengna {runs}',
  'Approving it makes the schedule and starts it; it can be turned off or changed under Team, Schedules.': 'Nyatujuan éta ngadamel jadwalna sareng langsung ngajalankeunana; jadwal tiasa dipareuman atanapi dirobih di Tim, Jadwal.',
  'No schedule is made.': 'Teu aya jadwal anu didamel.',
  'Propose a schedule': 'Ngusulkeun jadwal',
  'Approving it changes the goal; until then the work carries on under the goal as it is.': 'Nyatujuan ieu bakal ngarobih udagan; dugi ka harita padamelan diteraskeun handapeun udagan anu ayeuna.',
  'The goal stays as it is.': 'Udagan tetep sapertos ayeuna.',
  'mission': 'misi',
  'objective': 'tujuan',
  'key result': 'hasil utama',
  'Active': 'Aktif',
  'Met': 'Kahontal',
  'Abandoned': 'Ditinggalkeun',
  'This work asked for it at tier {tier}, and policy {policies} requires your approval.': 'Padamelan ieu nyuhunkeun tindakan ieu dina tingkat {tier}, sareng kawijakan {policies} meryogikeun persetujuan anjeun.',
  'This work asked for it at tier {tier}, and the task began with content from outside the company.': 'Padamelan ieu nyuhunkeun tindakan ieu dina tingkat {tier}, sareng tugasna dimimitian ku eusi ti luar pausahaan.',
  'This work asked for it at tier {tier}, and the work read content from outside the company before asking.': 'Padamelan ieu nyuhunkeun tindakan ieu dina tingkat {tier}, sareng padamelan éta maos eusi ti luar pausahaan sateuacan nyuhunkeun.',
  'This work asked for it at tier {tier}, after the work read content from outside the company, and the guardian asked you first: {reason}': 'Padamelan ieu nyuhunkeun tindakan ieu dina tingkat {tier}, saparantos padamelan éta maos eusi ti luar pausahaan, sareng panjaga naros heula ka anjeun: {reason}',
  'it doubted this call before, and you allowed it once': 'kantos ragu kana panggero ieu, sareng anjeun parantos ngidinanana sakali',
  'This work asked for it at tier {tier}, which cannot be reversed.': 'Padamelan ieu nyuhunkeun tindakan ieu dina tingkat {tier}, anu teu tiasa dibalikeun.',
  'You approved this once already, and the worker carrying it out stopped before it could say whether it happened: it may already have happened. Check before approving it again.': 'Anjeun parantos nyatujuan ieu sakali, sareng pagawé anu ngalaksanakeunana eureun sateuacan sempet nyarioskeun naha éta kajantenan: panginten parantos kajantenan. Pariksa heula sateuacan nyatujuanana deui.',
  'What this is for — {goals}': 'Kanggo naon ieu — {goals}',
  'The task halts and no external change is made.': 'Tugas mandeg sareng henteu aya parobihan ka luar anu dilakukeun.',
  'Scored against {total} references: {passed} passed, {failed} failed.': 'Dipeunteun ku {total} rujukan: {passed} lulus, {failed} gagal.',
  'This role has fewer than {minimum} accepted references, so the change is unscored. That is not the same as passing.': 'Peran ieu gaduh kirang ti {minimum} rujukan anu ditampi, janten parobihan ieu teu acan dipeunteun. Éta henteu sami sareng lulus.',
  'The role keeps working exactly as it does now.': 'Peran ieu tetep damel persis sapertos ayeuna.',
  '{role} asks: {question}': '{role} naros: {question}',
  'The run did not say more than the question.': 'Palaksanaan henteu nyarios nanaon salian ti patarosanana.',
  'The task is stopped, and nothing it was going to do happens.': 'Tugas dieureunkeun, sareng naon anu badé dilakukeunana moal kajantenan.',
  'You proposed it.': 'Anjeun anu ngusulkeun.',
  'It came with a bundle.': 'Kaparigelan ieu dibantun ku hiji pakét.',
  'An agent proposed it.': 'Hiji agén anu ngusulkeun.',
  'It was learned from the company\'s work.': 'Kaparigelan ieu hasil diajar tina padamelan perusahaan.',
  'Skill "{skill}", version {version}': 'Kaparigelan “{skill}”, vérsi {version}',
  'The reviewer approved it: {note}': 'Panilik parantos nyatujuan: {note}',
  'The reviewer approved it.': 'Panilik parantos nyatujuan.',
  'Nothing changes; the current version of the skill stays in force.': 'Teu aya anu robih; vérsi kaparigelan anu ayeuna tetep lumaku.',
  'Skills the bundle "{bundle}" brings: {count}': 'Kaparigelan anu dibantun ku pakét “{bundle}”: {count}',
  'The reviewer read them all and approved these:': 'Panilik parantos maos sadayana sareng nyatujuan ieu:',
  'It turned these down, and they stay off:': 'Ieu anu ditampik, sareng tetep pareum:',
  'Approve to switch them all on, or deny to turn them all down. To decide one at a time, open the Skills page.': 'Satujuan kanggo ngahurungkeun sadayana, atanapi Tolak kanggo nampik sadayana. Kanggo mutuskeun hiji-hiji, buka kaca Kaparigelan.',
  'Nothing changes; none of these skills is switched on.': 'Teu aya anu robih; teu aya kaparigelan ieu anu dihurungkeun.',
  'I am {ceo}, and I run {company} for you. Three things before we start: what does {company} sell, and to whom? How much may it spend in a month? And what should its first piece of work be -- or shall I suggest one?': 'Abdi {ceo}, anu ngajalankeun {company} kanggo anjeun. Tilu perkawis sateuacan urang ngamimitian: naon anu dijual ku {company}, sareng ka saha? Sabaraha waragad anu kenging dianggé dina sabulan? Sareng naon padamelan kahijina — atanapi abdi nu ngusulkeun?',
  'Read a customer conversation': 'Aos obrolan palanggan',
  'Reply to a customer': 'Waler palanggan',
  'Read a page in the browser': 'Maca kaca dina browser',
  'Fill in a page in the browser': 'Ngeusian kaca dina browser',
  'Ask you to take over the browser': 'Nyuhunkeun anjeun nyandak alih browser',
  '{host} refused the model key ({status}), so nothing that needs the model can run. Open Settings, This deployment, Model, paste a key that works, test it and save.':
    '{host} nolak konci modél ({status}), jadi euweuh pagawéan anu butuh modél anu bisa jalan. Buka Setélan, Pamasangan ieu, Modél AI, témpélkeun konci anu tiasa dipaké, uji, tuluy simpen.',
  '{host} refused the model key, and work is waiting': '{host} nolak konci modél, sarta pagawéan keur ngantosan',
  'What is waiting for the model carries on by itself once a key that works is in use.':
    'Pagawéan anu ngantosan modél bakal diteruskeun sorangan sanggeus konci anu tiasa dipaké geus dipaké.',
  'A task ended before it was done: {task}':
    'Hiji tugas eureun samemeh réngsé: {task}',
  'It ended as: {reason}. No other card was raised for it, so it is here rather than silent.':
    'Ahirna: {reason}. Euweuh kartu séjén anu dijieun pikeun éta, ku kituna aya di dieu sangkan teu jempé.',
};
