/**
 * ไทย: what the platform itself says to the owner outside the console
 * (src/owner/say.ts), keyed by its English.
 *
 * The terms are the console's (console/src/locales/th.ts, whose header holds
 * the glossary): อนุมัติ and ปฏิเสธ, กล่องขาเข้า, รายการ for an item, การ์ด for
 * a card, and ระบบนี้ for the This deployment page, with its sections joined
 * by " > " as the console writes them. The register is polite and neutral,
 * with no gendered particle; the assistant says ฉัน. Thai ends a sentence with
 * a space, not a full stop. Telegram and WhatsApp buttons stay short: WhatsApp
 * cuts a button at 20 characters and a list row at 24.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'เหตุขัดข้อง: {title}',
  'Done: {goal}': 'เสร็จแล้ว: {goal}',
  'Stopped before finishing: {goal}': 'หยุดก่อนเสร็จ: {goal}',
  'Not done: {goal}': 'ไม่ได้ทำ: {goal}',
  'Why: {reason}': 'สาเหตุ: {reason}',
  'a task': 'งานหนึ่ง',
  'Approval needed: {title}': 'รอการอนุมัติ: {title}',
  '{summary} — if denied: {consequence}': '{summary} — หากปฏิเสธ: {consequence}',
  '{role} asks:': '{role} ถามว่า:',
  'If denied:': 'หากปฏิเสธ:',
  'Expires:': 'หมดอายุ:',
  'This one is decided in the app.': 'รายการนี้ต้องตัดสินในแอป',
  'Open in PALUGADA': 'เปิดใน PALUGADA',
  'Approve': 'อนุมัติ',
  'Deny': 'ปฏิเสธ',
  'Ask': 'ถาม',
  'Approved. Nothing left to press here.': 'อนุมัติแล้ว ไม่ต้องกดอะไรที่นี่อีก',
  'Denied. Nothing left to press here.': 'ปฏิเสธแล้ว ไม่ต้องกดอะไรที่นี่อีก',
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    'หมดเวลาโดยไม่มีคำตอบ การเงียบถือเป็นการปฏิเสธ จึงไม่มีการดำเนินการใด',
  'This bot only answers to its owner.': 'บอตนี้ตอบเฉพาะเจ้าของเท่านั้น',
  'That one has to be approved in the app.': 'รายการนี้ต้องอนุมัติในแอป',
  'That could not be recorded.': 'บันทึกไม่สำเร็จ',
  'That item no longer exists.': 'รายการนี้ไม่มีอยู่แล้ว',
  'What do you want to ask about "{title}"? Reply to this message.':
    'คุณต้องการถามอะไรเกี่ยวกับ “{title}” ตอบกลับข้อความนี้',
  'Your question': 'คำถามของคุณ',
  'Type your question as a reply.': 'พิมพ์คำถามของคุณเป็นข้อความตอบกลับ',
  'Asked. The answer will be on the item in the app.': 'ส่งคำถามแล้ว คำตอบจะแสดงที่รายการนี้ในแอป',
  'Answer': 'ตอบ',
  'Answer in words': 'ตอบเป็นข้อความ',
  'That choice is not on this question.': 'คำถามนี้ไม่มีตัวเลือกนั้น',
  'Chosen: {choice}.': 'เลือกแล้ว: {choice}',
  'Stop the task': 'หยุดงาน',
  'Your answer to "{question}"? Reply to this message.': 'คำตอบของคุณสำหรับ “{question}” ตอบกลับข้อความนี้',
  'Your answer': 'คำตอบของคุณ',
  'Type your answer as a reply.': 'พิมพ์คำตอบของคุณเป็นข้อความตอบกลับ',
  'Answered. The task carries on with it.': 'ตอบแล้ว งานจะทำต่อโดยใช้คำตอบนี้',
  'That is too long for one question; keep it under {max} characters.':
    'ยาวเกินไปสำหรับคำถามเดียว เขียนให้ไม่เกิน {max} ตัวอักษร',
  '[a key, not kept]': '[คีย์ ไม่ได้เก็บไว้]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    'ข้อความนี้ดูเหมือนคีย์ ฉันจึงไม่ได้เก็บไว้หรือส่งไปที่ใด คีย์ต้องใส่ในช่องปิดผนึกบนการ์ด หรือในหน้าของคีย์นั้นใน “ระบบนี้” บอกฉันว่าคีย์นี้ใช้สำหรับอะไร แล้วฉันจะแสดงการ์ดให้คุณ',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'ยังไม่ได้ตั้งค่าโมเดล ฉันจึงยังคิดไม่ได้ เลือกโมเดลที่ ระบบนี้ > โมเดล แล้วฉันจะช่วยเรื่องอื่นๆ ได้ทั้งหมด',
  'The model did not answer: {reason}': 'โมเดลไม่ตอบ: {reason}',
  'Here is what I propose.': 'นี่คือสิ่งที่ฉันเสนอ',
  'I have nothing to add.': 'ฉันไม่มีอะไรจะเพิ่มเติม',
  '{name}, CEO of {company}': '{name} CEO ของ {company}',
  'That could not be answered: {reason}': 'ตอบไม่ได้: {reason}',
  'I read text and voice notes.': 'ฉันอ่านได้เฉพาะข้อความและข้อความเสียง',
  'Now talking to {name}.': 'ตอนนี้คุณกำลังคุยกับ {name}',
  'Choose whom to talk to.': 'เลือกว่าจะคุยกับใคร',
  'Choose whom to talk to': 'เลือกว่าจะคุยกับใคร',
  'Talk to PALUGADA about the whole deployment': 'คุยกับ PALUGADA เรื่องทั้งระบบ',
  'Who you are talking to, and how': 'คุณกำลังคุยกับใคร และคุยอย่างไร',
  'Stopped.': 'หยุดแล้ว',
  'Write here to talk to {name}.': 'พิมพ์ที่นี่เพื่อคุยกับ {name}',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    'คุณกำลังคุยกับ {name} พิมพ์ข้อความหรือส่งข้อความเสียงได้ ใช้ /ceo เพื่อเลือกว่าจะคุยกับใคร และ /palugada เพื่อคุยกับ PALUGADA เรื่องทั้งระบบ',
  'You said: "{words}"': 'คุณพูดว่า: “{words}”',
  'in the app': 'ในแอป',
  'Apply: {summary}': 'นำไปใช้: {summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    'ยังไม่มีบริการฟังเสียง: เลือกผู้ให้บริการในแอป ที่ ระบบนี้ > เครื่องมือ > การฟัง',
  'That recording is too long; keep a voice note under {max} MB.':
    'ไฟล์เสียงยาวเกินไป ข้อความเสียงต้องไม่เกิน {max} MB',
  'I could not make out any words in that.': 'ฉันฟังไม่ออกว่าพูดว่าอะไร',
  'Done: {summary}': 'เสร็จแล้ว: {summary}',
  'That one is applied in the app.': 'รายการนี้ต้องนำไปใช้ในแอป',
  'That card no longer exists.': 'การ์ดนี้ไม่มีอยู่แล้ว',
  'That card was already applied.': 'การ์ดนี้ถูกนำไปใช้แล้ว',
  'That card was dismissed.': 'การ์ดนี้ถูกปัดทิ้งแล้ว',
  'That card failed when it was applied.': 'การ์ดนี้ล้มเหลวขณะนำไปใช้',
  'That could not be done: {reason}': 'ทำไม่สำเร็จ: {reason}',
  'Choose': 'เลือก',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    'คุณต้องการถามอะไรเกี่ยวกับ “{title}” พิมพ์คำถามเป็นข้อความตอบกลับข้อความนี้',
  'Your answer to "{question}"? Reply to this message with your answer.':
    'คำตอบของคุณสำหรับ “{question}” พิมพ์คำตอบเป็นข้อความตอบกลับข้อความนี้',
  'I read text messages here.': 'ที่นี่ฉันอ่านได้เฉพาะข้อความตัวอักษร',
  'Apply one of these here:': 'เลือกนำรายการหนึ่งไปใช้ที่นี่:',
  'Apply {number}': 'ใช้ข้อ {number}',
  'Signed in to {provider} for the {alias} key': 'ลงชื่อเข้าใช้ {provider} สำหรับคีย์ {alias} แล้ว',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'กลับไปที่ PALUGADA: ตอนนี้ฝ่ายถือคีย์นี้แล้ว และจะต่ออายุก่อนหมดอายุ ปิดแท็บนี้ได้เลย',
  'Signed in to {name}': 'ลงชื่อเข้าใช้ {name} แล้ว',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'กลับไปที่ PALUGADA เพื่อเลือกเครื่องมือที่บทบาทใช้ได้ ปิดแท็บนี้ได้เลย',
  'Not signed in': 'ยังไม่ได้ลงชื่อเข้าใช้',
  'Recorded: approved.': 'บันทึกแล้ว: อนุมัติ',
  'Recorded: denied.': 'บันทึกแล้ว: ปฏิเสธ',
  'Recorded: asked.': 'บันทึกแล้ว: ถาม',
  'Asked. Nothing left to press here.': 'ส่งคำถามแล้ว ไม่ต้องกดอะไรที่นี่อีก',
  'Withdrawn: the task it was asking about has finished.': 'ถอนแล้ว: งานที่รายการนี้ถามถึงเสร็จแล้ว',
  'Withdrawn: the task it was asking about has failed.': 'ถอนแล้ว: งานที่รายการนี้ถามถึงล้มเหลว',
  'Withdrawn: the task it was asking about was stopped.': 'ถอนแล้ว: งานที่รายการนี้ถามถึงถูกหยุด',
  'Withdrawn: the task it was asking about was cancelled.': 'ถอนแล้ว: งานที่รายการนี้ถามถึงถูกยกเลิก',
  'Decided. Nothing left to press here.': 'ตัดสินแล้ว ไม่ต้องกดอะไรที่นี่อีก',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': 'ถอนแล้ว: เอเจนต์เปลี่ยนสิ่งที่เสนอ และส่งคำขอใหม่สำหรับข้อเสนอใหม่แล้ว',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': 'ถอนแล้ว: บริษัทไม่ได้อยู่ในระยะที่ข้อเสนอนี้จะย้ายออกไปแล้ว',
  'Withdrawn: it was already decided in the app.': 'ถอนแล้ว: รายการนี้ถูกตัดสินในแอปไปแล้ว',
  'Withdrawn. Nothing left to press here.': 'ถอนแล้ว ไม่ต้องกดอะไรที่นี่อีก',
  'company': 'บริษัท',
  'Work stopped: the {account} account is out of tokens': 'งานหยุดแล้ว: บัญชี {account} ใช้โทเคนหมดแล้ว',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': '“{work}” หยุดเพราะบัญชี {account} ใช้ไป {spent} จาก {max} โทเคนแล้ว เพิ่มเพดานที่หน้าการเงิน แล้วเปิดงานและกดทำต่อ: งานจะทำต่อจากจุดที่หยุด',
  'Withdrawn: you continued the task it was about.': 'ถอนออกแล้ว: คุณทำงานที่เกี่ยวข้องต่อแล้ว',
  'Broke its contract': 'ทำผิดสัญญาของงาน',
  'Refused by a policy': 'ถูกนโยบายปฏิเสธ',
  'Out of budget': 'งบประมาณหมด',
  'Handed on too many times': 'ถูกส่งต่อหลายครั้งเกินไป',
  'Missed its deadline': 'เลยกำหนดส่ง',
  'Its result did not check out': 'ผลลัพธ์ตรวจสอบไม่ผ่าน',
  'A capability it needs is down': 'ความสามารถที่งานต้องใช้ขัดข้อง',
  'No runtime could take it': 'ไม่มีรันไทม์ใดรับงานได้',
  'Went in a circle': 'ทำงานวนซ้ำไม่จบ',
  'Split into too many sub-tasks': 'แตกเป็นงานย่อยมากเกินไป',
  'Wrote more than its role allows one run': 'เขียนมากกว่าที่บทบาทอนุญาตต่อรอบ',
  'Your approval was not given in time': 'คุณไม่ได้อนุมัติทันเวลา',
  'Stopped by you': 'คุณสั่งหยุด',
  'Cancelled by you': 'คุณยกเลิก',
  'The company is frozen': 'บริษัทถูกแช่แข็ง',
  'Its record did not match on replay': 'บันทึกไม่ตรงกันเมื่อเล่นซ้ำ',
  'It kept stopping the worker running it': 'ทำให้เวิร์กเกอร์ที่รันงานนี้หยุดซ้ำๆ',
  'Not done': 'ไม่ได้ทำ',
  'Task failed': 'งานล้มเหลว',
  'Digest for {day}': 'สรุปประจำวันที่ {day}',
  'Spent: {amount}': 'ใช้ไป: {amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': 'งาน: เสร็จแล้ว {done}, ล้มเหลว {failed}, หยุดแล้ว {stopped}',
  'Inbox: {open} waiting (incidents: {incidents})': 'กล่องขาเข้า: รออยู่ {open} (เหตุขัดข้อง: {incidents})',
  'Stopped ({count}): {reason}': 'หยุดแล้ว ({count}): {reason}',
  'Start an ad campaign': 'เริ่มแคมเปญโฆษณา',
  'Block time on the calendar': 'จองเวลาในปฏิทิน',
  'Read the calendar': 'อ่านปฏิทิน',
  'Run code': 'รันโค้ด',
  'Add a note to a customer': 'เพิ่มหมายเหตุในข้อมูลลูกค้า',
  'Read customer records': 'อ่านข้อมูลลูกค้า',
  'Release to the live site': 'นำขึ้นเว็บไซต์จริง',
  'Release to the test site': 'นำขึ้นเว็บไซต์ทดสอบ',
  'Change a domain\'s nameservers': 'เปลี่ยนเนมเซิร์ฟเวอร์ของโดเมน',
  'Read a domain\'s records': 'อ่านเรคคอร์ดของโดเมน',
  'Change a domain\'s record': 'เปลี่ยนเรคคอร์ดของโดเมน',
  'Write a document': 'เขียนเอกสาร',
  'Sign a document': 'ลงนามในเอกสาร',
  'Buy a domain': 'ซื้อโดเมน',
  'Transfer a domain': 'โอนโดเมน',
  'Draft an email': 'ร่างอีเมล',
  'Send an email': 'ส่งอีเมล',
  'List files': 'แสดงรายการไฟล์',
  'Transfer money': 'โอนเงิน',
  'Propose a goal change': 'เสนอให้เปลี่ยนเป้าหมาย',
  'Make a picture': 'สร้างภาพ',
  'Issue an invoice': 'ออกใบแจ้งหนี้',
  'Pay an invoice': 'ชำระใบแจ้งหนี้',
  'Read the books': 'อ่านบัญชีของบริษัท',
  'Read the mailbox': 'อ่านกล่องจดหมาย',
  'Search what the company knows': 'ค้นหาสิ่งที่บริษัทรู้',
  'Record a measure': 'บันทึกตัวชี้วัด',
  'Read product numbers': 'อ่านตัวเลขของผลิตภัณฑ์',
  'Ask you a question': 'ถามคำถามคุณ',
  'Write down a plan': 'บันทึกแผน',
  'Delete a record': 'ลบข้อมูลหนึ่งรายการ',
  'Propose a code change': 'เสนอการแก้ไขโค้ด',
  'Read the code': 'อ่านโค้ด',
  'Destroy a server': 'ทำลายเซิร์ฟเวอร์',
  'Read a skill': 'อ่านทักษะ',
  'Publish a post': 'เผยแพร่โพสต์',
  'Read text aloud': 'อ่านข้อความออกเสียง',
  'Turn speech into text': 'ถอดเสียงเป็นข้อความ',
  'Propose a new stage': 'เสนอให้ย้ายไปยังระยะใหม่',
  'Wait for work handed on': 'รองานที่ส่งต่อไป',
  'Hand work to another role': 'ส่งต่องานให้บทบาทอื่น',
  'File a ticket': 'สร้างทิกเก็ต',
  'List tickets': 'แสดงรายการทิกเก็ต',
  'Check a service is up': 'ตรวจว่าบริการยังทำงานอยู่',
  'Read a web page': 'อ่านหน้าเว็บ',
  'Open a web page': 'เปิดหน้าเว็บ',
  'Search the web': 'ค้นหาเว็บ',
  'no stage': 'ไม่มีระยะ',
  'Explore': 'สำรวจ',
  'Validate': 'ทดสอบตลาด',
  'Build': 'สร้าง',
  'Launch': 'เปิดตัว',
  'Grow': 'เติบโต',
  'Wind down': 'ปิดกิจการ',
  'Monthly budget reached; the company is paused': 'ถึงงบประมาณรายเดือนแล้ว บริษัทหยุดชั่วคราว',
  '{spent} of {limit} spent since {since}. No new task will start and no external action will run until you raise the ceiling or allow spending past it for a while, under Money.': 'ใช้ไป {spent} จาก {limit} ตั้งแต่ {since} จะไม่มีงานใหม่เริ่ม และไม่มีการดำเนินการภายนอกใดทำงาน จนกว่าคุณจะเพิ่มเพดาน หรืออนุญาตให้ใช้จ่ายเกินเพดานชั่วคราว ที่หน้าการเงิน',
  'Monthly budget is 80% spent': 'ใช้งบประมาณรายเดือนไปแล้ว 80%',
  '{spent} of {limit} spent since {since}. At 100% the company pauses.': 'ใช้ไป {spent} จาก {limit} ตั้งแต่ {since} เมื่อถึง 100% บริษัทจะหยุดชั่วคราว',
  'Role {role} is paused for spending too fast': 'บทบาท {role} ถูกหยุดชั่วคราวเพราะใช้จ่ายเร็วเกินไป',
  '{role} spent {spent} in the last hour, {multiple} times its usual {usual} an hour. It is paused before the monthly ceiling is reached, so there is money left to work with once you have found out why. Resume it when you have.': '{role} ใช้ไป {spent} ในชั่วโมงที่ผ่านมา เป็น {multiple} เท่าของปกติที่ใช้ชั่วโมงละ {usual} บทบาทนี้ถูกหยุดชั่วคราวก่อนถึงเพดานรายเดือน เพื่อให้ยังมีเงินเหลือใช้ทำงานเมื่อคุณหาสาเหตุเจอแล้ว เมื่อหาเจอแล้วให้สั่งทำต่อ',
  'Daily model spend over threshold': 'ค่าใช้จ่ายโมเดลรายวันเกินเกณฑ์',
  'Model spend today is {spent}, over the {limit} ceiling.': 'ค่าใช้จ่ายโมเดลวันนี้อยู่ที่ {spent} เกินเพดาน {limit}',
  'Task failure rate over threshold': 'อัตรางานล้มเหลวเกินเกณฑ์',
  '{failed} of {finished} tasks failed or stopped today ({rate}%), over the {limit}% threshold.': 'วันนี้มีงานล้มเหลวหรือถูกหยุด {failed} จาก {finished} งาน ({rate}%) เกินเกณฑ์ {limit}%',
  'Unusual number of policy refusals': 'นโยบายปฏิเสธบ่อยผิดปกติ',
  'Actions refused by a policy today: {count}, over the threshold of {limit}. Either an agent is probing its limits or a policy is miscalibrated.': 'การกระทำที่ถูกนโยบายปฏิเสธวันนี้: {count} ครั้ง เกินเกณฑ์ {limit} ครั้ง อาจเป็นเพราะเอเจนต์กำลังลองหยั่งขอบเขตของตัวเอง หรือนโยบายตั้งค่าไว้ไม่เหมาะสม',
  'External writes failed verification': 'การเขียนไปยังภายนอกไม่ผ่านการยืนยัน',
  'Writes outside that reported success but read back differently: {count}. Something is changing them other than as asked.': 'การเขียนไปยังภายนอกที่รายงานว่าสำเร็จ แต่อ่านกลับมาแล้วไม่ตรงกัน: {count} รายการ มีบางอย่างกำลังเปลี่ยนข้อมูลเหล่านั้นโดยไม่เป็นไปตามที่สั่ง',
  'A capability stopped being usable': 'ความสามารถหนึ่งใช้งานไม่ได้แล้ว',
  'Tasks that could not start today because a capability their role needs failed its check: {count}. A credential has probably expired or a quota is used up.': 'งานที่เริ่มไม่ได้วันนี้เพราะความสามารถที่บทบาทต้องใช้ไม่ผ่านการตรวจสอบ: {count} งาน ข้อมูลรับรองอาจหมดอายุ หรือโควตาอาจหมดแล้ว',
  'A worker stopped reporting mid-run': 'เวิร์กเกอร์หยุดรายงานกลางรอบการทำงาน',
  'Runs that stopped reporting and were taken back today: {count}. The work was picked up again; the tokens they had already spent were not recovered.': 'รอบการทำงานที่หยุดรายงานและถูกดึงกลับวันนี้: {count} รอบ งานถูกรับไปทำต่อแล้ว แต่โทเค็นที่ใช้ไปแล้วไม่ได้คืนมา',
  '{role} was refused {denials} times today, at the limit of {limit}. No task will run as this role until you lift the freeze. The usual causes are a missing capability grant, a policy the role\'s charter does not account for, or work the role was never equipped to do.': '{role} ถูกปฏิเสธ {denials} ครั้งในวันนี้ ถึงขีดจำกัด {limit} ครั้งแล้ว จะไม่มีงานใดทำงานในบทบาทนี้จนกว่าคุณจะยกเลิกการแช่แข็ง สาเหตุที่พบบ่อยคือขาดสิทธิ์ใช้ความสามารถ มีนโยบายที่กฎบัตรของบทบาทไม่ได้คำนึงถึง หรือเป็นงานที่บทบาทนี้ไม่เคยถูกเตรียมไว้ให้ทำ',
  'Role {role} is frozen after repeated denials': 'บทบาท {role} ถูกแช่แข็งหลังจากถูกปฏิเสธซ้ำๆ',
  'What it was refused: {capabilities}': 'สิ่งที่ถูกปฏิเสธ: {capabilities}',
  'It is waiting for an approval, and none is open, so nothing you can answer will move it.': 'งานนี้รอการอนุมัติอยู่ แต่ไม่มีคำขออนุมัติใดเปิดอยู่ ไม่ว่าคุณจะตอบอะไรก็ทำให้งานเดินต่อไม่ได้',
  'It is waiting for a review, and none is pending, so no reviewer and no decision of yours will move it.': 'งานนี้รอการตรวจทานอยู่ แต่ไม่มีการตรวจทานใดค้างอยู่ ทั้งผู้ตรวจทานและการตัดสินใจของคุณจึงทำให้งานเดินต่อไม่ได้',
  'It is parked until a window reopens, and the window never does.': 'งานนี้ถูกพักไว้จนกว่าช่วงเวลาจะเปิดอีกครั้ง แต่ช่วงเวลานั้นไม่เคยเปิดเลย',
  'A task is waiting on nothing': 'งานหนึ่งกำลังรอสิ่งที่ไม่มีวันมาถึง',
  '"{task}" has been waiting since {since}. {why} Approve to run it again from where it stopped, or deny to cancel it.': '“{task}” รอมาตั้งแต่ {since} {why} อนุมัติเพื่อให้ทำอีกครั้งจากจุดที่หยุด หรือปฏิเสธเพื่อยกเลิกงาน',
  'A task keeps stopping the worker running it': 'งานหนึ่งทำให้เวิร์กเกอร์ที่รันงานนี้หยุดซ้ำๆ',
  '"{task}" lost its worker {lost} times: each time the worker running it stopped answering before the work finished. What it had done is kept. It is halted so it cannot take another worker down; run it again once the cause is found, or cancel it.': '“{task}” ทำให้เสียเวิร์กเกอร์ไป {lost} ครั้ง: ทุกครั้งเวิร์กเกอร์ที่รันงานนี้หยุดตอบสนองก่อนงานจะเสร็จ สิ่งที่ทำไปแล้วยังเก็บไว้ งานถูกหยุดไว้เพื่อไม่ให้เวิร์กเกอร์ตัวอื่นล่มไปด้วย เมื่อพบสาเหตุแล้วให้ทำอีกครั้ง หรือยกเลิกงาน',
  '{services} stayed unreachable, and the work that needs it stopped': '{services} ยังติดต่อไม่ได้ และงานที่ต้องใช้จึงหยุดลง',
  'The task waited about {minutes} minutes, looking again each time, and has stopped. Once the service answers, run it again.': 'งานรอประมาณ {minutes} นาที โดยลองตรวจซ้ำทุกครั้ง และตอนนี้หยุดแล้ว เมื่อบริการตอบสนองแล้ว ให้ทำอีกครั้ง',
  'It was tried {tries} times over about {minutes} minutes.': 'ลองไปแล้ว {tries} ครั้งในช่วงประมาณ {minutes} นาที',
  'This role can take actions that cannot be undone, so the run was not silently moved to a different model.': 'บทบาทนี้สามารถดำเนินการที่ย้อนกลับไม่ได้ รอบการทำงานจึงไม่ถูกย้ายไปใช้โมเดลอื่นอย่างเงียบๆ',
  'No fallback model is left for this role.': 'ไม่มีโมเดลสำรองเหลือสำหรับบทบาทนี้แล้ว',
  'Model {model} failed and the run was not moved': 'โมเดล {model} ล้มเหลว และรอบการทำงานไม่ได้ถูกย้าย',
  'External write failed verification': 'การเขียนไปยังภายนอกไม่ผ่านการยืนยัน',
  'The task wrote to an outside service and read it back, and what it read did not match. Look at the place it wrote to before you run it again: the write may have happened.': 'งานเขียนข้อมูลไปยังบริการภายนอกแล้วอ่านกลับมา และสิ่งที่อ่านได้ไม่ตรงกัน ตรวจดูปลายทางที่งานเขียนไปก่อนจะทำอีกครั้ง: การเขียนอาจเกิดขึ้นแล้ว',
  'Review deadlocked after {rounds} revisions: {capability}': 'การตรวจทานหาข้อยุติไม่ได้หลังแก้ไข {rounds} รอบ: {capability}',
  'The role and its reviewer did not agree on {capability}.': 'บทบาทและผู้ตรวจทานไม่เห็นตรงกันเรื่อง {capability}',
  'The reviewer\'s last note: {note}': 'บันทึกล่าสุดของผู้ตรวจทาน: {note}',
  'The reviewer left no note.': 'ผู้ตรวจทานไม่ได้ทิ้งบันทึกไว้',
  'What it was judged against: {criteria}': 'เกณฑ์ที่ใช้ตัดสิน: {criteria}',
  'Review produced no usable verdict: {capability}': 'การตรวจทานไม่ได้ให้ผลตัดสินที่ใช้ได้: {capability}',
  'The reviewing task ended without a decision that could be read. The proposed action is still blocked and needs your judgement.': 'งานตรวจทานจบลงโดยไม่มีการตัดสินใจที่อ่านได้ การกระทำที่เสนอยังถูกระงับอยู่และต้องให้คุณพิจารณา',
  'another stage': 'ระยะอื่น',
  'Either answer only closes this: the company stays in the {stage} stage.': 'ไม่ว่าจะตอบอย่างไรก็เพียงปิดรายการนี้ บริษัทยังอยู่ในระยะ {stage}',
  'Either answer only closes this: the company stays without a stage.': 'ไม่ว่าจะตอบอย่างไรก็เพียงปิดรายการนี้ บริษัทยังไม่มีระยะ',
  'To move it anyway, set the stage on the Overview.': 'หากยังต้องการย้าย ให้ตั้งระยะที่หน้าภาพรวม',
  '{reviewer} stopped a proposal to move the company from {from} to {to}': '{reviewer} หยุดข้อเสนอให้ย้ายบริษัทจาก {from} ไปยัง {to}',
  '{reviewer} reviewed it before you and stopped it:': '{reviewer} ตรวจทานก่อนคุณและหยุดข้อเสนอนี้:',
  'No reason was given.': 'ไม่ได้ระบุเหตุผล',
  'What was proposed:': 'สิ่งที่เสนอ:',
  'The company stays in the {stage} stage.': 'บริษัทยังอยู่ในระยะ {stage}',
  'The company stays without a stage.': 'บริษัทยังไม่มีระยะ',
  'Move the company from {from} to {to}?': 'ย้ายบริษัทจาก {from} ไปยัง {to} หรือไม่',
  'Reviewed by {reviewer} before you:': '{reviewer} ตรวจทานก่อนคุณแล้ว:',
  'The schedule "{schedule}" keeps producing the same result': 'กำหนดการ “{schedule}” ให้ผลลัพธ์เดิมซ้ำๆ',
  'Its last {runs} runs all ended with the same output. That is sometimes exactly right -- a report with nothing new to say -- and often a schedule that stopped doing anything useful while still being paid for. Deny to turn it off; approve to keep it running and not be asked about this result again.': '{runs} รอบล่าสุดจบด้วยผลลัพธ์เดียวกันทั้งหมด บางครั้งนั่นก็ถูกต้องแล้ว เช่น รายงานที่ไม่มีอะไรใหม่ให้บอก แต่บ่อยครั้งคือกำหนดการที่ไม่ได้ทำอะไรที่มีประโยชน์แล้วทั้งที่ยังเสียเงินอยู่ ปฏิเสธเพื่อปิดกำหนดการ อนุมัติเพื่อให้ทำงานต่อและไม่ต้องถามเรื่องผลลัพธ์นี้อีก',
  'Capability {capability} failed preflight': 'ความสามารถ {capability} ไม่ผ่านการตรวจสอบ',
  'Work that needs it is stopped rather than started: fix the cause, then run that work again. The usual causes are an expired or wrongly scoped credential, a quota used up, or an address that is wrong.': 'งานที่ต้องใช้ความสามารถนี้ถูกหยุดแทนที่จะเริ่ม แก้ไขสาเหตุ แล้วทำงานนั้นอีกครั้ง สาเหตุที่พบบ่อยคือข้อมูลรับรองหมดอายุหรือกำหนดขอบเขตไว้ไม่ถูกต้อง โควตาหมด หรือที่อยู่ไม่ถูกต้อง',
  'Batch guard stopped {capability}': 'ตัวป้องกันชุดคำสั่งหยุด {capability}',
  'It did not match the plan its run recorded. Nothing was sent, and no service was called.': 'ไม่ตรงกับแผนที่รอบการทำงานบันทึกไว้ ไม่มีสิ่งใดถูกส่ง และไม่มีบริการใดถูกเรียก',
  '{role} was asked first and has had {minutes} minutes.': '{role} ได้รับเรื่องก่อนและมีเวลาไปแล้ว {minutes} นาที',
  '{role} is not a role in this company, so this came to you at once.': '{role} ไม่ใช่บทบาทในบริษัทนี้ เรื่องนี้จึงส่งถึงคุณทันที',
  '{role} could not be given this: the company has no active goal or project to hang it from.': 'มอบเรื่องนี้ให้ {role} ไม่ได้: บริษัทไม่มีเป้าหมายหรือโปรเจกต์ที่ใช้งานอยู่ให้ผูกไว้',
  '{role} could not be given this ({record}), so this came to you at once.': 'มอบเรื่องนี้ให้ {role} ไม่ได้ ({record}) เรื่องนี้จึงส่งถึงคุณทันที',
  '{role} stopped without an account of what it did ({why}).': '{role} หยุดโดยไม่ได้รายงานว่าทำอะไรไป ({why})',
  '{role} finished without an account of what it did.': '{role} ทำเสร็จโดยไม่ได้รายงานว่าทำอะไรไป',
  '{role} failed without an account of what it did.': '{role} ล้มเหลวโดยไม่ได้รายงานว่าทำอะไรไป',
  '{role} was stopped without an account of what it did.': '{role} ถูกหยุดโดยไม่ได้รายงานว่าทำอะไรไป',
  'Proposed change to the {kind} "{goal}"': 'ข้อเสนอให้เปลี่ยน {kind} “{goal}”',
  'Currently: {statement}': 'ปัจจุบัน: {statement}',
  'Currently: {statement} ({status})': 'ปัจจุบัน: {statement} ({status})',
  'Proposed: {statement}': 'ที่เสนอ: {statement}',
  'Proposed status: {status}': 'สถานะที่เสนอ: {status}',
  'Reason given: {reason}': 'เหตุผลที่ให้มา: {reason}',
  'Approving it changes the goal; until then the work carries on under the goal as it is.': 'การอนุมัติจะเปลี่ยนเป้าหมาย ระหว่างนี้งานจะดำเนินต่อตามเป้าหมายเดิม',
  'The goal stays as it is.': 'เป้าหมายยังคงเดิม',
  'mission': 'พันธกิจ',
  'objective': 'วัตถุประสงค์',
  'key result': 'ผลลัพธ์หลัก',
  'Active': 'ใช้งานอยู่',
  'Met': 'บรรลุแล้ว',
  'Abandoned': 'ล้มเลิกแล้ว',
  'This work asked for it at tier {tier}, and policy {policies} requires your approval.': 'งานนี้ขอใช้ที่ระดับ {tier} และนโยบาย {policies} กำหนดให้ต้องได้รับการอนุมัติจากคุณ',
  'This work asked for it at tier {tier}, and the task began with content from outside the company.': 'งานนี้ขอใช้ที่ระดับ {tier} และงานเริ่มต้นจากเนื้อหาภายนอกบริษัท',
  'This work asked for it at tier {tier}, and the work read content from outside the company before asking.': 'งานนี้ขอใช้ที่ระดับ {tier} และงานได้อ่านเนื้อหาจากภายนอกบริษัทก่อนจะขอ',
  'This work asked for it at tier {tier}, after the work read content from outside the company, and the guardian asked you first: {reason}': 'งานนี้ขอใช้ที่ระดับ {tier} หลังจากงานอ่านเนื้อหาจากภายนอกบริษัท และผู้พิทักษ์ขอถามคุณก่อน: {reason}',
  'it doubted this call before, and you allowed it once': 'ผู้พิทักษ์เคยสงสัยการเรียกนี้มาก่อน และคุณอนุญาตไปแล้วครั้งหนึ่ง',
  'This work asked for it at tier {tier}, which cannot be reversed.': 'งานนี้ขอใช้ที่ระดับ {tier} ซึ่งย้อนกลับไม่ได้',
  'You approved this once already, and the worker carrying it out stopped before it could say whether it happened: it may already have happened. Check before approving it again.': 'คุณเคยอนุมัติเรื่องนี้ไปแล้วครั้งหนึ่ง และเวิร์กเกอร์ที่ดำเนินการหยุดไปก่อนจะบอกได้ว่าเกิดขึ้นแล้วหรือยัง: อาจเกิดขึ้นไปแล้ว ตรวจสอบก่อนอนุมัติอีกครั้ง',
  'What this is for — {goals}': 'สิ่งนี้มีไว้เพื่อ — {goals}',
  'The task halts and no external change is made.': 'งานจะหยุด และไม่มีการเปลี่ยนแปลงภายนอกใดเกิดขึ้น',
  'Scored against {total} references: {passed} passed, {failed} failed.': 'ประเมินกับตัวอย่างอ้างอิง {total} รายการ: ผ่าน {passed} ไม่ผ่าน {failed}',
  'This role has fewer than {minimum} accepted references, so the change is unscored. That is not the same as passing.': 'บทบาทนี้มีตัวอย่างอ้างอิงที่ยอมรับแล้วน้อยกว่า {minimum} รายการ การเปลี่ยนแปลงจึงไม่ได้รับคะแนน ซึ่งไม่ได้แปลว่าผ่าน',
  'The role keeps working exactly as it does now.': 'บทบาทนี้ทำงานต่อไปเหมือนเดิมทุกประการ',
  '{role} asks: {question}': '{role} ถามว่า: {question}',
  'The run did not say more than the question.': 'รอบการทำงานไม่ได้บอกอะไรมากกว่าคำถาม',
  'The task is stopped, and nothing it was going to do happens.': 'งานถูกหยุด และสิ่งที่งานจะทำจะไม่เกิดขึ้น',
};
