/**
 * Filipino: what the platform itself says to the owner outside the
 * console (src/owner/say.ts), keyed by its English. The terms are the
 * console's (console/src/locales/tl.ts), so a button on the phone reads
 * as the same button in the app.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'Insidente: {title}',
  'Done: {goal}': 'Tapos na: {goal}',
  'Stopped before finishing: {goal}': 'Huminto bago matapos: {goal}',
  'Not done: {goal}': 'Hindi nagawa: {goal}',
  'Why: {reason}': 'Dahilan: {reason}',
  'a task': 'isang gawain',
  'Approval needed: {title}': 'Kailangan ng pag-apruba: {title}',
  '{summary} — if denied: {consequence}': '{summary} — kapag tinanggihan: {consequence}',
  'If denied:': 'Kapag tinanggihan:',
  'Expires:': 'Mag-e-expire:',
  'This one is decided in the app.': 'Sa app pinagpapasyahan ang isang ito.',
  'Open in PALUGADA': 'Buksan sa PALUGADA',
  'Approve': 'I-approve',
  'Deny': 'Tanggihan',
  'Ask': 'Magtanong',
  'Approved. Nothing left to press here.': 'Inaprubahan. Wala nang pipindutin dito.',
  'Denied. Nothing left to press here.': 'Tinanggihan. Wala nang pipindutin dito.',
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    'Nag-expire nang walang sagot. Pagtanggi ang pananahimik, kaya walang ginawa.',
  'This bot only answers to its owner.': 'Sa may-ari lang nito sumasagot ang bot na ito.',
  'That one has to be approved in the app.': 'Sa app dapat aprubahan ang isang iyan.',
  'That could not be recorded.': 'Hindi iyon maitala.',
  'That item no longer exists.': 'Wala na ang item na iyan.',
  'What do you want to ask about "{title}"? Reply to this message.':
    'Ano ang gusto mong itanong tungkol sa “{title}”? Sumagot sa mensaheng ito.',
  'Your question': 'Ang iyong tanong',
  'Type your question as a reply.': 'I-type ang iyong tanong bilang reply.',
  'Asked. The answer will be on the item in the app.': 'Naitanong na. Nasa item sa app ang magiging sagot.',
  'Answer': 'Sagutin',
  'Answer in words': 'Sumagot gamit ang mga salita',
  'That choice is not on this question.': 'Wala sa tanong na ito ang piniling iyan.',
  'Chosen: {choice}.': 'Napili: {choice}.',
  'Stop the task': 'Ihinto ang gawain',
  'Your answer to "{question}"? Reply to this message.': 'Ang sagot mo sa “{question}”? Sumagot sa mensaheng ito.',
  'Your answer': 'Ang iyong sagot',
  'Type your answer as a reply.': 'I-type ang iyong sagot bilang reply.',
  'Answered. The task carries on with it.': 'Nasagot. Itutuloy ito ng gawain gamit iyon.',
  'That is too long for one question; keep it under {max} characters.':
    'Masyadong mahaba iyan para sa isang tanong; panatilihin itong mas maikli sa {max} character.',
  '[a key, not kept]': '[isang key, hindi itinago]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    'Mukhang key iyan, kaya hindi ko ito itinago o ipinadala kahit saan. Sa naka-seal na field sa isang card inilalagay ang mga key, o sa page nito sa “Deployment na ito”: sabihin mo sa akin kung para saan ito at ilalagay ko sa harap mo ang card.',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'Wala pang naka-set up na modelo, kaya hindi pa ako makapag-isip. Pumili ng isa sa “Deployment na ito”, “Modelo”; pagkatapos ay matutulungan na kita sa lahat ng iba pa.',
  'The model did not answer: {reason}': 'Hindi sumagot ang modelo: {reason}',
  'Here is what I propose.': 'Ito ang mungkahi ko.',
  'I have nothing to add.': 'Wala na akong maidadagdag.',
  '{name}, CEO of {company}': '{name}, CEO ng {company}',
  'That could not be answered: {reason}': 'Hindi iyon masagot: {reason}',
  'I read text and voice notes.': 'Nagbabasa ako ng teksto at voice note.',
  'Now talking to {name}.': 'Kausap na ngayon si {name}.',
  'Choose whom to talk to.': 'Piliin kung sino ang kakausapin.',
  'Choose whom to talk to': 'Piliin kung sino ang kakausapin',
  'Talk to PALUGADA about the whole deployment': 'Kausapin ang PALUGADA tungkol sa buong deployment',
  'Who you are talking to, and how': 'Sino ang kausap mo, at paano',
  'Stopped.': 'Inihinto.',
  'Write here to talk to {name}.': 'Sumulat dito para kausapin si {name}.',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    'Si {name} ang kausap mo. Sumulat, o magpadala ng voice note. Ang /ceo ang pumipili kung sino ang kausap mo; ang /palugada ay para kausapin ang PALUGADA tungkol sa buong deployment.',
  'You said: "{words}"': 'Sinabi mo: “{words}”',
  'in the app': 'sa app',
  'Apply: {summary}': 'Ilapat: {summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    'Wala pang nakakarinig ng pananalita: pumili ng provider sa app, sa “Deployment na ito”, “Mga tool”, “Pakikinig”.',
  'That recording is too long; keep a voice note under {max} MB.':
    'Masyadong mahaba ang recording na iyan; panatilihing mas maliit sa {max} MB ang voice note.',
  'I could not make out any words in that.': 'Wala akong naintindihang salita riyan.',
  'Done: {summary}': 'Tapos na: {summary}',
  'That one is applied in the app.': 'Sa app inilalapat ang isang iyan.',
  'That card no longer exists.': 'Wala na ang card na iyan.',
  'That card was already applied.': 'Nailapat na ang card na iyan.',
  'That card was dismissed.': 'Na-dismiss na ang card na iyan.',
  'That card failed when it was applied.': 'Nabigo ang card na iyan nang ilapat.',
  'That could not be done: {reason}': 'Hindi iyon magawa: {reason}',
  'Choose': 'Pumili',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    'Ano ang gusto mong itanong tungkol sa “{title}”? Sagutin ang mensaheng ito gamit ang iyong tanong.',
  'Your answer to "{question}"? Reply to this message with your answer.':
    'Ang sagot mo sa “{question}”? Sagutin ang mensaheng ito gamit ang iyong sagot.',
  'I read text messages here.': 'Text message ang binabasa ko rito.',
  'Apply one of these here:': 'Ilapat ang isa sa mga ito rito:',
  'Apply {number}': 'Ilapat ang {number}',
  'Signed in to {provider} for the {alias} key': 'Naka-sign in sa {provider} para sa key na {alias}',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'Bumalik sa PALUGADA: hawak na ng dibisyon ang key na ito, at nire-renew ito bago maubos. Puwede nang isara ang tab na ito.',
  'Signed in to {name}': 'Naka-sign in sa {name}',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'Bumalik sa PALUGADA para piliin kung alin sa mga tool nito ang puwedeng gamitin ng mga role. Puwede nang isara ang tab na ito.',
  'Not signed in': 'Hindi naka-sign in',
  'Recorded: approved.': 'Naitala: inaprubahan.',
  'Recorded: denied.': 'Naitala: tinanggihan.',
  'Recorded: asked.': 'Naitala: itinanong.',
  'Asked. Nothing left to press here.': 'Naitanong na. Wala nang pipindutin dito.',
  'Withdrawn: the task it was asking about has finished.': 'Binawi: tapos na ang gawaing itinatanong nito.',
  'Withdrawn: the task it was asking about has failed.': 'Binawi: nabigo ang gawaing itinatanong nito.',
  'Withdrawn: the task it was asking about was stopped.': 'Binawi: inihinto ang gawaing itinatanong nito.',
  'Withdrawn: the task it was asking about was cancelled.': 'Binawi: kinansela ang gawaing itinatanong nito.',
  'Decided. Nothing left to press here.': 'Napagpasyahan. Wala nang pipindutin dito.',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': 'Binawi: binago ng agent ang mungkahi nito at nagtanong ulit tungkol sa bago.',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': 'Binawi: wala na ang kumpanya sa yugtong aalisan sana nito ayon sa mungkahing ito.',
  'Withdrawn: it was already decided in the app.': 'Binawi: napagpasyahan na ito sa app.',
  'Withdrawn. Nothing left to press here.': 'Binawi. Wala nang pipindutin dito.',
  'Work stopped: the {account} account is out of tokens': 'Huminto ang trabaho: ubos na ang token ng account na {account}',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': 'Huminto ang “{work}” dahil nagamit na ng account na {account} ang {spent} sa {max} nitong token. Itaas ang limit nito sa Pera, pagkatapos ay buksan ang gawain at pindutin ang Ituloy: magpapatuloy ito mula sa kung saan ito huminto.',
  'Withdrawn: you continued the task it was about.': 'Binawi: itinuloy mo na ang gawaing tinutukoy nito.',
};
