/**
 * Filipino: what the platform itself says to the owner outside the
 * console (src/owner/say.ts), keyed by its English. The terms are the
 * console's (console/src/locales/tl.ts), so a button on the phone reads
 * as the same button in the app.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'Insidente: {title}',
  'Done: {goal}': 'Tapos na: {goal}',
  'Stopped before finishing: {goal}': 'Huminto bago matapos: {goal}',
  'Not done: {goal}': 'Hindi nagawa: {goal}',
  'Why: {reason}': 'Dahilan: {reason}',
  'a task': 'isang gawain',
  'Approval needed: {title}': 'Kailangan ng pag-apruba: {title}',
  '{summary} — if denied: {consequence}': '{summary} — kapag tinanggihan: {consequence}',
  '{role} asks:': 'Tanong ni {role}:',
  'If denied:': 'Kapag tinanggihan:',
  'Expires:': 'Mag-e-expire:',
  'This one is decided in the app.': 'Sa app pinagpapasyahan ang isang ito.',
  'Open in PALUGADA': 'Buksan sa PALUGADA',
  'Approve': 'I-approve',
  'Deny': 'Tanggihan',
  'Ask': 'Magtanong',
  'Approved. Nothing left to press here.': 'Inaprubahan. Wala nang pipindutin dito.',
  'Denied. Nothing left to press here.': 'Tinanggihan. Wala nang pipindutin dito.',
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    'Nag-expire nang walang sagot. Pagtanggi ang pananahimik, kaya walang ginawa.',
  'This bot only answers to its owner.': 'Sa may-ari lang nito sumasagot ang bot na ito.',
  'That one has to be approved in the app.': 'Sa app dapat aprubahan ang isang iyan.',
  'That could not be recorded.': 'Hindi iyon maitala.',
  'That item no longer exists.': 'Wala na ang item na iyan.',
  'What do you want to ask about "{title}"? Reply to this message.':
    'Ano ang gusto mong itanong tungkol sa “{title}”? Sumagot sa mensaheng ito.',
  'Your question': 'Ang iyong tanong',
  'Type your question as a reply.': 'I-type ang iyong tanong bilang reply.',
  'Asked. The answer will be on the item in the app.': 'Naitanong na. Nasa item sa app ang magiging sagot.',
  'Answer': 'Sagutin',
  'Answer in words': 'Sumagot gamit ang mga salita',
  'That choice is not on this question.': 'Wala sa tanong na ito ang piniling iyan.',
  'Chosen: {choice}.': 'Napili: {choice}.',
  'Stop the task': 'Ihinto ang gawain',
  'Your answer to "{question}"? Reply to this message.': 'Ang sagot mo sa “{question}”? Sumagot sa mensaheng ito.',
  'Your answer': 'Ang iyong sagot',
  'Type your answer as a reply.': 'I-type ang iyong sagot bilang reply.',
  'Answered. The task carries on with it.': 'Nasagot. Itutuloy ito ng gawain gamit iyon.',
  'That is too long for one question; keep it under {max} characters.':
    'Masyadong mahaba iyan para sa isang tanong; panatilihin itong mas maikli sa {max} character.',
  '[a key, not kept]': '[isang key, hindi itinago]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    'Mukhang key iyan, kaya hindi ko ito itinago o ipinadala kahit saan. Sa naka-seal na field sa isang card inilalagay ang mga key, o sa page nito sa “Deployment na ito”: sabihin mo sa akin kung para saan ito at ilalagay ko sa harap mo ang card.',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'Wala pang naka-set up na modelo, kaya hindi pa ako makapag-isip. Pumili ng isa sa “Deployment na ito”, “Modelo”; pagkatapos ay matutulungan na kita sa lahat ng iba pa.',
  'The model did not answer: {reason}': 'Hindi sumagot ang modelo: {reason}',
  'Here is what I propose.': 'Ito ang mungkahi ko.',
  'I have nothing to add.': 'Wala na akong maidadagdag.',
  '{name}, CEO of {company}': '{name}, CEO ng {company}',
  'That could not be answered: {reason}': 'Hindi iyon masagot: {reason}',
  'I read text and voice notes.': 'Nagbabasa ako ng teksto at voice note.',
  'Now talking to {name}.': 'Kausap na ngayon si {name}.',
  'Choose whom to talk to.': 'Piliin kung sino ang kakausapin.',
  'Choose whom to talk to': 'Piliin kung sino ang kakausapin',
  'Talk to PALUGADA about the whole deployment': 'Kausapin ang PALUGADA tungkol sa buong deployment',
  'Who you are talking to, and how': 'Sino ang kausap mo, at paano',
  'Stopped.': 'Inihinto.',
  'Write here to talk to {name}.': 'Sumulat dito para kausapin si {name}.',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    'Si {name} ang kausap mo. Sumulat, o magpadala ng voice note. Ang /ceo ang pumipili kung sino ang kausap mo; ang /palugada ay para kausapin ang PALUGADA tungkol sa buong deployment.',
  'You said: "{words}"': 'Sinabi mo: “{words}”',
  'in the app': 'sa app',
  'Apply: {summary}': 'Ilapat: {summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    'Wala pang nakakarinig ng pananalita: pumili ng provider sa app, sa “Deployment na ito”, “Mga tool”, “Pakikinig”.',
  'That recording is too long; keep a voice note under {max} MB.':
    'Masyadong mahaba ang recording na iyan; panatilihing mas maliit sa {max} MB ang voice note.',
  'I could not make out any words in that.': 'Wala akong naintindihang salita riyan.',
  'Done: {summary}': 'Tapos na: {summary}',
  'That one is applied in the app.': 'Sa app inilalapat ang isang iyan.',
  'That card no longer exists.': 'Wala na ang card na iyan.',
  'That card was already applied.': 'Nailapat na ang card na iyan.',
  'That card was dismissed.': 'Na-dismiss na ang card na iyan.',
  'That card failed when it was applied.': 'Nabigo ang card na iyan nang ilapat.',
  'That could not be done: {reason}': 'Hindi iyon magawa: {reason}',
  'Choose': 'Pumili',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    'Ano ang gusto mong itanong tungkol sa “{title}”? Sagutin ang mensaheng ito gamit ang iyong tanong.',
  'Your answer to "{question}"? Reply to this message with your answer.':
    'Ang sagot mo sa “{question}”? Sagutin ang mensaheng ito gamit ang iyong sagot.',
  'I read text messages here.': 'Text message ang binabasa ko rito.',
  'Apply one of these here:': 'Ilapat ang isa sa mga ito rito:',
  'Apply {number}': 'Ilapat ang {number}',
  'Signed in to {provider} for the {alias} key': 'Naka-sign in sa {provider} para sa key na {alias}',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'Bumalik sa PALUGADA: hawak na ng dibisyon ang key na ito, at nire-renew ito bago maubos. Puwede nang isara ang tab na ito.',
  'Signed in to {name}': 'Naka-sign in sa {name}',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'Bumalik sa PALUGADA para piliin kung alin sa mga tool nito ang puwedeng gamitin ng mga role. Puwede nang isara ang tab na ito.',
  'Not signed in': 'Hindi naka-sign in',
  'Recorded: approved.': 'Naitala: inaprubahan.',
  'Recorded: denied.': 'Naitala: tinanggihan.',
  'Recorded: asked.': 'Naitala: itinanong.',
  'Asked. Nothing left to press here.': 'Naitanong na. Wala nang pipindutin dito.',
  'Withdrawn: the task it was asking about has finished.': 'Binawi: tapos na ang gawaing itinatanong nito.',
  'Withdrawn: the task it was asking about has failed.': 'Binawi: nabigo ang gawaing itinatanong nito.',
  'Withdrawn: the task it was asking about was stopped.': 'Binawi: inihinto ang gawaing itinatanong nito.',
  'Withdrawn: the task it was asking about was cancelled.': 'Binawi: kinansela ang gawaing itinatanong nito.',
  'Decided. Nothing left to press here.': 'Napagpasyahan. Wala nang pipindutin dito.',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': 'Binawi: binago ng agent ang mungkahi nito at nagtanong ulit tungkol sa bago.',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': 'Binawi: wala na ang kumpanya sa yugtong aalisan sana nito ayon sa mungkahing ito.',
  'Withdrawn: it was already decided in the app.': 'Binawi: napagpasyahan na ito sa app.',
  'Withdrawn. Nothing left to press here.': 'Binawi. Wala nang pipindutin dito.',
  'company': 'kumpanya',
  'Work stopped: the {account} account is out of tokens': 'Huminto ang trabaho: ubos na ang token ng account na {account}',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': 'Huminto ang “{work}” dahil nagamit na ng account na {account} ang {spent} sa {max} nitong token. Itaas ang limit nito sa Pera, pagkatapos ay buksan ang gawain at pindutin ang Ituloy: magpapatuloy ito mula sa kung saan ito huminto.',
  'Withdrawn: you continued the task it was about.': 'Binawi: itinuloy mo na ang gawaing tinutukoy nito.',
  'Broke its contract': 'Lumabag sa kontrata nito',
  'Refused by a policy': 'Tinanggihan ng isang patakaran',
  'Out of budget': 'Ubos na ang badyet',
  'Handed on too many times': 'Masyadong maraming beses ipinasa',
  'Missed its deadline': 'Lumampas sa deadline nito',
  'Its result did not check out': 'Hindi pumasa sa pagsusuri ang resulta nito',
  'A capability it needs is down': 'Hindi gumagana ang isang kakayahang kailangan nito',
  'No runtime could take it': 'Walang runtime na makakakuha nito',
  'Went in a circle': 'Umikot-ikot lang',
  'Split into too many sub-tasks': 'Hinati sa napakaraming sub-gawain',
  'Wrote more than its role allows one run': 'Sumulat nang higit sa pinapayagan ng role nito sa isang takbo',
  'Your approval was not given in time': 'Hindi dumating sa oras ang iyong pag-apruba',
  'Stopped by you': 'Inihinto mo',
  'Cancelled by you': 'Kinansela mo',
  'The company is frozen': 'Naka-freeze ang kumpanya',
  'Its record did not match on replay': 'Hindi tumugma ang rekord nito sa replay',
  'It kept stopping the worker running it': 'Paulit-ulit nitong pinahinto ang worker na nagpapatakbo rito',
  'Not done': 'Hindi nagawa',
  'Task failed': 'Nabigo ang gawain',
  'Digest for {day}': 'Buod para sa {day}',
  'Spent: {amount}': 'Nagastos: {amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': 'Trabaho: {done} tapos na, {failed} nabigo, {stopped} nahinto',
  'Inbox: {open} waiting (incidents: {incidents})': 'Inbox: {open} naghihintay (mga insidente: {incidents})',
  'Stopped ({count}): {reason}': 'Nahinto ({count}): {reason}',
  'Start an ad campaign': 'Magsimula ng ad campaign',
  'Block time on the calendar': 'Magreserba ng oras sa kalendaryo',
  'Read the calendar': 'Basahin ang kalendaryo',
  'Run code': 'Magpatakbo ng code',
  'Add a note to a customer': 'Magdagdag ng tala sa record ng customer',
  'Read customer records': 'Basahin ang mga record ng customer',
  'Release to the live site': 'Ilabas sa live na site',
  'Release to the test site': 'Ilabas sa pansubok na site',
  'Change a domain\'s nameservers': 'Baguhin ang mga nameserver ng domain',
  'Read a domain\'s records': 'Basahin ang mga record ng domain',
  'Change a domain\'s record': 'Baguhin ang isang record ng domain',
  'Write a document': 'Sumulat ng dokumento',
  'Sign a document': 'Pumirma sa dokumento',
  'Buy a domain': 'Bumili ng domain',
  'Transfer a domain': 'Ilipat ang isang domain',
  'Draft an email': 'Mag-draft ng email',
  'Send an email': 'Magpadala ng email',
  'List files': 'Ilista ang mga file',
  'Transfer money': 'Maglipat ng pera',
  'Propose a goal change': 'Magmungkahi ng pagbabago sa layunin',
  'Make a picture': 'Gumawa ng larawan',
  'Issue an invoice': 'Mag-isyu ng invoice',
  'Pay an invoice': 'Magbayad ng invoice',
  'Read the books': 'Basahin ang talaan ng pananalapi',
  'Read the mailbox': 'Basahin ang mailbox',
  'Search what the company knows': 'Hanapin ang alam ng kumpanya',
  'Record a measure': 'Magtala ng sukatan',
  'Read product numbers': 'Basahin ang mga numero ng produkto',
  'Ask you a question': 'Magtanong sa iyo',
  'Write down a plan': 'Magtala ng plano',
  'Delete a record': 'Burahin ang isang record',
  'Propose a code change': 'Magmungkahi ng pagbabago sa code',
  'Read the code': 'Basahin ang code',
  'Destroy a server': 'Burahin nang tuluyan ang isang server',
  'Read a skill': 'Basahin ang isang kasanayan',
  'Publish a post': 'Mag-publish ng post',
  'Read text aloud': 'Basahin nang malakas ang teksto',
  'Turn speech into text': 'Gawing teksto ang pananalita',
  'Propose a new stage': 'Magmungkahi ng bagong yugto',
  'Wait for work handed on': 'Hintayin ang gawaing ipinasa',
  'Hand work to another role': 'Ipasa ang trabaho sa ibang role',
  'File a ticket': 'Magbukas ng ticket',
  'List tickets': 'Ilista ang mga ticket',
  'Check a service is up': 'Suriin kung gumagana ang serbisyo',
  'Read a web page': 'Basahin ang isang web page',
  'Open a web page': 'Buksan ang isang web page',
  'Search the web': 'Maghanap sa web',
  'no stage': 'walang yugto',
  'Explore': 'Paggalugad',
  'Validate': 'Pagpapatunay',
  'Build': 'Pagbuo',
  'Launch': 'Paglulunsad',
  'Grow': 'Paglago',
  'Wind down': 'Pagsasara',
  'Monthly budget reached; the company is paused': 'Naabot ang buwanang badyet; naka-pause ang kumpanya',
  '{spent} of {limit} spent since {since}. No new task will start and no external action will run until you raise the ceiling or allow spending past it for a while, under Money.': '{spent} sa {limit} ang nagastos mula {since}. Walang bagong gawaing magsisimula at walang aksyong panlabas na tatakbo hanggang itaas mo ang limit o pansamantalang payagan ang paggastos nang lampas dito, sa “Pera”.',
  'Monthly budget is 80% spent': 'Nagastos na ang 80% ng buwanang badyet',
  '{spent} of {limit} spent since {since}. At 100% the company pauses.': '{spent} sa {limit} ang nagastos mula {since}. Sa 100%, mapa-pause ang kumpanya.',
  'Role {role} is paused for spending too fast': 'Naka-pause si {role} dahil masyadong mabilis ang paggastos nito',
  '{role} spent {spent} in the last hour, {multiple} times its usual {usual} an hour. It is paused before the monthly ceiling is reached, so there is money left to work with once you have found out why. Resume it when you have.': 'Gumastos si {role} ng {spent} sa nakaraang oras, {multiple} beses ng karaniwan nitong {usual} bawat oras. Na-pause ito bago maabot ang buwanang limit, para may matira pang pera na magagamit kapag nalaman mo na ang dahilan. Ituloy ito kapag nalaman mo na.',
  'Daily model spend over threshold': 'Lumampas sa threshold ang araw-araw na gastos sa modelo',
  'Model spend today is {spent}, over the {limit} ceiling.': 'Ang gastos sa modelo ngayong araw ay {spent}, lampas sa limit na {limit}.',
  'Task failure rate over threshold': 'Lumampas sa threshold ang rate ng pagkabigo ng mga gawain',
  '{failed} of {finished} tasks failed or stopped today ({rate}%), over the {limit}% threshold.': '{failed} sa {finished} gawain ang nabigo o huminto ngayong araw ({rate}%), lampas sa threshold na {limit}%.',
  'Unusual number of policy refusals': 'Hindi pangkaraniwang dami ng pagtanggi ng patakaran',
  'Actions refused by a policy today: {count}, over the threshold of {limit}. Either an agent is probing its limits or a policy is miscalibrated.': 'Mga aksyong tinanggihan ng isang patakaran ngayong araw: {count}, lampas sa threshold na {limit}. Maaaring may agent na sumusubok sa mga limit nito, o may patakarang mali ang pagkakatakda.',
  'External writes failed verification': 'Hindi pumasa sa beripikasyon ang mga write sa labas',
  'Writes outside that reported success but read back differently: {count}. Something is changing them other than as asked.': 'Mga write sa labas na nag-ulat ng tagumpay pero iba ang lumabas nang basahin ulit: {count}. May nagbabago sa mga ito nang hindi ayon sa hiniling.',
  'A capability stopped being usable': 'Hindi na magamit ang isang kakayahan',
  'Tasks that could not start today because a capability their role needs failed its check: {count}. A credential has probably expired or a quota is used up.': 'Mga gawaing hindi makapagsimula ngayong araw dahil hindi pumasa sa pagsusuri ang isang kakayahang kailangan ng kanilang role: {count}. Malamang na nag-expire ang isang credential o naubos ang isang quota.',
  'A worker stopped reporting mid-run': 'Huminto sa pag-uulat ang isang worker sa gitna ng takbo',
  'Runs that stopped reporting and were taken back today: {count}. The work was picked up again; the tokens they had already spent were not recovered.': 'Mga takbong huminto sa pag-uulat at binawi ngayong araw: {count}. Itinuloy ulit ang trabaho; hindi na nabawi ang mga token na nagastos na nila.',
  '{role} was refused {denials} times today, at the limit of {limit}. No task will run as this role until you lift the freeze. The usual causes are a missing capability grant, a policy the role\'s charter does not account for, or work the role was never equipped to do.': 'Tinanggihan si {role} nang {denials} beses ngayong araw, abot sa limit na {limit}. Walang gawaing tatakbo bilang role na ito hanggang i-unfreeze mo ito. Ang karaniwang dahilan ay kulang na pahintulot sa isang kakayahan, isang patakarang hindi isinasaalang-alang ng charter ng role, o trabahong hindi kailanman inihanda ang role na gawin.',
  'Role {role} is frozen after repeated denials': 'Na-freeze si {role} matapos ang paulit-ulit na pagtanggi',
  'What it was refused: {capabilities}': 'Mga tinanggihan dito: {capabilities}',
  'It is waiting for an approval, and none is open, so nothing you can answer will move it.': 'Naghihintay ito ng pag-apruba, at walang bukas, kaya walang maisasagot ka na magpapausad dito.',
  'It is waiting for a review, and none is pending, so no reviewer and no decision of yours will move it.': 'Naghihintay ito ng review, at walang nakabinbin, kaya walang reviewer at walang pasya mo na magpapausad dito.',
  'It is parked until a window reopens, and the window never does.': 'Nakaparada ito hanggang magbukas ulit ang isang takdang oras, at hindi na iyon magbubukas kailanman.',
  'A task is waiting on nothing': 'May gawaing naghihintay sa wala',
  '"{task}" has been waiting since {since}. {why} Approve to run it again from where it stopped, or deny to cancel it.': 'Naghihintay ang “{task}” mula pa {since}. {why} I-approve para patakbuhin itong muli mula sa kung saan ito huminto, o Tanggihan para i-cancel ito.',
  'A task keeps stopping the worker running it': 'May gawaing paulit-ulit na nagpapahinto sa worker na nagpapatakbo rito',
  '"{task}" lost its worker {lost} times: each time the worker running it stopped answering before the work finished. What it had done is kept. It is halted so it cannot take another worker down; run it again once the cause is found, or cancel it.': 'Nawalan ng worker ang “{task}” nang {lost} beses: sa bawat pagkakataon, huminto sa pagsagot ang worker na nagpapatakbo rito bago natapos ang trabaho. Itinatago ang nagawa na nito. Inihinto ito para hindi na makapagpabagsak ng isa pang worker; patakbuhin itong muli kapag nahanap na ang dahilan, o i-cancel ito.',
  '{services} stayed unreachable, and the work that needs it stopped': 'Nanatiling hindi maabot ang {services}, at huminto ang trabahong nangangailangan nito',
  'The task waited about {minutes} minutes, looking again each time, and has stopped. Once the service answers, run it again.': 'Naghintay ang gawain nang mga {minutes} minuto, sinusubukan ulit sa bawat pagkakataon, at huminto na. Kapag sumagot na ang serbisyo, patakbuhin itong muli.',
  'It was tried {tries} times over about {minutes} minutes.': 'Sinubukan ito nang {tries} beses sa loob ng mga {minutes} minuto.',
  'This role can take actions that cannot be undone, so the run was not silently moved to a different model.': 'Kayang gumawa ng role na ito ng mga aksyong hindi na mababawi, kaya hindi tahimik na inilipat ang takbo sa ibang modelo.',
  'No fallback model is left for this role.': 'Wala nang natitirang pamalit na modelo para sa role na ito.',
  'Model {model} failed and the run was not moved': 'Nabigo ang modelong {model} at hindi inilipat ang takbo',
  'External write failed verification': 'Hindi pumasa sa beripikasyon ang isang write sa labas',
  'The task wrote to an outside service and read it back, and what it read did not match. Look at the place it wrote to before you run it again: the write may have happened.': 'Sumulat ang gawain sa isang serbisyo sa labas at binasa ito ulit, at hindi tumugma ang nabasa nito. Tingnan ang lugar na sinulatan nito bago mo ito patakbuhin ulit: maaaring natuloy na ang pagsulat.',
  'Review deadlocked after {rounds} revisions: {capability}': 'Naipit ang review matapos ang {rounds} rebisyon: {capability}',
  'The role and its reviewer did not agree on {capability}.': 'Hindi nagkasundo ang role at ang reviewer nito tungkol sa {capability}.',
  'The reviewer\'s last note: {note}': 'Huling tala ng reviewer: {note}',
  'The reviewer left no note.': 'Walang iniwang tala ang reviewer.',
  'What it was judged against: {criteria}': 'Ang pamantayang ginamit sa paghatol: {criteria}',
  'Review produced no usable verdict: {capability}': 'Walang magagamit na hatol ang review: {capability}',
  'The reviewing task ended without a decision that could be read. The proposed action is still blocked and needs your judgement.': 'Natapos ang gawaing nagre-review nang walang mababasang desisyon. Naka-block pa rin ang iminungkahing aksyon at kailangan nito ang iyong paghatol.',
  'another stage': 'ibang yugto',
  'Either answer only closes this: the company stays in the {stage} stage.': 'Alinmang sagot ay isasara lang ito: mananatili ang kumpanya sa yugtong {stage}.',
  'Either answer only closes this: the company stays without a stage.': 'Alinmang sagot ay isasara lang ito: mananatiling walang yugto ang kumpanya.',
  'To move it anyway, set the stage on the Overview.': 'Para ilipat pa rin ito, itakda ang yugto sa “Pangkalahatang-tanaw”.',
  '{reviewer} stopped a proposal to move the company from {from} to {to}': 'Pinahinto ni {reviewer} ang mungkahing ilipat ang kumpanya mula {from} papuntang {to}',
  '{reviewer} reviewed it before you and stopped it:': 'Sinuri ito ni {reviewer} bago ka at pinahinto ito:',
  'No reason was given.': 'Walang ibinigay na dahilan.',
  'What was proposed:': 'Ang iminungkahi:',
  'The company stays in the {stage} stage.': 'Mananatili ang kumpanya sa yugtong {stage}.',
  'The company stays without a stage.': 'Mananatiling walang yugto ang kumpanya.',
  'Move the company from {from} to {to}?': 'Ilipat ang kumpanya mula {from} papuntang {to}?',
  'Reviewed by {reviewer} before you:': 'Sinuri ni {reviewer} bago ka:',
  'The schedule "{schedule}" keeps producing the same result': 'Paulit-ulit na pareho ang resulta ng iskedyul na “{schedule}”',
  'Its last {runs} runs all ended with the same output. That is sometimes exactly right -- a report with nothing new to say -- and often a schedule that stopped doing anything useful while still being paid for. Deny to turn it off; approve to keep it running and not be asked about this result again.': 'Pare-pareho ang output ng huling {runs} takbo nito. Minsan, iyon mismo ang tama — isang ulat na walang bagong masasabi — at madalas, isa itong iskedyul na tumigil nang gumawa ng anumang kapaki-pakinabang pero binabayaran pa rin. Tanggihan para i-off ito; I-approve para patuloy itong tumakbo at hindi ka na tanungin tungkol sa resultang ito.',
  'Capability {capability} failed preflight': 'Hindi pumasa sa paunang pagsusuri ang kakayahang {capability}',
  'Work that needs it is stopped rather than started: fix the cause, then run that work again. The usual causes are an expired or wrongly scoped credential, a quota used up, or an address that is wrong.': 'Inihinto ang trabahong nangangailangan nito sa halip na simulan: ayusin ang dahilan, pagkatapos ay patakbuhin ulit ang trabahong iyon. Ang karaniwang dahilan ay credential na nag-expire o mali ang saklaw, quota na naubos na, o maling address.',
  'Batch guard stopped {capability}': 'Pinahinto ng bantay sa batch ang {capability}',
  'It did not match the plan its run recorded. Nothing was sent, and no service was called.': 'Hindi ito tumugma sa planong itinala ng takbo nito. Walang naipadala, at walang serbisyong tinawag.',
  '{role} was asked first and has had {minutes} minutes.': 'Unang tinanong si {role} at nabigyan na ng {minutes} minuto.',
  '{role} is not a role in this company, so this came to you at once.': 'Hindi role sa kumpanyang ito si {role}, kaya agad itong napunta sa iyo.',
  '{role} could not be given this: the company has no active goal or project to hang it from.': 'Hindi ito maibigay kay {role}: walang aktibong layunin o proyekto ang kumpanya na mapaglalagyan nito.',
  '{role} could not be given this ({record}), so this came to you at once.': 'Hindi ito maibigay kay {role} ({record}), kaya agad itong napunta sa iyo.',
  '{role} stopped without an account of what it did ({why}).': 'Huminto si {role} nang walang ulat sa ginawa nito ({why}).',
  '{role} finished without an account of what it did.': 'Natapos si {role} nang walang ulat sa ginawa nito.',
  '{role} failed without an account of what it did.': 'Nabigo si {role} nang walang ulat sa ginawa nito.',
  '{role} was stopped without an account of what it did.': 'Inihinto si {role} nang walang ulat sa ginawa nito.',
  'Proposed change to the {kind} "{goal}"': 'Iminumungkahing pagbabago sa {kind} na “{goal}”',
  'Currently: {statement}': 'Sa ngayon: {statement}',
  'Currently: {statement} ({status})': 'Sa ngayon: {statement} ({status})',
  'Proposed: {statement}': 'Iminumungkahi: {statement}',
  'Proposed status: {status}': 'Iminumungkahing status: {status}',
  'Reason given: {reason}': 'Ibinigay na dahilan: {reason}',
  'Approving it changes the goal; until then the work carries on under the goal as it is.': 'Kapag inaprubahan ito, mababago ang layunin; hanggang doon, magpapatuloy ang trabaho sa ilalim ng layunin gaya ng dati.',
  'The goal stays as it is.': 'Mananatili ang layunin gaya ng dati.',
  'mission': 'misyon',
  'objective': 'layunin',
  'key result': 'pangunahing resulta',
  'Active': 'Aktibo',
  'Met': 'Naabot',
  'Abandoned': 'Iniwan',
  'This work asked for it at tier {tier}, and policy {policies} requires your approval.': 'Hiniling ito ng trabahong ito sa antas {tier}, at kailangan ng patakarang {policies} ang iyong pag-apruba.',
  'This work asked for it at tier {tier}, and the task began with content from outside the company.': 'Hiniling ito ng trabahong ito sa antas {tier}, at nagsimula ang gawain sa content mula sa labas ng kumpanya.',
  'This work asked for it at tier {tier}, and the work read content from outside the company before asking.': 'Hiniling ito ng trabahong ito sa antas {tier}, at nagbasa ang trabaho ng content mula sa labas ng kumpanya bago humiling.',
  'This work asked for it at tier {tier}, after the work read content from outside the company, and the guardian asked you first: {reason}': 'Hiniling ito ng trabahong ito sa antas {tier}, matapos magbasa ang trabaho ng content mula sa labas ng kumpanya, at nagtanong muna sa iyo ang tagabantay: {reason}',
  'it doubted this call before, and you allowed it once': 'pinagdudahan na nito ang tawag na ito dati, at pinayagan mo ito nang isang beses',
  'This work asked for it at tier {tier}, which cannot be reversed.': 'Hiniling ito ng trabahong ito sa antas {tier}, na hindi na mababawi.',
  'You approved this once already, and the worker carrying it out stopped before it could say whether it happened: it may already have happened. Check before approving it again.': 'Na-approve mo na ito minsan, at huminto ang worker na nagsasagawa nito bago nito nasabi kung natuloy ito: maaaring natuloy na ito. Suriin muna bago ito i-approve ulit.',
  'What this is for — {goals}': 'Para saan ito — {goals}',
  'The task halts and no external change is made.': 'Hihinto ang gawain at walang pagbabagong gagawin sa labas.',
  'Scored against {total} references: {passed} passed, {failed} failed.': 'Na-score laban sa {total} reference: {passed} pumasa, {failed} bumagsak.',
  'This role has fewer than {minimum} accepted references, so the change is unscored. That is not the same as passing.': 'Kulang sa {minimum} ang tinanggap na reference ng role na ito, kaya walang score ang pagbabago. Hindi iyon katulad ng pagpasa.',
  'The role keeps working exactly as it does now.': 'Patuloy na magtatrabaho ang role nang eksaktong gaya ng ngayon.',
  '{role} asks: {question}': 'Tanong ni {role}: {question}',
  'The run did not say more than the question.': 'Wala nang ibang sinabi ang takbo bukod sa tanong.',
  'The task is stopped, and nothing it was going to do happens.': 'Ihihinto ang gawain, at hindi mangyayari ang anumang gagawin sana nito.',
};
