/**
 * Türkçe: what the platform itself says to the owner outside the console
 * (src/owner/say.ts), keyed by its English.
 *
 * The words are the console's (console/src/locales/tr.ts): Onayla, Reddet and
 * Sor on the buttons, "Bu kurulum, Araçlar, Dinleme" for the screens it
 * points at, and "siz" for the owner. No case suffix touches a placeholder:
 * a value stands after a colon, beside its noun, or next to a postposition
 * written apart ("{name} ile"). WhatsApp cuts a reply button's title at 20
 * characters and a list row's at 24, so those stay short.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'Aksaklık: {title}',
  'Done: {goal}': 'Tamamlandı: {goal}',
  'Stopped before finishing: {goal}': 'Bitmeden durdu: {goal}',
  'Not done: {goal}': 'Yapılmadı: {goal}',
  'Why: {reason}': 'Neden: {reason}',
  'a task': 'bir görev',
  'Approval needed: {title}': 'Onay gerekiyor: {title}',
  '{summary} — if denied: {consequence}': '{summary} — reddedilirse: {consequence}',
  '{role} asks:': '{role} soruyor:',
  'If denied:': 'Reddedilirse:',
  'Expires:': 'Sona erme:',
  'This one is decided in the app.': 'Bu, uygulamada karara bağlanır.',
  'Open in PALUGADA': "PALUGADA'da aç",
  'Approve': 'Onayla',
  'Deny': 'Reddet',
  'Ask': 'Sor',
  'Approved. Nothing left to press here.': 'Onaylandı. Burada basılacak başka bir şey yok.',
  'Denied. Nothing left to press here.': 'Reddedildi. Burada basılacak başka bir şey yok.',
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    'Yanıtlanmadan süresi doldu. Sessizlik ret sayılır; bu yüzden hiçbir şey yapılmadı.',
  'This bot only answers to its owner.': 'Bu bot yalnızca sahibine yanıt verir.',
  'That one has to be approved in the app.': 'Bunun uygulamada onaylanması gerekiyor.',
  'That could not be recorded.': 'Bu kaydedilemedi.',
  'That item no longer exists.': 'Bu öğe artık yok.',
  'What do you want to ask about "{title}"? Reply to this message.':
    '“{title}” hakkında ne sormak istiyorsunuz? Bu mesajı yanıtlayın.',
  'Your question': 'Sorunuz',
  'Type your question as a reply.': 'Sorunuzu bu mesaja yanıt olarak yazın.',
  'Asked. The answer will be on the item in the app.': 'Soruldu. Yanıt, uygulamadaki öğede görünecek.',
  'Answer': 'Yanıtla',
  'Answer in words': 'Sözle yanıtla',
  'That choice is not on this question.': 'Bu seçenek bu soruda yok.',
  'Chosen: {choice}.': 'Seçildi: {choice}.',
  'Stop the task': 'Görevi durdur',
  'Your answer to "{question}"? Reply to this message.': '“{question}” sorusuna yanıtınız nedir? Bu mesajı yanıtlayın.',
  'Your answer': 'Yanıtınız',
  'Type your answer as a reply.': 'Yanıtınızı bu mesaja yanıt olarak yazın.',
  'Answered. The task carries on with it.': 'Yanıtlandı. Görev bu yanıtla devam ediyor.',
  'That is too long for one question; keep it under {max} characters.':
    'Tek bir soru için çok uzun; {max} karakterin altında tutun.',
  '[a key, not kept]': '[bir anahtar, saklanmadı]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    'Bu bir anahtara benziyor; bu yüzden onu saklamadım ve hiçbir yere göndermedim. Anahtarlar bir kartın mühürlü alanına ya da Bu kurulum altındaki kendi sayfalarına girilir: ne için olduğunu söyleyin, kartı önünüze koyayım.',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'Henüz bir model ayarlanmadı; bu yüzden düşünemiyorum. Şuradan bir tane seçin: Bu kurulum, Yapay zekâ modeli. Sonra diğer her konuda yardımcı olabilirim.',
  'The model did not answer: {reason}': 'Model yanıt vermedi: {reason}',
  'Here is what I propose.': 'Önerim şu.',
  'I have nothing to add.': 'Ekleyecek bir şeyim yok.',
  '{name}, CEO of {company}': "{name}, {company} şirketinin CEO'su",
  'That could not be answered: {reason}': 'Bu yanıtlanamadı: {reason}',
  'I read text and voice notes.': 'Metin ve sesli mesajları okurum.',
  'Now talking to {name}.': 'Şu anda konuştuğunuz: {name}.',
  'Choose whom to talk to.': 'Kiminle konuşacağınızı seçin.',
  'Choose whom to talk to': 'Kiminle konuşacağınızı seçin',
  'Talk to PALUGADA about the whole deployment': 'Kurulumun tamamı hakkında PALUGADA ile konuşun',
  'Who you are talking to, and how': 'Kiminle ve nasıl konuştuğunuz',
  'Stopped.': 'Durduruldu.',
  'Write here to talk to {name}.': '{name} ile konuşmak için buraya yazın.',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    'Şu anda {name} ile konuşuyorsunuz. Yazın ya da sesli mesaj gönderin. /ceo kiminle konuşacağınızı seçer; /palugada sizi kurulumun tamamı hakkında PALUGADA ile konuşturur.',
  'You said: "{words}"': 'Söylediğiniz: “{words}”',
  'in the app': 'uygulamada',
  'Apply: {summary}': 'Uygula: {summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    'Henüz konuşmayı dinleyen bir şey yok: uygulamada şuradan bir sağlayıcı seçin: Bu kurulum, Araçlar, Dinleme.',
  'That recording is too long; keep a voice note under {max} MB.': 'Bu kayıt çok uzun; sesli mesajı {max} MB altında tutun.',
  'I could not make out any words in that.': 'Bu kayıtta tek bir kelime bile anlayamadım.',
  'Done: {summary}': 'Yapıldı: {summary}',
  'That one is applied in the app.': 'Bu kart uygulamada uygulanır.',
  'That card no longer exists.': 'Bu kart artık yok.',
  'That card was already applied.': 'Bu kart zaten uygulandı.',
  'That card was dismissed.': 'Bu kart yok sayıldı.',
  'That card failed when it was applied.': 'Bu kart uygulanırken başarısız oldu.',
  'That could not be done: {reason}': 'Bu yapılamadı: {reason}',
  'Choose': 'Seç',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    '“{title}” hakkında ne sormak istiyorsunuz? Sorunuzu bu mesaja yanıt olarak yazın.',
  'Your answer to "{question}"? Reply to this message with your answer.':
    '“{question}” sorusuna yanıtınız nedir? Yanıtınızı bu mesaja yanıt olarak yazın.',
  'I read text messages here.': 'Burada metin mesajlarını okurum.',
  'Apply one of these here:': 'Bunlardan birini buradan uygulayın:',
  'Apply {number}': 'Uygula: {number}',
  'Signed in to {provider} for the {alias} key': '{alias} anahtarı için {provider} hizmetinde oturum açıldı',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    "PALUGADA'ya dönün: bu anahtar artık departmanda tutuluyor ve süresi dolmadan yenileniyor. Bu sekmeyi kapatabilirsiniz.",
  'Signed in to {name}': '{name} hizmetinde oturum açıldı',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    "Rollerin hangi araçlarını kullanabileceğini seçmek için PALUGADA'ya dönün. Bu sekmeyi kapatabilirsiniz.",
  'Not signed in': 'Oturum açılmadı',
  'Recorded: approved.': 'Kaydedildi: onaylandı.',
  'Recorded: denied.': 'Kaydedildi: reddedildi.',
  'Recorded: asked.': 'Kaydedildi: soruldu.',
  'Asked. Nothing left to press here.': 'Soruldu. Burada basılacak başka bir şey yok.',
  'Withdrawn: the task it was asking about has finished.': 'Geri çekildi: ilgili görev tamamlandı.',
  'Withdrawn: the task it was asking about has failed.': 'Geri çekildi: ilgili görev başarısız oldu.',
  'Withdrawn: the task it was asking about was stopped.': 'Geri çekildi: ilgili görev durduruldu.',
  'Withdrawn: the task it was asking about was cancelled.': 'Geri çekildi: ilgili görev iptal edildi.',
  'Decided. Nothing left to press here.': 'Karara bağlandı. Burada basılacak başka bir şey yok.',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': 'Geri çekildi: ajan önerisini değiştirdi ve yenisi için yeniden sordu.',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': 'Geri çekildi: bu öneri şirketi bulunduğu aşamadan taşıyacaktı, ama şirket artık o aşamada değil.',
  'Withdrawn: it was already decided in the app.': 'Geri çekildi: uygulamada zaten karara bağlanmıştı.',
  'Withdrawn. Nothing left to press here.': 'Geri çekildi. Burada basılacak başka bir şey yok.',
  'company': 'Şirket',
  'Work stopped: the {account} account is out of tokens': 'İş durdu: {account} hesabının token’ları bitti',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': '“{work}” durdu çünkü {account} hesabı {max} token’ının {spent} tanesini kullandı. Para bölümünde tavanını yükseltin, sonra görevi açıp Devam et’e basın: kaldığı yerden sürer.',
  'Withdrawn: you continued the task it was about.': 'Geri çekildi: ilgili görevi sürdürdünüz.',
  'Broke its contract': 'Sözleşmesini ihlal etti',
  'Refused by a policy': 'Bir ilke tarafından reddedildi',
  'Out of budget': 'Bütçe tükendi',
  'Handed on too many times': 'Çok fazla kez devredildi',
  'Missed its deadline': 'Son tarihini kaçırdı',
  'Its result did not check out': 'Sonucu doğrulamadan geçemedi',
  'A capability it needs is down': 'İhtiyaç duyduğu bir yetenek çalışmıyor',
  'No runtime could take it': 'Hiçbir çalışma ortamı onu üstlenemedi',
  'Went in a circle': 'Döngüye girdi',
  'Split into too many sub-tasks': 'Çok fazla alt göreve bölündü',
  'Wrote more than its role allows one run': 'Rolünün bir çalıştırmada izin verdiğinden fazlasını yazdı',
  'Your approval was not given in time': 'Onayınız zamanında verilmedi',
  'Stopped by you': 'Sizin tarafınızdan durduruldu',
  'Cancelled by you': 'Sizin tarafınızdan iptal edildi',
  'The company is frozen': 'Şirket donduruldu',
  'Its record did not match on replay': 'Yeniden oynatmada kaydı eşleşmedi',
  'It kept stopping the worker running it': 'Onu çalıştıran işleyiciyi sürekli durdurdu',
  'Not done': 'Yapılmadı',
  'Task failed': 'Görev başarısız oldu',
  'Digest for {day}': '{day} özeti',
  'Spent: {amount}': 'Harcanan: {amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': 'İşler: {done} tamamlandı, {failed} başarısız, {stopped} durduruldu',
  'Inbox: {open} waiting (incidents: {incidents})': 'Gelen kutusu: {open} bekliyor (aksaklıklar: {incidents})',
  'Stopped ({count}): {reason}': 'Durdurulan ({count}): {reason}',
  'Start an ad campaign': 'Reklam kampanyası başlat',
  'Block time on the calendar': 'Takvimde zaman ayır',
  'Read the calendar': 'Takvimi oku',
  'Run code': 'Kod çalıştır',
  'Add a note to a customer': 'Müşteri kaydına not ekle',
  'Read customer records': 'Müşteri kayıtlarını oku',
  'Release to the live site': 'Canlı siteye yayınla',
  'Release to the test site': 'Test sitesine yayınla',
  'Change a domain\'s nameservers': 'Alan adının ad sunucularını değiştir',
  'Read a domain\'s records': 'Alan adının kayıtlarını oku',
  'Change a domain\'s record': 'Alan adının kaydını değiştir',
  'Write a document': 'Belge yaz',
  'Sign a document': 'Belge imzala',
  'Buy a domain': 'Alan adı satın al',
  'Transfer a domain': 'Alan adını transfer et',
  'Draft an email': 'E-posta taslağı hazırla',
  'Send an email': 'E-posta gönder',
  'List files': 'Dosyaları listele',
  'Transfer money': 'Para gönder',
  'Propose a goal change': 'Hedef değişikliği öner',
  'Make a picture': 'Görsel üret',
  'Issue an invoice': 'Fatura kes',
  'Pay an invoice': 'Fatura öde',
  'Read the books': 'Muhasebe kayıtlarını oku',
  'Read the mailbox': 'Posta kutusunu oku',
  'Search what the company knows': 'Şirketin bildiklerinde ara',
  'Record a measure': 'Metrik değeri kaydet',
  'Read product numbers': 'Ürün rakamlarını oku',
  'Ask you a question': 'Size soru sor',
  'Write down a plan': 'Plan kaydet',
  'Delete a record': 'Kayıt sil',
  'Propose a code change': 'Kod değişikliği öner',
  'Read the code': 'Kodu oku',
  'Destroy a server': 'Sunucuyu yok et',
  'Read a skill': 'Beceri oku',
  'Publish a post': 'Gönderi yayımla',
  'Read text aloud': 'Metni sesli oku',
  'Turn speech into text': 'Konuşmayı yazıya dök',
  'Propose a new stage': 'Yeni aşama öner',
  'Wait for work handed on': 'Devredilen işi bekle',
  'Hand work to another role': 'İşi başka bir role devret',
  'File a ticket': 'Talep oluştur',
  'List tickets': 'Talepleri listele',
  'Check a service is up': 'Hizmetin çalıştığını kontrol et',
  'Read a web page': 'Web sayfası oku',
  'Open a web page': 'Web sayfası aç',
  'Search the web': 'Web\'de ara',
  'no stage': 'aşama yok',
  'Explore': 'Keşif',
  'Validate': 'Doğrulama',
  'Build': 'Geliştirme',
  'Launch': 'Lansman',
  'Grow': 'Büyüme',
  'Wind down': 'Kapanış',
  'Monthly budget reached; the company is paused': 'Aylık bütçeye ulaşıldı; şirket duraklatıldı',
  '{spent} of {limit} spent since {since}. No new task will start and no external action will run until you raise the ceiling or allow spending past it for a while, under Money.': '{since} tarihinden beri {limit} tutarındaki tavandan {spent} harcandı. Para bölümünde tavanı yükseltene ya da tavanı aşan harcamaya bir süreliğine izin verene kadar yeni görev başlamaz ve hiçbir dış eylem çalışmaz.',
  'Monthly budget is 80% spent': 'Aylık bütçenin %80\'i harcandı',
  '{spent} of {limit} spent since {since}. At 100% the company pauses.': '{since} tarihinden beri {limit} tutarındaki tavandan {spent} harcandı. %100\'e ulaşıldığında şirket duraklatılır.',
  'Role {role} is paused for spending too fast': '{role} rolü çok hızlı harcama yaptığı için duraklatıldı',
  '{role} spent {spent} in the last hour, {multiple} times its usual {usual} an hour. It is paused before the monthly ceiling is reached, so there is money left to work with once you have found out why. Resume it when you have.': '{role} rolü son bir saatte {spent} harcadı; bu, saatlik olağan {usual} tutarının {multiple} katı. Aylık tavana ulaşılmadan önce duraklatıldı; böylece nedenini bulduğunuzda çalışmak için para kalmış olur. Nedenini bulunca rolü sürdürün.',
  'Daily model spend over threshold': 'Günlük model harcaması eşiği aştı',
  'Model spend today is {spent}, over the {limit} ceiling.': 'Bugünkü model harcaması {spent}; bu, {limit} tutarındaki tavanın üzerinde.',
  'Task failure rate over threshold': 'Görev hata oranı eşiği aştı',
  '{failed} of {finished} tasks failed or stopped today ({rate}%), over the {limit}% threshold.': 'Bugün {finished} görevden {failed} tanesi başarısız oldu ya da durduruldu (%{rate}); bu, %{limit} eşiğinin üzerinde.',
  'Unusual number of policy refusals': 'Olağan dışı sayıda ilke reddi',
  'Actions refused by a policy today: {count}, over the threshold of {limit}. Either an agent is probing its limits or a policy is miscalibrated.': 'Bugün bir ilke tarafından reddedilen eylemler: {count}; bu, {limit} eşiğinin üzerinde. Ya bir ajan sınırlarını yokluyor ya da bir ilke yanlış ayarlanmış.',
  'External writes failed verification': 'Dış yazma işlemleri doğrulamadan geçemedi',
  'Writes outside that reported success but read back differently: {count}. Something is changing them other than as asked.': 'Başarılı olduğunu bildiren ama geri okunduğunda farklı çıkan dış yazma işlemleri: {count}. Bir şey onları istenenden farklı biçimde değiştiriyor.',
  'A capability stopped being usable': 'Bir yetenek kullanılamaz hâle geldi',
  'Tasks that could not start today because a capability their role needs failed its check: {count}. A credential has probably expired or a quota is used up.': 'Rollerinin ihtiyaç duyduğu bir yetenek kontrolden geçemediği için bugün başlayamayan görevler: {count}. Muhtemelen bir kimlik bilgisinin süresi doldu ya da bir kota bitti.',
  'A worker stopped reporting mid-run': 'Bir işleyici çalıştırmanın ortasında sinyal vermeyi bıraktı',
  'Runs that stopped reporting and were taken back today: {count}. The work was picked up again; the tokens they had already spent were not recovered.': 'Bugün sinyal vermeyi bırakıp geri alınan çalıştırmalar: {count}. İş yeniden ele alındı; daha önce harcanmış token\'lar geri kazanılamadı.',
  '{role} was refused {denials} times today, at the limit of {limit}. No task will run as this role until you lift the freeze. The usual causes are a missing capability grant, a policy the role\'s charter does not account for, or work the role was never equipped to do.': '{role} rolü bugün {denials} kez reddedildi ve {limit} sınırına ulaştı. Dondurmayı kaldırana kadar bu rolle hiçbir görev çalışmaz. Bunun nedeni genellikle bir yetenek için eksik yetki, rolün tüzüğünün hesaba katmadığı bir ilke ya da rolün hiçbir zaman donatılmadığı bir iştir.',
  'Role {role} is frozen after repeated denials': '{role} rolü tekrarlanan retler sonrasında donduruldu',
  'What it was refused: {capabilities}': 'Reddedilenler: {capabilities}',
  'It is waiting for an approval, and none is open, so nothing you can answer will move it.': 'Görev bir onay bekliyor ama açık bir onay yok; bu yüzden vereceğiniz hiçbir yanıt onu ilerletmez.',
  'It is waiting for a review, and none is pending, so no reviewer and no decision of yours will move it.': 'Görev bir inceleme bekliyor ama bekleyen bir inceleme yok; bu yüzden ne bir inceleyici ne de sizin vereceğiniz bir karar onu ilerletir.',
  'It is parked until a window reopens, and the window never does.': 'Görev bir zaman aralığı yeniden açılana kadar bekletiliyor, ama o aralık hiç açılmıyor.',
  'A task is waiting on nothing': 'Bir görev gelmeyecek bir şeyi bekliyor',
  '"{task}" has been waiting since {since}. {why} Approve to run it again from where it stopped, or deny to cancel it.': '“{task}” görevi {since} itibarıyla bekliyor. {why} Kaldığı yerden yeniden çalıştırmak için “Onayla”, iptal etmek için “Reddet” seçeneğini kullanın.',
  'A task keeps stopping the worker running it': 'Bir görev, onu çalıştıran işleyiciyi sürekli durduruyor',
  '"{task}" lost its worker {lost} times: each time the worker running it stopped answering before the work finished. What it had done is kept. It is halted so it cannot take another worker down; run it again once the cause is found, or cancel it.': '“{task}” görevi işleyicisini {lost} kez kaybetti: her seferinde onu çalıştıran işleyici iş bitmeden yanıt vermeyi bıraktı. Yaptıkları saklanır. Başka bir işleyiciyi de çökertmemesi için durduruldu; neden bulununca yeniden çalıştırın ya da iptal edin.',
  '{services} stayed unreachable, and the work that needs it stopped': 'Ulaşılamadı: {services}; buna ihtiyaç duyan iş durduruldu',
  'The task waited about {minutes} minutes, looking again each time, and has stopped. Once the service answers, run it again.': 'Görev yaklaşık {minutes} dakika bekledi, her seferinde yeniden baktı ve durdu. Hizmet yanıt verdiğinde yeniden çalıştırın.',
  'It was tried {tries} times over about {minutes} minutes.': 'Yaklaşık {minutes} dakika içinde {tries} kez denendi.',
  'This role can take actions that cannot be undone, so the run was not silently moved to a different model.': 'Bu rol geri alınamayan eylemler yapabildiği için çalıştırma sessizce başka bir modele aktarılmadı.',
  'No fallback model is left for this role.': 'Bu rol için yedek model kalmadı.',
  'Model {model} failed and the run was not moved': '{model} modeli başarısız oldu ve çalıştırma başka bir modele aktarılmadı',
  'External write failed verification': 'Dış yazma işlemi doğrulamadan geçemedi',
  'The task wrote to an outside service and read it back, and what it read did not match. Look at the place it wrote to before you run it again: the write may have happened.': 'Görev dış bir hizmete yazdı ve geri okudu, ama okuduğu şey eşleşmedi. Yeniden çalıştırmadan önce yazdığı yeri kontrol edin: yazma işlemi gerçekleşmiş olabilir.',
  'Review deadlocked after {rounds} revisions: {capability}': 'İnceleme {rounds} revizyondan sonra tıkandı: {capability}',
  'The role and its reviewer did not agree on {capability}.': 'Rol ve inceleyicisi “{capability}” konusunda anlaşamadı.',
  'The reviewer\'s last note: {note}': 'İnceleyicinin son notu: {note}',
  'The reviewer left no note.': 'İnceleyici not bırakmadı.',
  'What it was judged against: {criteria}': 'Değerlendirme ölçütleri: {criteria}',
  'Review produced no usable verdict: {capability}': 'İnceleme kullanılabilir bir karar üretmedi: {capability}',
  'The reviewing task ended without a decision that could be read. The proposed action is still blocked and needs your judgement.': 'İnceleme görevi okunabilir bir karar olmadan sona erdi. Önerilen eylem hâlâ engelli ve sizin değerlendirmenizi bekliyor.',
  'another stage': 'başka bir aşama',
  'Either answer only closes this: the company stays in the {stage} stage.': 'Hangi yanıtı verirseniz verin yalnızca bu öğe kapanır: şirket {stage} aşamasında kalır.',
  'Either answer only closes this: the company stays without a stage.': 'Hangi yanıtı verirseniz verin yalnızca bu öğe kapanır: şirket aşamasız kalır.',
  'To move it anyway, set the stage on the Overview.': 'Yine de geçirmek için aşamayı Genel bakış sayfasında belirleyin.',
  '{reviewer} stopped a proposal to move the company from {from} to {to}': '{reviewer}, şirketin aşamasının “{from}” yerine “{to}” olması önerisini durdurdu',
  '{reviewer} reviewed it before you and stopped it:': '{reviewer} bunu sizden önce inceledi ve durdurdu:',
  'No reason was given.': 'Bir neden belirtilmedi.',
  'What was proposed:': 'Öneri:',
  'The company stays in the {stage} stage.': 'Şirket {stage} aşamasında kalır.',
  'The company stays without a stage.': 'Şirket aşamasız kalır.',
  'Move the company from {from} to {to}?': 'Şirketin aşaması “{from}” yerine “{to}” olsun mu?',
  'Reviewed by {reviewer} before you:': 'Sizden önce {reviewer} inceledi:',
  'The schedule "{schedule}" keeps producing the same result': '“{schedule}” zamanlaması sürekli aynı sonucu üretiyor',
  'Its last {runs} runs all ended with the same output. That is sometimes exactly right -- a report with nothing new to say -- and often a schedule that stopped doing anything useful while still being paid for. Deny to turn it off; approve to keep it running and not be asked about this result again.': 'Son {runs} çalıştırmanın hepsi aynı çıktıyla bitti. Bu bazen tam olarak doğrudur — söyleyecek yeni bir şeyi olmayan bir rapor gibi — ama çoğu zaman artık işe yarar bir şey yapmayan, yine de parası ödenen bir zamanlamadır. “Reddet” zamanlamayı kapatır; “Onayla” çalışmaya devam ettirir ve bu sonuç için size bir daha sorulmaz.',
  'Capability {capability} failed preflight': '“{capability}” yeteneği ön kontrolden geçemedi',
  'Work that needs it is stopped rather than started: fix the cause, then run that work again. The usual causes are an expired or wrongly scoped credential, a quota used up, or an address that is wrong.': 'Buna ihtiyaç duyan iş başlatılmak yerine durduruluyor: nedeni giderin, sonra o işi yeniden çalıştırın. Bunun nedeni genellikle süresi dolmuş ya da kapsamı yanlış ayarlanmış bir kimlik bilgisi, biten bir kota ya da yanlış bir adrestir.',
  'Batch guard stopped {capability}': 'Toplu işlem denetimi “{capability}” yeteneğini durdurdu',
  'It did not match the plan its run recorded. Nothing was sent, and no service was called.': 'Çalıştırmanın kaydettiği planla eşleşmedi. Hiçbir şey gönderilmedi ve hiçbir hizmet çağrılmadı.',
  '{role} was asked first and has had {minutes} minutes.': 'Önce {role} rolüne soruldu ve ona {minutes} dakika verildi.',
  '{role} is not a role in this company, so this came to you at once.': '{role} bu şirkette bir rol değil, bu yüzden bu doğrudan size geldi.',
  '{role} could not be given this: the company has no active goal or project to hang it from.': 'Bu, {role} rolüne verilemedi: şirketin bunu bağlayacak etkin bir hedefi ya da projesi yok.',
  '{role} could not be given this ({record}), so this came to you at once.': 'Bu, {role} rolüne verilemedi ({record}); bu yüzden doğrudan size geldi.',
  '{role} stopped without an account of what it did ({why}).': '{role} rolü ne yaptığını anlatmadan durdu ({why}).',
  '{role} finished without an account of what it did.': '{role} rolü ne yaptığını anlatmadan bitirdi.',
  '{role} failed without an account of what it did.': '{role} rolü ne yaptığını anlatmadan başarısız oldu.',
  '{role} was stopped without an account of what it did.': '{role} rolü ne yaptığını anlatmadan durduruldu.',
  'Proposed change to the {kind} "{goal}"': '{kind} için değişiklik önerisi: “{goal}”',
  'Currently: {statement}': 'Şu an: {statement}',
  'Currently: {statement} ({status})': 'Şu an: {statement} ({status})',
  'Proposed: {statement}': 'Önerilen: {statement}',
  'Proposed status: {status}': 'Önerilen durum: {status}',
  'Reason given: {reason}': 'Belirtilen neden: {reason}',
  'Approving it changes the goal; until then the work carries on under the goal as it is.': 'Onaylarsanız hedef değişir; o zamana kadar iş, hedefin şimdiki hâliyle sürer.',
  'The goal stays as it is.': 'Hedef olduğu gibi kalır.',
  'mission': 'misyon',
  'objective': 'amaç',
  'key result': 'anahtar sonuç',
  'Active': 'Etkin',
  'Met': 'Ulaşıldı',
  'Abandoned': 'Vazgeçildi',
  'This work asked for it at tier {tier}, and policy {policies} requires your approval.': 'Bu iş bunu {tier}. seviyede istedi ve {policies} ilkesi onayınızı gerektiriyor.',
  'This work asked for it at tier {tier}, and the task began with content from outside the company.': 'Bu iş bunu {tier}. seviyede istedi ve görev şirket dışından gelen içerikle başladı.',
  'This work asked for it at tier {tier}, and the work read content from outside the company before asking.': 'Bu iş bunu {tier}. seviyede istedi ve istemeden önce şirket dışından içerik okudu.',
  'This work asked for it at tier {tier}, after the work read content from outside the company, and the guardian asked you first: {reason}': 'Bu iş bunu şirket dışından içerik okuduktan sonra {tier}. seviyede istedi ve koruyucu önce size sordu: {reason}',
  'it doubted this call before, and you allowed it once': 'bu çağrıdan daha önce de şüphelenmişti ve siz bir kez izin vermiştiniz',
  'This work asked for it at tier {tier}, which cannot be reversed.': 'Bu iş bunu {tier}. seviyede istedi; bu seviye geri alınamaz.',
  'You approved this once already, and the worker carrying it out stopped before it could say whether it happened: it may already have happened. Check before approving it again.': 'Bunu daha önce bir kez onayladınız ve onu yürüten işleyici, gerçekleşip gerçekleşmediğini bildiremeden durdu: zaten gerçekleşmiş olabilir. Yeniden onaylamadan önce kontrol edin.',
  'What this is for — {goals}': 'Neye hizmet ediyor — {goals}',
  'The task halts and no external change is made.': 'Görev durur ve dışarıda hiçbir değişiklik yapılmaz.',
  'Scored against {total} references: {passed} passed, {failed} failed.': '{total} referansa göre puanlandı: {passed} başarılı, {failed} başarısız.',
  'This role has fewer than {minimum} accepted references, so the change is unscored. That is not the same as passing.': 'Bu rolün kabul edilmiş referans sayısı {minimum} değerinden az, bu yüzden değişiklik puansız. Bu, başarılı olmakla aynı şey değildir.',
  'The role keeps working exactly as it does now.': 'Rol tam olarak şimdiki gibi çalışmaya devam eder.',
  '{role} asks: {question}': '{role} soruyor: {question}',
  'The run did not say more than the question.': 'Çalıştırma sorudan başka bir şey söylemedi.',
  'The task is stopped, and nothing it was going to do happens.': 'Görev durdurulur ve yapmak üzere olduğu hiçbir şey gerçekleşmez.',
};
