/**
 * Tiếng Việt: what the platform itself says to the owner outside the console
 * (src/owner/say.ts), keyed by its English.
 *
 * The terms are the console's (console/src/locales/vi.ts, whose header holds
 * the glossary): phê duyệt and từ chối, hộp thư đến, mục for an item, thẻ for
 * a card (a browser tab is "tab"), and Hệ thống này for the This deployment
 * page, with its sections joined by " > " as the console writes them. The
 * owner is "bạn"; the assistant says "tôi". Telegram and WhatsApp buttons
 * stay short: WhatsApp cuts a button at 20 characters and a list row at 24.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': 'Sự cố: {title}',
  'Done: {goal}': 'Đã xong: {goal}',
  'Stopped before finishing: {goal}': 'Đã dừng trước khi xong: {goal}',
  'Not done: {goal}': 'Không làm được: {goal}',
  'Why: {reason}': 'Lý do: {reason}',
  'a task': 'một nhiệm vụ',
  'Approval needed: {title}': 'Cần phê duyệt: {title}',
  '{summary} — if denied: {consequence}': '{summary} — nếu từ chối: {consequence}',
  '{role} asks:': '{role} hỏi:',
  'If denied:': 'Nếu từ chối:',
  'Expires:': 'Hết hạn:',
  'This one is decided in the app.': 'Mục này cần quyết định trong ứng dụng.',
  'Open in PALUGADA': 'Mở trong PALUGADA',
  'Approve': 'Phê duyệt',
  'Deny': 'Từ chối',
  'Ask': 'Hỏi',
  'Approved. Nothing left to press here.': 'Đã phê duyệt. Không cần nhấn gì thêm ở đây.',
  'Denied. Nothing left to press here.': 'Đã từ chối. Không cần nhấn gì thêm ở đây.',
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    'Đã hết hạn mà không có trả lời. Im lặng được coi là từ chối, nên không có gì được thực hiện.',
  'This bot only answers to its owner.': 'Bot này chỉ phản hồi chủ sở hữu.',
  'That one has to be approved in the app.': 'Mục này phải được phê duyệt trong ứng dụng.',
  'That could not be recorded.': 'Không ghi nhận được.',
  'That item no longer exists.': 'Mục này không còn tồn tại.',
  'What do you want to ask about "{title}"? Reply to this message.':
    'Bạn muốn hỏi gì về “{title}”? Hãy trả lời tin nhắn này.',
  'Your question': 'Câu hỏi của bạn',
  'Type your question as a reply.': 'Nhập câu hỏi của bạn bằng cách trả lời tin nhắn.',
  'Asked. The answer will be on the item in the app.':
    'Đã gửi câu hỏi. Câu trả lời sẽ hiển thị ở mục này trong ứng dụng.',
  'Answer': 'Trả lời',
  'Answer in words': 'Trả lời bằng lời',
  'That choice is not on this question.': 'Câu hỏi này không có lựa chọn đó.',
  'Chosen: {choice}.': 'Đã chọn: {choice}.',
  'Stop the task': 'Dừng nhiệm vụ',
  'Your answer to "{question}"? Reply to this message.':
    'Câu trả lời của bạn cho “{question}”? Hãy trả lời tin nhắn này.',
  'Your answer': 'Câu trả lời của bạn',
  'Type your answer as a reply.': 'Nhập câu trả lời của bạn bằng cách trả lời tin nhắn.',
  'Answered. The task carries on with it.': 'Đã trả lời. Nhiệm vụ tiếp tục với câu trả lời đó.',
  'That is too long for one question; keep it under {max} characters.':
    'Quá dài cho một câu hỏi; hãy giữ dưới {max} ký tự.',
  '[a key, not kept]': '[một khóa, không được lưu]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    'Đây có vẻ là một khóa, nên tôi không lưu và không gửi đi đâu cả. Khóa phải nhập vào ô niêm phong trên thẻ, hoặc trên trang riêng của nó trong Hệ thống này: hãy cho tôi biết khóa dùng để làm gì và tôi sẽ đưa thẻ cho bạn.',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    'Chưa thiết lập mô hình nào nên tôi chưa thể suy nghĩ. Hãy chọn một mô hình tại Hệ thống này > Mô hình; sau đó tôi có thể giúp mọi việc khác.',
  'The model did not answer: {reason}': 'Mô hình không trả lời: {reason}',
  'Here is what I propose.': 'Đây là đề xuất của tôi.',
  'I have nothing to add.': 'Tôi không có gì để bổ sung.',
  '{name}, CEO of {company}': '{name}, CEO của {company}',
  'That could not be answered: {reason}': 'Không thể trả lời: {reason}',
  'I read text and voice notes.': 'Tôi chỉ đọc được tin nhắn văn bản và tin nhắn thoại.',
  'Now talking to {name}.': 'Bạn đang trò chuyện với {name}.',
  'Choose whom to talk to.': 'Chọn người bạn muốn trò chuyện.',
  'Choose whom to talk to': 'Chọn người để trò chuyện',
  'Talk to PALUGADA about the whole deployment': 'Trò chuyện với PALUGADA về toàn hệ thống',
  'Who you are talking to, and how': 'Bạn đang trò chuyện với ai, và cách trò chuyện',
  'Stopped.': 'Đã dừng.',
  'Write here to talk to {name}.': 'Nhắn ở đây để trò chuyện với {name}.',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    'Bạn đang trò chuyện với {name}. Hãy nhắn tin hoặc gửi tin nhắn thoại. /ceo để chọn người trò chuyện; /palugada để trò chuyện với PALUGADA về toàn hệ thống.',
  'You said: "{words}"': 'Bạn đã nói: “{words}”',
  'in the app': 'trong ứng dụng',
  'Apply: {summary}': 'Áp dụng: {summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    'Chưa có dịch vụ nghe giọng nói: hãy chọn nhà cung cấp trong ứng dụng, tại Hệ thống này > Công cụ > Nghe.',
  'That recording is too long; keep a voice note under {max} MB.':
    'Bản ghi âm quá dài; tin nhắn thoại phải dưới {max} MB.',
  'I could not make out any words in that.': 'Tôi không nghe ra được từ nào.',
  'Done: {summary}': 'Đã xong: {summary}',
  'That one is applied in the app.': 'Mục này cần áp dụng trong ứng dụng.',
  'That card no longer exists.': 'Thẻ này không còn tồn tại.',
  'That card was already applied.': 'Thẻ này đã được áp dụng.',
  'That card was dismissed.': 'Thẻ này đã bị bỏ qua.',
  'That card failed when it was applied.': 'Thẻ này đã thất bại khi áp dụng.',
  'That could not be done: {reason}': 'Không thể thực hiện: {reason}',
  'Choose': 'Chọn',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    'Bạn muốn hỏi gì về “{title}”? Hãy trả lời tin nhắn này bằng câu hỏi của bạn.',
  'Your answer to "{question}"? Reply to this message with your answer.':
    'Câu trả lời của bạn cho “{question}”? Hãy trả lời tin nhắn này bằng câu trả lời của bạn.',
  'I read text messages here.': 'Ở đây tôi chỉ đọc tin nhắn văn bản.',
  'Apply one of these here:': 'Áp dụng một trong các thẻ sau tại đây:',
  'Apply {number}': 'Áp dụng {number}',
  'Signed in to {provider} for the {alias} key': 'Đã đăng nhập {provider} để lấy khóa {alias}',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    'Hãy quay lại PALUGADA: bộ phận giờ đã giữ khóa này, và khóa sẽ được gia hạn trước khi hết hạn. Bạn có thể đóng tab này.',
  'Signed in to {name}': 'Đã đăng nhập {name}',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    'Hãy quay lại PALUGADA để chọn những công cụ mà vai trò được dùng. Bạn có thể đóng tab này.',
  'Not signed in': 'Chưa đăng nhập',
  'Recorded: approved.': 'Đã ghi nhận: phê duyệt.',
  'Recorded: denied.': 'Đã ghi nhận: từ chối.',
  'Recorded: asked.': 'Đã ghi nhận: đã hỏi.',
  'Asked. Nothing left to press here.': 'Đã gửi câu hỏi. Không cần nhấn gì thêm ở đây.',
  'Withdrawn: the task it was asking about has finished.': 'Đã rút lại: nhiệm vụ liên quan đã hoàn thành.',
  'Withdrawn: the task it was asking about has failed.': 'Đã rút lại: nhiệm vụ liên quan đã thất bại.',
  'Withdrawn: the task it was asking about was stopped.': 'Đã rút lại: nhiệm vụ liên quan đã bị dừng.',
  'Withdrawn: the task it was asking about was cancelled.': 'Đã rút lại: nhiệm vụ liên quan đã bị hủy.',
  'Decided. Nothing left to press here.': 'Đã quyết định. Không cần nhấn gì thêm ở đây.',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': 'Đã rút lại: agent đã thay đổi đề xuất và hỏi lại về đề xuất mới.',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': 'Đã rút lại: công ty không còn ở giai đoạn mà đề xuất này định chuyển đi.',
  'Withdrawn: it was already decided in the app.': 'Đã rút lại: mục này đã được quyết định trong ứng dụng.',
  'Withdrawn. Nothing left to press here.': 'Đã rút lại. Không cần nhấn gì thêm ở đây.',
  'company': 'công ty',
  'Work stopped: the {account} account is out of tokens': 'Công việc dừng lại: tài khoản {account} đã hết token',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': '“{work}” dừng lại vì tài khoản {account} đã dùng {spent} trên {max} token. Hãy nâng trần của nó trong mục Tài chính, rồi mở nhiệm vụ và nhấn Tiếp tục: nhiệm vụ sẽ tiếp tục từ chỗ đã dừng.',
  'Withdrawn: you continued the task it was about.': 'Đã rút lại: bạn đã tiếp tục nhiệm vụ mà nó nói đến.',
  'Broke its contract': 'Vi phạm hợp đồng',
  'Refused by a policy': 'Bị chính sách từ chối',
  'Out of budget': 'Hết ngân sách',
  'Handed on too many times': 'Bị chuyển tiếp quá nhiều lần',
  'Missed its deadline': 'Trễ hạn chót',
  'Its result did not check out': 'Kết quả không qua được kiểm tra',
  'A capability it needs is down': 'Năng lực cần dùng đang ngừng hoạt động',
  'No runtime could take it': 'Không môi trường chạy nào nhận được',
  'Went in a circle': 'Chạy vòng lặp',
  'Split into too many sub-tasks': 'Bị chia thành quá nhiều nhiệm vụ con',
  'Wrote more than its role allows one run': 'Viết nhiều hơn mức vai trò cho phép trong một lượt chạy',
  'Your approval was not given in time': 'Bạn chưa phê duyệt kịp thời hạn',
  'Stopped by you': 'Bạn đã dừng',
  'Cancelled by you': 'Bạn đã hủy',
  'The company is frozen': 'Công ty bị đóng băng',
  'Its record did not match on replay': 'Hồ sơ không khớp khi phát lại',
  'It kept stopping the worker running it': 'Nó liên tục làm dừng bộ thực thi đang chạy nó',
  'Not done': 'Không làm được',
  'Task failed': 'Nhiệm vụ đã thất bại',
  'Digest for {day}': 'Tóm tắt ngày {day}',
  'Spent: {amount}': 'Đã chi: {amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': 'Công việc: {done} hoàn thành, {failed} thất bại, {stopped} đã dừng',
  'Inbox: {open} waiting (incidents: {incidents})': 'Hộp thư đến: {open} đang chờ (sự cố: {incidents})',
  'Stopped ({count}): {reason}': 'Đã dừng ({count}): {reason}',
  'Start an ad campaign': 'Bắt đầu chiến dịch quảng cáo',
  'Block time on the calendar': 'Giữ khung giờ trên lịch',
  'Read the calendar': 'Đọc lịch',
  'Run code': 'Chạy mã',
  'Add a note to a customer': 'Thêm ghi chú vào hồ sơ khách hàng',
  'Read customer records': 'Đọc hồ sơ khách hàng',
  'Release to the live site': 'Phát hành lên trang chính thức',
  'Release to the test site': 'Phát hành lên trang thử nghiệm',
  'Change a domain\'s nameservers': 'Thay đổi máy chủ DNS của tên miền',
  'Read a domain\'s records': 'Đọc bản ghi của tên miền',
  'Change a domain\'s record': 'Thay đổi bản ghi của tên miền',
  'Write a document': 'Viết tài liệu',
  'Sign a document': 'Ký tài liệu',
  'Buy a domain': 'Mua tên miền',
  'Transfer a domain': 'Chuyển tên miền',
  'Draft an email': 'Soạn nháp email',
  'Send an email': 'Gửi email',
  'List files': 'Liệt kê tệp',
  'Transfer money': 'Chuyển tiền',
  'Propose a goal change': 'Đề xuất thay đổi mục tiêu',
  'Make a picture': 'Tạo hình ảnh',
  'Issue an invoice': 'Xuất hóa đơn',
  'Pay an invoice': 'Thanh toán hóa đơn',
  'Read the books': 'Đọc sổ sách kế toán',
  'Read the mailbox': 'Đọc hộp thư',
  'Search what the company knows': 'Tìm trong những gì công ty biết',
  'Record a measure': 'Ghi nhận chỉ số',
  'Read product numbers': 'Đọc số liệu sản phẩm',
  'Ask you a question': 'Hỏi bạn một câu',
  'Write down a plan': 'Ghi lại kế hoạch',
  'Delete a record': 'Xóa bản ghi',
  'Propose a code change': 'Đề xuất thay đổi mã nguồn',
  'Read the code': 'Đọc mã nguồn',
  'Destroy a server': 'Phá hủy máy chủ',
  'Read a skill': 'Đọc kỹ năng',
  'Publish a post': 'Đăng bài viết',
  'Read text aloud': 'Đọc to văn bản',
  'Turn speech into text': 'Chuyển giọng nói thành văn bản',
  'Propose a new stage': 'Đề xuất giai đoạn mới',
  'Wait for work handed on': 'Chờ việc đã bàn giao',
  'Hand work to another role': 'Giao việc cho vai trò khác',
  'File a ticket': 'Tạo phiếu việc',
  'List tickets': 'Liệt kê phiếu việc',
  'Check a service is up': 'Kiểm tra dịch vụ còn hoạt động',
  'Read a web page': 'Đọc trang web',
  'Open a web page': 'Mở trang web',
  'Search the web': 'Tìm kiếm web',
  'no stage': 'chưa có giai đoạn',
  'Explore': 'Khám phá',
  'Validate': 'Kiểm chứng',
  'Build': 'Xây dựng',
  'Launch': 'Ra mắt',
  'Grow': 'Tăng trưởng',
  'Wind down': 'Thu hẹp hoạt động',
  'Monthly budget reached; the company is paused': 'Đã dùng hết ngân sách hằng tháng; công ty đang tạm dừng',
  '{spent} of {limit} spent since {since}. No new task will start and no external action will run until you raise the ceiling or allow spending past it for a while, under Money.': 'Đã chi {spent} trên {limit} kể từ {since}. Sẽ không có nhiệm vụ mới nào bắt đầu và không có hành động bên ngoài nào được thực hiện cho đến khi bạn nâng hạn mức hoặc tạm thời cho phép chi tiêu vượt hạn mức, trong mục Tài chính.',
  'Monthly budget is 80% spent': 'Đã chi 80% ngân sách hằng tháng',
  '{spent} of {limit} spent since {since}. At 100% the company pauses.': 'Đã chi {spent} trên {limit} kể từ {since}. Khi đạt 100%, công ty sẽ tạm dừng.',
  'Role {role} is paused for spending too fast': 'Vai trò {role} bị tạm dừng vì chi tiêu quá nhanh',
  '{role} spent {spent} in the last hour, {multiple} times its usual {usual} an hour. It is paused before the monthly ceiling is reached, so there is money left to work with once you have found out why. Resume it when you have.': '{role} đã chi {spent} trong một giờ qua, gấp {multiple} lần mức thường lệ {usual} mỗi giờ. Vai trò bị tạm dừng trước khi chạm hạn mức hằng tháng, để vẫn còn tiền cho công việc khi bạn đã tìm ra nguyên nhân. Khi đã tìm ra, hãy cho vai trò tiếp tục.',
  'Daily model spend over threshold': 'Chi tiêu cho mô hình trong ngày vượt ngưỡng',
  'Model spend today is {spent}, over the {limit} ceiling.': 'Chi tiêu cho mô hình hôm nay là {spent}, vượt hạn mức {limit}.',
  'Task failure rate over threshold': 'Tỷ lệ nhiệm vụ thất bại vượt ngưỡng',
  '{failed} of {finished} tasks failed or stopped today ({rate}%), over the {limit}% threshold.': 'Hôm nay có {failed} trên {finished} nhiệm vụ thất bại hoặc bị dừng ({rate}%), vượt ngưỡng {limit}%.',
  'Unusual number of policy refusals': 'Số lần bị chính sách từ chối cao bất thường',
  'Actions refused by a policy today: {count}, over the threshold of {limit}. Either an agent is probing its limits or a policy is miscalibrated.': 'Số hành động bị chính sách từ chối hôm nay: {count}, vượt ngưỡng {limit}. Hoặc một agent đang dò giới hạn của mình, hoặc một chính sách đang được thiết lập chưa đúng.',
  'External writes failed verification': 'Các thao tác ghi ra bên ngoài không qua được xác minh',
  'Writes outside that reported success but read back differently: {count}. Something is changing them other than as asked.': 'Số thao tác ghi ra bên ngoài báo thành công nhưng đọc lại thì khác: {count}. Có thứ gì đó đang thay đổi chúng theo cách không ai yêu cầu.',
  'A capability stopped being usable': 'Một năng lực không còn dùng được',
  'Tasks that could not start today because a capability their role needs failed its check: {count}. A credential has probably expired or a quota is used up.': 'Số nhiệm vụ hôm nay không thể bắt đầu vì một năng lực mà vai trò của chúng cần không qua được kiểm tra: {count}. Có lẽ một thông tin xác thực đã hết hạn hoặc hạn ngạch đã dùng hết.',
  'A worker stopped reporting mid-run': 'Một bộ thực thi ngừng báo cáo giữa lượt chạy',
  'Runs that stopped reporting and were taken back today: {count}. The work was picked up again; the tokens they had already spent were not recovered.': 'Số lượt chạy ngừng báo cáo và đã được thu hồi hôm nay: {count}. Công việc đã được nhận lại; số token đã tiêu tốn thì không lấy lại được.',
  '{role} was refused {denials} times today, at the limit of {limit}. No task will run as this role until you lift the freeze. The usual causes are a missing capability grant, a policy the role\'s charter does not account for, or work the role was never equipped to do.': '{role} đã bị từ chối {denials} lần hôm nay, chạm giới hạn {limit}. Không nhiệm vụ nào chạy dưới vai trò này cho đến khi bạn bỏ đóng băng. Nguyên nhân thường gặp là thiếu quyền dùng một năng lực, một chính sách mà điều lệ của vai trò không tính đến, hoặc công việc mà vai trò chưa từng được trang bị để làm.',
  'Role {role} is frozen after repeated denials': 'Vai trò {role} bị đóng băng sau nhiều lần bị từ chối',
  'What it was refused: {capabilities}': 'Những gì bị từ chối: {capabilities}',
  'It is waiting for an approval, and none is open, so nothing you can answer will move it.': 'Nhiệm vụ đang chờ phê duyệt nhưng không có yêu cầu phê duyệt nào đang mở, nên không câu trả lời nào của bạn có thể giúp nó chạy tiếp.',
  'It is waiting for a review, and none is pending, so no reviewer and no decision of yours will move it.': 'Nhiệm vụ đang chờ rà soát nhưng không có lượt rà soát nào đang chờ xử lý, nên không người rà soát nào và không quyết định nào của bạn có thể giúp nó chạy tiếp.',
  'It is parked until a window reopens, and the window never does.': 'Nhiệm vụ được tạm gác cho đến khi một khung giờ mở lại, nhưng khung giờ đó không bao giờ mở lại.',
  'A task is waiting on nothing': 'Một nhiệm vụ đang chờ mà không có gì để chờ',
  '"{task}" has been waiting since {since}. {why} Approve to run it again from where it stopped, or deny to cancel it.': '“{task}” đã chờ từ {since}. {why} Phê duyệt để chạy lại từ chỗ đã dừng, hoặc từ chối để hủy.',
  'A task keeps stopping the worker running it': 'Một nhiệm vụ liên tục làm dừng bộ thực thi đang chạy nó',
  '"{task}" lost its worker {lost} times: each time the worker running it stopped answering before the work finished. What it had done is kept. It is halted so it cannot take another worker down; run it again once the cause is found, or cancel it.': '“{task}” đã mất bộ thực thi {lost} lần: mỗi lần, bộ thực thi đang chạy nó ngừng phản hồi trước khi công việc xong. Những gì đã làm vẫn được giữ lại. Nhiệm vụ bị dừng hẳn để không kéo sập thêm bộ thực thi khác; hãy chạy lại khi đã tìm ra nguyên nhân, hoặc hủy nó.',
  '{services} stayed unreachable, and the work that needs it stopped': '{services} vẫn không kết nối được, và công việc cần đến nó đã dừng',
  'The task waited about {minutes} minutes, looking again each time, and has stopped. Once the service answers, run it again.': 'Nhiệm vụ đã chờ khoảng {minutes} phút, mỗi lần đều kiểm tra lại, và giờ đã dừng. Khi dịch vụ phản hồi, hãy chạy lại.',
  'It was tried {tries} times over about {minutes} minutes.': 'Đã thử {tries} lần trong khoảng {minutes} phút.',
  'This role can take actions that cannot be undone, so the run was not silently moved to a different model.': 'Vai trò này có thể thực hiện những hành động không thể hoàn tác, nên lượt chạy không bị âm thầm chuyển sang mô hình khác.',
  'No fallback model is left for this role.': 'Vai trò này không còn mô hình dự phòng nào.',
  'Model {model} failed and the run was not moved': 'Mô hình {model} gặp lỗi và lượt chạy không được chuyển đi',
  'External write failed verification': 'Thao tác ghi ra bên ngoài không qua được xác minh',
  'The task wrote to an outside service and read it back, and what it read did not match. Look at the place it wrote to before you run it again: the write may have happened.': 'Nhiệm vụ đã ghi vào một dịch vụ bên ngoài rồi đọc lại, và nội dung đọc được không khớp. Hãy xem nơi nó đã ghi vào trước khi chạy lại: thao tác ghi có thể đã diễn ra.',
  'Review deadlocked after {rounds} revisions: {capability}': 'Rà soát rơi vào bế tắc sau {rounds} lần sửa: {capability}',
  'The role and its reviewer did not agree on {capability}.': 'Vai trò và người rà soát của nó không thống nhất được về {capability}.',
  'The reviewer\'s last note: {note}': 'Ghi chú cuối của người rà soát: {note}',
  'The reviewer left no note.': 'Người rà soát không để lại ghi chú nào.',
  'What it was judged against: {criteria}': 'Tiêu chí dùng để đánh giá: {criteria}',
  'Review produced no usable verdict: {capability}': 'Rà soát không cho ra kết luận dùng được: {capability}',
  'The reviewing task ended without a decision that could be read. The proposed action is still blocked and needs your judgement.': 'Nhiệm vụ rà soát đã kết thúc mà không có quyết định nào đọc được. Hành động được đề xuất vẫn bị chặn và cần bạn phán đoán.',
  'another stage': 'giai đoạn khác',
  'Either answer only closes this: the company stays in the {stage} stage.': 'Dù trả lời thế nào, mục này cũng chỉ được đóng lại: công ty vẫn ở giai đoạn {stage}.',
  'Either answer only closes this: the company stays without a stage.': 'Dù trả lời thế nào, mục này cũng chỉ được đóng lại: công ty vẫn chưa có giai đoạn.',
  'To move it anyway, set the stage on the Overview.': 'Nếu vẫn muốn chuyển, hãy đặt giai đoạn trong mục Tổng quan.',
  '{reviewer} stopped a proposal to move the company from {from} to {to}': '{reviewer} đã chặn đề xuất chuyển công ty từ {from} sang {to}',
  '{reviewer} reviewed it before you and stopped it:': '{reviewer} đã rà soát trước bạn và chặn đề xuất này:',
  'No reason was given.': 'Không có lý do nào được đưa ra.',
  'What was proposed:': 'Nội dung đề xuất:',
  'The company stays in the {stage} stage.': 'Công ty vẫn ở giai đoạn {stage}.',
  'The company stays without a stage.': 'Công ty vẫn chưa có giai đoạn.',
  'Move the company from {from} to {to}?': 'Chuyển công ty từ {from} sang {to}?',
  'Reviewed by {reviewer} before you:': 'Đã được {reviewer} rà soát trước bạn:',
  'The schedule "{schedule}" keeps producing the same result': 'Lịch chạy “{schedule}” liên tục cho ra cùng một kết quả',
  'Its last {runs} runs all ended with the same output. That is sometimes exactly right -- a report with nothing new to say -- and often a schedule that stopped doing anything useful while still being paid for. Deny to turn it off; approve to keep it running and not be asked about this result again.': '{runs} lượt chạy gần nhất của nó đều kết thúc với cùng một đầu ra. Đôi khi như vậy là hoàn toàn đúng — một báo cáo không có gì mới để nói — nhưng thường là một lịch chạy đã không còn làm được gì hữu ích mà vẫn tốn tiền. Từ chối để tắt nó; phê duyệt để nó tiếp tục chạy và không bị hỏi lại về kết quả này.',
  'Capability {capability} failed preflight': 'Năng lực {capability} không qua được kiểm tra',
  'Work that needs it is stopped rather than started: fix the cause, then run that work again. The usual causes are an expired or wrongly scoped credential, a quota used up, or an address that is wrong.': 'Công việc cần đến nó bị dừng thay vì được bắt đầu: hãy khắc phục nguyên nhân, rồi chạy lại công việc đó. Nguyên nhân thường gặp là thông tin xác thực đã hết hạn hoặc sai phạm vi, hạn ngạch đã dùng hết, hoặc địa chỉ bị sai.',
  'Batch guard stopped {capability}': 'Lớp chặn theo lô đã dừng {capability}',
  'It did not match the plan its run recorded. Nothing was sent, and no service was called.': 'Nó không khớp với kế hoạch mà lượt chạy đã ghi lại. Không có gì được gửi đi, và không dịch vụ nào được gọi.',
  '{role} was asked first and has had {minutes} minutes.': '{role} đã được hỏi trước và đã có {minutes} phút.',
  '{role} is not a role in this company, so this came to you at once.': '{role} không phải là vai trò trong công ty này, nên việc này được chuyển ngay cho bạn.',
  '{role} could not be given this: the company has no active goal or project to hang it from.': 'Không thể giao việc này cho {role}: công ty không có mục tiêu hoặc dự án nào đang hoạt động để gắn vào.',
  '{role} could not be given this ({record}), so this came to you at once.': 'Không thể giao việc này cho {role} ({record}), nên việc này được chuyển ngay cho bạn.',
  '{role} stopped without an account of what it did ({why}).': '{role} đã dừng mà không báo lại đã làm gì ({why}).',
  '{role} finished without an account of what it did.': '{role} đã hoàn thành mà không báo lại đã làm gì.',
  '{role} failed without an account of what it did.': '{role} đã thất bại mà không báo lại đã làm gì.',
  '{role} was stopped without an account of what it did.': '{role} đã bị dừng mà không báo lại đã làm gì.',
  'Proposed change to the {kind} "{goal}"': 'Đề xuất thay đổi {kind} “{goal}”',
  'Currently: {statement}': 'Hiện tại: {statement}',
  'Currently: {statement} ({status})': 'Hiện tại: {statement} ({status})',
  'Proposed: {statement}': 'Đề xuất: {statement}',
  'Proposed status: {status}': 'Trạng thái đề xuất: {status}',
  'Reason given: {reason}': 'Lý do được đưa ra: {reason}',
  'Approving it changes the goal; until then the work carries on under the goal as it is.': 'Phê duyệt sẽ thay đổi mục tiêu; cho đến lúc đó, công việc vẫn tiếp tục theo mục tiêu hiện tại.',
  'The goal stays as it is.': 'Mục tiêu giữ nguyên.',
  'mission': 'sứ mệnh',
  'objective': 'mục tiêu',
  'key result': 'kết quả then chốt',
  'Active': 'Đang hoạt động',
  'Met': 'Đã đạt',
  'Abandoned': 'Đã từ bỏ',
  'This work asked for it at tier {tier}, and policy {policies} requires your approval.': 'Công việc này yêu cầu hành động này ở cấp {tier}, và chính sách {policies} cần bạn phê duyệt.',
  'This work asked for it at tier {tier}, and the task began with content from outside the company.': 'Công việc này yêu cầu hành động này ở cấp {tier}, và nhiệm vụ bắt đầu từ nội dung bên ngoài công ty.',
  'This work asked for it at tier {tier}, and the work read content from outside the company before asking.': 'Công việc này yêu cầu hành động này ở cấp {tier}, và trước khi yêu cầu, công việc đã đọc nội dung từ bên ngoài công ty.',
  'This work asked for it at tier {tier}, after the work read content from outside the company, and the guardian asked you first: {reason}': 'Công việc này yêu cầu hành động này ở cấp {tier} sau khi đã đọc nội dung từ bên ngoài công ty, và người gác đã hỏi bạn trước: {reason}',
  'it doubted this call before, and you allowed it once': 'trước đây nó đã nghi ngờ lệnh gọi này, và bạn đã cho phép một lần',
  'This work asked for it at tier {tier}, which cannot be reversed.': 'Công việc này yêu cầu hành động này ở cấp {tier}, tức là không thể hoàn tác.',
  'You approved this once already, and the worker carrying it out stopped before it could say whether it happened: it may already have happened. Check before approving it again.': 'Bạn đã phê duyệt việc này một lần, và bộ thực thi đang thực hiện nó đã dừng trước khi kịp báo việc đó đã diễn ra hay chưa: có thể nó đã diễn ra rồi. Hãy kiểm tra trước khi phê duyệt lại.',
  'What this is for — {goals}': 'Mục đích của việc này — {goals}',
  'The task halts and no external change is made.': 'Nhiệm vụ dừng lại và không có thay đổi nào bên ngoài được thực hiện.',
  'Scored against {total} references: {passed} passed, {failed} failed.': 'Chấm điểm trên {total} mẫu tham chiếu: {passed} đạt, {failed} không đạt.',
  'This role has fewer than {minimum} accepted references, so the change is unscored. That is not the same as passing.': 'Vai trò này có ít hơn {minimum} mẫu tham chiếu đã được chấp nhận, nên thay đổi này chưa được chấm điểm. Điều đó không giống với đạt.',
  'The role keeps working exactly as it does now.': 'Vai trò tiếp tục làm việc đúng như hiện tại.',
  '{role} asks: {question}': '{role} hỏi: {question}',
  'The run did not say more than the question.': 'Lượt chạy không nói gì thêm ngoài câu hỏi.',
  'The task is stopped, and nothing it was going to do happens.': 'Nhiệm vụ bị dừng, và không việc gì nó định làm sẽ xảy ra.',
  'You proposed it.': 'Bạn đã đề xuất kỹ năng này.',
  'It came with a bundle.': 'Kỹ năng này đi kèm một gói.',
  'An agent proposed it.': 'Một agent đã đề xuất kỹ năng này.',
  'It was learned from the company\'s work.': 'Kỹ năng này được học từ công việc của công ty.',
  'Skill "{skill}", version {version}': 'Kỹ năng “{skill}”, phiên bản {version}',
  'The reviewer approved it: {note}': 'Người rà soát đã phê duyệt: {note}',
  'The reviewer approved it.': 'Người rà soát đã phê duyệt.',
  'Nothing changes; the current version of the skill stays in force.': 'Không có gì thay đổi; phiên bản hiện tại của kỹ năng vẫn giữ hiệu lực.',
  'Skills the bundle "{bundle}" brings: {count}': 'Các kỹ năng gói “{bundle}” mang theo: {count}',
  'The reviewer read them all and approved these:': 'Người rà soát đã đọc tất cả và phê duyệt những kỹ năng này:',
  'It turned these down, and they stay off:': 'Những kỹ năng sau đã bị bác bỏ và vẫn tắt:',
  'Approve to switch them all on, or deny to turn them all down. To decide one at a time, open the Skills page.': 'Phê duyệt để bật tất cả, hoặc từ chối để bác bỏ tất cả. Để quyết định từng kỹ năng một, hãy mở mục Kỹ năng.',
  'Nothing changes; none of these skills is switched on.': 'Không có gì thay đổi; không kỹ năng nào trong số này được bật.',
};
