/**
 * 简体中文: what the platform itself says to the owner outside the console
 * (src/owner/say.ts), keyed by its English.
 *
 * The terms are the console's (console/src/locales/zh.ts): the owner is 您,
 * an approval 审批, an incident 异常, a card is applied (应用), and "the app"
 * is the console (控制台), so that "apply it in the app" does not read as
 * 应用 twice. Screens are named as the console draws them: “本部署 > 模型”.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': '异常：{title}',
  'Done: {goal}': '已完成：{goal}',
  'Stopped before finishing: {goal}': '未完成即停止：{goal}',
  'Not done: {goal}': '未办成：{goal}',
  'Why: {reason}': '原因：{reason}',
  'a task': '一项任务',
  'Approval needed: {title}': '需要审批：{title}',
  '{summary} — if denied: {consequence}': '{summary}——如果拒绝：{consequence}',
  '{role} asks:': '{role} 问：',
  'If denied:': '如果拒绝：',
  'Expires:': '到期时间：',
  'This one is decided in the app.': '此事项需要在控制台中决定。',
  'Open in PALUGADA': '在 PALUGADA 中打开',
  'Approve': '批准',
  'Deny': '拒绝',
  'Ask': '提问',
  'Approved. Nothing left to press here.': '已批准。这里无需再操作。',
  'Denied. Nothing left to press here.': '已拒绝。这里无需再操作。',
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    '超时未回应。沉默即视为拒绝，因此未执行任何操作。',
  'This bot only answers to its owner.': '此机器人只回应其所有者。',
  'That one has to be approved in the app.': '此事项必须在控制台中批准。',
  'That could not be recorded.': '无法记录此操作。',
  'That item no longer exists.': '该事项已不存在。',
  'What do you want to ask about "{title}"? Reply to this message.':
    '关于“{title}”，您想问什么？请回复此消息。',
  'Your question': '您的问题',
  'Type your question as a reply.': '请以回复的形式输入您的问题。',
  'Asked. The answer will be on the item in the app.': '已提问。回答会显示在控制台中的该事项上。',
  'Answer': '回答',
  'Answer in words': '用文字回答',
  'That choice is not on this question.': '此问题没有这个选项。',
  'Chosen: {choice}.': '已选择：{choice}。',
  'Stop the task': '停止任务',
  'Your answer to "{question}"? Reply to this message.': '您对“{question}”的回答是？请回复此消息。',
  'Your answer': '您的回答',
  'Type your answer as a reply.': '请以回复的形式输入您的回答。',
  'Answered. The task carries on with it.': '已回答。任务将据此继续。',
  'That is too long for one question; keep it under {max} characters.':
    '一个问题不能这么长；请控制在 {max} 个字符以内。',
  '[a key, not kept]': '[一个密钥，未保存]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    '这看起来像是密钥，所以我没有保存它，也没有发送到任何地方。密钥应填写在卡片上的加密字段中，或“本部署”中对应的页面上：告诉我它的用途，我会把卡片呈给您。',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    '尚未设置模型，所以我还无法思考。请在“本部署 > 模型”中选择一个；之后其他事情我都能帮忙。',
  'The model did not answer: {reason}': '模型没有响应：{reason}',
  'Here is what I propose.': '以下是我的建议。',
  'I have nothing to add.': '我没有什么要补充的。',
  '{name}, CEO of {company}': '{name}，{company} 的 CEO',
  'That could not be answered: {reason}': '无法回答：{reason}',
  'I read text and voice notes.': '我可以读取文字消息和语音消息。',
  'Now talking to {name}.': '现在与 {name} 对话。',
  'Choose whom to talk to.': '请选择对话对象。',
  'Choose whom to talk to': '选择对话对象',
  'Talk to PALUGADA about the whole deployment': '与 PALUGADA 讨论整个部署',
  'Who you are talking to, and how': '当前对话对象及使用方法',
  'Stopped.': '已停止。',
  'Write here to talk to {name}.': '在这里输入即可与 {name} 对话。',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    '您正在与 {name} 对话。可以发文字，也可以发语音消息。/ceo 用于选择对话对象；/palugada 用于与 PALUGADA 讨论整个部署。',
  'You said: "{words}"': '您说：“{words}”',
  'in the app': '在控制台中',
  'Apply: {summary}': '应用：{summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    '尚无语音识别服务：请在控制台的“本部署 > 工具 > 语音识别”中选择提供商。',
  'That recording is too long; keep a voice note under {max} MB.': '录音太长了；请将语音消息控制在 {max} MB 以内。',
  'I could not make out any words in that.': '我没能听清其中的任何话语。',
  'Done: {summary}': '已完成：{summary}',
  'That one is applied in the app.': '此卡片需要在控制台中应用。',
  'That card no longer exists.': '该卡片已不存在。',
  'That card was already applied.': '该卡片已应用过。',
  'That card was dismissed.': '该卡片已被忽略。',
  'That card failed when it was applied.': '该卡片应用时失败。',
  'That could not be done: {reason}': '无法完成：{reason}',
  'Choose': '选择',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    '关于“{title}”，您想问什么？请回复此消息并写下您的问题。',
  'Your answer to "{question}"? Reply to this message with your answer.':
    '您对“{question}”的回答是？请回复此消息并写下您的回答。',
  'I read text messages here.': '在这里我只能读取文字消息。',
  'Apply one of these here:': '可在此应用以下任一项：',
  'Apply {number}': '应用第 {number} 项',
  'Signed in to {provider} for the {alias} key': '已登录 {provider}，用于 {alias} 密钥',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    '请返回 PALUGADA：该部门现已持有此密钥，并会在其过期前自动续期。此标签页可以关闭了。',
  'Signed in to {name}': '已登录 {name}',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    '请返回 PALUGADA，选择角色可以使用它的哪些工具。此标签页可以关闭了。',
  'Not signed in': '未登录',
  "Recorded: approved.": "已记录：批准。",
  "Recorded: denied.": "已记录：拒绝。",
  "Recorded: asked.": "已记录：提问。",
  "Asked. Nothing left to press here.": "已提问。这里无需再操作。",
  "Withdrawn: the task it was asking about has finished.": "已撤回：所询问的任务已完成。",
  "Withdrawn: the task it was asking about has failed.": "已撤回：所询问的任务已失败。",
  "Withdrawn: the task it was asking about was stopped.": "已撤回：所询问的任务已被停止。",
  "Withdrawn: the task it was asking about was cancelled.": "已撤回：所询问的任务已被取消。",
  'Decided. Nothing left to press here.': '已决定。这里无需再操作。',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': '已撤回：智能体更改了提议，并就新提议重新发起询问。',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': '已撤回：公司已不在此提议要变更的阶段。',
  'Withdrawn: it was already decided in the app.': '已撤回：已在控制台中作出决定。',
  'Withdrawn. Nothing left to press here.': '已撤回。这里无需再操作。',
  'company': '公司',
  'Work stopped: the {account} account is out of tokens': '工作已停止：{account} 账户的令牌已用完',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': '“{work}”已停止，因为 {account} 账户已用掉 {max} 个令牌中的 {spent} 个。请在“资金”中提高其上限，然后打开该任务并点击“继续”：它会从停止的地方继续。',
  'Withdrawn: you continued the task it was about.': '已撤回：你已继续了它所涉及的任务。',
  'Broke its contract': '违反了任务约定',
  'Refused by a policy': '被策略拒绝',
  'Out of budget': '预算用尽',
  'Handed on too many times': '转交次数过多',
  'Missed its deadline': '错过了截止时间',
  'Its result did not check out': '其结果未通过核验',
  'A capability it needs is down': '所需的某项能力不可用',
  'No runtime could take it': '没有可接手的运行时',
  'Went in a circle': '陷入了循环',
  'Split into too many sub-tasks': '拆分出的子任务过多',
  'Wrote more than its role allows one run': '单次运行写入的内容超出了角色允许的上限',
  'Your approval was not given in time': '您未及时批准',
  'Stopped by you': '已被您停止',
  'Cancelled by you': '已被您取消',
  'The company is frozen': '公司已冻结',
  'Its record did not match on replay': '重放时记录不一致',
  'It kept stopping the worker running it': '它屡次导致运行它的工作进程停止',
  'Not done': '未办成',
  'Task failed': '任务失败',
  'Digest for {day}': '{day} 摘要',
  'Spent: {amount}': '已支出：{amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': '工作：完成 {done}，失败 {failed}，停止 {stopped}',
  'Inbox: {open} waiting (incidents: {incidents})': '收件箱：{open} 项等待中（异常：{incidents}）',
  'Stopped ({count}): {reason}': '已停止（{count}）：{reason}',
  'Start an ad campaign': '启动广告活动',
  'Block time on the calendar': '在日历上预留时间',
  'Read the calendar': '读取日历',
  'Run code': '运行代码',
  'Add a note to a customer': '为客户添加备注',
  'Read customer records': '读取客户记录',
  'Release to the live site': '发布到正式网站',
  'Release to the test site': '发布到测试网站',
  'Change a domain\'s nameservers': '修改域名的 DNS 服务器',
  'Read a domain\'s records': '读取域名解析记录',
  'Change a domain\'s record': '修改域名解析记录',
  'Write a document': '编写文档',
  'Sign a document': '签署文档',
  'Buy a domain': '购买域名',
  'Transfer a domain': '转移域名',
  'Draft an email': '起草邮件',
  'Send an email': '发送邮件',
  'List files': '列出文件',
  'Transfer money': '转账',
  'Propose a goal change': '提议修改目标',
  'Make a picture': '生成图片',
  'Issue an invoice': '开具发票',
  'Pay an invoice': '支付发票',
  'Read the books': '读取账目',
  'Read the mailbox': '读取邮箱',
  'Search what the company knows': '搜索公司掌握的知识',
  'Record a measure': '录入指标数值',
  'Read product numbers': '读取产品数据',
  'Ask you a question': '向您提问',
  'Write down a plan': '记录计划',
  'Delete a record': '删除记录',
  'Propose a code change': '提议修改代码',
  'Read the code': '读取代码',
  'Destroy a server': '销毁服务器',
  'Read a skill': '读取技能',
  'Publish a post': '发布帖子',
  'Read text aloud': '朗读文本',
  'Turn speech into text': '语音转文字',
  'Propose a new stage': '提议进入新阶段',
  'Wait for work handed on': '等待已转交的工作',
  'Hand work to another role': '将工作转交给其他角色',
  'File a ticket': '提交工单',
  'List tickets': '列出工单',
  'Check a service is up': '检查服务是否正常',
  'Read a web page': '读取网页',
  'Open a web page': '打开网页',
  'Search the web': '搜索网页',
  'no stage': '无阶段',
  'Explore': '探索',
  'Validate': '验证',
  'Build': '构建',
  'Launch': '上线',
  'Grow': '增长',
  'Wind down': '收尾',
  'Monthly budget reached; the company is paused': '已达到每月预算，公司已暂停',
  '{spent} of {limit} spent since {since}. No new task will start and no external action will run until you raise the ceiling or allow spending past it for a while, under Money.': '自 {since} 起已支出 {spent}，上限为 {limit}。在您于“资金”中提高上限或限时放行超出上限的支出之前，不会启动新任务，也不会执行任何外部操作。',
  'Monthly budget is 80% spent': '每月预算已用掉 80%',
  '{spent} of {limit} spent since {since}. At 100% the company pauses.': '自 {since} 起已支出 {spent}，上限为 {limit}。达到 100% 时公司将暂停。',
  'Role {role} is paused for spending too fast': '角色 {role} 因支出过快已暂停',
  '{role} spent {spent} in the last hour, {multiple} times its usual {usual} an hour. It is paused before the monthly ceiling is reached, so there is money left to work with once you have found out why. Resume it when you have.': '{role} 在过去一小时支出了 {spent}，是其平时每小时 {usual} 的 {multiple} 倍。它在达到每月上限之前就已暂停，这样您查明原因后仍有资金可用于工作。查明后请恢复它。',
  'Daily model spend over threshold': '当日模型支出超过阈值',
  'Model spend today is {spent}, over the {limit} ceiling.': '今日模型支出为 {spent}，超过了 {limit} 的上限。',
  'Task failure rate over threshold': '任务失败率超过阈值',
  '{failed} of {finished} tasks failed or stopped today ({rate}%), over the {limit}% threshold.': '今天 {finished} 个任务中有 {failed} 个失败或被停止（{rate}%），超过了 {limit}% 的阈值。',
  'Unusual number of policy refusals': '策略拒绝次数异常',
  'Actions refused by a policy today: {count}, over the threshold of {limit}. Either an agent is probing its limits or a policy is miscalibrated.': '今天被策略拒绝的操作：{count} 次，超过了 {limit} 次的阈值。要么是某个智能体在试探自己的权限边界，要么是某项策略设置不当。',
  'External writes failed verification': '外部写入未通过核验',
  'Writes outside that reported success but read back differently: {count}. Something is changing them other than as asked.': '报告成功、但读回结果不一致的外部写入：{count} 次。有东西在以未经要求的方式改动它们。',
  'A capability stopped being usable': '某项能力已无法使用',
  'Tasks that could not start today because a capability their role needs failed its check: {count}. A credential has probably expired or a quota is used up.': '今天因角色所需的能力未通过检查而无法启动的任务：{count} 个。可能是凭据已过期，或配额已用尽。',
  'A worker stopped reporting mid-run': '某个工作进程在运行中途停止了上报',
  'Runs that stopped reporting and were taken back today: {count}. The work was picked up again; the tokens they had already spent were not recovered.': '今天停止上报并被收回的运行：{count} 次。工作已被重新领取；它们已消耗的 token 无法收回。',
  '{role} was refused {denials} times today, at the limit of {limit}. No task will run as this role until you lift the freeze. The usual causes are a missing capability grant, a policy the role\'s charter does not account for, or work the role was never equipped to do.': '{role} 今天被拒绝了 {denials} 次，已达到 {limit} 次的限制。在您解冻之前，不会有任务以此角色运行。常见原因是缺少某项能力的授权、角色章程没有考虑到某项策略，或者这项工作是该角色从未具备条件去做的。',
  'Role {role} is frozen after repeated denials': '角色 {role} 因屡次被拒绝而冻结',
  'What it was refused: {capabilities}': '被拒绝的内容：{capabilities}',
  'It is waiting for an approval, and none is open, so nothing you can answer will move it.': '它在等待审批，但没有任何待处理的审批，因此您的任何回答都无法让它继续。',
  'It is waiting for a review, and none is pending, so no reviewer and no decision of yours will move it.': '它在等待审核，但没有任何待处理的审核，因此无论审核者还是您的任何决定都无法让它继续。',
  'It is parked until a window reopens, and the window never does.': '它被搁置到某个时段重新开放，而那个时段永远不会再开放。',
  'A task is waiting on nothing': '某个任务在空等',
  '"{task}" has been waiting since {since}. {why} Approve to run it again from where it stopped, or deny to cancel it.': '“{task}”自 {since} 起一直在等待。{why}批准即从停止处重新运行，拒绝则取消它。',
  'A task keeps stopping the worker running it': '某个任务屡次导致运行它的工作进程停止',
  '"{task}" lost its worker {lost} times: each time the worker running it stopped answering before the work finished. What it had done is kept. It is halted so it cannot take another worker down; run it again once the cause is found, or cancel it.': '“{task}”已 {lost} 次失去工作进程：每次运行它的工作进程都在工作完成前停止响应。它已完成的部分会保留。它已被停止，以免再拖垮另一个工作进程；查明原因后请重新运行，或取消它。',
  '{services} stayed unreachable, and the work that needs it stopped': '{services} 一直无法连接，需要它的工作已停止',
  'The task waited about {minutes} minutes, looking again each time, and has stopped. Once the service answers, run it again.': '该任务等待了约 {minutes} 分钟，每次都重新检查，现已停止。服务恢复响应后，请重新运行。',
  'It was tried {tries} times over about {minutes} minutes.': '已在约 {minutes} 分钟内尝试了 {tries} 次。',
  'This role can take actions that cannot be undone, so the run was not silently moved to a different model.': '此角色能执行不可撤销的操作，因此运行没有被悄悄切换到其他模型。',
  'No fallback model is left for this role.': '此角色已没有可用的备用模型。',
  'Model {model} failed and the run was not moved': '模型 {model} 出错，运行未被切换',
  'External write failed verification': '外部写入未通过核验',
  'The task wrote to an outside service and read it back, and what it read did not match. Look at the place it wrote to before you run it again: the write may have happened.': '该任务向外部服务写入后又读回，读到的内容不一致。重新运行之前，请先查看它写入的位置：写入可能已经发生。',
  'Review deadlocked after {rounds} revisions: {capability}': '审核在 {rounds} 轮修改后陷入僵局：{capability}',
  'The role and its reviewer did not agree on {capability}.': '该角色与其审核者未能就 {capability} 达成一致。',
  'The reviewer\'s last note: {note}': '审核者的最后备注：{note}',
  'The reviewer left no note.': '审核者没有留下备注。',
  'What it was judged against: {criteria}': '评判所依据的标准：{criteria}',
  'Review produced no usable verdict: {capability}': '审核未得出可用的结论：{capability}',
  'The reviewing task ended without a decision that could be read. The proposed action is still blocked and needs your judgement.': '审核任务结束时没有可读取的决定。所提议的操作仍被阻止，需要您来判断。',
  'another stage': '另一个阶段',
  'Either answer only closes this: the company stays in the {stage} stage.': '无论哪种回答都只会关闭此事项：公司仍处于{stage}阶段。',
  'Either answer only closes this: the company stays without a stage.': '无论哪种回答都只会关闭此事项：公司仍没有阶段。',
  'To move it anyway, set the stage on the Overview.': '如仍要调整，请在“概览”中设置阶段。',
  '{reviewer} stopped a proposal to move the company from {from} to {to}': '{reviewer} 拦下了将公司从{from}转到{to}的提议',
  '{reviewer} reviewed it before you and stopped it:': '{reviewer} 在您之前审核了此提议并将其拦下：',
  'No reason was given.': '未给出理由。',
  'What was proposed:': '提议内容：',
  'The company stays in the {stage} stage.': '公司仍处于{stage}阶段。',
  'The company stays without a stage.': '公司仍没有阶段。',
  'Move the company from {from} to {to}?': '是否将公司从{from}转到{to}？',
  'Reviewed by {reviewer} before you:': '在您之前已由 {reviewer} 审核：',
  'The schedule "{schedule}" keeps producing the same result': '定时计划“{schedule}”一直产生相同的结果',
  'Its last {runs} runs all ended with the same output. That is sometimes exactly right -- a report with nothing new to say -- and often a schedule that stopped doing anything useful while still being paid for. Deny to turn it off; approve to keep it running and not be asked about this result again.': '它最近 {runs} 次运行的输出全部相同。这有时完全正常——比如一份没有新内容可报告的报告——但更常见的是，定时计划已经不再做任何有用的事，却仍在花钱。拒绝即关闭它；批准则让它继续运行，并且不再就此结果询问您。',
  'Capability {capability} failed preflight': '能力 {capability} 未通过检查',
  'Work that needs it is stopped rather than started: fix the cause, then run that work again. The usual causes are an expired or wrongly scoped credential, a quota used up, or an address that is wrong.': '需要它的工作已停止，而不是启动：请修复原因，然后重新运行该工作。常见原因是凭据过期或权限范围有误、配额用尽，或地址错误。',
  'Batch guard stopped {capability}': '批量防护拦下了 {capability}',
  'It did not match the plan its run recorded. Nothing was sent, and no service was called.': '它与本次运行记录的计划不符。没有发送任何内容，也没有调用任何服务。',
  '{role} was asked first and has had {minutes} minutes.': '已先询问 {role}，至今已过去 {minutes} 分钟。',
  '{role} is not a role in this company, so this came to you at once.': '{role} 不是本公司的角色，因此此事项已立即转给您。',
  '{role} could not be given this: the company has no active goal or project to hang it from.': '无法将此事项交给 {role}：公司没有可挂靠的生效中目标或项目。',
  '{role} could not be given this ({record}), so this came to you at once.': '无法将此事项交给 {role}（{record}），因此已立即转给您。',
  '{role} stopped without an account of what it did ({why}).': '{role} 已停止，但没有说明它做了什么（{why}）。',
  '{role} finished without an account of what it did.': '{role} 已完成，但没有说明它做了什么。',
  '{role} failed without an account of what it did.': '{role} 失败了，且没有说明它做了什么。',
  '{role} was stopped without an account of what it did.': '{role} 被停止了，且没有说明它做了什么。',
  'Proposed change to the {kind} "{goal}"': '对{kind}“{goal}”的修改提议',
  'Currently: {statement}': '当前：{statement}',
  'Currently: {statement} ({status})': '当前：{statement}（{status}）',
  'Proposed: {statement}': '提议：{statement}',
  'Proposed status: {status}': '提议的状态：{status}',
  'Reason given: {reason}': '给出的理由：{reason}',
  'Approving it changes the goal; until then the work carries on under the goal as it is.': '批准后目标即会修改；在此之前，工作按现有目标继续进行。',
  'The goal stays as it is.': '目标保持不变。',
  'mission': '使命',
  'objective': '目标（O）',
  'key result': '关键结果（KR）',
  'Active': '生效中',
  'Met': '已达成',
  'Abandoned': '已放弃',
  'This work asked for it at tier {tier}, and policy {policies} requires your approval.': '此工作以等级 {tier} 请求该操作，且策略 {policies} 要求经您批准。',
  'This work asked for it at tier {tier}, and the task began with content from outside the company.': '此工作以等级 {tier} 请求该操作，且该任务是由公司外部的内容发起的。',
  'This work asked for it at tier {tier}, and the work read content from outside the company before asking.': '此工作以等级 {tier} 请求该操作，且该工作在请求之前读取了公司外部的内容。',
  'This work asked for it at tier {tier}, after the work read content from outside the company, and the guardian asked you first: {reason}': '此工作在读取公司外部的内容之后，以等级 {tier} 请求该操作，守护者先来询问您：{reason}',
  'it doubted this call before, and you allowed it once': '它之前就怀疑过这次调用，您允许过一次',
  'This work asked for it at tier {tier}, which cannot be reversed.': '此工作以等级 {tier} 请求该操作，该等级不可撤销。',
  'You approved this once already, and the worker carrying it out stopped before it could say whether it happened: it may already have happened. Check before approving it again.': '您已经批准过一次，而执行它的工作进程在报告是否已完成之前就停止了：它可能已经发生。再次批准前请先检查。',
  'What this is for — {goals}': '用途——{goals}',
  'The task halts and no external change is made.': '任务停止，不做任何外部更改。',
  'Scored against {total} references: {passed} passed, {failed} failed.': '按 {total} 个参考样例评分：{passed} 个通过，{failed} 个未通过。',
  'This role has fewer than {minimum} accepted references, so the change is unscored. That is not the same as passing.': '此角色已接受的参考样例少于 {minimum} 个，因此此修改不计分。这不等于通过。',
  'The role keeps working exactly as it does now.': '该角色完全按现在的方式继续工作。',
  '{role} asks: {question}': '{role} 问：{question}',
  'The run did not say more than the question.': '该运行除了问题本身没有更多说明。',
  'The task is stopped, and nothing it was going to do happens.': '任务已停止，它原本要做的事都不会发生。',
};
