/**
 * 简体中文: what the platform itself says to the owner outside the console
 * (src/owner/say.ts), keyed by its English.
 *
 * The terms are the console's (console/src/locales/zh.ts): the owner is 您,
 * an approval 审批, an incident 异常, a card is applied (应用), and "the app"
 * is the console (控制台), so that "apply it in the app" does not read as
 * 应用 twice. Screens are named as the console draws them: “本部署 > 模型”.
 */
export const SENTENCES: Readonly<Record<string, string>> = {
  'Incident: {title}': '异常：{title}',
  'Done: {goal}': '已完成：{goal}',
  'Stopped before finishing: {goal}': '未完成即停止：{goal}',
  'Not done: {goal}': '未办成：{goal}',
  'Why: {reason}': '原因：{reason}',
  'a task': '一项任务',
  'Approval needed: {title}': '需要审批：{title}',
  '{summary} — if denied: {consequence}': '{summary}——如果拒绝：{consequence}',
  '{role} asks:': '{role} 问：',
  'If denied:': '如果拒绝：',
  'Expires:': '到期时间：',
  'This one is decided in the app.': '此事项需要在控制台中决定。',
  'Open in PALUGADA': '在 PALUGADA 中打开',
  'Approve': '批准',
  'Deny': '拒绝',
  'Ask': '提问',
  'Approved. Nothing left to press here.': '已批准。这里无需再操作。',
  'Denied. Nothing left to press here.': '已拒绝。这里无需再操作。',
  'Expired unanswered. Silence is a refusal, so nothing was done.':
    '超时未回应。沉默即视为拒绝，因此未执行任何操作。',
  'This bot only answers to its owner.': '此机器人只回应其所有者。',
  'That one has to be approved in the app.': '此事项必须在控制台中批准。',
  'That could not be recorded.': '无法记录此操作。',
  'That item no longer exists.': '该事项已不存在。',
  'What do you want to ask about "{title}"? Reply to this message.':
    '关于“{title}”，您想问什么？请回复此消息。',
  'Your question': '您的问题',
  'Type your question as a reply.': '请以回复的形式输入您的问题。',
  'Asked. The answer will be on the item in the app.': '已提问。回答会显示在控制台中的该事项上。',
  'Answer': '回答',
  'Answer in words': '用文字回答',
  'That choice is not on this question.': '此问题没有这个选项。',
  'Chosen: {choice}.': '已选择：{choice}。',
  'Stop the task': '停止任务',
  'Your answer to "{question}"? Reply to this message.': '您对“{question}”的回答是？请回复此消息。',
  'Your answer': '您的回答',
  'Type your answer as a reply.': '请以回复的形式输入您的回答。',
  'Answered. The task carries on with it.': '已回答。任务将据此继续。',
  'That is too long for one question; keep it under {max} characters.':
    '一个问题不能这么长；请控制在 {max} 个字符以内。',
  '[a key, not kept]': '[一个密钥，未保存]',
  'That looks like a key, so I did not keep it or send it anywhere. Keys go in the sealed field on a card, or on their page in This deployment: tell me what it is for and I will put the card in front of you.':
    '这看起来像是密钥，所以我没有保存它，也没有发送到任何地方。密钥应填写在卡片上的加密字段中，或“本部署”中对应的页面上：告诉我它的用途，我会把卡片呈给您。',
  'No model is set up yet, so I cannot think. Choose one under This deployment, Model; then I can help with everything else.':
    '尚未设置模型，所以我还无法思考。请在“本部署 > 模型”中选择一个；之后其他事情我都能帮忙。',
  'The model did not answer: {reason}': '模型没有响应：{reason}',
  'Here is what I propose.': '以下是我的建议。',
  'I have nothing to add.': '我没有什么要补充的。',
  '{name}, CEO of {company}': '{name}，{company} 的 CEO',
  'That could not be answered: {reason}': '无法回答：{reason}',
  'I read text and voice notes.': '我可以读取文字消息和语音消息。',
  'Now talking to {name}.': '现在与 {name} 对话。',
  'Choose whom to talk to.': '请选择对话对象。',
  'Choose whom to talk to': '选择对话对象',
  'Talk to PALUGADA about the whole deployment': '与 PALUGADA 讨论整个部署',
  'Who you are talking to, and how': '当前对话对象及使用方法',
  'Stopped.': '已停止。',
  'Write here to talk to {name}.': '在这里输入即可与 {name} 对话。',
  'You are talking to {name}. Write, or send a voice note. /ceo chooses whom you talk to; /palugada talks to PALUGADA about the whole deployment.':
    '您正在与 {name} 对话。可以发文字，也可以发语音消息。/ceo 用于选择对话对象；/palugada 用于与 PALUGADA 讨论整个部署。',
  'You said: "{words}"': '您说：“{words}”',
  'in the app': '在控制台中',
  'Apply: {summary}': '应用：{summary}',
  'Nothing hears speech yet: choose a provider in the app, under This deployment, Tools, Listening.':
    '尚无语音识别服务：请在控制台的“本部署 > 工具 > 语音识别”中选择提供商。',
  'That recording is too long; keep a voice note under {max} MB.': '录音太长了；请将语音消息控制在 {max} MB 以内。',
  'I could not make out any words in that.': '我没能听清其中的任何话语。',
  'Done: {summary}': '已完成：{summary}',
  'That one is applied in the app.': '此卡片需要在控制台中应用。',
  'That card no longer exists.': '该卡片已不存在。',
  'That card was already applied.': '该卡片已应用过。',
  'That card was dismissed.': '该卡片已被忽略。',
  'That card failed when it was applied.': '该卡片应用时失败。',
  'That could not be done: {reason}': '无法完成：{reason}',
  'Choose': '选择',
  'What do you want to ask about "{title}"? Reply to this message with your question.':
    '关于“{title}”，您想问什么？请回复此消息并写下您的问题。',
  'Your answer to "{question}"? Reply to this message with your answer.':
    '您对“{question}”的回答是？请回复此消息并写下您的回答。',
  'I read text messages here.': '在这里我只能读取文字消息。',
  'Apply one of these here:': '可在此应用以下任一项：',
  'Apply {number}': '应用第 {number} 项',
  'Signed in to {provider} for the {alias} key': '已登录 {provider}，用于 {alias} 密钥',
  'Go back to PALUGADA: the division holds this key now, and it is renewed before it runs out. This tab can be closed.':
    '请返回 PALUGADA：该部门现已持有此密钥，并会在其过期前自动续期。此标签页可以关闭了。',
  'Signed in to {name}': '已登录 {name}',
  'Go back to PALUGADA to choose which of its tools roles may use. This tab can be closed.':
    '请返回 PALUGADA，选择角色可以使用它的哪些工具。此标签页可以关闭了。',
  'Not signed in': '未登录',
  "Recorded: approved.": "已记录：批准。",
  "Recorded: denied.": "已记录：拒绝。",
  "Recorded: asked.": "已记录：提问。",
  "Asked. Nothing left to press here.": "已提问。这里无需再操作。",
  "Withdrawn: the task it was asking about has finished.": "已撤回：所询问的任务已完成。",
  "Withdrawn: the task it was asking about has failed.": "已撤回：所询问的任务已失败。",
  "Withdrawn: the task it was asking about was stopped.": "已撤回：所询问的任务已被停止。",
  "Withdrawn: the task it was asking about was cancelled.": "已撤回：所询问的任务已被取消。",
  'Decided. Nothing left to press here.': '已决定。这里无需再操作。',
  'Withdrawn: the agent changed what it proposes and asked again about the new one.': '已撤回：智能体更改了提议，并就新提议重新发起询问。',
  'Withdrawn: the company is no longer at the stage this proposal would move it from.': '已撤回：公司已不在此提议要变更的阶段。',
  'Withdrawn: it was already decided in the app.': '已撤回：已在控制台中作出决定。',
  'Withdrawn. Nothing left to press here.': '已撤回。这里无需再操作。',
  'company': '公司',
  'Work stopped: the {account} account is out of tokens': '工作已停止：{account} 账户的令牌已用完',
  '"{work}" stopped because the {account} account has used {spent} of its {max} tokens. Raise its ceiling under Money, then open the task and press Continue: it carries on from where it stopped.': '“{work}”已停止，因为 {account} 账户已用掉 {max} 个令牌中的 {spent} 个。请在“资金”中提高其上限，然后打开该任务并点击“继续”：它会从停止的地方继续。',
  'Withdrawn: you continued the task it was about.': '已撤回：你已继续了它所涉及的任务。',
  'Broke its contract': '违反了任务约定',
  'Refused by a policy': '被策略拒绝',
  'Out of budget': '预算用尽',
  'Handed on too many times': '转交次数过多',
  'Missed its deadline': '错过了截止时间',
  'Its result did not check out': '其结果未通过核验',
  'A capability it needs is down': '所需的某项能力不可用',
  'No runtime could take it': '没有可接手的运行时',
  'Went in a circle': '陷入了循环',
  'Split into too many sub-tasks': '拆分出的子任务过多',
  'Wrote more than its role allows one run': '单次运行写入的内容超出了角色允许的上限',
  'Your approval was not given in time': '您未及时批准',
  'Stopped by you': '已被您停止',
  'Cancelled by you': '已被您取消',
  'The company is frozen': '公司已冻结',
  'Its record did not match on replay': '重放时记录不一致',
  'It kept stopping the worker running it': '它屡次导致运行它的工作进程停止',
  'Not done': '未办成',
  'Task failed': '任务失败',
  'Digest for {day}': '{day} 摘要',
  'Spent: {amount}': '已支出：{amount}',
  'Work: {done} done, {failed} failed, {stopped} stopped': '工作：完成 {done}，失败 {failed}，停止 {stopped}',
  'Inbox: {open} waiting (incidents: {incidents})': '收件箱：{open} 项等待中（异常：{incidents}）',
  'Stopped ({count}): {reason}': '已停止（{count}）：{reason}',
  'Start an ad campaign': '启动广告活动',
  'Block time on the calendar': '在日历上预留时间',
  'Read the calendar': '读取日历',
  'Run code': '运行代码',
  'Add a note to a customer': '为客户添加备注',
  'Read customer records': '读取客户记录',
  'Release to the live site': '发布到正式网站',
  'Release to the test site': '发布到测试网站',
  'Change a domain\'s nameservers': '修改域名的 DNS 服务器',
  'Read a domain\'s records': '读取域名解析记录',
  'Change a domain\'s record': '修改域名解析记录',
  'Write a document': '编写文档',
  'Sign a document': '签署文档',
  'Buy a domain': '购买域名',
  'Transfer a domain': '转移域名',
  'Draft an email': '起草邮件',
  'Send an email': '发送邮件',
  'List files': '列出文件',
  'Transfer money': '转账',
  'Propose a goal change': '提议修改目标',
  'Make a picture': '生成图片',
  'Issue an invoice': '开具发票',
  'Pay an invoice': '支付发票',
  'Read the books': '读取账目',
  'Read the mailbox': '读取邮箱',
  'Search what the company knows': '搜索公司掌握的知识',
  'Record a measure': '录入指标数值',
  'Read product numbers': '读取产品数据',
  'Ask you a question': '向您提问',
  'Write down a plan': '记录计划',
  'Delete a record': '删除记录',
  'Propose a code change': '提议修改代码',
  'Read the code': '读取代码',
  'Destroy a server': '销毁服务器',
  'Read a skill': '读取技能',
  'Publish a post': '发布帖子',
  'Read text aloud': '朗读文本',
  'Turn speech into text': '语音转文字',
  'Propose a new stage': '提议进入新阶段',
  'Wait for work handed on': '等待已转交的工作',
  'Hand work to another role': '将工作转交给其他角色',
  'File a ticket': '提交工单',
  'List tickets': '列出工单',
  'Check a service is up': '检查服务是否正常',
  'Read a web page': '读取网页',
  'Open a web page': '打开网页',
  'Search the web': '搜索网页',
};
